force-app/main/default/objects/Trigger_Configuration__mdt/Trigger_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>this will contain all the information needed for implementing the trigger framework</description>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Configuration__mdt/fields/Implementing_Class__c.field-meta.xml
<CustomField>
    <fullName>Implementing_Class__c</fullName>
    <description>name of the class that will be used for this process</description>
    <inlineHelpText>name of the class that will be used for this process</inlineHelpText>
    <label>Implementing Class</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerProcessingManagerTest.cls
/**
 * @author Itzik Winograd
 * @date 06/10/2022
 * @description Test class for TriggerProcessingManager.
 *              This class will use unit tests (and not business-logic tests), since this is a service.
 */
@isTest
public with sharing class TriggerProcessingManagerTest {
    private static FINAL String PROCESS_NAME = 'TestTrigger';

    @IsTest
    public static void testHandle(){
        TriggerProcessingManager.handle(PROCESS_NAME);
    }

    @IsTest
    public static void testDetermineContext(){
        TriggerProcessingManager.determineContext(PROCESS_NAME);
    }

    @IsTest
    public static void testGetProcessesAndExecute(){
        list<Trigger_Configuration__mdt> processes = TriggerProcessingManager.getProcesses(PROCESS_NAME, 'before', 'insert');
        TriggerProcessingManager.executeProcess(processes[0].Implementing_Class__c, null, null);
        TriggerProcessingManager.preventMultipleRuns(processes[0].Implementing_Class__c);
    }

}