force-app/main/default/objects/Campaign/fields/A_B_Test__c.field-meta.xml
<CustomField>
    <fullName>A_B_Test__c</fullName>
    <defaultValue>false</defaultValue>
    <label>A/B Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Asset_Type2__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type2__c</fullName>
    <description>MIS-4271</description>
    <inlineHelpText>Specify the activity’s sub-category</inlineHelpText>
    <label>Asset Type2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Event - External</fullName>
            </value>
            <value>
                <fullName>Event - Innovation Days</fullName>
            </value>
            <value>
                <fullName>Event - Owned</fullName>
            </value>
            <value>
                <fullName>Event - Online</fullName>
            </value>
            <value>
                <fullName>Content - Report</fullName>
            </value>
            <value>
                <fullName>Content - Case Study</fullName>
            </value>
            <value>
                <fullName>Content - Infographic</fullName>
            </value>
            <value>
                <fullName>Content - Blog Post</fullName>
            </value>
            <value>
                <fullName>Content - Video</fullName>
            </value>
            <value>
                <fullName>Content - Landing Page</fullName>
            </value>
            <value>
                <fullName>Email - One-off</fullName>
            </value>
            <value>
                <fullName>Email - Automated Cadence</fullName>
            </value>
            <value>
                <fullName>Email - Triggered</fullName>
            </value>
            <value>
                <fullName>Email - Newsletter</fullName>
            </value>
            <value>
                <fullName>Chat Bot - One-off</fullName>
            </value>
            <value>
                <fullName>Chat Bot - Automated</fullName>
            </value>
            <value>
                <fullName>Webinar - Recording</fullName>
            </value>
            <value>
                <fullName>Webinar - Internal</fullName>
            </value>
            <value>
                <fullName>Webinar - External</fullName>
            </value>
            <value>
                <fullName>Lead List</fullName>
            </value>
            <value>
                <fullName>Survey - Feedback</fullName>
            </value>
            <value>
                <fullName>Survey - Satisfaction</fullName>
            </value>
            <value>
                <fullName>Survey - NPS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Marketing</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Utility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>The channel for promoting your campaign.</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adwords</fullName>
            </value>
            <value>
                <fullName>Banner</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Brand Events</fullName>
            </value>
            <value>
                <fullName>Chili Piper</fullName>
            </value>
            <value>
                <fullName>Cohort Plus</fullName>
            </value>
            <value>
                <fullName>Discord</fullName>
            </value>
            <value>
                <fullName>Email campaign Pardot</fullName>
            </value>
            <value>
                <fullName>Email SalesLoft</fullName>
            </value>
            <value>
                <fullName>Email SFMC</fullName>
            </value>
            <value>
                <fullName>Employment Advocacy Program</fullName>
            </value>
            <value>
                <fullName>Event - external</fullName>
            </value>
            <value>
                <fullName>Event - internal</fullName>
            </value>
            <value>
                <fullName>Exit Pop Up</fullName>
            </value>
            <value>
                <fullName>External providers</fullName>
            </value>
            <value>
                <fullName>Facebook organic</fullName>
            </value>
            <value>
                <fullName>Facebook paid</fullName>
            </value>
            <value>
                <fullName>GDN</fullName>
            </value>
            <value>
                <fullName>Growth Hackers</fullName>
            </value>
            <value>
                <fullName>Indie Hackers</fullName>
            </value>
            <value>
                <fullName>Intercom</fullName>
            </value>
            <value>
                <fullName>LinkedIn Corona Group</fullName>
            </value>
            <value>
                <fullName>LinkedIn organic</fullName>
            </value>
            <value>
                <fullName>LinkedIn Paid</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Owned Events</fullName>
            </value>
            <value>
                <fullName>Pardot Auto Education</fullName>
            </value>
            <value>
                <fullName>Pardot Auto Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department you work at in Similarweb</inlineHelpText>
    <label>Department</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Development</fullName>
            </value>
            <value>
                <fullName>Demand Generation</fullName>
            </value>
            <value>
                <fullName>Product Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>MIS-4498
Updated Values according to GTM - MIS-1928</description>
    <inlineHelpText>For multiple regions, select “Global”</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
                <isActive>false</isActive>
                <label>ALL</label>
            </value>
            <value>
                <fullName>Brazil</fullName>
                <isActive>false</isActive>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>EMEA Dach</fullName>
                <isActive>false</isActive>
                <label>EMEA Dach</label>
            </value>
            <value>
                <fullName>EMEA UK</fullName>
                <isActive>false</isActive>
                <label>EMEA UK</label>
            </value>
            <value>
                <fullName>Europe</fullName>
                <isActive>false</isActive>
                <label>Europe</label>
            </value>
            <value>
                <fullName>France</fullName>
                <isActive>false</isActive>
                <label>France</label>
            </value>
            <value>
                <fullName>Germany</fullName>
                <isActive>false</isActive>
                <label>Germany</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
            <value>
                <fullName>Italy</fullName>
                <isActive>false</isActive>
                <label>Italy</label>
            </value>
            <value>
                <fullName>Japan</fullName>
                <isActive>false</isActive>
                <label>Japan</label>
            </value>
            <value>
                <fullName>Mexico</fullName>
                <isActive>false</isActive>
                <label>Mexico</label>
            </value>
            <value>
                <fullName>SEA</fullName>
                <isActive>false</isActive>
                <label>SEA</label>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
                <isActive>false</isActive>
                <label>United Kingdom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/SFMC_Journey_Name__c.field-meta.xml
<CustomField>
    <fullName>SFMC_Journey_Name__c</fullName>
    <description>MIS-4482</description>
    <label>SFMC Journey Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/General_Key_Value_pair__mdt/General_Key_Value_pair__mdt.object-meta.xml
<CustomObject>
    <description>Hold a key-value pair for specific process</description>
    <label>General Key-Value pair</label>
    <pluralLabel>General Key-Value pairs</pluralLabel>
</CustomObject>

force-app/main/default/objects/General_Key_Value_pair__mdt/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>The process name to query the key-value pairs by.</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateCampaignFromEmailResultBatch.cls
/**
 * Created by Alon.Shalev on 11/28/2023.
 */

public with sharing class CreateCampaignFromEmailResultBatch implements Database.Batchable<sObject>, Schedulable {
  private Map<String, String> campaignFieldToValueMap = new Map<String, String>();

  public CreateCampaignFromEmailResultBatch() {
    List<General_Key_Value_pair__mdt> keyValuePairsSettings = [
      SELECT Key__c, Value__c
      FROM General_Key_Value_pair__mdt
      WHERE ProcessName__c = 'CreateCampaignFromEmailResultBatch'
    ];
    for (General_Key_Value_pair__mdt setting : keyValuePairsSettings) {
      this.campaignFieldToValueMap.put(setting.Key__c, setting.Value__c);
    }
  }

  public void execute(SchedulableContext SC) {
    CreateCampaignFromEmailResultBatch batch = new CreateCampaignFromEmailResultBatch();
    Integer runningBatchSize = 100;
    Database.executeBatch(batch, runningBatchSize);
  }

  public Database.QueryLocator start(Database.BatchableContext BC) {
    String query =
      'SELECT Id,Name,et4ae5__DateSent__c,et4ae5__Lead__c,et4ae5__Contact__c ' +
      'FROM et4ae5__IndividualEmailResult__c ' +
      'WHERE (et4ae5__Opened__c = true OR et4ae5__Clicked__c = true) ' +
      'AND LastModifiedDate >= YESTERDAY';
    return Database.getQueryLocator(query);
  }

  public void execute(
    Database.BatchableContext BC,
    List<et4ae5__IndividualEmailResult__c> scope
  ) {
    // data collections
    Map<String, et4ae5__IndividualEmailResult__c> emailResultsNameMap = new Map<String, et4ae5__IndividualEmailResult__c>();
    List<Campaign> campaignToInsertList = new List<Campaign>();
    List<CampaignMember> campaignMemberToInsertList = new List<CampaignMember>();
    Set<String> leadIdFromEmailResultSet = new Set<String>();
    Set<String> contactIdFromEmailResultSet = new Set<String>();
    for (et4ae5__IndividualEmailResult__c emailResult : scope) {
      if (emailResult.Name.contains(' --')) {
        String prefixName = emailResult.Name.substringBefore(' --');
        emailResultsNameMap.put(prefixName, emailResult);
        if (emailResult.et4ae5__Lead__c != null) {
          leadIdFromEmailResultSet.add(emailResult.et4ae5__Lead__c);
        }
        if (emailResult.et4ae5__Contact__c != null) {
          contactIdFromEmailResultSet.add(emailResult.et4ae5__Contact__c);
        }
      }
    }

    // part 1 campaign creation

    List<Campaign> existingCampaignList = [
      SELECT Id, Name
      FROM Campaign
      WHERE Name IN :emailResultsNameMap.keySet()
    ];

    Set<String> existingCampaignNameSet = new Set<String>();
    for (Campaign existing : existingCampaignList) {
      existingCampaignNameSet.add(existing.Name);
    }

    for (String prefixName : emailResultsNameMap.keySet()) {
      if (!existingCampaignNameSet.contains(prefixName)) {
        campaignToInsertList.add(
          createCampaign(prefixName, emailResultsNameMap.get(prefixName))
        );
      }
    }
    if (!campaignToInsertList.isEmpty()) {
      insert campaignToInsertList;
    }

    //part 2 campaign Member creation
    List<Campaign> afterInsertCampaignList = [
      SELECT Id, Name
      FROM Campaign
      WHERE Name IN :emailResultsNameMap.keySet()
    ];

    Map<String, Campaign> nameToCampaignMap = new Map<String, Campaign>();

    for (Campaign campaign : afterInsertCampaignList) {
      nameToCampaignMap.put(campaign.Name, campaign);
    }
    Set<String> keySetOfExistingCampaignMemberSet = getKeySetOfExistingCampaignMemberSet(
      leadIdFromEmailResultSet,
      contactIdFromEmailResultSet,
      afterInsertCampaignList
    );
    for (et4ae5__IndividualEmailResult__c emailResult : scope) {
      if (emailResult.Name.contains(' --')) {
        String prefixName = emailResult.Name.substringBefore(' --');
        if (
          needToCreateCampaignMember(
            emailResult,
            nameToCampaignMap.get(prefixName),
            keySetOfExistingCampaignMemberSet
          )
        ) {
          String newlyCreatedKey = nameToCampaignMap.get(prefixName).Id + ':';
          newlyCreatedKey += emailResult.et4ae5__Contact__c != null
            ? emailResult.et4ae5__Contact__c
            : emailResult.et4ae5__Lead__c;
          keySetOfExistingCampaignMemberSet.add(newlyCreatedKey);
          campaignMemberToInsertList.add(
            createCampaignMember(emailResult, nameToCampaignMap.get(prefixName))
          );
        }
      }
    }
    if (!campaignMemberToInsertList.isEmpty()) {
      Database.SaveResult[] saveResults = Database.insert(
        campaignMemberToInsertList,
        false
      );

      for (Database.SaveResult result : saveResults) {
        if (!result.isSuccess()) {
          for (Database.Error err : result.getErrors()) {
            // Check if the error is due to a duplicate value
            if (
              !(err.getStatusCode() == StatusCode.DUPLICATE_VALUE &&
              err.getMessage().contains('Already a campaign'))
            ) {
              // Handle other errors - by throwing an exception
              throw new CreateCampaignException(
                'Insert failed due to a non-duplicate error'
              );
            }
          }
        }
      }
    }
  }

  private Set<String> getKeySetOfExistingCampaignMemberSet(
    Set<String> leadIdFromEmailResultSet,
    Set<String> contactIdFromEmailResultSet,
    List<Campaign> afterInsertCampaignList
  ) {
    List<CampaignMember> existingCampaignMembersList = [
      SELECT Id, ContactId, LeadId, CampaignId
      FROM CampaignMember
      WHERE
        (LeadId IN :leadIdFromEmailResultSet
        OR ContactId IN :contactIdFromEmailResultSet)
        AND CampaignId IN :afterInsertCampaignList
    ];

    Set<String> keySetOfExistingCampaignMemberSet = new Set<String>();
    for (CampaignMember existingCampaignMember : existingCampaignMembersList) {
      keySetOfExistingCampaignMemberSet.add(
        createKeySetFromCampaignMember(existingCampaignMember)
      );
    }
    return keySetOfExistingCampaignMemberSet;
  }
  private boolean needToCreateCampaignMember(
    et4ae5__IndividualEmailResult__c emailResult,
    Campaign campaign,
    Set<String> keySetOfExistingCampaignMemberSet
  ) {
    String newlyCreatedKey = campaign.Id + ':';
    newlyCreatedKey += emailResult.et4ae5__Contact__c != null
      ? emailResult.et4ae5__Contact__c
      : emailResult.et4ae5__Lead__c;
    return !keySetOfExistingCampaignMemberSet.contains(newlyCreatedKey);
  }

  private String createKeySetFromCampaignMember(
    CampaignMember existingCampaignMember
  ) {
    // the key will be Campaign +":"+ contactId OR leadId
    String key = existingCampaignMember.CampaignId;
    if (existingCampaignMember.ContactId != null) {
      key += ':' + existingCampaignMember.ContactId;
    }
    if (existingCampaignMember.LeadId != null) {
      key += ':' + existingCampaignMember.LeadId;
    }
    return key;
  }

  private CampaignMember createCampaignMember(
    et4ae5__IndividualEmailResult__c emailResult,
    Campaign campaign
  ) {
    System.debug('campaign--' + campaign);
    CampaignMember newCampaignMember = new CampaignMember();
    newCampaignMember.CampaignId = campaign.Id;
    newCampaignMember.LeadId = emailResult.et4ae5__Lead__c;
    newCampaignMember.ContactId = emailResult.et4ae5__Contact__c;
    newCampaignMember.Status = 'Opened';
    return newCampaignMember;
  }

  private Campaign createCampaign(
    String prefixName,
    et4ae5__IndividualEmailResult__c emailResult
  ) {
    Campaign campaign = new Campaign();
    campaign.Name = prefixName;
    campaign.SFMC_Journey_Name__c = prefixName;
    campaign.Region__c = this.campaignFieldToValueMap.containsKey('Region__c')
      ? this.campaignFieldToValueMap.get('Region__c')
      : null;
    campaign.BudgetedCost = this.campaignFieldToValueMap.containsKey(
        'BudgetedCost'
      )
      ? Decimal.valueOf(this.campaignFieldToValueMap.get('BudgetedCost'))
      : null;
    campaign.Department__c = this.campaignFieldToValueMap.containsKey(
        'Department__c'
      )
      ? this.campaignFieldToValueMap.get('Department__c')
      : null;
    campaign.StartDate = Date.valueOf(emailResult.et4ae5__DateSent__c);
    campaign.EndDate = Date.valueOf(emailResult.et4ae5__DateSent__c);
    campaign.Type = 'Email';
    campaign.Channel__c = 'Email SFMC';
    campaign.Asset_Type2__c = populateAssetType(prefixName);
    campaign.IsActive = true;
    campaign.A_B_Test__c = checkPattern(emailResult.Name);
    return campaign;
  }

  private Boolean checkPattern(String inputText) {
    // Define the regex pattern
    String patternString = '- [A-Za-z] --';

    // Compile the pattern
    Pattern pattern = Pattern.compile(patternString);

    // Create a matcher for the input text
    Matcher matcher = pattern.matcher(inputText);
    return matcher.find();
  }

  private String populateAssetType(String prefixName) {
    String assetType;
    if (prefixName.startsWith('OE - NWL')) {
      assetType = 'Email - Newsletter';
    } else if (prefixName.startsWith('OE')) {
      assetType = 'Email - One-off';
    } else if (prefixName.startsWith('AE')) {
      assetType = 'Email - Automated Cadence';
    } else if (prefixName.startsWith('TE')) {
      assetType = 'Email - Triggered';
    }
    return assetType;
  }

  public void finish(Database.BatchableContext BC) {
  }

  public class CreateCampaignException extends Exception {
  }
}