force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <inlineHelpText>The channel for promoting your campaign.</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adwords</fullName>
            </value>
            <value>
                <fullName>Banner</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Brand Events</fullName>
            </value>
            <value>
                <fullName>Chili Piper</fullName>
            </value>
            <value>
                <fullName>Cohort Plus</fullName>
            </value>
            <value>
                <fullName>Discord</fullName>
            </value>
            <value>
                <fullName>Email campaign Pardot</fullName>
            </value>
            <value>
                <fullName>Email SalesLoft</fullName>
            </value>
            <value>
                <fullName>Email SFMC</fullName>
            </value>
            <value>
                <fullName>Employment Advocacy Program</fullName>
            </value>
            <value>
                <fullName>Event - external</fullName>
            </value>
            <value>
                <fullName>Event - internal</fullName>
            </value>
            <value>
                <fullName>Exit Pop Up</fullName>
            </value>
            <value>
                <fullName>External providers</fullName>
            </value>
            <value>
                <fullName>Facebook organic</fullName>
            </value>
            <value>
                <fullName>Facebook paid</fullName>
            </value>
            <value>
                <fullName>GDN</fullName>
            </value>
            <value>
                <fullName>Growth Hackers</fullName>
            </value>
            <value>
                <fullName>Indie Hackers</fullName>
            </value>
            <value>
                <fullName>Intercom</fullName>
            </value>
            <value>
                <fullName>LinkedIn Corona Group</fullName>
            </value>
            <value>
                <fullName>LinkedIn organic</fullName>
            </value>
            <value>
                <fullName>LinkedIn Paid</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Owned Events</fullName>
            </value>
            <value>
                <fullName>Pardot Auto Education</fullName>
            </value>
            <value>
                <fullName>Pardot Auto Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department you work at in Similarweb</inlineHelpText>
    <label>Department</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Development</fullName>
            </value>
            <value>
                <fullName>Demand Generation</fullName>
            </value>
            <value>
                <fullName>Product Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/SFMC_Journey_Name__c.field-meta.xml
<CustomField>
    <fullName>SFMC_Journey_Name__c</fullName>
    <description>MIS-4482</description>
    <label>SFMC Journey Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Inferral_Solution_Valid_Criteria_List__c/Inferral_Solution_Valid_Criteria_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution L Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/InferralSolutionCValidCriteriaList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution C Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMap__c/InferralSolutionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Lead</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/InferralSolutionMapContact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Contact</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Banking and insurance</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Recruitment and HR</fullName>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/CreateCampaignFromEmailResultBatchTest.cls
@isTest
public class CreateCampaignFromEmailResultBatchTest {

    @testSetup
    static void setup() {
        Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
        iss.Name='Default Value';
        iss.Value__c='Sales';
        insert iss;

        InferralSolutionMap__c ismTest = new InferralSolutionMap__c();
        ismTest.SW_Industry__c = 'AdTech and AdNetwork';
        ismTest.Department__c = 'BI / Analytics';
        ismTest.Inferred_Solution__c = 'Research';
        ismTest.Name = 'test';
        insert ismTest;

        InferralSolutionMapContact__c ismCTest = new InferralSolutionMapContact__c();
        ismCTest.SW_Industry__c = 'AdTech and AdNetwork';
        ismTest.Department__c = 'BI / Analytics';
        ismCTest.Inferred_Solution__c = 'Research';
        ismCTest.Name = 'test';
        insert ismCTest;

        Inferral_Solution_Valid_Criteria_List__c islvcl = new Inferral_Solution_Valid_Criteria_List__c();
        islvcl.Name='department__c';
        islvcl.Is_Valid__c=true;
        insert islvcl;

        Inferral_Solution_Valid_Criteria_List__c islvcl2 = new Inferral_Solution_Valid_Criteria_List__c();
        islvcl2.Name='sw_industry__c';
        islvcl2.Is_Valid__c=true;
        insert islvcl2;

        InferralSolutionCValidCriteriaList__c islcvcl = new InferralSolutionCValidCriteriaList__c();
        islcvcl.Name='department__c';
        islcvcl.Is_Valid__c=true;
        insert islcvcl;

        InferralSolutionCValidCriteriaList__c islcvcl2 = new InferralSolutionCValidCriteriaList__c();
        islcvcl2.Name='sw_industry__c';
        islcvcl2.Is_Valid__c=true;
        insert islcvcl2;
        Campaign campaign = new Campaign(Name = 'Test Campaign');
        insert campaign;
        Lead l1 = TestDataFactory.createLead();
        insert l1;
        // Create test data for et4ae5__IndividualEmailResult__c with the same prefix name
        String prefixName = 'Test Email -- 1'; // Example prefix name
        et4ae5__Automated_Send__c triggeredSend = new et4ae5__Automated_Send__c();
        triggeredSend.Name = 'test';
        insert triggeredSend;
        et4ae5__IndividualEmailResult__c emailResult1 = new et4ae5__IndividualEmailResult__c(
                Name = 'Test Campaign -- for this test',
                et4ae5__Opened__c = true,
                et4ae5__TriggeredSendDefinition__c = triggeredSend.Id,
                et4ae5__Lead__c = l1.Id
        );
        et4ae5__IndividualEmailResult__c emailResult2 = new et4ae5__IndividualEmailResult__c(
                Name = prefixName,
                et4ae5__Opened__c = true,
                et4ae5__TriggeredSendDefinition__c = triggeredSend.Id,
                et4ae5__Lead__c = l1.Id
        );
        insert new List<et4ae5__IndividualEmailResult__c>{emailResult1, emailResult2};
    }

    @isTest
    static void testCreateCampaignsFromEmailResults() {
        // Start the batch job
        Test.startTest();
        CreateCampaignFromEmailResultBatch batchJob = new CreateCampaignFromEmailResultBatch();
        ID batchInstanceId = Database.executeBatch(batchJob);
        Test.stopTest();

        // Verify that only one campaign was created
        List<Campaign> createdCampaigns = [SELECT Name,Type,Channel__c,SFMC_Journey_Name__c FROM Campaign];
        List<CampaignMember> createdCampaignMembersList = [SELECT id,CampaignId,Status FROM CampaignMember WHERE CampaignId IN:createdCampaigns];
        System.debug('createdCampaignMembersList--'+createdCampaignMembersList);
        System.assertEquals(2, createdCampaigns.size());
        System.assertEquals(2, createdCampaignMembersList.size());
//        System.assertEquals('Opened', createdCampaignMembersList[0].Status);
//        System.assertEquals('Opened', createdCampaignMembersList[1].Status);
        System.assertEquals(createdCampaigns[0].Id, createdCampaignMembersList[0].CampaignId);
        System.assertEquals(createdCampaigns[1].Id, createdCampaignMembersList[1].CampaignId);

        // Assert other details about the campaign as needed
        Campaign createdCampaign = createdCampaigns[1];
        System.assertEquals('Test Email', createdCampaign.Name);
        System.assertEquals('Email', createdCampaign.Type);
        System.assertEquals('Email SFMC', createdCampaign.Channel__c);
        System.assertEquals('Test Email', createdCampaign.SFMC_Journey_Name__c);
    }

    @isTest
    public static void testSchedule(){
        String CRON_EXP = '0 0 0 3 9 ? 2050';
        Test.startTest();
        // Schedule the test job
        String jobId = System.schedule('CreateCampaignFromEmailResultBatch '+Datetime.now(),CRON_EXP,
                new CreateCampaignFromEmailResultBatch());
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
        FROM CronTrigger
        WHERE id = :jobId];
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP,ct.CronExpression);
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        // Verify the next time the job will run
        System.assertEquals('2050-09-03 00:00:00', String.valueOf(ct.NextFireTime));
        Test.stopTest();
    }

}