force-app/main/default/objects/Campaign/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department you work at in Similarweb</inlineHelpText>
    <label>Department</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Development</fullName>
            </value>
            <value>
                <fullName>Demand Generation</fullName>
            </value>
            <value>
                <fullName>Product Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/Campaign_Member_History_Tracking__c.object-meta.xml
<CustomObject>
    <label>Campaign Member History Tracking</label>
    <nameField>
        <label>Campign Member History Traking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member History Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Campign_Member_History_Trakings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Changed_Field__c.field-meta.xml
<CustomField>
    <fullName>Changed_Field__c</fullName>
    <label>Changed Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Changed_value__c.field-meta.xml
<CustomField>
    <fullName>Changed_value__c</fullName>
    <label>Changed value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_name_from_leadcapture__c.field-meta.xml
<CustomField>
    <fullName>Campaign_name_from_leadcapture__c</fullName>
    <label>Campaign name from leadcapture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMap__c/InferralSolutionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Lead</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Banking and insurance</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Recruitment and HR</fullName>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/CampaignMemberHandlerTest.cls
/**
 * Created by Alon.Shalev on 11/20/2023.
 */

@isTest
public class CampaignMemberHandlerTest {
  @testSetup
  static void setup() {
    Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
    iss.Name = 'Default Value';
    iss.Value__c = 'Sales';
    insert iss;

    InferralSolutionMap__c ismTest = new InferralSolutionMap__c();
    ismTest.SW_Industry__c = 'AdTech and AdNetwork';
    ismTest.Department__c = 'BI / Analytics';
    ismTest.Inferred_Solution__c = 'Research';
    ismTest.Name = 'test';
    insert ismTest;
  }

  //    @isTest
  //    static void testCampaignMemberInsertTrigger() {
  //        // Create test data for the Campaign Member insert trigger
  //        Campaign campaign = new Campaign(Name = 'Test Campaign');
  //        insert campaign;
  //        Lead lead = TestDataFactory.createLead();
  //        insert lead;
  //
  //        CampaignMember campaignMember = new CampaignMember(
  //                CampaignId = campaign.Id,
  //                LeadId = lead.Id,
  //                ContactId = null,
  //                Status = 'Sent'
  //        );
  //        insert campaignMember;
  //
  //        // Query the Campaign Member History Tracking records and add assertions as needed
  //        List<Campaign_Member_History_Tracking__c> historyRecords = [SELECT Id,Changed_Field__c FROM Campaign_Member_History_Tracking__c WHERE Event_Type__c = 'Created'];
  //        System.debug('historyRecords--'+historyRecords.size());
  //        System.assertEquals(false, historyRecords.isEmpty(), 'Expected 14 history record to be created for insert and the list is empty');
  //
  //        // Add more assertions as needed based on your specific requirements
  //    }

  @isTest
  static void testCampaignMemberUpdateTrigger() {
    // Create test data for the Campaign Member update trigger
    Campaign campaign = new Campaign(Name = 'Test Campaign');
    insert campaign;

    Lead lead = TestDataFactory.createLead();
    insert lead;

    CampaignMember campaignMember = new CampaignMember(
      CampaignId = campaign.Id,
      LeadId = lead.Id,
      ContactId = null,
      Status = 'Sent',
      Campaign_name_from_leadcapture__c = 'empty'
    );
    insert campaignMember;

    // Update the Campaign Member record
    campaignMember.Campaign_name_from_leadcapture__c = 'Updated Value';
    update campaignMember;

    // Query the Campaign Member History Tracking records and add assertions as needed
    List<Campaign_Member_History_Tracking__c> historyRecords = [
      SELECT
        Id,
        Changed_Field__c,
        Campaign__c,
        Original_Value__c,
        Changed_value__c
      FROM Campaign_Member_History_Tracking__c
      WHERE Event_Type__c = 'Updated'
      ORDER BY CreatedDate
    ];
    System.assertEquals(
      false,
      historyRecords.isEmpty(),
      'Expected at least 1 history records to be created for update'
    );
    System.assertEquals('empty', historyRecords[0].Original_Value__c);
    System.assertEquals('Updated Value', historyRecords[0].Changed_value__c);
    System.assertEquals(
      'Campaign_name_from_leadcapture__c',
      historyRecords[0].Changed_Field__c
    );
    System.assertEquals(campaign.Id, historyRecords[0].Campaign__c);

    // Add more assertions as needed based on your specific requirements
  }
}