force-app/main/default/objects/Campaign/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>If you promote multiple SW Solutions, select “Cross”</inlineHelpText>
    <label>Primary Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cross</fullName>
            </value>
            <value>
                <fullName>Web Intelligence</fullName>
            </value>
            <value>
                <fullName>Search Intelligence</fullName>
            </value>
            <value>
                <fullName>Stock Intelligence</fullName>
            </value>
            <value>
                <fullName>Sales Intelligence</fullName>
            </value>
            <value>
                <fullName>Shopper Intelligence</fullName>
            </value>
            <value>
                <fullName>DaaS</fullName>
            </value>
            <value>
                <fullName>App Intelligence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Update_Campaign_Members__c.field-meta.xml
<CustomField>
    <fullName>Update_Campaign_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MIS-7645</description>
    <label>Update Campaign Members</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_Description__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Description__c</fullName>
    <description>MIS-7645</description>
    <label>Campaign Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>#1112876 Need for the alert purpose</description>
    <formula>TEXT( Campaign.Type )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Description__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Description__c</fullName>
    <description>use this field whenever we will upload lists manually to Pardot and then push it to SFDC</description>
    <label>Campaign Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>MIS-7645</description>
    <label>Campaign Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign_Description__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Description__c</fullName>
    <description>use this field whenever we will upload lists manually to Pardot and then push it to SFDC
MIS 1032</description>
    <label>Campaign Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign_Solution__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Solution__c</fullName>
    <label>Campaign Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampaignBatchable.cls
public with sharing class CampaignBatchable implements Database.Batchable<SObject> {
  private Set<String> campaignIds;
  private List<Log_Event__e> logEventsList = new List<Log_Event__e>();

  public CampaignBatchable(Set<String> campaignIds) {
    this.campaignIds = campaignIds;
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      [
        SELECT
          Id,
          Description,
          LeadId,
          ContactId,
          Campaign.Description,
          Campaign.Solution__c,
          Campaign.Type,
          Lead.Status,
          Lead.IsConverted,
          CampaignId,
          Campaign_Description__c
        FROM CampaignMember
        WHERE CampaignId IN :this.campaignIds
      ]
    );
  }

  public void execute(Database.BatchableContext bc, List<SObject> scope) {
    List<CampaignMember> members = (List<CampaignMember>) scope;
    List<Lead> updatedLeads = new List<Lead>();
    List<Contact> updatedContacts = new List<Contact>();
    Set<String> scopeCampaignIds = new Set<String>();

    for (CampaignMember m : members) {
      String description = m.Campaign.Description,
        solution = m.Campaign.Solution__c,
        type = m.Campaign.Type;
      scopeCampaignIds.add(m.CampaignId);
      m.Campaign_Description__c = description;

      if (m.LeadId != null && !m.Lead.IsConverted) {
        updatedLeads.add(
          new Lead(
            Id = m.LeadId,
            Campaign_Description__c = description,
            Campaign_Solution__c = solution,
            Campaign_Type__c = type
          )
        );
      }
      if (m.ContactId != null) {
        updatedContacts.add(
          new Contact(
            Id = m.ContactId,
            Campaign_Description__c = description,
            Campaign_Solution__c = solution,
            Campaign_Type__c = type
          )
        );
      }
    }

    List<Campaign> campaignsToUpdate = new List<Campaign>();
    for (String cId : scopeCampaignIds) {
      campaignsToUpdate.add(
        new Campaign(Id = cId, Update_Campaign_Members__c = false)
      );
    }

    try {
      update members;
      update campaignsToUpdate;
      if (!updatedLeads.isEmpty()) {
        update updatedLeads;
      }
      if (!updatedContacts.isEmpty()) {
        update updatedContacts;
      }
    } catch (Exception e) {
      logEventsList.add(
        LogEventUtils.createLogEventRecord(
          members,
          'CampaignBatchable',
          'execute',
          JSON.serialize(members),
          e.getMessage(),
          'Error',
          null,
          null
        )
      );
    }

    if (!logEventsList.isEmpty()) {
      Eventbus.publish(logEventsList);
    }
  }

  public void finish(Database.BatchableContext bc) {
  }
}