force-app/main/default/objects/Case/fields/Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Type__c</fullName>
    <description>MIS-6324</description>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Quote Metrics</fullName>
            </value>
            <value>
                <fullName>Zuora Integration</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
            <value>
                <fullName>Sync Issues</fullName>
            </value>
            <value>
                <fullName>Permissions</fullName>
            </value>
            <value>
                <fullName>Visibility</fullName>
            </value>
            <value>
                <fullName>New Item</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Validation Error</fullName>
            </value>
            <value>
                <fullName>Company Name/Address Change - Open Balance</fullName>
            </value>
            <value>
                <fullName>Company Address Change - Country</fullName>
            </value>
            <value>
                <fullName>Subsidiary Change - Outside SWMB Policy</fullName>
            </value>
            <value>
                <fullName>Change Payment Method  - Mid Term</fullName>
            </value>
            <value>
                <fullName>Amend License Fees</fullName>
            </value>
            <value>
                <fullName>Amend Payment Terms</fullName>
            </value>
            <value>
                <fullName>Amend Payment Frequency</fullName>
            </value>
            <value>
                <fullName>Amend Address</fullName>
            </value>
            <value>
                <fullName>Amend Customer Name</fullName>
            </value>
            <value>
                <fullName>Amend Currency</fullName>
            </value>
            <value>
                <fullName>Replace Contract (Multiple Contracts Signed)</fullName>
            </value>
            <value>
                <fullName>Reassignment</fullName>
            </value>
            <value>
                <fullName>Customer Routing</fullName>
            </value>
            <value>
                <fullName>Internal Escalation</fullName>
            </value>
            <value>
                <fullName>Customer NDA</fullName>
            </value>
            <value>
                <fullName>Customer MSA</fullName>
            </value>
            <value>
                <fullName>Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Waterfall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Do_Not_Reopen__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Reopen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MIS-6802</description>
    <label>Do Not Reopen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Original_Requester__c.field-meta.xml
<CustomField>
    <fullName>Original_Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Cases (Original Requester)</relationshipLabel>
    <relationshipName>Child_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requester</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FeedCommentHandler.cls
/**
 * Created by Alon.Shalev on 10/20/2024.
 */

public with sharing class FeedCommentHandler {
  public void callFlowWhenCaseRelated(List<FeedComment> newList) {
    Map<String, Object> inputs = new Map<String, Object>();
    List<FeedComment> relevantFeedComments = new List<FeedComment>();
    Set<Id> caseIds = new Set<Id>();

    for (FeedComment comment : newList) {
      String parentId = comment.ParentId;
      if (parentId.startsWith('500')) {
        relevantFeedComments.add(comment);
        caseIds.add(parentId);
      }
    }
    if (!relevantFeedComments.isEmpty()) {
      Map<Id, Case> relatedCasesMap = new Map<Id, Case>(
        [
          SELECT
            Id,
            CaseNumber,
            Subject,
            Status,
            type,
            RecordType.Name,
            Case_Sub_Type__c,
            Requester__r.profile.Name,
            Requester__c,
            Do_Not_Reopen__c,
            Original_Requester__c
          FROM Case
          WHERE Id IN :caseIds
        ]
      );
      Map<Id, FlowParamsObj> flowParamMap = new Map<Id, FlowParamsObj>();
      for (FeedComment feedComment : relevantFeedComments) {
        if (!flowParamMap.containsKey(feedComment.Id)) {
          flowParamMap.put(feedComment.Id, new FlowParamsObj());
        }
        FlowParamsObj thisFlowObj = flowParamMap.get(feedComment.Id);
        thisFlowObj.caseItem = relatedCasesMap.get(feedComment.ParentId);
        thisFlowObj.feedComment = feedComment;
      }
      system.debug('hello tal');
      inputs.put('JSON_Collection', flowParamMap.values()[0]);
      Flow.Interview myFlow = new Flow.Interview.FeedComment_AL_New_Comment_On_Case(
        inputs
      );
      system.debug('hello tal2 -- ' + inputs);
      myFlow.start();
      system.debug('hello tal3 -- ' + inputs);
    }
  }
}