force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please add the relevant quote for you deal</inlineHelpText>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <businessProcess>Billing</businessProcess>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Legal.recordType-meta.xml
<RecordType>
    <fullName>Legal</fullName>
    <active>true</active>
    <businessProcess>Legal</businessProcess>
    <label>Legal</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Signature_date__c.field-meta.xml
<CustomField>
    <fullName>Signature_date__c</fullName>
    <label>Signature date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Zuora_Quote__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zuora Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Green_Lane_Document__c.field-meta.xml
<CustomField>
    <fullName>Green_Lane_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked By Billing when final version approved</description>
    <label>Green Lane Document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1113759 populates manually</description>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>FA with analyst/eng</fullName>
            </value>
            <value>
                <fullName>Pending Client</fullName>
            </value>
            <value>
                <fullName>Pending GTM</fullName>
            </value>
            <value>
                <fullName>Pending finance</fullName>
            </value>
            <value>
                <fullName>Pending Dragons</fullName>
            </value>
            <value>
                <fullName>In R&amp;D process</fullName>
            </value>
            <value>
                <fullName>DaaS to Deliver - Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed lost</fullName>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Account Preliminary Interest</fullName>
            </value>
            <value>
                <fullName>Actively Working</fullName>
            </value>
            <value>
                <fullName>Approved By Billing</fullName>
            </value>
            <value>
                <fullName>Assigned to SE/CSA</fullName>
            </value>
            <value>
                <fullName>Building Presentation</fullName>
            </value>
            <value>
                <fullName>Feasibility Pending</fullName>
                <label>Checking feasibility &amp; estimating effort</label>
            </value>
            <value>
                <fullName>Client Approval received</fullName>
                <label>Client Approval</label>
            </value>
            <value>
                <fullName>Client interest confirmed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Completed (sent to billing)</fullName>
            </value>
            <value>
                <fullName>Data Set Trial</fullName>
            </value>
            <value>
                <fullName>Data Set Trial - Evaluation</fullName>
            </value>
            <value>
                <fullName>Effort estimated</fullName>
            </value>
            <value>
                <fullName>Feasibility assessment (with Analysts / Engineers)</fullName>
            </value>
            <value>
                <fullName>Feasibility Confirmed</fullName>
            </value>
            <value>
                <fullName>Full Brief received</fullName>
            </value>
            <value>
                <fullName>Initiated - Future deliveries remaining</fullName>
            </value>
            <value>
                <fullName>Not Feasible</fullName>
            </value>
            <value>
                <fullName>Pending Rep To Adjust Quote</fullName>
                <label>Pending Requester</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Legal_Services.recordType-meta.xml
<RecordType>
    <fullName>Legal_Services</fullName>
    <active>false</active>
    <label>Legal Services</label>
</RecordType>

force-app/main/default/classes/FileUploadController.cls
public with sharing class FileUploadController {

    @AuraEnabled
    public static void validate(String quoteId, Boolean isFinalContract){
        System.debug('validate----'+quoteId);
        System.debug(isFinalContract);
        String quoteKeyPrefix = zqu__Quote__c.SObjectType.getDescribe().getKeyPrefix();
        String parameterPrefix = quoteId.substring(0, 3);
        Boolean isQuoteId = (quoteKeyPrefix == parameterPrefix);
        if(isQuoteId){
            if(isFinalContract){
                Set<String> quoteStatusSet = new Set<String>{
                    'Terms Pending',
                    'Pending Legal Or Billing request',
                    'Deal Size Pending',
                    'Pending Rep To Adjust Quote'
                };
                zqu__Quote__c quote = [SELECT id, zqu_Quote_Status__c, zqu__PaymentMethod__c FROM zqu__Quote__c WHERE id =: quoteId];
                
                if(quoteStatusSet.contains(quote.zqu_Quote_Status__c) && quote.zqu__PaymentMethod__c == 'Other') {
                    throw new UploadDocumentException('The signed version of the contract can only be uploaded after the quote has been finalized and approved');
                }
            }
        }
    }

    @AuraEnabled
    public static String getUserProfileName() {
        User u = [SELECT Profile.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        return u.Profile.Name;
    }

    @AuraEnabled
    public static void setLookup(String filesJson, String quoteId, String oppId, Date signDate, Boolean isFinalContract) {
        Id recordId = quoteId;

        String sobjectType = recordId.getSObjectType().getDescribe().getName();
        boolean isFromCase = sobjectType == 'Case';

        quoteId = replaceRecordWithQuote(quoteId);
        
        List<Object> files = (List<Object>)JSON.deserializeUntyped(filesJson);
        List<ContentDocumentLink> contDocLinks = new List<ContentDocumentLink>();

        Set<String> fileIdSet = new Set<String>();
        Set<String> cntVSIdSet = new Set<String>();
        
        for(Object obj : files){
            Map<String,Object> file = (Map<String,Object>)obj;
            fileIdSet.add(String.valueOf(file.get('documentId')));
        }

        for(String fileId : fileIdSet){
            ContentDocumentLink cdlOpp = new ContentDocumentLink(ContentDocumentId=fileId,LINKEDENTITYID = oppId);
            contDocLinks.add(cdlOpp);
            if(isFromCase){
                System.debug('creating contentDocumentLink related to the quote');
                ContentDocumentLink cdlQuote = new ContentDocumentLink(ContentDocumentId=fileId,LINKEDENTITYID = quoteId);
                contDocLinks.add(cdlQuote);
            }
        }

        insert contDocLinks;

        List<ContentDocument> contDocs = [SELECT Id, LatestPublishedVersionId FROM ContentDocument WHERE Id IN :fileIdSet];



        for(ContentDocument doc : contDocs){
            cntVSIdSet.add(doc.LatestPublishedVersionId);
        }

        List<ContentVersion> docs = [SELECT Id, Zuora_Quote__c, Signature_date__c FROM ContentVersion WHERE Id IN :cntVSIdSet];

        System.debug(docs);
        System.debug(cntVSIdSet);

        for(ContentVersion doc : docs){
            doc.Zuora_Quote__c = quoteId;
        }
        ZQuoteContentVersionService.setSignatureDate(docs, signDate);
        ZQuoteContentVersionService.changeQuotefields(docs, isFinalContract);
        update docs;

        //updateQuoteToGreenLine(quoteId);
    }


//    private static void updateQuoteToGreenLine(String quoteId){
//
//        List<ContentDocumentLink> cdlList = [SELECT Id
//                , ContentDocument.OwnerId
//                , ContentDocument.Owner.Name
//                , ContentDocument.Owner.Profile.Name
//                , ContentDocument.LatestPublishedVersionId
//        FROM ContentDocumentLink
//        WHERE LinkedEntityId = :quoteId
//        ORDER BY ContentDocument.LastModifiedDate DESC];
//        if(cdlList.size() > 0){
//            Set<String> profileNameSet = new Set<String>{
//                'SW Legal',
//                'SW Billing',
//                'System Administrator'
//            };
//
//            /* Check if all related requests to the zqu__Quote__c are completed and Green_Lane_Document__c checkbox is checked.
//            *  Condition described in the MQ-1157 ticket
//            */
//            List<Request__c> requestList = [SELECT Id, RecordType.DeveloperName, Status__c,Green_Lane_Document__c FROM Request__c WHERE Quote__c =: quoteId];
//            Boolean legalRequestsNotExists = requestList.isEmpty();
//            Boolean allLegalRequestsCompleted = true;
//            if(legalRequestsNotExists == false){
//                for(Request__c request: requestList){
//                    if(
//                        request.RecordType.DeveloperName == 'Legal_Services' &&
//                        request.Status__c.contains('Completed') &&
//                        request.Green_Lane_Document__c == true
//                    ){
//                        continue;
//                    } else {
//                        allLegalRequestsCompleted = false;
//                        break;
//                    }
//                }
//            } else {
//                allLegalRequestsCompleted = false;
//            }
//
//            zqu__Quote__c quoteToUpdate = new zqu__Quote__c();
//            quoteToUpdate.Id = quoteId;
////            quoteToUpdate.Contract_Upload_Reason__c = longTextValue;
//            String contractOwnerName = cdlList[0].ContentDocument.Owner.Name;
//            String contractOwnerProfile = cdlList[0].ContentDocument.Owner.Profile.Name;
//
//            /*Check, if by first scenario the all Request__c records, related to the zqu__Quote are 'Completed'
//             * and the Contract (Document) was uploaded by one of the SW profile
//             */
//            Boolean isAllRequestCompletedAndContractUploadedBySWProfile = profileNameSet.contains(contractOwnerProfile) && allLegalRequestsCompleted;
//
//            /*Check, if by second scenario the Contract, related to the zqu__Quote, was generated auotmatically
//             * and no related Request__c records to the zqu__Quote__c exists
//             */
//            Boolean isContractGeneratedWithoutRequests = contractOwnerName.containsIgnoreCase('Salesforce Admin') && legalRequestsNotExists;
//
//            if(isAllRequestCompletedAndContractUploadedBySWProfile || isContractGeneratedWithoutRequests){
//                quoteToUpdate.Q2C_Green_Lane__c = true;
//            } else {
//                quoteToUpdate.Q2C_Green_Lane__c = false;
//            }
//            update quoteToUpdate;
//        }
//    }

    private static String replaceRecordWithQuote(String quoteId){
        Id recordId = quoteId;
        String sobjectType = recordId.getSObjectType().getDescribe().getName();

        if(sobjectType == 'Request__c'){
            Request__c relatedRequest = [
                SELECT
                    id,
                    Quote__c
                FROM Request__c
                WHERE Id =: recordId
                LIMIT 1
            ];
            if(String.isNotBlank(relatedRequest.Quote__c)){
                quoteId = relatedRequest.Quote__c;
            } else {
                throw new QuoteOppFilesException('There is no associated quote for this request');
            }

        }
        if(sobjectType == 'Case'){
            Case caseItem = [SELECT Id,Quote__c FROM Case WHERE Id = : recordId];
            if(String.isNotBlank(caseItem.Quote__c)){
                quoteId = caseItem.Quote__c;
            } else {
                throw new QuoteOppFilesException('There is no associated quote for this caseItem');
            }

        }
        return quoteId;
    }

    public class QuoteOppFilesException extends Exception {
	
    }

    private class UploadDocumentException extends Exception {

    }
}