force-app/main/default/objects/ZuoraContractPaymentTermMD__mdt/ZuoraContractPaymentTermMD__mdt.object-meta.xml
<CustomObject>
    <label>ZuoraContractPaymentTermMD</label>
    <pluralLabel>ZuoraContractPaymentTermMDs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZuoraContractPaymentTermMD__mdt/fields/Initial_Term__c.field-meta.xml
<CustomField>
    <fullName>Initial_Term__c</fullName>
    <label>Initial Term</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZuoraContractPaymentTermMD__mdt/fields/JP_parent_name__c.field-meta.xml
<CustomField>
    <fullName>JP_parent_name__c</fullName>
    <label>JP parent name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gaprise Collections</fullName>
                <default>true</default>
                <label>Gaprise Collections</label>
            </value>
            <value>
                <fullName>Gaprise Direct Contract USD</fullName>
            </value>
            <value>
                <fullName>Gaprise inc.</fullName>
            </value>
            <value>
                <fullName>SW Japan Direct Account</fullName>
            </value>
            <value>
                <fullName>Gaprise Direct Contract JPY</fullName>
            </value>
            <value>
                <fullName>SW Japan Direct Account JPY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraContractPaymentTermMD__mdt/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
                <default>true</default>
                <label>Annual</label>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Every 2 Years</fullName>
            </value>
            <value>
                <fullName>Every 3 years</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Full Term</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraContractPaymentTermMD__mdt/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Upon Receipt</fullName>
                <default>true</default>
                <label>Due Upon Receipt</label>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 50</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
            <value>
                <fullName>Net 180</fullName>
            </value>
            <value>
                <fullName>EOM + 30</fullName>
            </value>
            <value>
                <fullName>Other (non - Standard)</fullName>
            </value>
            <value>
                <fullName>EOM + 45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraContractPaymentTermMD__mdt/fields/Payment_Term_Contract__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Contract__c</fullName>
    <label>Payment Term Contract</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ContractPaymentTermService.cls
public class ContractPaymentTermService {
    
    public static String obtainContractTerm(String paymentFrequency, Decimal initialTerm, String paymentType, String paymentTerm, String jpParentName){
        String result = '';
        String error = '';
        String paymentTermId = 'PAYMENT_TERM_VALUE';
        List<ZuoraContractPaymentTermMD__mdt> contractPaymentTermList = [SELECT Id, Payment_Term_Contract__c
                                                                         FROM ZuoraContractPaymentTermMD__mdt 
                                                                         WHERE Payment_Frequency__c =: paymentFrequency AND 
                                                                         Initial_Term__c = :initialTerm AND 
                                                                         Payment_Term__c = :paymentTerm AND 
                                                                         Payment_Type__c =:paymentType AND
                                                                         JP_parent_name__c =: jpParentName
                                                                         LIMIT 1];
        if(contractPaymentTermList.isEmpty()){
            return error;
        } else {
            if (String.isNotBlank(paymentTerm)) {
                result = contractPaymentTermList[0].Payment_Term_Contract__c.replace(paymentTermId, paymentTerm.toLowerCase());
            }
            return result;
        }
    }
    
}