force-app/main/default/objects/BillingAccountManagerSettings__c/BillingAccountManagerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Billing Account Manager Settings</label>
</CustomObject>

force-app/main/default/objects/BillingAccountManagerSettings__c/fields/HasAdminPermissions__c.field-meta.xml
<CustomField>
    <fullName>HasAdminPermissions__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Has Admin Permissions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BillingAccountManagerSettings__c/fields/ReturnToPage__c.field-meta.xml
<CustomField>
    <fullName>ReturnToPage__c</fullName>
    <defaultValue>&quot;Billing Account&quot;</defaultValue>
    <label>Return To Page</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingAccountManagerSettings__c/fields/UseNewHPM__c.field-meta.xml
<CustomField>
    <fullName>UseNewHPM__c</fullName>
    <defaultValue>&quot;Yes&quot;</defaultValue>
    <label>Use New HPM</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ManagerSettingsController.cls
public with sharing class ManagerSettingsController {

    public List<SelectOption> profileOptions {get;set;}
    public String selectedProfile {get;set;}
    public BillingAccountManagerSettings__c managerSettings {get;set;}
    private BillingAccountManagerSettings__c userSettings;
    public Boolean isAdmin {get;set;}
    private List<Profile> tenantProfiles = new List<Profile>();
    private final String DEFAULT_SETTINGS_LABEL = '--Organizational Default Settings--';
    public final String DEFAULT_SETTINGS_VALUE {get;set;}
    private String returnToLevel;
    private String newHPM;

    public ManagerSettingsController() {
        userSettings = BillingAccountManagerSettings__c.getInstance(UserInfo.getProfileId());
        isAdmin = userSettings.hasAdminPermissions__c;
        DEFAULT_SETTINGS_VALUE = 'Default';
        profileOptions = new List<SelectOption>();
        tenantProfiles = [Select Id, Name FROM Profile];
        createProfileOptions(tenantProfiles);
        managerSettings = BillingAccountManagerSettings__c.getOrgDefaults();
        selectedProfile = DEFAULT_SETTINGS_VALUE;
        returnToLevel = managerSettings.ReturnToPage__c;
        newHPM = managerSettings.UseNewHpm__c;

    }

    private void createProfileOptions(List<Profile> profileList){
        profileOptions.add(new SelectOption(DEFAULT_SETTINGS_VALUE, DEFAULT_SETTINGS_LABEL));
        for (Profile profile : profileList){
            profileOptions.add(new SelectOption(profile.Id, profile.Name));
        }
    }

    public void changeProfile(){
        if (selectedProfile == DEFAULT_SETTINGS_VALUE){
            managerSettings = BillingAccountManagerSettings__c.getOrgDefaults();
        } else {
            managerSettings = BillingAccountManagerSettings__c.getInstance(selectedProfile);
        }
        managerSettings.ReturnToPage__c = returnToLevel;
        managerSettings.UseNewHPM__c = newHPM;
    }

    public void saveSettings(){
        if (managerSettings.SetupOwnerId == null && selectedProfile != DEFAULT_SETTINGS_VALUE){
            managerSettings.SetupOwnerId = selectedProfile;
        }
        upsert managerSettings;
    }

    public void setToDefault(){
        if (selectedProfile != DEFAULT_SETTINGS_VALUE && managerSettings.Id != null){
            delete managerSettings;
            managerSettings = BillingAccountManagerSettings__c.getInstance(selectedProfile);
        }
    }
}