force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Distribution_Handled__c.field-meta.xml
<CustomField>
    <fullName>Is_Distribution_Handled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A technical field that helps marketing cloud distribution</description>
    <label>Is Distribution Handled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/SFMC_Processed_by_Distribution__c.object-meta.xml
<CustomObject>
    <description>jira - SFMC-23
custom setting that decide the precent of leads by solution will be processed by SFMC system. the rest of the leads of the solution will be processed in pardot</description>
    <label>SFMC Processed by Distribution</label>
    <nameField>
        <label>SFMC Processed by Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFMC Processed by Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/fields/Initial_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Date__c</fullName>
    <label>Initial Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/fields/Processed_by_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Processed_by_SFMC__c</fullName>
    <label>Processed by SFMC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/LeadDistributionBatchTest.cls
/**
 * @author Zohar Sinay
 * @date 22/11/2021
 * @description Distribute leads to marketing cloud and pardot lead test
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      -
 * date        -
 * description -
 * --------------------------------------------------------------------------------------
 */

@istest
public with sharing class LeadDistributionBatchTest {
  @testSetup
  static void setup() {
    Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
    iss.Name = 'Default Value';
    iss.Value__c = 'Sales';
    insert iss;

    SFMC_Processed_by_Distribution__c processedByDistribution = setDistribution(
      20,
      0,
      'Sales'
    );
    insert processedByDistribution;
    SFMC_Processed_by_Distribution__c processedByDistribution1 = setDistribution(
      10,
      1,
      'Investors'
    );
    insert processedByDistribution1;
    SFMC_Processed_by_Distribution__c processedByDistribution2 = setDistribution(
      20,
      2,
      'Research'
    );
    insert processedByDistribution2;
    SFMC_Processed_by_Distribution__c processedByDistribution3 = setDistribution(
      30,
      3,
      'Marketing'
    );
    insert processedByDistribution3;
    SFMC_Processed_by_Distribution__c processedByDistribution4 = setDistribution(
      40,
      4,
      'Sales (SI)'
    );
    insert processedByDistribution4;
    SFMC_Processed_by_Distribution__c processedByDistribution5 = setDistribution(
      50,
      5,
      'Agency (MI)'
    );
    insert processedByDistribution5;
    SFMC_Processed_by_Distribution__c processedByDistribution6 = setDistribution(
      60,
      6,
      'Investors (II)'
    );
    insert processedByDistribution6;
    SFMC_Processed_by_Distribution__c processedByDistribution7 = setDistribution(
      70,
      7,
      'Publishers & Media'
    );
    insert processedByDistribution7;
    SFMC_Processed_by_Distribution__c processedByDistribution8 = setDistribution(
      80,
      8,
      'AI / PI'
    );
    insert processedByDistribution8;
    SFMC_Processed_by_Distribution__c processedByDistribution9 = setDistribution(
      90,
      9,
      'Marketing (MI)'
    );
    insert processedByDistribution9;
  }

  @isTest
  static void createDistributionedLeads0() {
    Lead lead1 = new Lead(
      LastName = 'Test 1',
      Company = 'Test comp',
      email = 'jumbo101@mumbo.com',
      Inferred_Solution__c = 'Sales',
      Is_Distribution_Handled__c = true
    );

    List<Lead> leadList = new List<Lead>();
    for (Integer i = 0; i < 3; i++) {
      leadList.add(
        new Lead(
          LastName = 'Test ' + i,
          Company = 'Test comp' + i,
          email = 'jumbo' + i + '@mumbo.com',
          Inferred_Solution__c = 'Sales'
        )
      );
    }

    insert lead1;
    DateTime obsoleteDate = Datetime.now().addMinutes(-15);
    Test.startTest();
    insert leadList;
    LeadDistributionBatch ldb = new LeadDistributionBatch();
    Database.executebatch(ldb, 5);
    Test.stopTest();
  }

  private static SFMC_Processed_by_Distribution__c setDistribution(
    Decimal SFMCPercent,
    Decimal counter,
    String solution
  ) {
    return new SFMC_Processed_by_Distribution__c(
      Processed_by_SFMC__c = SFMCPercent,
      Initial_Date__c = date.today() - 1,
      Counter__c = counter,
      Solution__c = solution
    );
  }
}