force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Manual_Unsync_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Manual_Unsync_SFMC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Unsync SFMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Pro_User_Type__c.field-meta.xml
<CustomField>
    <fullName>Pro_User_Type__c</fullName>
    <label>Pro User Type Old field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>SW_Fit_Score__c</fullName>
    <label>SW Fit Score</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/UnsyncMarketingCloudLeadsBatchTest.cls
/**
 * Created by zohar.sinay on 08/06/2023.
 */
@isTest
public with sharing class UnsyncMarketingCloudLeadsBatchTest {
  @TestSetup
  static void setup() {
    Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
    iss.Name = 'Default Value';
    iss.Value__c = 'Sales';
    insert iss;
  }

  static testMethod void testLeadBatch() {
    // Create test data
    List<Lead> leads = new List<Lead>();
    leads.add(
      new Lead(
        LastName = 'Test1',
        Company = 'TestCo1',
        Email = 'alon@sostupid.com',
        Status = 'Open - Not Contacted',
        Sync_to_Sfmc__c = true,
        Pro_User_Type__c = 'Demo',
        Manual_Unsync_SFMC__c = false,
        Employees_Min__c = 5,
        SW_Fit_Score__c = 'e'
      )
    );
    leads.add(
      new Lead(
        LastName = 'Test2',
        Company = 'TestCo2',
        Email = 'alon@sostupids.com',
        Status = 'Open - Not Contacted',
        Sync_to_Sfmc__c = true,
        Pro_User_Type__c = 'Demo',
        Manual_Unsync_SFMC__c = false,
        Employees_Min__c = 5,
        SW_Fit_Score__c = 'e'
      )
    );
    insert leads;

    // Set CreatedDate to a date in 2021
    DateTime createdDate = DateTime.newInstance(2021, 2, 1);
    Test.setCreatedDate(leads[0].Id, createdDate);
    Test.setCreatedDate(leads[1].Id, createdDate);

    // Convert the first Lead
    Database.LeadConvert lc = new Database.LeadConvert();
    lc.setLeadId(leads[0].Id);
    lc.setConvertedStatus('Qualified');
    Database.LeadConvertResult lcr = Database.convertLead(lc);
    System.assert(lcr.isSuccess());

    // Execute the batch job
    Test.startTest();
    UnsyncMarketingCloudLeadsBatch leadBatch = new UnsyncMarketingCloudLeadsBatch();
    ID batchProcessId = Database.executeBatch(leadBatch, 1);
    Test.stopTest();

    // Assert that only the first Lead was updated
    List<Lead> updatedLeads = [
      SELECT Id, Manual_Unsync_SFMC__c
      FROM Lead
      WHERE Manual_Unsync_SFMC__c = TRUE
    ];
    System.assertEquals(
      1,
      updatedLeads.size(),
      'Incorrect number of Leads updated'
    );
    System.assertEquals(
      leads[1].Id,
      updatedLeads[0].Id,
      'Incorrect Lead was updated'
    );
  }
}