force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Lead_To_Merge_Fields__c/Lead_To_Merge_Fields__c.object-meta.xml
<CustomObject>
    <description>A technical object in order to merge leads with No_Company or NA Last name.</description>
    <label>Lead To Merge</label>
    <nameField>
        <label>Lead To Merge Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads To Merge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_To_Merge_Fields__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Company field to merge</description>
    <label>Company</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead_To_Merge_Fields__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name to merge</description>
    <label>Last Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/SFMC_Processed_by_Distribution__c.object-meta.xml
<CustomObject>
    <description>jira - SFMC-23
custom setting that decide the precent of leads by solution will be processed by SFMC system. the rest of the leads of the solution will be processed in pardot</description>
    <label>SFMC Processed by Distribution</label>
    <nameField>
        <label>SFMC Processed by Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFMC Processed by Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/fields/Initial_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Date__c</fullName>
    <label>Initial Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/fields/Processed_by_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Processed_by_SFMC__c</fullName>
    <label>Processed by SFMC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TransferFromMergeToLeadBatchTest.cls
/**
 * Created by Alon.Shalev on 4/10/2023.
 */

@IsTest
private class TransferFromMergeToLeadBatchTest {
  @TestSetup
  static void setup() {
    // Create test data for Lead_To_Merge_Fields__c object
    List<Lead_To_Merge_Fields__c> testData = new List<Lead_To_Merge_Fields__c>();
    SFMC_Processed_by_Distribution__c processedByDistribution8 = setDistribution(
      80,
      8,
      'AI / PI'
    );
    insert processedByDistribution8;
    Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
    iss.Name = 'Default Value';
    iss.Value__c = 'Sales';
    insert iss;

    Lead lead1 = new Lead(
      LastName = 'ZoharIsStupid',
      Company = 'ABC Company 1',
      email = 'jumbo101@mumbo.com'
    );
    insert lead1;
    testData.add(
      new Lead_To_Merge_Fields__c(
        Name = lead1.id,
        Last_Name__c = 'Smith',
        Company__c = 'ABC Company'
      )
    );
    insert testData;
  }

  @IsTest
  static void testBatchJob() {
    // Start batch job
    Test.startTest();
    TransferFromMergeToLeadBatch batchJob = new TransferFromMergeToLeadBatch();
    Database.executeBatch(batchJob);
    Test.stopTest();
  }
  private static SFMC_Processed_by_Distribution__c setDistribution(
    Decimal SFMCPercent,
    Decimal counter,
    String solution
  ) {
    return new SFMC_Processed_by_Distribution__c(
      Processed_by_SFMC__c = SFMCPercent,
      Initial_Date__c = date.today() - 1,
      Counter__c = counter,
      Solution__c = solution
    );
  }

  @IsTest
  static void testScheduledJob() {
    Test.startTest();
    String CRON_EXP = '0 0 0 3 9 ? 2100';
    System.schedule(
      'TransferFromMergeToLeadBatchTest',
      CRON_EXP,
      new TransferFromMergeToLeadBatch()
    );
    Test.stopTest();
  }
}