force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/SFMC_Processed_by_Distribution__c.object-meta.xml
<CustomObject>
    <description>jira - SFMC-23
custom setting that decide the precent of leads by solution will be processed by SFMC system. the rest of the leads of the solution will be processed in pardot</description>
    <label>SFMC Processed by Distribution</label>
    <nameField>
        <label>SFMC Processed by Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFMC Processed by Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/fields/Initial_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Date__c</fullName>
    <label>Initial Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SFMC_Processed_by_Distribution__c/fields/Processed_by_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Processed_by_SFMC__c</fullName>
    <label>Processed by SFMC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FieldsToMergeTest.cls
@isTest
private class FieldsToMergeTest {

    @TestSetup
    static void setup() {
        SFMC_Processed_by_Distribution__c processedByDistribution8 = setDistribution(80, 8, 'AI / PI');
        insert processedByDistribution8;
        Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
        iss.Name='Default Value';
        iss.Value__c='Sales';
        insert iss;
    }


    private static SFMC_Processed_by_Distribution__c setDistribution(Decimal SFMCPercent, Decimal counter, String solution){
        return new SFMC_Processed_by_Distribution__c(
                Processed_by_SFMC__c = SFMCPercent,
                Initial_Date__c = date.today() - 1,
                Counter__c = counter,
                Solution__c = solution
        );
    }

    @isTest
    static void testFieldsToMerge() {

        // Create test data
        Lead lead1 = new Lead(
                LastName='Doe 1',
                Company='ABC Company 1',
                email='jumbo101@mumbo.com'
        );
        Lead lead2 = new Lead(
                LastName='Smith 2',
                Company='ABC Company 2',
                email='jumbo102@mumbo.com'
        );
        insert lead1;
        insert lead2;

        // Create input data for queueable

        // Enqueue the queueable
        FieldsToMerge queueable = new FieldsToMerge(new LeadCaptureService.leadCaptureWrapper());
        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

    }

    @isTest
    static void testFieldsToMergeWithVersion3() {

        // Create test data
        Lead lead1 = new Lead(
                LastName='Doe 1',
                Company='ABC Company 1',
                email='jumbo101@mumbo.com'
        );
        Lead lead2 = new Lead(
                LastName='Smith 2',
                Company='ABC Company 2',
                email='jumbo102@mumbo.com'
        );
        insert new List<Lead>{lead2,lead1};

        // Create input data for queueable

        // Enqueue the queueable
        FieldsToMerge queueable = new FieldsToMerge(new Map<String,Object>());
        Test.startTest();
        System.enqueueJob(queueable);
        Test.stopTest();

    }
}