force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>&quot;Bill to&quot;/&quot;Sold to&quot; Information</fullName>
            </value>
            <value>
                <fullName>Account Configuration</fullName>
            </value>
            <value>
                <fullName>Account Maintenance/Value</fullName>
            </value>
            <value>
                <fullName>Add SOW (for Advisory Services/Managed Services/DaaS)</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Training</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>API Dashboard</fullName>
            </value>
            <value>
                <fullName>API Integration</fullName>
            </value>
            <value>
                <fullName>Apps Android - Accuracy</fullName>
            </value>
            <value>
                <fullName>Apps Android - Coverage</fullName>
            </value>
            <value>
                <fullName>Apps IOS - Accuracy</fullName>
            </value>
            <value>
                <fullName>Apps IOS - Coverage</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
                <label>Basic Onboarding Package</label>
            </value>
            <value>
                <fullName>Best Practice Webinar</fullName>
            </value>
            <value>
                <fullName>Account Update request</fullName>
                <label>Billing Account Update Request</label>
            </value>
            <value>
                <fullName>Campaign Feature Upsell</fullName>
            </value>
            <value>
                <fullName>Campaign Trial</fullName>
            </value>
            <value>
                <fullName>Change Start/End Date</fullName>
            </value>
            <value>
                <fullName>Churn Prevention</fullName>
            </value>
            <value>
                <fullName>Client Breach</fullName>
            </value>
            <value>
                <fullName>Client Call (Not specific to a project)</fullName>
            </value>
            <value>
                <fullName>Client Red Lines</fullName>
            </value>
            <value>
                <fullName>Code of Conduct</fullName>
            </value>
            <value>
                <fullName>Conditional Trial</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Contact Data</fullName>
            </value>
            <value>
                <fullName>Contract Review request</fullName>
                <label>Contract Review Request</label>
            </value>
            <value>
                <fullName>Customer Success Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RequestActionService.cls
public class RequestActionService {
  @InvocableMethod(
    label='Create Zendesk ticket'
    description='Request to create a ticket in Zendesk'
    category='Request'
  )
  public static void createTicket(List<Id> requestId) {
    System.debug('### in RequestActionService');
    List<Request__c> requestList = [
      SELECT Id, Request_Type__c, RecordType.DeveloperName
      FROM Request__c
      WHERE Id IN :requestId
    ];
    if (!requestList.isEmpty()) {
      RequestDomain.createTicket(requestList);
    }
  }
}