force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>&quot;Bill to&quot;/&quot;Sold to&quot; Information</fullName>
            </value>
            <value>
                <fullName>Account Configuration</fullName>
            </value>
            <value>
                <fullName>Account Maintenance/Value</fullName>
            </value>
            <value>
                <fullName>Add SOW (for Advisory Services/Managed Services/DaaS)</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Training</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>API Dashboard</fullName>
            </value>
            <value>
                <fullName>API Integration</fullName>
            </value>
            <value>
                <fullName>Apps Android - Accuracy</fullName>
            </value>
            <value>
                <fullName>Apps Android - Coverage</fullName>
            </value>
            <value>
                <fullName>Apps IOS - Accuracy</fullName>
            </value>
            <value>
                <fullName>Apps IOS - Coverage</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
                <label>Basic Onboarding Package</label>
            </value>
            <value>
                <fullName>Best Practice Webinar</fullName>
            </value>
            <value>
                <fullName>Account Update request</fullName>
                <label>Billing Account Update Request</label>
            </value>
            <value>
                <fullName>Campaign Feature Upsell</fullName>
            </value>
            <value>
                <fullName>Campaign Trial</fullName>
            </value>
            <value>
                <fullName>Change Start/End Date</fullName>
            </value>
            <value>
                <fullName>Churn Prevention</fullName>
            </value>
            <value>
                <fullName>Client Breach</fullName>
            </value>
            <value>
                <fullName>Client Call (Not specific to a project)</fullName>
            </value>
            <value>
                <fullName>Client Red Lines</fullName>
            </value>
            <value>
                <fullName>Code of Conduct</fullName>
            </value>
            <value>
                <fullName>Conditional Trial</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Contact Data</fullName>
            </value>
            <value>
                <fullName>Contract Review request</fullName>
                <label>Contract Review Request</label>
            </value>
            <value>
                <fullName>Customer Success Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Ticket_number_in_Zendesk__c.field-meta.xml
<CustomField>
    <fullName>Ticket_number_in_Zendesk__c</fullName>
    <description>Populates only for Vendor_form at the moment</description>
    <label>Ticket number in Zendesk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Zendesk_Integration_Issue__c.field-meta.xml
<CustomField>
    <fullName>Zendesk_Integration_Issue__c</fullName>
    <description>Fields stores the error value if it happens during ticket creation in Zendesk</description>
    <label>Zendesk Integration Issue</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RequestTicketCreationQueueableTest.cls
@isTest
public class RequestTicketCreationQueueableTest {
  @TestSetup
  static void setup() {
    TestDataFactory.createSimilarWeb_CS();
    TestDataFactory.createBaseProductConfiguration_CS();
    TestDataFactory.createInferredSolutionSettings_CS();
    insert TestDataFactory.createBaseProductContract_CS();
    insert TestDataFactory.createBaseProductConfiguration_CS();
    insert TestDataFactory.createBaseProductControlling_CS();
    insert TestDataFactory.createBaseProductDependent_CS();
    insert TestDataFactory.createBaseProductDefaultAddon_CS();
    insert TestDataFactory.createBaseProductDynamicAddon_CS();
    insert TestDataFactory.createBaseProductNumOfUsers_CS();

    Account a = TestDataFactory.CreateAccount();
    a.billingcountry = 'Israel';
    insert a;
    Contact c = TestDataFactory.CreateContact(a, 'test@testing.com');
    c.MailingCountry = 'Israel';
    insert c;
    Opportunity opp = TestDataFactory.CreateOpportunity(a);
    opp.Type = 'New Sale';
    insert opp;
  }

  @isTest
  static void executeQueuebleJobSuccessTest() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
    Request__c rquest = TestDataFactory.createRequest(opp);
    MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
    insert rquest;
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, mock);
    Map<Id, ZendeskIntegrationService.ZendeskRequestWrapper> requestMap = generateRequestMap(
      new List<Request__c>{ rquest }
    );
    Test.setMock(HttpCalloutMock.class, mock);
    RequestTicketCreationQueueable ticketCreationJob = new RequestTicketCreationQueueable(
      requestMap,
      'Request__c'
    );
    ticketCreationJob.execute(null);
    Test.stopTest();
    rquest = [SELECT Id, Ticket_number_in_Zendesk__c FROM Request__c LIMIT 1];
    System.assert(String.isNotBlank(rquest.Ticket_number_in_Zendesk__c));
    System.assert(!rquest.Ticket_number_in_Zendesk__c.contains('Error'));
  }

  @isTest
  static void updateRequestByUnexpectedErrorTest() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
    Request__c rquest = TestDataFactory.createRequest(opp);
    insert rquest;
    Test.startTest();
    RequestTicketCreationQueueable ticketCreationJob = new RequestTicketCreationQueueable(
      null,
      'Request__c'
    );
    ticketCreationJob.updateRequestByUnexpectedError(
      new List<Id>{ rquest.Id },
      'Error'
    );
    Test.stopTest();
    rquest = [SELECT Id, Zendesk_Integration_Issue__c FROM Request__c LIMIT 1];
    System.assert(String.isNotBlank(rquest.Zendesk_Integration_Issue__c));
    System.assert(rquest.Zendesk_Integration_Issue__c.contains('Error'));
  }

  /* @date: 2021-11-15
   * @author: Itzik Winograd
   * @description: The error field was changed from Ticket_number_in_Zendesk__c to Zendesk_Integration_Issue__c
   */
  @isTest
  static void executeQueuebleJobFailTest() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
    Request__c rquest = TestDataFactory.createRequest(opp);
    MockUtil.ZendeskIntegrationServiceErrorHttpMock mock = new MockUtil.ZendeskIntegrationServiceErrorHttpMock();
    insert rquest;
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, mock);
    Map<Id, ZendeskIntegrationService.ZendeskRequestWrapper> requestMap = generateRequestMap(
      new List<Request__c>{ rquest }
    );
    Test.setMock(HttpCalloutMock.class, mock);
    RequestTicketCreationQueueable ticketCreationJob = new RequestTicketCreationQueueable(
      requestMap,
      'Request__c'
    );
    ticketCreationJob.execute(null);
    Test.stopTest();
    rquest = [SELECT Id, Zendesk_Integration_Issue__c FROM Request__c LIMIT 1]; //Ticket_number_in_Zendesk__c
    System.assert(String.isNotBlank(rquest.Zendesk_Integration_Issue__c)); //Ticket_number_in_Zendesk__c
    System.assert(rquest.Zendesk_Integration_Issue__c.contains('Error')); //Ticket_number_in_Zendesk__c
  }

  private static Map<Id, ZendeskIntegrationService.ZendeskRequestWrapper> generateRequestMap(
    List<Request__c> newList
  ) {
    Map<String, List<Id>> requestTypeToIdsMap = new Map<String, List<Id>>();
    for (Request__c request : newList) {
      if (requestTypeToIdsMap.containsKey(request.Request_Type__c)) {
        List<Id> requestIdList = requestTypeToIdsMap.get(
          request.Request_Type__c
        );
        requestIdList.add(request.Id);
        requestTypeToIdsMap.put(request.Request_Type__c, requestIdList);
      } else {
        requestTypeToIdsMap.put(
          request.Request_Type__c,
          new List<Id>{ request.Id }
        );
      }
    }
    Map<Id, ZendeskIntegrationService.ZendeskRequestWrapper> requestMap = ZendeskIntegrationService.generateTicketList(
      requestTypeToIdsMap,
      'Request__c'
    );

    return requestMap;
  }
}