force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1113759 populates manually</description>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Recipient_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Picklist__c</fullName>
    <label>Recipient</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aaron Feinblatt</fullName>
            </value>
            <value>
                <fullName>Aaron Wong</fullName>
            </value>
            <value>
                <fullName>Adam Wertheim</fullName>
            </value>
            <value>
                <fullName>Aidan Krakowsky</fullName>
            </value>
            <value>
                <fullName>Alexandre Koniecko</fullName>
            </value>
            <value>
                <fullName>Alex Donchenko</fullName>
            </value>
            <value>
                <fullName>Alex Donchenko (PS)</fullName>
            </value>
            <value>
                <fullName>Alisha Kapur</fullName>
            </value>
            <value>
                <fullName>Amit Ram</fullName>
            </value>
            <value>
                <fullName>Anand Ramanathan</fullName>
            </value>
            <value>
                <fullName>Anastasia Segal</fullName>
            </value>
            <value>
                <fullName>Andrea Girardello</fullName>
            </value>
            <value>
                <fullName>Andrew Bonnici</fullName>
            </value>
            <value>
                <fullName>Andrew Liu</fullName>
            </value>
            <value>
                <fullName>Anne-Christele Antoine</fullName>
            </value>
            <value>
                <fullName>Antonello Musina</fullName>
            </value>
            <value>
                <fullName>Aria Ertefaie</fullName>
            </value>
            <value>
                <fullName>Ariane Turley</fullName>
            </value>
            <value>
                <fullName>Ariel Even</fullName>
            </value>
            <value>
                <fullName>Ariella Magid</fullName>
            </value>
            <value>
                <fullName>Ariyeh Taitz</fullName>
            </value>
            <value>
                <fullName>Audrey Guilloux</fullName>
            </value>
            <value>
                <fullName>Aurore Miniatura</fullName>
            </value>
            <value>
                <fullName>Banke daCosta</fullName>
            </value>
            <value>
                <fullName>Becca Edelman</fullName>
            </value>
            <value>
                <fullName>Becca Edelman (EMEA)</fullName>
            </value>
            <value>
                <fullName>Becka Abram (M)</fullName>
            </value>
            <value>
                <fullName>Belinda Kwok</fullName>
            </value>
            <value>
                <fullName>Ben Fernando (EMEA)</fullName>
            </value>
            <value>
                <fullName>Ben Fernando (VAP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requester</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>FA with analyst/eng</fullName>
            </value>
            <value>
                <fullName>Pending Client</fullName>
            </value>
            <value>
                <fullName>Pending GTM</fullName>
            </value>
            <value>
                <fullName>Pending finance</fullName>
            </value>
            <value>
                <fullName>Pending Dragons</fullName>
            </value>
            <value>
                <fullName>In R&amp;D process</fullName>
            </value>
            <value>
                <fullName>DaaS to Deliver - Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed lost</fullName>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Account Preliminary Interest</fullName>
            </value>
            <value>
                <fullName>Actively Working</fullName>
            </value>
            <value>
                <fullName>Approved By Billing</fullName>
            </value>
            <value>
                <fullName>Assigned to SE/CSA</fullName>
            </value>
            <value>
                <fullName>Building Presentation</fullName>
            </value>
            <value>
                <fullName>Feasibility Pending</fullName>
                <label>Checking feasibility &amp; estimating effort</label>
            </value>
            <value>
                <fullName>Client Approval received</fullName>
                <label>Client Approval</label>
            </value>
            <value>
                <fullName>Client interest confirmed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Completed (sent to billing)</fullName>
            </value>
            <value>
                <fullName>Data Set Trial</fullName>
            </value>
            <value>
                <fullName>Data Set Trial - Evaluation</fullName>
            </value>
            <value>
                <fullName>Effort estimated</fullName>
            </value>
            <value>
                <fullName>Feasibility assessment (with Analysts / Engineers)</fullName>
            </value>
            <value>
                <fullName>Feasibility Confirmed</fullName>
            </value>
            <value>
                <fullName>Full Brief received</fullName>
            </value>
            <value>
                <fullName>Initiated - Future deliveries remaining</fullName>
            </value>
            <value>
                <fullName>Not Feasible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Legal_Services.recordType-meta.xml
<RecordType>
    <fullName>Legal_Services</fullName>
    <active>false</active>
    <label>Legal Services</label>
</RecordType>

force-app/main/default/classes/QuoteOppRequestsRelatedListController.cls
public with sharing class QuoteOppRequestsRelatedListController {
  private static final Integer MAX_SIZE = 15;

  @AuraEnabled
  public static Response obtainRequestsFromRelatedOpportunity(String quoteId) {
    Response response;
    try {
      Id relatedOpportunityId = obtainRelatedOpportunityId(quoteId);
      ResponseDataWrapper responseDataWrapper = new ResponseDataWrapper();
      List<RequestWrapper> requestWrapperList = new List<RequestWrapper>();

      List<Request__c> requestList = [
        SELECT
          Id,
          Name,
          RecordType.Name,
          Requester__c,
          Recipient_Picklist__c,
          LastModifiedDate,
          Status__c
        FROM Request__c
        WHERE Opportunity__c = :relatedOpportunityId
      ];
      for (Request__c request_i : requestList) {
        if (requestWrapperList.size() >= MAX_SIZE) {
          responseDataWrapper.isMoreRequests = true;
          break;
        }
        requestWrapperList.add(new RequestWrapper(request_i));
      }
      requestWrapperList.sort();
      responseDataWrapper.requestWrapperList = requestWrapperList;
      responseDataWrapper.relatedOpportunityId = relatedOpportunityId;
      response = new Response(responseDataWrapper);
    } catch (Exception ex) {
      response = new Response(ex.getMessage());
    }
    return response;
  }

  private static Id obtainRelatedOpportunityId(String quoteId) {
    if (String.isBlank(quoteId)) {
      throw new DMLException('Quote Id is empty');
    }
    zqu__Quote__c quote = [
      SELECT Id, zqu__Opportunity__c
      FROM zqu__Quote__c
      WHERE Id = :quoteId
    ];
    if (quote == null) {
      throw new DMLException('Quote not exist');
    }
    if (quote.zqu__Opportunity__c == null) {
      throw new DMLException('Quotes opportunity not exist');
    }
    return quote.zqu__Opportunity__c;
  }

  @AuraEnabled
  public static Response obtainRequestsFromRelatedQuote(String quoteId) {
    Response response;
    try {
      if (String.isBlank(quoteId)) {
        throw new DMLException('Quote Id is empty');
      }
      zqu__Quote__c quote = [
        SELECT Id, zqu__Opportunity__c
        FROM zqu__Quote__c
        WHERE Id = :quoteId
      ];
      if (quote == null) {
        throw new DMLException('Quote not exist');
      }
      Id relatedQuoteId = quoteId;
      ResponseDataWrapper responseDataWrapper = new ResponseDataWrapper();
      List<RequestWrapper> requestWrapperList = new List<RequestWrapper>();
      List<Request__c> requestList = [
        SELECT
          Id,
          Name,
          RecordType.Name,
          Requester__c,
          Recipient_Picklist__c,
          LastModifiedDate,
          Status__c
        FROM Request__c
        WHERE
          Quote__c = :relatedQuoteId
          AND RecordType.DeveloperName = 'Legal_Services'
      ];
      for (Request__c request_i : requestList) {
        if (requestWrapperList.size() >= MAX_SIZE) {
          responseDataWrapper.isMoreRequests = true;
          break;
        }
        requestWrapperList.add(new RequestWrapper(request_i));
      }
      requestWrapperList.sort();
      responseDataWrapper.requestWrapperList = requestWrapperList;
      responseDataWrapper.relatedOpportunityId = quote.zqu__Opportunity__c;
      responseDataWrapper.relatedQuoteId = relatedQuoteId;

      response = new Response(responseDataWrapper);
    } catch (Exception ex) {
      response = new Response(ex.getMessage());
    }

    return response;
  }

  private class ResponseDataWrapper {
    @AuraEnabled
    public List<RequestWrapper> requestWrapperList;

    @AuraEnabled
    public String relatedOpportunityId;

    @AuraEnabled
    public String relatedQuoteId;

    @AuraEnabled
    public Boolean isMoreRequests;

    public ResponseDataWrapper() {
      isMoreRequests = false;
    }
  }

  private class RequestWrapper implements Comparable {
    @AuraEnabled
    public Id recordId { get; set; }

    @AuraEnabled
    public String name { get; set; }

    @AuraEnabled
    public String recordTypeName { get; set; }

    @AuraEnabled
    public String requester { get; set; }

    @AuraEnabled
    public String recipient { get; set; }

    @AuraEnabled
    public String status { get; set; }

    @AuraEnabled
    public Datetime lastModifiedDate { get; set; }

    public RequestWrapper(Request__c request) {
      this.recordId = request.Id;
      this.name = request.Name;
      this.recordTypeName = request.RecordType.Name;
      this.requester = request.Requester__c;
      this.recipient = request.Recipient_Picklist__c;
      this.status = request.Status__c;
      this.lastModifiedDate = request.LastModifiedDate;
    }

    public Integer compareTo(Object compareTo) {
      RequestWrapper compareToRw = (RequestWrapper) compareTo;
      if (lastModifiedDate == compareToRw.lastModifiedDate)
        return 0;
      if (lastModifiedDate < compareToRw.lastModifiedDate)
        return 1;
      return -1;
    }
  }
}