force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/List_price__c.field-meta.xml
<CustomField>
    <fullName>List_price__c</fullName>
    <inlineHelpText>For AS request - This field refers to &apos;Full AS Contract Price&apos;</inlineHelpText>
    <label>List Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1113759 populates manually</description>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Regularity__c.field-meta.xml
<CustomField>
    <fullName>Regularity__c</fullName>
    <label>Delivery Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One time</fullName>
            </value>
            <value>
                <fullName>Recurring Quarterly</fullName>
                <label>Recurring - Quarterly</label>
            </value>
            <value>
                <fullName>Recurring Monthly</fullName>
                <label>Recurring - Monthly</label>
            </value>
            <value>
                <fullName>Recurring - Ad Hoc</fullName>
            </value>
            <value>
                <fullName>Recurring - Weekly</fullName>
            </value>
            <value>
                <fullName>Recurring - Daily</fullName>
            </value>
            <value>
                <fullName>One-time + Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>FA with analyst/eng</fullName>
            </value>
            <value>
                <fullName>Pending Client</fullName>
            </value>
            <value>
                <fullName>Pending GTM</fullName>
            </value>
            <value>
                <fullName>Pending finance</fullName>
            </value>
            <value>
                <fullName>Pending Dragons</fullName>
            </value>
            <value>
                <fullName>In R&amp;D process</fullName>
            </value>
            <value>
                <fullName>DaaS to Deliver - Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed lost</fullName>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Account Preliminary Interest</fullName>
            </value>
            <value>
                <fullName>Actively Working</fullName>
            </value>
            <value>
                <fullName>Approved By Billing</fullName>
            </value>
            <value>
                <fullName>Assigned to SE/CSA</fullName>
            </value>
            <value>
                <fullName>Building Presentation</fullName>
            </value>
            <value>
                <fullName>Feasibility Pending</fullName>
                <label>Checking feasibility &amp; estimating effort</label>
            </value>
            <value>
                <fullName>Client Approval received</fullName>
                <label>Client Approval</label>
            </value>
            <value>
                <fullName>Client interest confirmed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Completed (sent to billing)</fullName>
            </value>
            <value>
                <fullName>Data Set Trial</fullName>
            </value>
            <value>
                <fullName>Data Set Trial - Evaluation</fullName>
            </value>
            <value>
                <fullName>Effort estimated</fullName>
            </value>
            <value>
                <fullName>Feasibility assessment (with Analysts / Engineers)</fullName>
            </value>
            <value>
                <fullName>Feasibility Confirmed</fullName>
            </value>
            <value>
                <fullName>Full Brief received</fullName>
            </value>
            <value>
                <fullName>Initiated - Future deliveries remaining</fullName>
            </value>
            <value>
                <fullName>Not Feasible</fullName>
            </value>
            <value>
                <fullName>Proposal sent to GTM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomLookupFieldController.cls
public with sharing class CustomLookupFieldController {
    @AuraEnabled
    public static List<RecordWrapper> fetchRecords(String objectName, String filterField, String searchString, String value) {
        try {
            List<RecordWrapper> recordWrapperList = new List<RecordWrapper>();
            String query = 'SELECT Id, ' + filterField + ' FROM '+objectName;
            if(String.isNotBlank(value)) {
                query += ' WHERE Id = \''+ value + '\' LIMIT 49999';
            } else {
                query += ' WHERE '+filterField+
                		' LIKE ' + '\'' + String.escapeSingleQuotes(searchString.trim()) + '%\' LIMIT 49999';
            }
	        for(SObject s : Database.query(query)) {
	            recordWrapperList.add( new RecordWrapper((String)s.get(filterField), (String)s.get('id')) );
	        }
            return recordWrapperList;
	    } catch (Exception err) {
	    	if ( String.isNotBlank( err.getMessage() ) && err.getMessage().contains( 'error:' ) ) {
                throw new AuraHandledException(err.getMessage().split('error:')[1].split(':')[0] + '.');
            } else {
                throw new AuraHandledException(err.getMessage());
            }
	    }
    }

    @AuraEnabled
    public static List<RecordWrapper> fetchRequests(String searchString, String quoteId, String requestType){
        try {
            String requestNumber;
            if(searchString == null || String.isBlank(searchString)){
                requestNumber = '%%';
            } else{
                requestNumber = '%' + searchString + '%';
            }
            String regularity;
            if(requestType.toLowerCase().contains('onetime')){
                regularity = 'One time';
            } else if(requestType.toLowerCase().contains('recurring')){
                regularity = 'Recurring%';
            } else {
                throw new AuraHandledException('Wrong Reporting Recurrance');
            }
            Set<String> requestStatusSet = new Set<String>{
                    'Closed Won',
                    'Completed',
                    'Initiated - Future deliveries remaining',
                    'Proposal sent to GTM',
                    'Pending client'
            };
            List<RecordWrapper> recordWrapperList = new List<RecordWrapper>();
            List<Request__c> requestList = [
                SELECT id, Name, List_price__c, Regularity__c, Status__c, Opportunity__c, RecordType.Name, Quote__c
                FROM Request__c
                WHERE
                    Status__c IN: requestStatusSet AND List_price__c != null
                    AND RecordType.Name = 'Advisory Services Request' AND Regularity__c like: regularity 
                    AND Opportunity__c IN
                        (SELECT zqu__Opportunity__c FROM zqu__Quote__c WHERE id =: quoteId)
                    AND Name like: requestNumber
            ];
            for(Request__c request : requestList){
                recordWrapperList.add( new RecordWrapper((String)request.get('Name'), (String)request.get('id')) );
            }
            return recordWrapperList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class RecordWrapper {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
        public RecordWrapper(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
    class MyException extends Exception {
        
    }
}