force-app/main/default/objects/Custom_Query__mdt/Custom_Query__mdt.object-meta.xml
<CustomObject>
    <description>Use this custom metadata to create queries that are in use in Apex classes.</description>
    <label>Custom Query</label>
    <pluralLabel>Custom Queries</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Query__mdt/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <description>Use this field to order the different parts of the query</description>
    <inlineHelpText>Use this field to order the different parts of the query. use 01,02 etc for future changes.</inlineHelpText>
    <label>Order By</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Query__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The process name where this query is used at.</description>
    <label>Process Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Query__mdt/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The query or a part of it.</description>
    <inlineHelpText>The query or a part of it.</inlineHelpText>
    <label>Query</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CustomQueriesUtils.cls
/**
 * @author Itzik Winograd
 * @date 22/08/2021
 * @description This class provides service to create a query from the Custom_Query__mdt.
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      -
 * date        -
 * description -
 * --------------------------------------------------------------------------------------
 */
public without sharing class CustomQueriesUtils {
  /**
   * @author Itzik Winograd
   * @date 09/27/2021
   * @description Builds a query from the custom metadata Custom_Query__mdt.
   * @param String the process name to query the metadata by.
   * @return String fullQuery - the query that was built from all the custom metadata parts.
   */
  public static String getCustomQuery(String processName) {
    String fullQuery = '';
    for (Custom_Query__mdt customQueryPart : [
      SELECT DeveloperName, Order_By__c, Query__c
      FROM Custom_Query__mdt
      WHERE Process_Name__c = :processName
      ORDER BY Order_By__c ASC
    ]) {
      fullQuery += customQueryPart.Query__c + ' ';
    }
    System.debug(
      '### the fullQuery in the Custom_Query__mdt for the process ' +
        processName +
        ' is: ' +
        fullQuery
    );
    return fullQuery;
  }
}