force-app/main/default/objects/BatchTimePeriodsSettings__c/BatchTimePeriodsSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for scheduler with period less than 1 hour
Name - the name of scheduled class
Value - period in minutes</description>
    <label>Batch time periods Settings</label>
</CustomObject>

force-app/main/default/objects/BatchTimePeriodsSettings__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describes the business unit with the responsibility of the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Clean_Domain__c.field-meta.xml
<CustomField>
    <fullName>Clean_Domain__c</fullName>
    <formula>CASE(Email_address_domain_type__c, 
     &apos;Company&apos;, Email_DomainClean__c , 
     Website_Domain__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clean Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryCodeFromLeadCapture__c.field-meta.xml
<CustomField>
    <fullName>CountryCodeFromLeadCapture__c</fullName>
    <label>CountryCodeFromLeadCapture</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_address_domain_type__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type__c</fullName>
    <inlineHelpText>Indicates if the email belongs to a company or a free email provider</inlineHelpText>
    <label>Email address domain type SFDC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company - Secondary</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Employee_Min_Update_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Employee_Min_Update_Timestamp__c</fullName>
    <label>Employee Min Update Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <inlineHelpText>Link to LinkedIn Profile</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Orchestration_Journey__c.field-meta.xml
<CustomField>
    <fullName>Orchestration_Journey__c</fullName>
    <label>Orchestration Journey</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>LDR</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Freemail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Polygraph_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Polygraph_Company_Name__c</fullName>
    <label>Polygraph Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Polygraph_Update_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Polygraph_Update_Timestamp__c</fullName>
    <label>Polygraph Update Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Recalculate_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Business_Unit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculate Business Unit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>MIS-4670</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Strategic_Region__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Region__c</fullName>
    <label>Strategic Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agencies</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>LLM &amp; AI</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Consultancies</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Dach</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Big 6 Agency</fullName>
                <isActive>false</isActive>
                <label>Big 6 Agency</label>
            </value>
            <value>
                <fullName>Strategic INTL</fullName>
                <isActive>false</isActive>
                <label>Strategic INTL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/sw_connector__swId__c.field-meta.xml
<CustomField>
    <fullName>sw_connector__swId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Similarweb Domain</label>
    <referenceTo>sw_connector__SimilarWeb_Website_Data__c</referenceTo>
    <relationshipLabel>Similarweb_Lead_Enrich</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pardot_Data_Manipulation_Setting__c/Pardot_Data_Manipulation_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pardot Data Manipulation Setting</label>
</CustomObject>

force-app/main/default/classes/BusinessUnitUpdateBatch.cls
/*
 * Made by Viktoriia from Synebo
 */
global class BusinessUnitUpdateBatch implements Database.Batchable<sObject>, Schedulable {
  private static final Integer TIME_MARGIN = 1;
  private static Integer LAST_N_DAYS = 7;
  private String query;
  private DateTime previousRunTime;
  private Integer batchSize = 10;

  private Map<String, String> domainFieldsMap;

  global BusinessUnitUpdateBatch() {
  }

  global BusinessUnitUpdateBatch(Integer batchSize, DateTime previousTime) {
    this.batchSize = batchSize;
    this.previousRunTime = previousTime;
  }

  global BusinessUnitUpdateBatch(DateTime previousTime) {
    this.previousRunTime = previousTime;
  }

  global void execute(SchedulableContext SC) {
    //        //Schedule the batch in that value of minutes that is set in custom settings
    //        List<CronTrigger> cts = [SELECT ID, PreviousFireTime, NextFireTime, CronExpression, CronJobDetail.Name  FROM crontrigger
    //                            WHERE Id=: SC.getTriggerId() ];
    //        System.abortJob(SC.getTriggerId());
    //
    //        List<BatchTimePeriodsSettings__c> cs = [SELECT Name , Value__c
    //                                          		FROM  BatchTimePeriodsSettings__c
    //                                          		WHERE Name =: cts.get(0).CronJobDetail.Name
    //                                          		LIMIT 1];
    //        Integer schedulerMinute = DateTime.now().minute() + (cs.isEmpty() ? 30 : Integer.valueOf(cs[0].Value__c));
    //
    //        if(schedulerMinute < 60){
    //        	System.schedule(cts[0].CronJobDetail.Name, '0 '+ schedulerMinute +' * * * ?', this.batchSize != null ? new BusinessUnitUpdateBatch(this.batchSize) : new BusinessUnitUpdateBatch());
    //        } else {
    //            System.schedule(cts[0].CronJobDetail.Name, '0 '+ Math.abs(60 - schedulerMinute) +' * * * ?', this.batchSize != null ? new BusinessUnitUpdateBatch(this.batchSize) : new BusinessUnitUpdateBatch());
    //        }
    //        DateTime schPreviousRunTime = !cts.isEmpty() && cts[0].PreviousFireTime != null ? cts[0].PreviousFireTime.addMinutes(- Integer.valueOf(cs[0].Value__c) - TIME_MARGIN) :
    //        								DateTime.now().addHours(-1);
    //        System.debug('SC.getTriggerId() ' + SC.getTriggerId() + ', cron ' + cts[0] + '\nschPreviousRunTime ' + schPreviousRunTime);
    DateTime schPreviousRunTime = DateTime.now().addMinutes(-16);
    Database.executeBatch(new BusinessUnitUpdateBatch(schPreviousRunTime), 10);
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    try {
      LAST_N_DAYS = Integer.valueOf(Label.BU_Batch_Run_for_Last_N_days);
    } catch (Exception e) {
    }
    Id secureIntegrationUserId = [
      SELECT Id
      FROM User
      WHERE Name = 'Secure Integration'
    ]
    .id;
    List<String> excludedLeadRecordType = !String.isEmpty(
        Label.Excluded_Lead_RecordType_For_BU_Batch
      )
      ? Label.Excluded_Lead_RecordType_For_BU_Batch.split(',')
      : new List<String>();
    /*Take all Leads that are:
     * ((created in that value of LAST_N_DAYS that is set in Label BU_Batch_Run_for_Last_N_days AND
     *    Has no value in Business_Unit__c)
     *   OR Employee_Min_Update_Timestamp__c
     *   OR Recalculate_Business_Unit__c = true )
     * AND RecordTypeId not in Label Excluded_Lead_RecordType_For_BU_Batch
     * AND Polygraph_Update_Timestamp__c!=null
     */
    query =
      'SELECT Id,OwnerId,CreatedById,Country,CountryCodeFromLeadCapture__c,CountryCode, Business_Unit__c, Employees_Min__c, Clean_Domain__c,Polygraph_Company_Name__c,Orchestration_Journey__c, Email_address_domain_type__c, Recalculate_Business_Unit__c, LinkedIn_Profile__c, Strategic_Pod__c, Strategic_Region__c ' +
      'FROM Lead ' +
      'WHERE ((CreatedDate=LAST_N_DAYS:' +
      LAST_N_DAYS +
      +' AND Business_Unit__c = NULL ' +
      (excludedLeadRecordType.isEmpty()
        ? ''
        : ') ' +
          'OR (Employee_Min_Update_Timestamp__c > ' +
          previousRunTime.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') +
          ') ' +
          'OR (Recalculate_Business_Unit__c = true)) ' +
          'AND Lead.RecordTypeId NOT IN (\'' +
          String.join(excludedLeadRecordType, ',') +
          '\'' +
          ') ' +
          'AND Polygraph_Update_Timestamp__c!=null ');
      //                'AND ((sw_connector__swId__c != null  AND Website != null) OR  Website = null  OR CreatedById != :secureIntegrationUserId)'

    System.debug(
      '### BusinessUnitUpdateBatch previousRunTime: ' +
        previousRunTime +
        ', \nquery: ' +
        query
    );
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<Sobject> scope) {
    system.debug(scope.size());
    //Pardot_Data_Manipulation_Setting__c ldrOwnerSetting = Pardot_Data_Manipulation_Setting__c.getInstance('LDR_LEAD_OWNER_ID');
    String ldrOwnerSetting = String.valueOf(
      Pardot_Data_Manipulation_Setting__c.getInstance('LDR_LEAD_OWNER_ID')
        .Value__c
    );
    BusinessUnitUpdateHelper buuh = new BusinessUnitUpdateHelper();
    buuh.updateBusinessUnit(
      scope,
      'Clean_Domain__c',
      'Country',
      ldrOwnerSetting,
      false
    );
  }

  global void finish(Database.BatchableContext BC) {
  }
}