force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The Action requested in the process</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deactivate</fullName>
                <default>true</default>
                <label>Deactivate</label>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Role Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Fault_Massage__c.field-meta.xml
<CustomField>
    <fullName>Fault_Massage__c</fullName>
    <description>In case the automation for the action failed, save the reason for the failure</description>
    <label>Fault Massage</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Level_11__c.field-meta.xml
<CustomField>
    <fullName>Level_11__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Level 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Today_is_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Today_is_Action_Date__c</fullName>
    <formula>TODAY() =  Date_For_Action__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Today is Action Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Member__c/Territory_Member__c.object-meta.xml
<CustomObject>
    <label>Territory Member</label>
    <nameField>
        <displayFormat>TMN-{000}</displayFormat>
        <label>Territory Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Level_11__c.field-meta.xml
<CustomField>
    <fullName>Level_11__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Level 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeactivateUsersBatch.cls
public with sharing class DeactivateUsersBatch implements Database.Batchable<SObject>, Schedulable {

    public void execute(SchedulableContext sc) {
        Database.executeBatch(this, 1);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, User__c
            FROM Manage_Users_Log__c
            WHERE Today_is_Action_Date__c = true
            AND Action__c = 'Deactivate'
            AND Status__c = 'Open'
            AND User__c != NULL
        ]);
    }

    // This batch supposed to run only for 1 user per transaction
    public void execute(Database.BatchableContext bc, List<Manage_Users_Log__c> scope) {
        //try {
            User userToDeactivate = new User(Id = scope[0].User__c, IsActive = false, Level_11__c = false);
            update userToDeactivate;
            // List<AccountTeamMember> accTeamMembers = [SELECT Id, UserId FROM AccountTeamMember WHERE UserId =: scope[0].User__c];
            // List<Territory_Member__c> terrMembers = [SELECT Id, Name__c FROM Territory_Member__c WHERE Name__c =: scope[0].User__c];
            // List<UserPackageLicense> userPackageLicenses = [SELECT Id, UserId FROM UserPackageLicense WHERE UserId =: scope[0].User__c];
            // if (accTeamMembers.size() > 0) {
            //     delete accTeamMembers;
            // }
            // if (terrMembers.size() > 0) {
            //     delete terrMembers;
            // }
            // if (userPackageLicenses.size() > 0) {
            //     delete userPackageLicenses;
            // }
            scope[0].Status__c = 'Completed';
        // }
        // catch (Exception e) {
        //     scope[0].Status__c = 'Failed';
        //     scope[0].Fault_Massage__c = e.getMessage();
        // }
        System.enqueueJob(new LogUpdateQueueable(scope[0]));
    }

    public void finish(Database.BatchableContext bc) {
    }

    public class LogUpdateQueueable implements System.Queueable {
        Manage_Users_Log__c log;

        public LogUpdateQueueable(Manage_Users_Log__c rec) {
            this.log = rec;
        }

        public void execute(System.QueueableContext context) {
            update this.log;
        }
    }
}