force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Fault_Massage__c.field-meta.xml
<CustomField>
    <fullName>Fault_Massage__c</fullName>
    <description>In case the automation for the action failed, save the reason for the failure</description>
    <label>Fault Massage</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Level_11__c.field-meta.xml
<CustomField>
    <fullName>Level_11__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Level 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Member__c/Territory_Member__c.object-meta.xml
<CustomObject>
    <label>Territory Member</label>
    <nameField>
        <displayFormat>TMN-{000}</displayFormat>
        <label>Territory Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Level_11__c.field-meta.xml
<CustomField>
    <fullName>Level_11__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Level 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeactivateUsersQueueable.cls
public with sharing class DeactivateUsersQueueable implements System.Queueable {
    
    List<Manage_Users_Log__c> logs;
    Integer i;
    Boolean shouldStop, isSetupDml;

    public DeactivateUsersQueueable(List<Manage_Users_Log__c> logs, Integer i, Boolean isSetupDml) {
        this.isSetupDml = isSetupDml;
        this.shouldStop = false;
        this.logs = logs;
        this.i = i;
        if (this.i == this.logs.size()) {
            this.shouldStop = true;
        }
    }

    public void execute(System.QueueableContext context) {
        if (shouldStop) {
            update logs;
        }
        else {
            try {
                if (isSetupDml) {
                    List<UserPackageLicense> userPackageLicenses = [SELECT Id, UserId FROM UserPackageLicense WHERE UserId =: logs[i].User__c];
                    delete userPackageLicenses;
                    User userToDeactivate = new User(Id = logs[i].User__c, IsActive = false, Level_11__c = false);
                    update userToDeactivate;
                    logs[i].Status__c = 'Completed';
                }
                else {
                    List<AccountTeamMember> accTeamMembers = [SELECT Id, UserId FROM AccountTeamMember WHERE UserId =: logs[i].User__c];
                    List<Territory_Member__c> terrMembers = [SELECT Id, Name__c FROM Territory_Member__c WHERE Name__c =: logs[i].User__c];
                    delete accTeamMembers;
                    delete terrMembers;
                }
            }
            catch (Exception e) {
                logs[i].Status__c = 'Failed';
                logs[i].Fault_Massage__c = e.getMessage();
            }
            if (!Test.isRunningTest()) {
                System.enqueueJob(new DeactivateUsersQueueable(logs, isSetupDml ? i + 1 : i, !isSetupDml));
            }
        }
    }
}