force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The Action requested in the process</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deactivate</fullName>
                <default>true</default>
                <label>Deactivate</label>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Role Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Today_is_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Today_is_Action_Date__c</fullName>
    <formula>TODAY() =  Date_For_Action__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Today is Action Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeactivateUsersSchedulable.cls
public with sharing class DeactivateUsersSchedulable implements Schedulable {
  public void execute(SchedulableContext context) {
    List<Manage_Users_Log__c> logs = [
      SELECT Id, User__c
      FROM Manage_Users_Log__c
      WHERE
        Today_is_Action_Date__c = TRUE
        AND Action__c = 'Deactivate'
        AND Status__c = 'Open'
        AND User__c != NULL
    ];
    if (logs.size() > 0) {
      DeactivateUsersQueueable queueable = new DeactivateUsersQueueable(
        logs,
        0,
        false
      );
      System.enqueueJob(queueable);
    }
  }
}