force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <label>Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Business_Applications_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Business_Applications_Assignments__c</fullName>
    <label>Business Applications Assignments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Date_For_Action__c.field-meta.xml
<CustomField>
    <fullName>Date_For_Action__c</fullName>
    <description>The requested date to run the action.</description>
    <inlineHelpText>The requested date to run the action.</inlineHelpText>
    <label>Date For Action</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Employee_Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Employee_Hire_Date__c</fullName>
    <label>Employee Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Permission_Set_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Assignments__c</fullName>
    <label>Permission Set Assignments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Public_Group_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_Assignments__c</fullName>
    <label>Public Group Assignments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Employee_Hire_Date__c</fullName>
    <description>MIS-143</description>
    <label>Employee Hire/Transition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ManageUserLogUpdater.cls
/**
 * Created by alon.shalev on 2/12/2023.
 */

public with sharing class ManageUserLogUpdater {
  @InvocableMethod(
    label='Update Manage User Log'
    description='Updates a Manage User Log record'
  )
  public static void updateManageUserLog(
    List<ManageUserLogInput> manageUserLogInputs
  ) {
    List<Manage_Users_Log__c> manageUserLogs = new List<Manage_Users_Log__c>();
    for (ManageUserLogInput manageUserLogInput : manageUserLogInputs) {
      Manage_Users_Log__c manageUserLog = new Manage_Users_Log__c();
      manageUserLog.Id = manageUserLogInput.Manage_User_Log_ID;
      manageUserLog.User__c = manageUserLogInput.User;
      manageUserLog.Status__c = manageUserLogInput.Status;
      manageUserLog.Date_For_Action__c = manageUserLogInput.Date_For_Action;
      manageUserLog.Employee_Hire_Date__c = manageUserLogInput.Employee_Hire_Date;
      manageUserLog.Business_Applications_Assignments__c = manageUserLogInput.Business_Applications_Assignments;
      manageUserLog.Permission_Set_Assignments__c = manageUserLogInput.Permission_Set_Assignments;
      manageUserLog.Public_Group_Assignments__c = manageUserLogInput.Public_Group_Assignments;
      manageUserLog.Approved_By__c = manageUserLogInput.Approved_By;
      manageUserLogs.add(manageUserLog);
    }
    system.enqueueJob(new ManageUserLogUpdaterQueueable(manageUserLogs));
  }

  public class ManageUserLogInput {
    @InvocableVariable(required=true)
    public Id Manage_User_Log_ID;
    @InvocableVariable
    public String User;
    @InvocableVariable
    public String Status;
    @InvocableVariable
    public Date Date_For_Action;
    @InvocableVariable
    public Date Employee_Hire_Date;
    @InvocableVariable
    public String Business_Applications_Assignments;
    @InvocableVariable
    public String Permission_Set_Assignments;
    @InvocableVariable
    public String Public_Group_Assignments;
    @InvocableVariable
    public String Approved_By;
  }
}