force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The Action requested in the process</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deactivate</fullName>
                <default>true</default>
                <label>Deactivate</label>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Role Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Date_For_Action__c.field-meta.xml
<CustomField>
    <fullName>Date_For_Action__c</fullName>
    <description>The requested date to run the action.</description>
    <inlineHelpText>The requested date to run the action.</inlineHelpText>
    <label>Date For Action</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Fault_Massage__c.field-meta.xml
<CustomField>
    <fullName>Fault_Massage__c</fullName>
    <description>In case the automation for the action failed, save the reason for the failure</description>
    <label>Fault Massage</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeactivateUsersBatchTest.cls
@IsTest
private class DeactivateUsersBatchTest {
  @TestSetup
  static void setup() {
    Profile stdProfile = [
      SELECT Id
      FROM Profile
      WHERE Name = 'Standard User'
      LIMIT 1
    ];

    User testUser = new User(
      FirstName = 'Test',
      LastName = 'Deactivate',
      Email = 'testdeactivate@example.com',
      Username = 'testdeactivate' + DateTime.now().getTime() + '@example.com',
      Alias = 'tdeact',
      ProfileId = stdProfile.Id,
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      TimeZoneSidKey = 'America/New_York',
      IsActive = true
    );
    insert testUser;

    Manage_Users_Log__c log = new Manage_Users_Log__c(
      User__c = testUser.Id,
      Action__c = 'Deactivate',
      Status__c = 'Open',
      Date_For_Action__c = Date.today()
    );
    insert log;
  }

  @IsTest
  static void testBasicDeactivation() {
    Test.startTest();
    DeactivateUsersBatch sb = new DeactivateUsersBatch();
    sb.execute(null);
    Test.stopTest();

    User deactivated = [
      SELECT IsActive
      FROM User
      WHERE LastName = 'Deactivate'
      LIMIT 1
    ];
    Manage_Users_Log__c log = [
      SELECT Status__c, Fault_Massage__c
      FROM Manage_Users_Log__c
      WHERE User__c = :deactivated.Id
      LIMIT 1
    ];
    System.debug('log: ' + log);
    System.assertEquals('Completed', log.Status__c);
    System.assertEquals(false, deactivated.IsActive);
  }
}