force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Business_Applications_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Business_Applications_Assignments__c</fullName>
    <label>Business Applications Assignments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Date_For_Action__c.field-meta.xml
<CustomField>
    <fullName>Date_For_Action__c</fullName>
    <description>The requested date to run the action.</description>
    <inlineHelpText>The requested date to run the action.</inlineHelpText>
    <label>Date For Action</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Employee_Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Employee_Hire_Date__c</fullName>
    <label>Employee Hire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Permission_Set_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Assignments__c</fullName>
    <label>Permission Set Assignments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Public_Group_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_Assignments__c</fullName>
    <label>Public Group Assignments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_Hire_Date__c.field-meta.xml
<CustomField>
    <fullName>Employee_Hire_Date__c</fullName>
    <description>MIS-143</description>
    <label>Employee Hire/Transition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ManageUserLogUpdaterTest.cls
/**
 * Created by alon.shalev on 2/12/2023.
 */

@IsTest
public class ManageUserLogUpdaterTest {
  @isTest
  static void testUpdateManageUserLog() {
    Manage_Users_Log__c manageUserLog = new Manage_Users_Log__c(
      User__c = UserInfo.getUserId(),
      Status__c = 'Completed',
      Date_For_Action__c = Date.today(),
      Employee_Hire_Date__c = Date.today(),
      Business_Applications_Assignments__c = 'Assigned',
      Permission_Set_Assignments__c = 'Assigned',
      Public_Group_Assignments__c = 'Assigned'
    );
    insert manageUserLog;
    Test.startTest();

    List<ManageUserLogUpdater.ManageUserLogInput> manageUserLogInputs = new List<ManageUserLogUpdater.ManageUserLogInput>();
    ManageUserLogUpdater.ManageUserLogInput manageUserLogInput = new ManageUserLogUpdater.ManageUserLogInput();
    manageUserLogInput.Manage_User_Log_ID = manageUserLog.Id;
    manageUserLogInput.User = UserInfo.getUserId();
    manageUserLogInput.Status = 'Completed';
    manageUserLogInput.Date_For_Action = Date.today().addDays(1);
    manageUserLogInput.Employee_Hire_Date = Date.today().addDays(1);
    manageUserLogInput.Business_Applications_Assignments = 'Not Assigned';
    manageUserLogInput.Permission_Set_Assignments = 'Not Assigned';
    manageUserLogInput.Public_Group_Assignments = 'Not Assigned';
    manageUserLogInputs.add(manageUserLogInput);
    ManageUserLogUpdater.updateManageUserLog(manageUserLogInputs);
    Test.stopTest();

    manageUserLog = [
      SELECT
        Id,
        Status__c,
        Date_For_Action__c,
        Employee_Hire_Date__c,
        Business_Applications_Assignments__c,
        Permission_Set_Assignments__c,
        Public_Group_Assignments__c
      FROM Manage_Users_Log__c
      WHERE Id = :manageUserLog.Id
    ];

    System.assertEquals('Completed', manageUserLog.Status__c);
    System.assertEquals(
      Date.today().addDays(1),
      manageUserLog.Date_For_Action__c
    );
    System.assertEquals(
      Date.today().addDays(1),
      manageUserLog.Employee_Hire_Date__c
    );
    System.assertEquals(
      'Not Assigned',
      manageUserLog.Business_Applications_Assignments__c
    );
    System.assertEquals(
      'Not Assigned',
      manageUserLog.Permission_Set_Assignments__c
    );
    System.assertEquals(
      'Not Assigned',
      manageUserLog.Public_Group_Assignments__c
    );
  }
}