force-app/main/default/objects/Contract/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly - Fix Price</fullName>
            </value>
            <value>
                <fullName>Monthly - Flex Rate</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>BI - Annual</fullName>
            </value>
            <value>
                <fullName>Fix Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/Monthly_Data_Request__c.object-meta.xml
<CustomObject>
    <description>Monthly data information we get per each &quot;Source&quot;. The data Method can be &quot;DAU&quot;/&quot;MAU&quot;/&quot;S2S&quot; and more. 
We get the data on a monthly bases from BI.</description>
    <label>Monthly Data Request</label>
    <nameField>
        <label>Monthly Data Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Data Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country that the DAU is pulled from. Used for BI to detect the Request.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Monthly_Source_Request__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Source_Request__c</fullName>
    <description>All the Monthly Data Request should roll up to the relevant Monthly Source Data</description>
    <label>Monthly Source Request</label>
    <referenceTo>Monthly_Source_Request__c</referenceTo>
    <relationshipLabel>Monthly Data Requests</relationshipLabel>
    <relationshipName>Monthly_Data_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Monthly Data Requests</relationshipLabel>
    <relationshipName>Monthly_Data_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Key number for BI to detect each Data Request</description>
    <label>Request Type</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Source of the Data Method. MIS-1690</description>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Monthly Data Requests</relationshipLabel>
    <relationshipName>Monthly_Data_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Partner_Request__c/Monthly_Partner_Request__c.object-meta.xml
<CustomObject>
    <description>Roll up data monthly payment on the Contract payment (final payment for the partner each month).</description>
    <label>Monthly Partner Request</label>
    <nameField>
        <label>Monthly Partner Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Partner Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Partner_Request__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <description>The Monthly Payment Data holds the total payment for the partner per month. It must be related to the Contract of the Partner.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Monthly_Partner_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Source_Request__c/Monthly_Source_Request__c.object-meta.xml
<CustomObject>
    <description>Each month new &quot;Monthly Data Method&quot; are created. These should be under a Monthly Source Data records. So we can roll up each Monthly payment to the Source level (and then to the Contract level)</description>
    <label>Monthly Source Request</label>
    <nameField>
        <label>Monthly Source Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Source Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Source_Request__c/fields/Monthly_Partner_Request__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Partner_Request__c</fullName>
    <description>All the Monthly Source Data should roll up to the &quot;Monthly Partner Data&quot;</description>
    <label>Monthly Partner Request</label>
    <referenceTo>Monthly_Partner_Request__c</referenceTo>
    <relationshipLabel>Monthly Source Requests</relationshipLabel>
    <relationshipName>Monthly_Source_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Source_Request__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Monthly Source Requests</relationshipLabel>
    <relationshipName>Monthly_Source_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Source_Request__c/fields/Source_Number__c.field-meta.xml
<CustomField>
    <fullName>Source_Number__c</fullName>
    <formula>Source__r.Source_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Information for every &quot;Data Request&quot; for each Source. Part of the Data Partner model.</description>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>In case the &quot;End Date&quot; of the Rate is not blank and equal/less TODAY the CB will be true.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The Tier/Country of the Request that will be created according the Rate</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Once populated, the &quot;Rate&quot; is no longer valid in the &quot;Monthly Data Request&quot; calculation.</description>
    <inlineHelpText>Once populated and Date is in the past, no Monthly Data Records will be created. In case the Source is no longer relevant, make sure to deactivate it!</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The actual Rate we pay for each data unit as agreed in the Contract</description>
    <label>Rate</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Part of the &quot;Data Partner&quot; model. A Source represents the Products that Similarweb pulls the data from. We get the &quot;Sources&quot; from the Data Partners.</description>
    <label>Source</label>
    <nameField>
        <label>Sources  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the Source is active or not. In case all the related &quot;Rates&quot; are with End Date less than Today it should be deactivated.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sources</relationshipLabel>
    <relationshipName>Sources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Source_Number__c.field-meta.xml
<CustomField>
    <fullName>Source_Number__c</fullName>
    <label>Source Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DataPartnersSpecificContractAController.cls
/**
 * @author Zohar Sinay
 * @date 27/02/2022
 * @description A class to create Data Partners for a specific contract
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      -
 * date        -
 * description -
 * --------------------------------------------------------------------------------------
 */

public with sharing class DataPartnersSpecificContractAController {
  private static final Integer thisMonth = Date.today().addDays(-30).month();
  private static final Integer thisYear = Date.today().addDays(-30).year();

  /**
   * @author Zohar Sinay
   * @date 27/02/2022
   * @Description Create data partners for a specific contract
   * @param contractId The Id of the contract to create the data for
   */
  @AuraEnabled
  public static void createNewDataPartnersForContract(id contractId) {
    Monthly_Partner_Request__c MPR = new Monthly_Partner_Request__c();
    Set<Id> ratesIdSet = new Set<Id>();
    Set<Id> sourceIdSet = new Set<Id>();
    List<Id> ratesToCreateList = new List<Id>();
    Map<Id, Rate__c> rateByIdMap = new Map<Id, Rate__c>();
    List<Monthly_Data_Request__c> MDRToInsertList = new List<Monthly_Data_Request__c>();
    Map<Id, Monthly_Source_Request__c> MSRBySource = new Map<Id, Monthly_Source_Request__c>();
    Map<Id, Monthly_Source_Request__c> MSRBySourceId = new Map<Id, Monthly_Source_Request__c>();
    Map<Id, Monthly_Data_Request__c> MDRByRateId = new Map<Id, Monthly_Data_Request__c>();

    Contract cont = [
      SELECT Id, Name, Account.Name
      FROM Contract
      WHERE Id = :contractId
      LIMIT 1
    ];
    String MPRName = createMPRName(cont);

    List<Monthly_Partner_Request__c> MPRList = [
      SELECT Id
      FROM Monthly_Partner_Request__c
      WHERE Name = :MPRName AND Contracts__c = :cont.Id
      LIMIT 1
    ];

    if (!MPRList.isEmpty()) {
      MPR = MPRList[0];
    } else {
      MPR.Name = MPRName;
      MPR.Contracts__c = cont.Id;
      insert MPR;
    }

    Map<Id, Source__c> sourceByIdMap = new Map<Id, Source__c>(
      [
        SELECT
          Id,
          Name,
          Source_Number__c,
          Contract__r.Payment_Method__c,
          Contract__r.Id,
          (
            SELECT
              Id,
              Country__c,
              Request_Type__c,
              Source__r.Name,
              Source__r.Source_Number__c,
              Source__c
            FROM Rates__r
            WHERE
              End_Date__c = NULL
              OR End_Date__c >= :date.today().addDays(-17)
          )
        FROM Source__c
        WHERE Contract__c = :contractId AND Active__c = TRUE
      ]
    );

    for (Source__c source : sourceByIdMap.values()) {
      sourceIdSet.add(source.Id);
      for (Rate__c rate : source.Rates__r) {
        rateByIdMap.put(rate.Id, rate);
        ratesIdSet.add(rate.Id);
      }
    }

    for (Monthly_Source_Request__c MSR : [
      SELECT
        Id,
        Source__c,
        Monthly_Partner_Request__c,
        (
          SELECT Id, Rate__c, Source__c
          FROM Monthly_Data_Requests__r
          WHERE Rate__c IN :ratesIdSet
        )
      FROM Monthly_Source_Request__c
      WHERE Source__c IN :sourceIdSet AND CreatedDate = THIS_MONTH
    ]) {
      MSRBySourceId.put(MSR.Source__c, MSR);
      for (Monthly_Data_Request__c MDR : MSR.Monthly_Data_Requests__r) {
        MDRByRateId.put(MDR.Rate__c, MDR);
      }
    }

    for (Source__c source : sourceByIdMap.values()) {
      if (!MSRBySourceId.containsKey(source.Id)) {
        MSRBySource.put(
          source.Id,
          createNewMonthlySourceRequests(source, MPR.Id)
        );
      }
    }

    if (!MSRBySource.isEmpty()) {
      insert MSRBySource.values();
    }

    for (Rate__c rate : rateByIdMap.values()) {
      if (!MDRByRateId.containsKey(rate.Id)) {
        Id MSRId = MSRBySource.isEmpty()
          ? MSRBySourceId.get(rate.Source__c).Id
          : MSRBySource.get(rate.Source__c).Id;
        MDRToInsertList.add(createNewMonthlyDataRequests(rate, MSRId));
      }
    }

    if (!MDRToInsertList.isEmpty()) {
      insert MDRToInsertList;
    }
  }

  /**
   * @author Zohar Sinay
   * @date 27/02/2022
   * @Description Create the Monthly Source Request according to the source and Monthly Partner Request
   * @param Source__c The source based on which's data the Monthly source request is build
   * @param Id The Id of the Montly Partner Request that needs to be associated
   * @return Monthly_Source_Request__c with all data assigned
   */
  public static Monthly_Source_Request__c createNewMonthlySourceRequests(
    Source__c source,
    Id MPRId
  ) {
    return new Monthly_Source_Request__c(
      Name = source.Name +
        '/' +
        source.Source_Number__c +
        '/' +
        String.valueOf(thisMonth) +
        '/' +
        String.valueOf(thisYear),
      Monthly_Partner_Request__c = MPRId,
      Source__c = source.Id
    );
  }

  /**
   * @author Zohar Sinay
   * @date 27/02/2022
   * @Description Create the Monthly Data Request according to the Rate and Monthly Source Request
   * @param Rate__c The rate based on which's data the monthtly data request is being populated
   * @param Id logEvent -Monthly Source Request Id related to this Monthly Data Request
   * @return Monthly_Data_Request__c with all data assigned
   */
  public static Monthly_Data_Request__c createNewMonthlyDataRequests(
    Rate__c rate,
    Id MSRId
  ) {
    return new Monthly_Data_Request__c(
      Name = rate.Source__r.Name +
        '/' +
        rate.Source__r.Source_Number__c +
        '/' +
        rate.Request_Type__c +
        '/' +
        rate.Country__c +
        '/' +
        String.valueOf(Date.today().addDays(-30).month()) +
        '/' +
        String.valueOf(Date.today().addDays(-30).year()),
      Monthly_Source_Request__c = MSRId,
      Source__c = rate.Source__c,
      Rate__c = rate.Id
    );
  }

  /**
   * @author Zohar Sinay
   * @date 27/02/2022
   * @Description Create the monthly partner request name
   * @param Account Account based on which the name of the Partner request is determined
   * @return String with all data assigned
   */
  public static String createMPRName(Contract cont) {
    String MPRName = String.isBlank(cont.Name) ? cont.Account.Name : cont.Name;
    MPRName += '/' + thisMonth + '/' + thisYear;
    return MPRName;
  }
}