force-app/main/default/objects/Zuora_Quote_Approval_Settings__c/Zuora_Quote_Approval_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Zuora Quote Approval Settings</label>
</CustomObject>

force-app/main/default/objects/Zuora_Quote_Approval_Settings__c/fields/Enable_Approval_process_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>Enable_Approval_process_for_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Approval process for Quote?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GetQuoteType.cls
public class GetQuoteType {
    @AuraEnabled
    public static Boolean getQType(String firstName) {
        
        Boolean result = false;

        /* zqu__Quote__c qType = [Select RecordType.Name From zqu__Quote__c where Id = :firstName]; */
        Zuora_Quote_Approval_Settings__c customSettingValue = Zuora_Quote_Approval_Settings__c.getOrgDefaults();
        
        if(customSettingValue.Enable_Approval_process_for_Quote__c == true){
            result = true;
        }
        
        return result;
    }
}