force-app/main/default/objects/Account/fields/AccountDomain__c.field-meta.xml
<CustomField>
    <fullName>AccountDomain__c</fullName>
    <label>AccountDomain</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_address_domain_type_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type_SFDC__c</fullName>
    <label>Email address domain type SFDC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>MIS-1696</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sys_Hierarchy_Required__c.field-meta.xml
<CustomField>
    <fullName>Sys_Hierarchy_Required__c</fullName>
    <description>This field will determine by LeanData if the new Account should be in Hierarchy structure under parent Account</description>
    <label>Sys Hierarchy Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account.SW_Industry__c ,
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;,
&apos;Agency&apos;, &apos;Agency&apos;,
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;,
&apos;B2B Software&apos;,&apos;B2B Software&apos;,
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;,
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;,
&apos;Big Tech&apos;,&apos;Big Tech&apos;,
&apos;Classifieds&apos;,&apos;Classifieds&apos;,
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;,
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;,
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;,
&apos;Education&apos;,&apos;Education&apos;,
&apos;Equity Research&apos;,&apos;Equity Research&apos;,
&apos;Financial services&apos;,&apos;Financial services&apos;,
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;,
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;,
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;,
&apos;Investors&apos;,&apos;Investors&apos;,
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;,
&apos;Other&apos;,&apos;Other&apos;,
&apos;Payments&apos;,&apos;Payments&apos;,
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;,
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;,
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;,
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;,
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;,
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;,
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;,
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;,
&apos;Private Equity and Venture Capital&apos;,&apos;Private Equity and Venture Capital&apos;,
&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/******************************************************************************* 
Name : AccountTriggerHandler
Description : Handler class for Account triggers
Created/Modified by Created/Modified Date Requested by Related Task/Issue 
---------------------------------------------------------------------------------------- 
1.Nevo Haarari           04/03/2018         ARIEL LOPEZ             [SW-28689] 
2.Nevo Haarari           11/04/2018         Omer/Doreen          	[SW-29066]
************************************************************************************/
public class AccountTriggerHandler {
  public void machParent(
    List<Account> accNewList,
    Map<Id, Account> accOldMap,
    Map<Id, Account> accNewMap
  ) {
    map<Id, String> accIdToDomain = new Map<Id, String>();
    List<Account> releventAccLst = new List<Account>();
    for (Account acc : accNewList) {
      System.debug('inside handler AccountTriggerHandler');
      //Insert
      System.debug('acc---' + acc.Domain__c);
      System.debug('acc---' + acc.AccountDomain__c);
      if (Trigger.isInsert) {
        if (
          acc.Sys_Hierarchy_Required__c == 'Yes' &&
          acc.Domain__c != null &&
          acc.Domain__c != ''
        ) {
          //&& acc.Email_address_domain_type_SFDC__c == 'Company'
          accIdToDomain.put(acc.id, acc.Domain__c.toLowerCase());
          releventAccLst.add(acc);
          acc.Sys_Hierarchy_Required__c = 'No';
          System.debug('acc.id==' + acc.id);
        }
      }

      //update
      if (Trigger.isUpdate) {
        if (
          acc.Sys_Hierarchy_Required__c == 'Yes' &&
          acc.Domain__c != null &&
          acc.Domain__c != ''
        ) {
          //&& acc.Email_address_domain_type_SFDC__c == 'Company'
          if (
            accOldMap != null &&
            accOldMap.get(acc.Id).Sys_Hierarchy_Required__c != 'Yes'
          ) {
            //call flow
            // call_machParent_Flow(acc.id);

            accIdToDomain.put(acc.id, acc.Domain__c.toLowerCase());
            releventAccLst.add(acc);
            System.debug('acc.id==' + acc.id);
            acc.Sys_Hierarchy_Required__c = 'No';
          }
        }
      }
    }
  }

  //MIS-4768

  public void updateMarketingPersona(
    Map<Id, Account> newMap,
    Map<Id, Account> oldMap
  ) {
    System.debug('alon start updateMarketingPersona--');
    Set<Id> changedAccountIdSet = new Set<Id>();
    for (Id accountId : newMap.keySet()) {
      if (
        newMap.get(accountId).SW_Industry__c !=
        oldMap.get(accountId).SW_Industry__c
      ) {
        changedAccountIdSet.add(accountId);
      }
    }
    System.debug('changedAccountIdSet---' + changedAccountIdSet);
    if (!changedAccountIdSet.isEmpty()) {
      system.enqueueJob(
        new UpdateMarketingPersonaQueueable(changedAccountIdSet)
      );
    }
  }

  public void updateStrategicPodOnContacts(
    Map<Id, Account> newMap,
    Map<Id, Account> oldMap
  ) {
    Set<Id> changedAccountIdSet = new Set<Id>();
    for (Id accountId : newMap.keySet()) {
      if (
        newMap.get(accountId).Strategic_Pod__c !=
        oldMap.get(accountId).Strategic_Pod__c
      ) {
        changedAccountIdSet.add(accountId);
      }
    }
    System.debug('changedAccountIdSet---' + changedAccountIdSet);
    if (!changedAccountIdSet.isEmpty()) {
      system.enqueueJob(
        new UpdatestrategicPodOnContactsQueueable(changedAccountIdSet)
      );
    }
  }

  public void handleClosedOppOwnerRevert(
    Map<Id, Account> newMap,
    Map<Id, Account> oldMap
  ) {
    System.debug('handleClosedOppOwnerRevert -- START');
    Set<String> allowedProfiles = new Set<String>{
      'System Administrator',
      'SW SalesOps',
      'SW SalesOps Extended'
    };
    String currentUserProfileName = [
      SELECT Name
      FROM Profile
      WHERE Id = :UserInfo.getProfileId()
    ]
    .Name;
    System.debug(
      'handleClosedOppOwnerRevert -- currentUserProfileName: ' +
      currentUserProfileName
    );

    if (allowedProfiles.contains(currentUserProfileName)) {
      System.debug(
        'handleClosedOppOwnerRevert -- User profile is allowed, exiting'
      );
      return;
    }

    // Collect accounts where owner has changed
    Set<Id> ownerChangedAccountIds = new Set<Id>();
    for (Id accountId : newMap.keySet()) {
      if (newMap.get(accountId).OwnerId != oldMap.get(accountId).OwnerId) {
        ownerChangedAccountIds.add(accountId);
        System.debug(
          'handleClosedOppOwnerRevert -- Account owner changed: ' +
            accountId +
            ' | Old Owner: ' +
            oldMap.get(accountId).OwnerId +
            ' | New Owner: ' +
            newMap.get(accountId).OwnerId
        );
      }
    }

    System.debug(
      'handleClosedOppOwnerRevert -- ownerChangedAccountIds: ' +
      ownerChangedAccountIds
    );

    if (ownerChangedAccountIds.isEmpty()) {
      System.debug(
        'handleClosedOppOwnerRevert -- No account owner changes detected, exiting'
      );
      return;
    }

    // Query closed opportunities under these accounts
    Set<Id> closedOppIds = new Set<Id>();
    for (Opportunity opp : [
      SELECT Id
      FROM Opportunity
      WHERE AccountId IN :ownerChangedAccountIds AND IsClosed = TRUE
    ]) {
      closedOppIds.add(opp.Id);
    }

    System.debug(
      'handleClosedOppOwnerRevert -- closedOppIds found: ' + closedOppIds
    );

    if (!closedOppIds.isEmpty()) {
      System.debug(
        'handleClosedOppOwnerRevert -- Enqueuing RevertClosedOppOwnerQueueable with ' +
          closedOppIds.size() +
          ' opportunities'
      );
      System.enqueueJob(new RevertClosedOppOwnerQueueable(closedOppIds));
    } else {
      System.debug(
        'handleClosedOppOwnerRevert -- No closed opportunities found, not enqueuing'
      );
    }
    System.debug('handleClosedOppOwnerRevert -- END');
  }
}