force-app/main/default/objects/Account/fields/AccountDomain__c.field-meta.xml
<CustomField>
    <fullName>AccountDomain__c</fullName>
    <label>AccountDomain</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_address_domain_type_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type_SFDC__c</fullName>
    <label>Email address domain type SFDC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sys_Hierarchy_Required__c.field-meta.xml
<CustomField>
    <fullName>Sys_Hierarchy_Required__c</fullName>
    <description>This field will determine by LeanData if the new Account should be in Hierarchy structure under parent Account</description>
    <label>Sys Hierarchy Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler_Test.cls
/******************************************************************************* 
Name : AccountTriggerHandler_Test
Description : test class for AccountTriggerHandler class
Created/Modified by Created/Modified Date Requested by Related Task/Issue 
---------------------------------------------------------------------------------------- 
1.Nevo Haarari			 04/03/2018			ARIEL LOPEZ				[SW-28689] 
*********************************************************************************** 
*/
@isTest   
public class AccountTriggerHandler_Test  {


	@isTest  
	 static void  AccountTriggerHandler_Insert_TEST() {
		Account a = new Account();
		a.name = 'test1';
		a.Business_Unit__c='SMB';
		a.AccountDomain__c = 'DIMA.com';
		a.Domain__c = 'DIMA.com';
		a.SW_Industry__c = 'test1';
		a.Sys_Hierarchy_Required__c = 'Yes';
		a.Email_address_domain_type_SFDC__c = 'Company';
		a.Website = 'DIMA.COM';
		insert a;
		a.Domain__c = 'Nevo2.com';
		update a;

	}

}