force-app/main/default/objects/Account/fields/Always_Active__c.field-meta.xml
<CustomField>
    <fullName>Always_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, will always be considered ACTIVE by routing rules</description>
    <label>Always Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AutoAlwaysActive__c.field-meta.xml
<CustomField>
    <fullName>AutoAlwaysActive__c</fullName>
    <formula>Owner.UserRoleId=&quot;00Eb0000000aCj1&quot; || Owner.UserRoleId=&quot;00Eb0000000aDZg&quot; ||
Owner.UserRoleId=&quot;00Eb0000000aF9a&quot; || Owner.UserRoleId=&quot;00Eb0000000aF8X&quot; ||
Owner.UserRoleId=&quot;00Eb0000000t8ab&quot; || Owner.UserRoleId=&quot;00Eb0000000xK2K&quot; ||
Owner.UserRoleId=&quot;00Eb0000000aF8m&quot; || Owner.UserRoleId=&quot;00Eb0000000aEmC&quot; ||
Owner.UserRoleId=&quot;00Eb0000000t99i&quot; || Owner.UserRoleId=&quot;00Eb0000000tAA4&quot; ||
Owner.UserRoleId=&quot;00Eb0000000t9M3&quot; || Owner.UserRoleId=&quot;00Eb0000000aF8S&quot; ||
Owner.UserRoleId=&quot;00Eb0000000aDZW&quot; || Owner.UserRoleId=&quot;00Eb0000000t9U3&quot; ||
Owner.UserRoleId=&quot;00Eb0000000tAB7&quot; || Owner.UserRoleId=&quot;00Eb0000000aL6m&quot; ||
Owner.UserRoleId=&quot;00Eb0000000aLOg&quot; || Owner.UserRoleId=&quot;00Eb0000000aLOb&quot; ||
Owner.UserRoleId=&quot;00Eb00000011ogu&quot; || Owner.UserRoleId=&quot;00Eb0000000fQjp&quot; ||
Owner.UserRoleId=&quot;00Eb0000000Ymou&quot; || Owner.UserRoleId=&quot;00E0O000002G8IC&quot; ||
Owner.UserRoleId=&quot;00E0O000002G8IR&quot; || Owner.UserRoleId=&quot;00E0O000002G8Il&quot; ||
Owner.UserRoleId=&quot;00E0O000002G8Il&quot; || Owner.UserRoleId=&quot;00E0O000002G8J5&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AutoAlwaysActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Customers</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Route_to__c.field-meta.xml
<CustomField>
    <fullName>Route_to__c</fullName>
    <label>Route to</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SDR</fullName>
                <default>true</default>
                <label>SDR</label>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Routing_Group__c.field-meta.xml
<CustomField>
    <fullName>Routing_Group__c</fullName>
    <label>Routing Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SDR_Name__c.field-meta.xml
<CustomField>
    <fullName>SDR_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <label>UID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Website_Category__c.field-meta.xml
<CustomField>
    <fullName>Website_Category__c</fullName>
    <label>Website Category</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/AutoAlwaysActive__c.field-meta.xml
<CustomField>
    <fullName>AutoAlwaysActive__c</fullName>
    <formula>Owner:User.UserRoleId=&quot;00Eb0000000aCj1&quot; || Owner:User.UserRoleId=&quot;00Eb0000000aDZg&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000aF9a&quot; || Owner:User.UserRoleId=&quot;00Eb0000000aF8X&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000t8ab&quot; || Owner:User.UserRoleId=&quot;00Eb0000000xK2K&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000aF8m&quot; || Owner:User.UserRoleId=&quot;00Eb0000000aEmC&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000t99i&quot; || Owner:User.UserRoleId=&quot;00Eb0000000tAA4&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000t9M3&quot; || Owner:User.UserRoleId=&quot;00Eb0000000aF8S&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000aDZW&quot; || Owner:User.UserRoleId=&quot;00Eb0000000t9U3&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000tAB7&quot; || Owner:User.UserRoleId=&quot;00Eb0000000aL6m&quot; ||
Owner:User.UserRoleId=&quot;00Eb0000000aLOg&quot; || Owner:User.UserRoleId=&quot;00Eb0000000aLOb&quot; ||
Owner:User.UserRoleId=&quot;00Eb00000011ogu&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AutoAlwaysActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describes the business unit with the responsibility of the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Routing_Group__c.field-meta.xml
<CustomField>
    <fullName>Routing_Group__c</fullName>
    <label>Routing Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SDR_Name__c.field-meta.xml
<CustomField>
    <fullName>SDR_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignmentButtonHandler.cls
public with sharing class AssignmentButtonHandler {
    
    public ApexPages.StandardController con;
    public Id target_id{get;set;}
    public static integer showalert=0;
    public static string ErrMsChecklist = '';
    
    public string AssignmentError {get;set;}
    
    public AssignmentButtonHandler(apexPages.StandardController con)
    {
        if(test.isRunningTest()){
            iHaveToDoThis();
        }
        this.con = con;
    }
    
    public AssignmentButtonHandler()
    {
        AssignmentError = apexpages.currentpage().getParameters().get('error');
    }
    public AssignmentButtonHandler(Id tid)
    {
        target_id = tid;
    }
    public static AssignmentButtonHandler factory(Id target_id){
        AssignmentButtonHandler abh = new AssignmentButtonHandler(target_id);
        return abh;
    }
        
    public PageReference ManualRoundRobinLeadSMB()
    {
        /*
        id lid = ApexPages.currentPage().getParameters().get('id');
        Lead l = [select id, reseller__c,Campaign_Name_UTM__c, CreatedDate,email,ownerid,status, isConverted,company , 
                    LastName, business_unit__c,owner.isactive,country,
                    from Lead where id=:lid limit 1];
        LeadTriggerHelperTemp.RoundRobinLead (l,'SMB_Sales');
        l.business_unit__c='SMB';
        update l;
        update LeadTriggerHelperTemp.RoundRobinCS.values();
        PageReference pageref = new PageReference('/'+lid);
        return pageref;*/
        
        return LeadReassignment ('IS_ReRouting');
        
    } 
    
    public PageReference ManualRoundRobinLeadENT()
    {
        id lid = target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        Lead l = [select id, reseller__c,Campaign_Name_UTM__c,CreatedDate,email,ownerid,status, 
                    isConverted,company , LastName, business_unit__c,owner.isactive,
                    industry, Website_Category__c,country
                 from Lead where id=:lid limit 1];
                 
        l.business_unit__c='Enterprise';
        update l;
        update LeadTriggerHelperTemp.RoundRobinCS.values();
        PageReference pageref = new PageReference('/'+lid);
        return pageref;
        
    } 
    
    public PageReference ManualAssignmentSMB ()
    {
        /* sw-27989
        // Reassign Inside CSM button - account
        id aid = target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        Account a = [select id,ownerid from Account where id=:aid];
        a.business_unit__c='Inside Sales';
        update a; // This is done to make sure user can update the record
        */
        return  AccAssignment ('IS_ReRouting');     
    
    }
    
    public PageReference ManualAssignmentSMBAM ()
    {
        id aid = target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        Account a = QueryAccount (aid);
        a.business_unit__c='Inside Sales';
        update a; // This is done to make sure user can update the record
        //PageReference pageref = AccountTriggerHelperTemp.ManualAssignment (aid,'SMB AM');
        /*if (a.billingcountry==null)
        {
            PageReference pr = new Pagereference ('/apex/AssignmentErrorpage?error=No Country found on account');
            return pr;
        }
        */
        a.Routing_Group__c = 'InsideCSM_ReRouting';
        LeadTriggerHelperTEMP.SetValidValues();
        Pagereference Pageref = new pageReference ('/'+aid);
        return Pageref;
    
    }
    
    public PageReference ManualAssignmentSMBPaidAccount ()
    {
        id aid = target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        Account a = [select id,ownerid from Account where id=:aid];
        //a.business_unit__c='SMB';
        update a; // This is done to make sure user can update the record
        PageReference pageref = AccountTriggerHelperTemp.ManualAssignment (aid,'SMB Paid Account');
        
        return pageref;
        
    
    }
    
    public PageReference ManualLeadReassignment()
    {
        return LeadReassignment('SDR_ReRouting');
    }
    
    public PageReference LeadReassignment(string routinggroup)
    {
        id lid = target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        Lead l = [select id, reseller__c,Campaign_Name_UTM__c,CreatedDate,email,ownerid,status, 
                    isConverted,company , LastName, business_unit__c,owner.isactive,
                    industry, Website_Category__c,country,routing_group__c
                 from Lead where id=:lid limit 1];

        l.routing_group__C = routinggroup;
        LeadTriggerHelperTemp.SetKey_TeamMap('Lead');
        LeadTriggerHelperTemp.SetValidValues();

        update LeadTriggerHelperTemp.RoundRobinCS.values();
        PageReference pageref = new PageReference('/'+lid);
        return pageref;
        
    } 
    
    public PageReference ManualAccAssignment()
    {
        // Reassign SDR Button - Account
        system.debug('TESTING ManualAccAssignment fired');
        id aid =  target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        //PageReference pageref = AccountTriggerHelperTemp.ManualAssignment (aid,'SDR_ReRouting',true);
        //PageReference pageref = AccountTriggerHelperTemp.ManualAssignment (aid,'SDR_ReRouting','SDR');
        Account a = [select id,ownerid from Account where id=:aid];
        update a; // This is done to make sure user can update the record
        return  AccAssignment ('SDR_ReRouting');    
        
    }
    
    public static Account QueryAccount (id aid)
    {
        Account a = [select id, reseller__c,website, parentid, ownerid,Always_Active__c,
                       name, uid__c,email__c,billingcountry,
                        Status__c,
                        Business_Unit__c,owner.isactive,AutoAlwaysActive__c,
                        CreatedDate,Routing_Group__c,SDR_Name__c,Route_to__c,
                        ShippingCountry,BillingState,ShippingState,

                            (select id, StageName, AccountId from Opportunities) ,
                            (select id, name, ownerid from ChildAccounts) ,
                            (select id, email, ownerid, CreatedDate from Contacts),
                            (select id,Zuora__Status__c,Zuora__NextRenewalDate__c  from Zuora__Subscriptions__r),
                            (select id,Zuora__PaymentMethod_Type__c from Zuora__R00N40000001kyLcEAI__r)
                    from Account where id=:aid limit 1];
        
        return a;
    }
    
    public PageReference AccAssignment(string routinggroup)
    {
        id aid = target_id!=null?target_id:ApexPages.currentPage().getParameters().get('id');
        Account a = QueryAccount (aid);
                    
        system.debug('TESTING AccAssignment Fired. Acc business unit is '+a.business_unit__c);          

        a.routing_Group__c = routinggroup;

        LeadTriggerHelperTemp.SetKey_TeamMap('Account');
        LeadTriggerHelperTemp.SetValidValues();

        PageReference pageref = new PageReference('/'+aid);
        return pageref;
    }

    private void iHaveToDoThis(){
        integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
    

}