force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR Old field</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <formula>Case(BillingCountry,

&quot;United States&quot;,1,
&quot;US&quot;,1,
&quot;Canada&quot;,1,
&quot;Japan&quot;,1,
&quot;Australia&quot;,1,
&quot;India&quot;,1,
&quot;Russia&quot;,1,
&quot;China&quot;,1,
&quot;United Kingdom&quot;,1,
&quot;France&quot;,1,
&quot;Germany&quot;,1,

&quot;Brazil&quot;,2,
&quot;Columbia&quot;,2,
&quot;Argentina&quot;,2,
&quot;Mexico&quot;,2,
&quot;Hong Kong&quot;,2,
&quot;Singapore&quot;,2,
&quot;New Zealand&quot;,2,
&quot;Malaysia&quot;,2,
&quot;Austria&quot;,2,
&quot;Switzerland&quot;,2,
&quot;Sweden&quot;,2,
&quot;Denmark&quot;,2,
&quot;Spain&quot;,2,
&quot;Portugal&quot;,2,
&quot;Italy&quot;,2,
&quot;Netherlands&quot;,2,
&quot;Ireland&quot;,2,
&quot;Israel&quot;,2,
&quot;Norway&quot;,2,
&quot;Finland&quot;,2,

&quot;&quot;,Null,

3
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wolves_Status__c.field-meta.xml
<CustomField>
    <fullName>Wolves_Status__c</fullName>
    <label>Wolves Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Wolves.recordType-meta.xml
<RecordType>
    <fullName>Wolves</fullName>
    <active>true</active>
    <label>Panel Acquisition</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Payment_Cap__c.field-meta.xml
<CustomField>
    <fullName>Payment_Cap__c</fullName>
    <description>Data Partners (Wolves) - Indicates if there is a payment cap in the Contract. Used in the &quot;Data Partner&quot; Account. In case the total monthly payment is greater than the &quot;Payment Cap&quot; the last should override and we pay the Partner the Cap.</description>
    <label>Payment Cap</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly - Fix Price</fullName>
            </value>
            <value>
                <fullName>Monthly - Flex Rate</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>BI - Annual</fullName>
            </value>
            <value>
                <fullName>Fix Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Information for every &quot;Data Request&quot; for each Source. Part of the Data Partner model.</description>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <label>Country/Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Tier_for_Data_Partners</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DAU</fullName>
            </value>
            <value>
                <fullName>MAU</fullName>
            </value>
            <value>
                <fullName>S2S</fullName>
            </value>
            <value>
                <fullName>New User</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <description>The date the &quot;Rate&quot; is effective. Should be same as the Contract period. But not always. If there is a change in the Rate it should inflict by the Effective/End Date.</description>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Once populated, the &quot;Rate&quot; is no longer valid in the &quot;Monthly Data Request&quot; calculation.</description>
    <inlineHelpText>Once populated and Date is in the past, no Monthly Data Records will be created. In case the Source is no longer relevant, make sure to deactivate it!</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The actual Rate we pay for each data unit as agreed in the Contract</description>
    <label>Rate</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Part of the &quot;Data Partner&quot; model. A Source represents the Products that Similarweb pulls the data from. We get the &quot;Sources&quot; from the Data Partners.</description>
    <label>Source</label>
    <nameField>
        <label>Sources  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sources</relationshipLabel>
    <relationshipName>Sources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>MIS-3889</description>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>MW</fullName>
            </value>
            <value>
                <fullName>Apps</fullName>
            </value>
            <value>
                <fullName>Solution Specific</fullName>
            </value>
            <value>
                <fullName>Scraping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Data Core</fullName>
            </value>
            <value>
                <fullName>Apps</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SHI</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>DMI</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>Cross</fullName>
            </value>
            <value>
                <fullName>DRI</fullName>
            </value>
            <value>
                <fullName>DaaS</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>B2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source__c/fields/Source_Number__c.field-meta.xml
<CustomField>
    <fullName>Source_Number__c</fullName>
    <label>Source Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DataPartnerSpecificContractTest.cls
/**
 * Created by zohar.sinay on 02/03/2022.
 */

@IsTest
private class DataPartnerSpecificContractTest {

    @testSetup
    public static void setup(){
         String dataPartnerRecordTypeId = Utility.getRecordTypeIdForObject(New Account().getSObjectType(), 'Wolves');
        Account acc = new Account(Name='test', ARR__c = 5, RecordTypeId = dataPartnerRecordTypeId,Wolves_Status__c = 'Active');
        insert acc;
        Contract cont = new Contract(Name = 'Test', StartDate = date.today(), AccountId = acc.id,
                ContractTerm = 36, Status = 'Draft', OwnerExpirationNotice = '60', Payment_Method__c = 'Monthly', Payment_Cap__c = 12000);
        insert cont;
        cont.Status = 'Activated';
        update cont;
        Source__c source = new Source__c(Name = 'zohar test', Contract__c = cont.Id, Source_Number__c = 1441,Solution__c = 'Apps');
        insert source;
        Rate__c rate = new Rate__c(Name = 'zohar test', Request_Type__c = 1001, Rate__c = 0.1, Source__c = source.Id, Country_Tier__c = 'Tier 1',
                Data_Type__c = 'DAU', Effective_Date__c = Date.today() - 1, End_Date__c = Date.today() + 100);
        insert rate;
    }

    @IsTest
    static void testBehavior() {
        Test.startTest();
        Database.executeBatch(new DataPartnerManagementBatch(), 20);
        Test.stopTest();
        Source__c source = [SELECT Id,Contract__c FROM Source__c LIMIT 1];
        Source__c source1 = new Source__c(Name = 'zohar test2', Contract__c = source.Contract__c, Source_Number__c = 1442,Solution__c = 'Apps');
        insert source1;
        Rate__c rate = new Rate__c(Name = 'zohar test2', Request_Type__c = 1001, Rate__c = 0.1, Source__c = source1.Id, Country_Tier__c = 'Tier 1',
                Data_Type__c = 'DAU', Effective_Date__c = Date.today() - 1, End_Date__c = Date.today() + 100);
        insert rate;
        DataPartnersSpecificContractAController.createNewDataPartnersForContract(source.Contract__c);
    }
}