force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR Old field</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Re_Evaluate_Territory__c.field-meta.xml
<CustomField>
    <fullName>Re_Evaluate_Territory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if true will be re calculate in the  TerritoryManagementBatch</description>
    <label>Re Evaluate Territory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>MIS-1696</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <formula>BI_Data__r.Sub_Division_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROE Sub Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Re_evaluate__c.field-meta.xml
<CustomField>
    <fullName>Re_evaluate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for re-evaluating territories at the daily batch</description>
    <label>Re-evaluate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>Use to define Account Members for Stegetic Accounts</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActivateAccountFlagBatchTest.cls
/**
 * Created by Alon.Shalev on 7/26/2022.
 */
@IsTest
public with sharing class ActivateAccountFlagBatchTest {

    @testSetup
    public static void setup(){
        Territory__c territory = new Territory__c();
//        territory.Sub_Division__c = 'test SubDivision';
        territory.Re_evaluate__c = true;
        territory.Strategic_Pod__c = 'NAL-US-FinServ';
        insert territory;

        Account acc = new Account(Name='test', ARR__c = 5);
        acc.Territory__c = territory.Id;
        insert acc;

    }

    @istest
    public static void testBatch(){
        Test.startTest();
        Database.executeBatch(new ActivateAccountFlagBatch(),1);
        Test.stopTest();

        // assert
        Territory__c afterBatchTerritory = [SELECT Re_evaluate__c FROM Territory__c LIMIT 1];
        Account afterBatchAccount = [SELECT Re_Evaluate_Territory__c FROM Account LIMIT 1];
        System.assertEquals(afterBatchAccount.Re_Evaluate_Territory__c,true);
        System.assertEquals(afterBatchTerritory.Re_evaluate__c,false);


    }



}