force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR Old field</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/fr_ARR__c.field-meta.xml
<CustomField>
    <fullName>fr_ARR__c</fullName>
    <formula>BI_Data__r.ARR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/fr_Next_Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>fr_Next_Renewal_Date__c</fullName>
    <formula>fr_NextRenewalDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Owner_Division__c</fullName>
    <formula>Owner.Division</formula>
    <label>Account Owner Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Solution__c.field-meta.xml
<CustomField>
    <fullName>Primary_Solution__c</fullName>
    <label>Primary Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Solution__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Solution__c</fullName>
    <label>Secondary Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Unable to identify</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Data__c/BI_Data__c.object-meta.xml
<CustomObject>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Related_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_ID__c</fullName>
    <description>Stores ID of the related record</description>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Netsuite_Daily_Exchange_Rate__c/Netsuite_Daily_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Netsuite Daily Exchange Rate</label>
</CustomObject>

force-app/main/default/objects/Netsuite_Daily_Exchange_Rate__c/fields/Currency_DDL__c.field-meta.xml
<CustomField>
    <fullName>Currency_DDL__c</fullName>
    <label>Currency (DDL)</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Netsuite_Daily_Exchange_Rate__c/fields/USD_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>USD_Exchange_Rate__c</fullName>
    <label>USD Exchange Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Solution__c.field-meta.xml
<CustomField>
    <fullName>Primary_Solution__c</fullName>
    <label>Primary Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Unable to identify</fullName>
                <isActive>false</isActive>
                <label>Unable to identify</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Marketing.recordType-meta.xml
<RecordType>
    <fullName>Marketing</fullName>
    <active>false</active>
    <businessProcess>Inside Sales</businessProcess>
    <label>Marketing</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Renewal</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/CreateOpportunitiesBatchTest.cls
/**
* @author Itzik Winograd
* @date 10/10/2021
* @description CreateOpportunitiesBatch Test class
* --------------------------------------------------------------------------------------
* CHANGE HISTORY:
* --------------------------------------------------------------------------------------
* author      - 
* date        - 
* description - 
* --------------------------------------------------------------------------------------
*/
@isTest
public class CreateOpportunitiesBatchTest {
    private static FieldMappingNewUtils fmnu = new FieldMappingNewUtils('CreateOpps_Renewal');
    //Test setup. Create account, Zuora__Subscription__c, Zuora__CustomerAccount__c and update the BiData record.
    @testSetup
    public static void createRenewalBatchTestSetup(){
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createBaseProductConfiguration_CS();
        TestDataFactory.createInferredSolutionSettings_CS();

        Test.setMock(HttpCalloutMock.class, new TR_Acc_BusinessUnitCalcTest.MockHttpResponseGenerator());
        Account acc = AccountUtils.getAccounts(1)[0];
        acc.Primary_Solution__c = 'Marketing';
        acc.Secondary_Solution__c = 'Unable to identify';
        acc.Status__c = 'ACTIVE';
        acc.ownerId = getValidUsers()[0].Id;
        insert acc;
        Bi_Data__c bidata = [SELECT Id, ARR__C FROM Bi_Data__c WHERE Related_Record_ID__c = :acc.Id];
        bidata.ARR__c = 50;
        
        update biData;
        Zuora__CustomerAccount__c billAcc = TestDataFactory.createBillingAccount(acc);
        insert billAcc;
        Zuora__Subscription__c sub = TestDataFactory.createSubscription(acc, billAcc);
        insert sub;

        Product2 p = new Product2(Family = 'Pricing', IsActive = true, Name = 'Test Pricing');
        insert p;
        PricebookEntry entry = new PricebookEntry(Product2Id = p.Id, Pricebook2Id = Test.getStandardPricebookId(), UnitPrice = 123, IsActive = true);
        insert entry;

        //Run Renewal Batch
        Test.startTest();
        Id batchInstanceId = Database.executeBatch(new CreateOpportunitiesBatch('CreateOpps_Renewal'), 5); 
        Test.stopTest();
    }
	/** 
    * @author Itzik Winograd
    * @date 10/10/2021
    * @description: 1. Since the batch ran on the testSetup, 
    * 				   Assert all the fields on the account matches the fields on the Renewal Opportunity
    * 				2. Update the currency on the Zuora__CustomerAccount__c and insert relevant custom settings
    * @Expected:  2. Assert all the fields on the account matches the fields on the Upsell Opportunity
    */ 
    @isTest
    public static void createOppsBatchTestRenewals(){
        //Make assertions of the renewal opportunity
        Account acc = (Account)Database.query(fmnu.getSourceQuery('Account', ''))[0];
        Opportunity oppRenewal = (Opportunity)Database.query(fmnu.getDestinationQuery('Opportunity', ''))[0];
        for(String dest : fmnu.destinationVsMapping.keySet()){
            if(fmnu.destinationVsMapping.get(dest).fixedValue == null){
                System.assertEquals(oppRenewal.get(dest),acc.get(fmnu.destinationVsMapping.get(dest).source), 'Mismatch in Opportunity field ' + dest);
            }
        }
        //Update currency
        Zuora__CustomerAccount__c zca = [SELECT Id, Zuora__Currency__c FROM Zuora__CustomerAccount__c LIMIT 1];
        zca.Zuora__Currency__c = 'EUR';
        update zca;
        Netsuite_Daily_Exchange_Rate__c setting = new Netsuite_Daily_Exchange_Rate__c(
        	Name = 'EUR',
            Currency_DDL__c = 'EUR',
            USD_Exchange_Rate__c = 1.2
        );
        insert setting;
        //Run Upsell Batch
        Test.startTest();
        Id batchInstanceId = Database.executeBatch(new CreateOpportunitiesBatch('CreateOpps_Upsell'), 5); 
        Test.stopTest();
        Opportunity oppUpsell = (Opportunity)Database.query(fmnu.getDestinationQuery('Opportunity', '')+ ' WHERE Type = \'Upsell\'')[0];
        for(String dest : fmnu.destinationVsMapping.keySet()){
            if(fmnu.destinationVsMapping.get(dest).fixedValue == null){
                System.assertEquals(oppUpsell.get(dest),acc.get(fmnu.destinationVsMapping.get(dest).source), 'Mismatch in Opportunity field ' + dest);
            }
        }

    }
    
    private static List<Account> getValidAccounts(){
        List<Account> accountsList = [
            SELECT Id, Name, OwnerId, Primary_Solution__c, Secondary_Solution__c,
                ( SELECT Id, Zuora__NextRenewalDate__c, Zuora__MRR__c, Zuora__CustomerAccount__r.Zuora__Currency__c
                    FROM Zuora__Subscriptions__r
                ORDER BY CreatedDate DESC
                LIMIT 1)
             FROM Account
            WHERE (Status__c = 'ACTIVE' OR Status__c = 'Suspended')
              AND (Owner.userRole.Name LIKE '%Reseller%' OR Owner.userRole.Name LIKE '%CSM%' OR Owner.userRole.Name LIKE '%GM%')
              AND (NOT Owner_Division__c LIKE '%Business Operations%')
              AND (NOT Owner_Division__c LIKE '%Marketing%')
              AND (NOT Owner_Division__c LIKE '%MIR%')
              AND fr_ARR__c > 0
              AND fr_Next_Renewal_Date__c != 2100-01-01
              AND ID NOT IN(
                SELECT AccountId
                  FROM Opportunity
                 WHERE Type = 'Renewal'
                   AND CloseDate > LAST_MONTH)
              AND ID NOT IN(
                SELECT zqu__Account__c
                  FROM zqu__Quote__c
                 WHERE zqu__Status__c = 'Pending Renewal Date')
        ];
        System.debug('@@@ found accountsList: ' + accountsList);
        return accountsList;
    }
    
     private static List<User> getValidUsers(){
		return [ SELECT Id
                   FROM User
                  WHERE isActive = true
                    AND (userRole.Name LIKE '%Reseller%' OR userRole.Name LIKE '%CSM%' OR userRole.Name LIKE '%GM%')
                    AND (NOT Division LIKE '%Business Operations%')
                    AND (NOT Division LIKE '%Marketing%')
                    AND (NOT Division LIKE '%MIR%')];
     }
}