force-app/main/default/objects/Account/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR Old field</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competition__c.field-meta.xml
<CustomField>
    <fullName>Competition__c</fullName>
    <label>Using a competitor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Not using a competitor</fullName>
            </value>
            <value>
                <fullName>Evaluating a competitor</fullName>
            </value>
            <value>
                <fullName>Currently using a competitor</fullName>
            </value>
            <value>
                <fullName>Will replace SW with a competitor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cycle__c.field-meta.xml
<CustomField>
    <fullName>Cycle__c</fullName>
    <label>Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2 Years</fullName>
            </value>
            <value>
                <fullName>3 Years</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cycle_Price__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Price__c</fullName>
    <label>Cycle Price ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sold__c.field-meta.xml
<CustomField>
    <fullName>Product_Sold__c</fullName>
    <label>Product Sold</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Sold</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SYS_CloseFlow__c.field-meta.xml
<CustomField>
    <fullName>SYS_CloseFlow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SYS CloseFlow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AlertForClosedWonOppsTest.cls
/**
 * @author Itzik Winograd
 * @date 15/02/2021
 * @description Test class for the AlertForClosedWonOPpps class
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      -
 * date        -
 * description -
 * --------------------------------------------------------------------------------------
 */

/**
 * @author Itzik Winograd
 * @date 15/02/2021
 * @description Create 5 alerts and publish them
 * @return none.
 */
@isTest
public inherited sharing class AlertForClosedWonOppsTest {
  public static Integer NUMBER_OF_OPPS = 2;
  @isTest
  public static void alertForClosedWonOppsInsertTest() {
    Integer N = NUMBER_OF_OPPS;
    List<Opportunity> opps = new List<Opportunity>();
    Opportunity opp;
    for (Integer i = 0; i < N; i++) {
      opp = createOpp(i);
      opp.StageName = 'Closed Won';
      opps.add(opp);
    }
    Test.startTest();
    List<Database.SaveResult> sr_lst = Database.insert(opps);
    Test.stopTest();
    // Verify that the publish was successful
    for (Integer i = 0; i < sr_lst.size(); i++) {
      System.assertEquals(
        true,
        sr_lst[i].isSuccess(),
        'Error in ' + opps[i].Name + ': ' + sr_lst[i].getErrors()
      );
    }
  }

  @isTest
  public static void alertForClosedWonOppsUpdateTest() {
    Integer N = NUMBER_OF_OPPS;
    List<Opportunity> opps = new List<Opportunity>();
    Account acc = AccountUtils.getAccounts(1)[0];
    insert acc;
    Opportunity opp;
    for (Integer i = 0; i < N; i++) {
      opp = createOpp(i);
      opp.StageName = 'Proposal';
      opp.AccountId = acc.Id;
      opps.add(opp);
    }
    Database.insert(opps);
    for (Opportunity oppToUpdate : opps) {
      oppToUpdate.stageName = 'Closed Won';
      oppToUpdate.SYS_CloseFlow__c = !oppToUpdate.SYS_CloseFlow__c;
    }
    Test.startTest();
    List<Database.SaveResult> sr_lst = Database.update(opps);
    Test.stopTest();
    // Verify that the publish was successful
    for (Integer i = 0; i < sr_lst.size(); i++) {
      System.assertEquals(
        true,
        sr_lst[i].isSuccess(),
        'Error in ' + opps[i].Name + ': ' + sr_lst[i].getErrors()
      );
    }
  }

  /**
   * --- change---
   * @author Elnur Alibaev
   * @date 01/08/2025
   * @description Removed Product_Sold__c from opp initiation
   */
  public static Opportunity createOpp(Integer i) {
    return new Opportunity(
      Name = 'test' + i,
      CloseDate = Date.today(),
      Cycle__c = 'Annually',
      OwnerId = userInfo.getUserId(),
      Arr__c = 499,
      Cycle_Price__c = 500,
      Competition__c = 'none',
      Type = 'upsell'
    );
  }
}