force-app/main/default/objects/Account/fields/BankDetials__c.field-meta.xml
<CustomField>
    <fullName>BankDetials__c</fullName>
    <label>Bank Detials</label>
    <length>700</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>PA_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>&quot;123456789012345678901234567890&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Total_DAU__c.field-meta.xml
<CustomField>
    <fullName>Total_DAU__c</fullName>
    <label>Total DAU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePDFSettings__c/InvoicePDFSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Invoice PDF Settings</label>
</CustomObject>

force-app/main/default/objects/PA_Invoice__c/PA_Invoice__c.object-meta.xml
<CustomObject>
    <label>PA Invoice</label>
    <nameField>
        <displayFormat>Invoice N-{000000000}</displayFormat>
        <label>PA Invoice  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PA_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PA Invoices</relationshipLabel>
    <relationshipName>PA_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Bank_Detials__c.field-meta.xml
<CustomField>
    <fullName>Bank_Detials__c</fullName>
    <label>Bank Detials</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Invoice_Due__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Due__c</fullName>
    <label>Invoice Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Invoice_Note__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Note__c</fullName>
    <label>Invoice Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Paid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_To_Date__c</fullName>
    <label>Paid To Date</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicePDFController.cls
public class InvoicePDFController {

    public InvoiceWrapper inv {get;set;}
    public String to {get;set;}
    public String email {get;set;}
    public String defaultCurrency {get;set;}
    public Decimal VATPercent {get;set;}
    
    //public List<> lineItems; 
    
    public InvoicePDFController(ApexPages.StandardController stdController){
        inv = new InvoiceWrapper(stdController.getId());
        to = InvoicePDFSettings__c.getall().containsKey('To') ? InvoicePDFSettings__c.getInstance('To').Value__c : 'SimilarWeb';
        email = InvoicePDFSettings__c.getall().containsKey('Email') ? InvoicePDFSettings__c.getInstance('Email').Value__c : 'admin@fsmsoft.com';
        defaultCurrency =  UserInfo.getDefaultCurrency();
        VATPercent = InvoicePDFSettings__c.getall().containsKey('VAT') ? Decimal.valueOf(InvoicePDFSettings__c.getInstance('VAT').Value__c) : 17.00;
    }
        
    
    public class InvoiceWrapper {
        public String name {get;set;}
        public PA_Invoice__c invoice {get;set;}
        public List<InvoiceLineItem__c> lineItems {get;set;}
        public Decimal Total {get;set;}
        public Decimal PaidToDate {get;set;}
        public Decimal Balance {get;set;}
        
        public Boolean israelAccount {get;set;}
        public Decimal VAT {get;set;}
        
        public InvoiceWrapper(String invId){
            this.invoice = [select id, name, Bank_Detials__c, Account__c, Account__r.Name, Account__r.BillingCountry, Account__r.BillingCity, Account__r.BillingStreet, Account__r.BillingState, 
                        Account__r.BillingPostalCode, Account__r.BankDetials__c, Invoice_Due__c, Invoice_Note__c, Paid_To_Date__c from PA_Invoice__c where Id=:invId];
            this.lineItems = [select Id, Name,Total_DAU__c, Name__c, Amount__c from InvoiceLineItem__c where Invoice__c=:invId];
            this.israelAccount = invoice.Account__r.BillingCountry == 'Israel' ? true : false;
            styleInvoice();
            countTotals();
            System.debug('lineItems ' + lineItems  + '\n' + 'Total ' + Total + ', Balance ' + Balance);
        }
        
        public void styleInvoice(){
            name = this.invoice.Name.replaceAll('([^1-9])*', '');
        }
        
        public void countTotals(){
            Total = 0; PaidToDate =  0; Balance = 0;
            for (InvoiceLineItem__c ili :lineItems ){
                if (ili.Amount__c != null)
                    Total+=ili.Amount__c ;
            }
            if (israelAccount){
                VAT = Total * 0.17;
                Total += VAT;
            }
            Balance = Total + PaidToDate;
        }
    }
    
}