force-app/main/default/objects/Account/fields/Base_Product__c.field-meta.xml
<CustomField>
    <fullName>Base_Product__c</fullName>
    <label>Base Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Base_Product__c/Base_Product__c.object-meta.xml
<CustomObject>
    <label>Base Product</label>
    <nameField>
        <label>Base Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/BI_Data__c.object-meta.xml
<CustomObject>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/fields/Base_Product__c.field-meta.xml
<CustomField>
    <fullName>Base_Product__c</fullName>
    <label>Base Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/ROE_Division__c.field-meta.xml
<CustomField>
    <fullName>ROE_Division__c</fullName>
    <label>ROE Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ENT Sales - France</fullName>
            </value>
            <value>
                <fullName>Global Sales - Investors</fullName>
            </value>
            <value>
                <fullName>Global Sales - US</fullName>
            </value>
            <value>
                <fullName>Reseller - SEA-Maestros</fullName>
            </value>
            <value>
                <fullName>ENT Sales - US</fullName>
            </value>
            <value>
                <fullName>Global Sales - Agencies</fullName>
            </value>
            <value>
                <fullName>Reseller - India-eDynamics</fullName>
            </value>
            <value>
                <fullName>SMB Sales - ROW</fullName>
            </value>
            <value>
                <fullName>Reseller - ANZ - Direct</fullName>
            </value>
            <value>
                <fullName>Reseller - Italy-GlobalDots</fullName>
            </value>
            <value>
                <fullName>Reseller - ANZ-Trellian</fullName>
            </value>
            <value>
                <fullName>Reseller - Japan</fullName>
            </value>
            <value>
                <fullName>Reseller - Turkey-Nielsen</fullName>
            </value>
            <value>
                <fullName>Global Sales - Europe</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil</fullName>
            </value>
            <value>
                <fullName>SMB Sales - US</fullName>
            </value>
            <value>
                <fullName>ENT Sales - Europe</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/SW_Behavioral_Rate__c.field-meta.xml
<CustomField>
    <fullName>SW_Behavioral_Rate__c</fullName>
    <label>SW Behavioral Rate</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ROE_Division__c.field-meta.xml
<CustomField>
    <fullName>ROE_Division__c</fullName>
    <formula>TEXT(BI_Data__r.ROE_Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROE Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SW_Behavioral_Rate__c.field-meta.xml
<CustomField>
    <fullName>SW_Behavioral_Rate__c</fullName>
    <formula>BI_Data__r.SW_Behavioral_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Behavioral Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fit_Score_Call_Log__c/Fit_Score_Call_Log__c.object-meta.xml
<CustomObject>
    <label>Fit Score Call Log</label>
    <nameField>
        <label>Fit Score Call Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fit Score Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Base_Product__c.field-meta.xml
<CustomField>
    <fullName>Base_Product__c</fullName>
    <label>Base Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MQL__c.field-meta.xml
<CustomField>
    <fullName>MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Behavioral_Rate__c.field-meta.xml
<CustomField>
    <fullName>SW_Behavioral_Rate__c</fullName>
    <formula>BI_Data__r.SW_Behavioral_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW_Behavioral_Rate__c</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>SW_Fit_Score__c</fullName>
    <label>SW Fit Score</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BIDataPopulateRelatedRecordsTrigger_Test.cls
/**
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      - Itzik Winograd
 * date        -  02/02/2021
 * description - Added line 31: bid.ROE_Division__c = 'SMB Sales - US',
 * and an assertion below. This line will test the class BiDataCallFitScore.
 * --------------------------------------------------------------------------------------
 */
@isTest
private class BIDataPopulateRelatedRecordsTrigger_Test {
  @testSetup
  static void prepareData() {
    TestDataFactory.createSimilarWeb_CS();
    TestDataFactory.createInferredSolutionSettings_CS();

    Account acc = TestDataFactory.createAccount();
    insert acc;
    Contact cnt = TestDataFactory.createContact(acc, 'test@aaa.com');
    insert cnt;
    Lead ld = TestDataFactory.createLead();
    insert ld;
  }

  @isTest
  static void testUpdate() {
    List<BI_Data__c> bids = [SELECT Id, Base_Product__c FROM BI_Data__c];
    for (BI_Data__c bid : bids) {
      bid.Base_Product__c = '1';
      bid.SW_Behavioral_Rate__c = 3;
      bid.ROE_Division__c = 'SMB Sales - US';
    }
    Test.startTest();
    update bids;
    Test.stopTest();

    Account acc = [SELECT Id, Base_Product__c FROM Account LIMIT 1];
    Contact cnt = [SELECT Id, Base_Product__c FROM Contact LIMIT 1];
    Lead ld = [SELECT Id, Base_Product__c FROM Lead LIMIT 1];

    List<Fit_Score_Call_Log__c> fitScoreLog = new List<Fit_Score_Call_Log__c>(
      [
        SELECT Id
        FROM Fit_Score_Call_Log__c
      ]
    );
    System.assertNotEquals(
      0,
      fitScoreLog.size(),
      'No Fit score call log was found!'
    );

    // System.assertEquals('1', acc.Base_Product__c);
    // System.assertEquals('1', ld.Base_Product__c);
    // System.assertEquals('1', cnt.Base_Product__c);
  }

  /**
   * @author Itzik Winograd
   * @date 04/05/2021
   * @description: Set SW_Behavioral_Rate__c to 'C' on a Contact that is mql=false.
   * Also, set SW_Fit_Score__c to 2 on the related bi record.
   * @expected: MQL on the Contact will be true since C-2 should be true.
   */
  @isTest
  public static void testMQLforCGrade() {
    Contact cnt = [
      SELECT Id, SW_Fit_Score__c, Bi_Data__c
      FROM Contact
      WHERE MQL__c = FALSE
      LIMIT 1
    ];
    cnt.SW_Fit_Score__c = 'C';

    BI_Data__c bid = [
      SELECT Id, Base_Product__c
      FROM BI_Data__c
      WHERE Id = :cnt.Bi_Data__c
    ];
    bid.SW_Behavioral_Rate__c = 2;

    Test.startTest();
    update cnt;
    update bid;
    Test.stopTest();

    cnt = [
      SELECT Id, MQL__c, SW_Fit_Score__c, BI_Data__r.SW_Behavioral_Rate__c
      FROM Contact
      LIMIT 1
    ];
    System.assertEquals(
      true,
      cnt.MQL__c,
      'MQL on Contact is not true as expected: ' +
        cnt.MQL__c +
        ', ' +
        cnt.SW_Fit_Score__c +
        ', ' +
        cnt.Bi_Data__r.SW_Behavioral_Rate__c
    );
  }
}