force-app/main/default/objects/Account/fields/Base_Product__c.field-meta.xml
<CustomField>
    <fullName>Base_Product__c</fullName>
    <label>Base Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hierarchy_Total_Open_Opps__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Total_Open_Opps__c</fullName>
    <label>Hierarchy Total Open Opps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_Touch_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Touch_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Touch Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Open_Opps__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Open_Opps__c</fullName>
    <label># of Open Opps.</label>
    <summaryFilterItems>
        <field>Opportunity.IsClosed</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent_Company_Domain__c.field-meta.xml
<CustomField>
    <fullName>Parent_Company_Domain__c</fullName>
    <description>#1101356 Populates by SalesOps
[OB] - Field type changed to &quot;Text&quot; and checked &quot;External Id&quot; - This is for using the field in &quot;Get Records&quot; in Flow.</description>
    <externalId>true</externalId>
    <label>Parent Company Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Part of Account Path</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Ongoing Outbound</fullName>
            </value>
            <value>
                <fullName>Pending Meeting</fullName>
            </value>
            <value>
                <fullName>Pre Pipeline</fullName>
            </value>
            <value>
                <fullName>Early Stage Pipeline</fullName>
            </value>
            <value>
                <fullName>Deal in Closing Pipeline</fullName>
            </value>
            <value>
                <fullName>Trial / NT / One-time</fullName>
            </value>
            <value>
                <fullName>Paying Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website, &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) != 0, MID(Website, 5, FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) -1), MID(Website, 5, LEN(Website) - 4)),

If(BEGINS(Website, &quot;http://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 12, LEN(Website) - 11)) != 0,MID(Website, 12, FIND(&apos;/&apos;, MID(Website,12,LEN(Website) - 11)) -1), MID(Website,12,LEN(Website)-11)),

If(BEGINS(Website, &quot;https://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 13, LEN(Website) - 12)) != 0,MID(Website, 13, FIND(&apos;/&apos;, MID(Website,13,LEN(Website) - 12)) -1), MID(Website,13,LEN(Website)-12)),

If(BEGINS(Website, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 8, LEN(Website) - 7)) != 0,MID(Website, 8, FIND(&apos;/&apos;, MID(Website,8,LEN(Website) - 7)) -1), MID(Website,8,LEN(Website)-7)),

If(BEGINS(Website, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 9, LEN(Website) - 8)) != 0,MID(Website, 9, FIND(&apos;/&apos;, MID(Website,9,LEN(Website) - 8)) -1), MID(Website,9,LEN(Website)-8)),

IF(FIND(&apos;/&apos;,MID(Website, 1, LEN(Website))) !=0,MID(Website,1,FIND(&apos;/&apos;, Website) - 1), Website ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Product__c/Base_Product__c.object-meta.xml
<CustomObject>
    <label>Base Product</label>
    <nameField>
        <label>Base Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Champion__c.field-meta.xml
<CustomField>
    <fullName>Champion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MIS-4112</description>
    <label>Champion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>PRO Demo</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website__c , &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 5, LEN(Website__c) - 4)) != 0, MID(Website__c, 5, FIND(&apos;/&apos;, MID(Website__c, 5, LEN(Website__c) - 4)) -1), MID(Website__c, 5, LEN(Website__c) - 4)), 

If(BEGINS(Website__c, &quot;http://www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 12, LEN(Website__c) - 11)) != 0,MID(Website__c, 12, FIND(&apos;/&apos;, MID(Website__c,12,LEN(Website__c) - 11)) -1), MID(Website__c,12,LEN(Website__c)-11)), 

If(BEGINS(Website__c, &quot;https://www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 13, LEN(Website__c) - 12)) != 0,MID(Website__c, 13, FIND(&apos;/&apos;, MID(Website__c,13,LEN(Website__c) - 12)) -1), MID(Website__c,13,LEN(Website__c)-12)), 

If(BEGINS(Website__c, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 8, LEN(Website__c) - 7)) != 0,MID(Website__c, 8, FIND(&apos;/&apos;, MID(Website__c,8,LEN(Website__c) - 7)) -1), MID(Website__c,8,LEN(Website__c)-7)), 

If(BEGINS(Website__c, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 9, LEN(Website__c) - 8)) != 0,MID(Website__c, 9, FIND(&apos;/&apos;, MID(Website__c,9,LEN(Website__c) - 8)) -1), MID(Website__c,9,LEN(Website__c)-8)), 

IF(FIND(&apos;/&apos;,MID(Website__c, 1, LEN(Website__c))) !=0,MID(Website__c,1,FIND(&apos;/&apos;, Website__c) - 1), Website__c ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <description>Disclaimer:
Record type = who created the meeting
Owner = who got the meeting</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Contact_Related_To__c.field-meta.xml
<CustomField>
    <fullName>Contact_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Related to:</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meetings__c.field-meta.xml
<CustomField>
    <fullName>Meetings__c</fullName>
    <description>Used in report to generate a list of # meetings per user, even if no meeting exists</description>
    <formula>VALUE(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label># Meetings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>In MIR, SDR and Sales Meetings - use the &quot;Complete Meeting&quot; Button at the top of the page</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Rescheduling</fullName>
            </value>
            <value>
                <fullName>Scheduling in Progress</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Base_product__c.field-meta.xml
<CustomField>
    <fullName>Base_product__c</fullName>
    <description>MIS-893 Base Product on Opp</description>
    <label>Base product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Champion__c.field-meta.xml
<CustomField>
    <fullName>Champion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>MIS-2043</description>
    <inlineHelpText>Who at the company with influence is advocating on your behalf?</inlineHelpText>
    <label>Champion</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Champion)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountHierarchyDataCtrl.cls
public with sharing class AccountHierarchyDataCtrl {

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getHierarchyData(String parentCompanyDomain,String websiteDomain, String accountId) {
        System.debug('started---' + parentCompanyDomain);
        Map<String, Object> hierarchyMap = new Map<String, Object>();
        handleSums(parentCompanyDomain,websiteDomain, hierarchyMap);

//        AccountHierarchy accountHierarchy = handleHierarchyAccounts(accountId);
//        System.debug('accountHierarchy--' + accountHierarchy);
        Map<Id,AccountMapObj> accountIdToRelationMap = new Map<Id, AccountHierarchyDataCtrl.AccountMapObj>();
        queryMainAccount(accountId,accountIdToRelationMap);
//        hierarchyMap.put('gridDataFromApex',convertToHierarchy(accountIdToRelationMap));
        hierarchyMap.put('gridDataFromApex',convertToHierarchy(accountIdToRelationMap));

//        hierarchyMap.put('gridData', transformToMap(accountHierarchy,new Set<Id>()));

        return hierarchyMap;
    }

    public static Map<String,Object> convertToHierarchy(Map<Id,AccountMapObj> accountIdToRelationMap){
        Map<String,Object> returnObj = new Map<String, Object>();
        for(AccountMapObj accountMapObj : accountIdToRelationMap.values()){
            if(accountMapObj.isTopParentAccount){
                returnObj = populateAll(accountMapObj,accountIdToRelationMap,true,true);
                break;
            }
        }
        return returnObj;
    }

    private static Map<String, Object> populateAll(AccountMapObj accountMapObj,Map<Id,AccountMapObj> accountIdToRelationMap,boolean isTopParent , boolean isExposed) {
        Map<String, Object> returnObj = new Map<String, Object>();
        returnObj.put('Id', accountMapObj.currentAccount.Id);
        returnObj.put('Name', accountMapObj.currentAccount.Name);
        returnObj.put('Status__c', accountMapObj.currentAccount.Status__c);
        returnObj.put('BillingCountry', accountMapObj.currentAccount.BillingCountry);
        returnObj.put('Number_of_Open_Opps__c', accountMapObj.currentAccount.Number_of_Open_Opps__c);
        returnObj.put('Website', accountMapObj.currentAccount.Website);
        returnObj.put('LastActivityDate', accountMapObj.currentAccount.LastActivityDate);
        returnObj.put('OwnerName', accountMapObj.currentAccount.Owner.Name); // Note: You may need to fetch the owner name separately
        returnObj.put('Base_Product__c', accountMapObj.currentAccount.Base_Product__c);
        returnObj.put('isExposed',isExposed);
        if(!accountMapObj.childAccounts.isEmpty()){
            isExposed = isTopParent;
            isTopParent = false;
            List<Map<String,Object>> children = new List<Map<String, Object>>();
            for(Account childAccount : accountMapObj.childAccounts){
                children.add(populateAll(accountIdToRelationMap.get(childAccount.Id),accountIdToRelationMap,isTopParent,isExposed));
            }
            returnObj.put('_children',children);
        }
        return returnObj;
    }


    public static void queryMainAccount(String accountId , Map<Id,AccountMapObj> accountIdToRelationMap){
        Account accountWithParentsAndChildren = [
                SELECT Id, Name, Status__c, Number_of_Open_Opps__c, Website, LastActivityDate, Owner.Name, Base_Product__c, BillingCountry, ParentId,
                (SELECT Id, Name, Status__c, Number_of_Open_Opps__c, Website, LastActivityDate, Owner.Name, Base_Product__c, BillingCountry, ParentId FROM ChildAccounts)
                FROM Account
                WHERE Id = :accountId
        ];
        AccountMapObj mainAccount =  new AccountMapObj();
        mainAccount.currentAccount = accountWithParentsAndChildren;
        accountIdToRelationMap.put(accountWithParentsAndChildren.Id , mainAccount);
        if(accountWithParentsAndChildren.ParentId != null){
            mainAccount.parentAccountId = accountWithParentsAndChildren.ParentId;
            queryMainAccount(mainAccount.parentAccountId , accountIdToRelationMap);
        }else{
            mainAccount.isTopParentAccount = true;
        }
        System.debug('accountWithParentsAndChildren.ChildAccounts---'+accountWithParentsAndChildren.ChildAccounts);
        if(!accountWithParentsAndChildren.ChildAccounts.isEmpty()){
            System.debug(' i am here');
            mainAccount.childAccounts = accountWithParentsAndChildren.ChildAccounts;
            queryChildAccounts(accountWithParentsAndChildren.ChildAccounts,accountIdToRelationMap);
        }else{
            mainAccount.isBottomAccount = true;
        }
    }

    private static void queryChildAccounts(List<Account> childAccounts , Map<Id,AccountMapObj> accountIdToRelationMap){

        List<Account> grandSonAccountList = new List<Account>();
        List<Account> childrenAccountWithGrandsonAccounts = [
                SELECT Id, Name, Status__c, Number_of_Open_Opps__c, Website, LastActivityDate, Owner.Name, Base_Product__c, BillingCountry, ParentId,
                (SELECT Id, Name, Status__c, Number_of_Open_Opps__c, Website, LastActivityDate, Owner.Name, Base_Product__c, BillingCountry, ParentId FROM ChildAccounts)
                FROM Account
                WHERE Id IN : childAccounts
        ];

        for (Account childAccount : childrenAccountWithGrandsonAccounts){
            AccountMapObj accountMapObj = new AccountMapObj();
            accountMapObj.parentAccountId = childAccount.ParentId;
            accountMapObj.currentAccount = childAccount;
            accountIdToRelationMap.put(childAccount.id ,accountMapObj);
            if(!childAccount.ChildAccounts.isEmpty()){
                accountMapObj.childAccounts = childAccount.ChildAccounts;
                grandSonAccountList.addAll(childAccount.ChildAccounts);
            }else{
                accountMapObj.isBottomAccount = true;
            }

        }
        if(!grandSonAccountList.isEmpty()){
            queryChildAccounts(grandSonAccountList,accountIdToRelationMap);
        }
    }

    public class AccountMapObj{
        @AuraEnabled
        public Account currentAccount;
        @AuraEnabled
        public Id parentAccountId;
        @AuraEnabled
        public List<Account> childAccounts;
        @AuraEnabled
        public Boolean isBottomAccount;
        @AuraEnabled
        public Boolean isTopParentAccount;

        public AccountMapObj(){
            this.isBottomAccount = false;
            this.childAccounts = new List<Account>();
            this.isTopParentAccount = false;
        }
    }
    private static void handleSums(String parentCompanyDomain,String websiteDomain, Map<String, Object> hierarchyMap) {
        Integer oppSum = 0;
        Integer subsSum = 0;
        Integer meetingsSum = 0;
        Integer contactsSum = 0;
        Integer contactsChampionsSum = 0;
        Integer payingAccountSum = 0;
        Integer noTouchAccountSum = 0;
        Integer activeOrAdminUserSum = 0;
        Decimal hierarchyTotalOpenOppsSum = 0;
        Integer hierarchyOwner = 0; // need to take from bi
        String allHierarchyBaseProductNames = ''; // need to take from bi
        Set<String> baseProductsSet = new Set<String>();
        String query = 'SELECT Id, Stage__c, No_Touch_Account__c,Hierarchy_Total_Open_Opps__c,Base_Product__c,Status__c,\n' +
                '                                        (SELECT Id,IsClosed FROM Opportunities),\n' +
                '                                        (SELECT Id FROM Meetings__r),\n' +
                '                                        (SELECT Id FROM Zuora__Subscriptions__r),\n' +
                '                                        (SELECT Id, Champion__c, Pro_User_Type__c FROM Contacts)\n' +
                '                                    FROM Account ' ;
        query += String.isNotBlank(parentCompanyDomain) ? 'WHERE Parent_Company_Domain__c = :parentCompanyDomain' : 'WHERE Parent_Company_Domain__c = null AND Website_Domain__c = :websiteDomain ';
        List<Account> accountList = Database.query(query);
//        List<Account> accountList = [SELECT Id, Stage__c, No_Touch_Account__c,Hierarchy_Total_Open_Opps__c,Base_Product__c,Status__c,
//                                        (SELECT Id FROM Opportunities),
//                                        (SELECT Id FROM Meetings__r),
//                                        (SELECT Id FROM Zuora__Subscriptions__r),
//                                        (SELECT Id, Champion__c, Pro_User_Type__c FROM Contacts)
//                                    FROM Account WHERE Parent_Company_Domain__c = :parentCompanyDomain];
        System.debug('accountList--'+accountList.size());
        for (Account acc : accountList) {
            if(String.isNotBlank(acc.Base_Product__c) &&  acc.Base_Product__c != 'NA'){
                System.debug('acc.asdasd -- '+acc.Base_Product__c);
                baseProductsSet.add(acc.Base_Product__c);
            }
            System.debug('baseProductsSet---'+baseProductsSet);
            for(Opportunity opp : acc.Opportunities){
                System.debug('baseProductsSet---'+baseProductsSet);
                if(opp.IsClosed == false){
                    hierarchyTotalOpenOppsSum ++;
                }
            }
            oppSum += acc.Opportunities.size();
            contactsSum += acc.Contacts.size();
            meetingsSum += acc.Meetings__r.size();
            subsSum += acc.Zuora__Subscriptions__r.size();
            for (Contact accountContact : acc.Contacts) {
                if (accountContact.Champion__c) {
                    contactsChampionsSum++;
                }
                if (accountContact.Pro_User_Type__c != null) {
                    if (accountContact.Pro_User_Type__c.containsIgnoreCase('User') || accountContact.Pro_User_Type__c.containsIgnoreCase('Admin')) {
                        activeOrAdminUserSum++;
                    }
                }
            }
            if (acc.Stage__c == 'Paying Account' && (acc.Status__c == 'Active' || acc.Status__c == 'Cancelled')) {
                payingAccountSum++;
            }
            if (acc.No_Touch_Account__c) {
                noTouchAccountSum++;
            }

        }
        System.debug('base product set ---- : '+baseProductsSet);
        System.debug('base product set -joined--- : '+String.join(new List<String>(baseProductsSet),','));
        hierarchyMap.put('totalAccounts', accountList.size());
        hierarchyMap.put('payingAccounts', payingAccountSum);
        hierarchyMap.put('noTouchAccounts', noTouchAccountSum);
        hierarchyMap.put('totalOpportunities', oppSum);
        hierarchyMap.put('totalSubscriptions', subsSum);
        hierarchyMap.put('totalMeetings', meetingsSum);
        hierarchyMap.put('totalContacts', contactsSum);
        hierarchyMap.put('totalChampions', contactsChampionsSum);
        hierarchyMap.put('totalAdmins', activeOrAdminUserSum);
        hierarchyMap.put('allHierarchyBaseProductUniqueNames',baseProductsSet.isEmpty() ?'N/A' : String.join(new List<String>(baseProductsSet),','));
        hierarchyMap.put('hierarchyTotalOpenOppsSum',hierarchyTotalOpenOppsSum);
//        hierarchyMap.put('hierarchyOwner', hierarchyOwner);
        System.debug('hierarchyMap--' + hierarchyMap);
        System.debug('world of account hierarchy --- ' + hierarchyMap.get('gridData'));
    }
}