force-app/main/default/objects/Account/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <description>MIS-2388</description>
    <inlineHelpText>please use https://www.didnotfind.com if no LinkedIn found</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website, &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) != 0, MID(Website, 5, FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) -1), MID(Website, 5, LEN(Website) - 4)),

If(BEGINS(Website, &quot;http://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 12, LEN(Website) - 11)) != 0,MID(Website, 12, FIND(&apos;/&apos;, MID(Website,12,LEN(Website) - 11)) -1), MID(Website,12,LEN(Website)-11)),

If(BEGINS(Website, &quot;https://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 13, LEN(Website) - 12)) != 0,MID(Website, 13, FIND(&apos;/&apos;, MID(Website,13,LEN(Website) - 12)) -1), MID(Website,13,LEN(Website)-12)),

If(BEGINS(Website, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 8, LEN(Website) - 7)) != 0,MID(Website, 8, FIND(&apos;/&apos;, MID(Website,8,LEN(Website) - 7)) -1), MID(Website,8,LEN(Website)-7)),

If(BEGINS(Website, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 9, LEN(Website) - 8)) != 0,MID(Website, 9, FIND(&apos;/&apos;, MID(Website,9,LEN(Website) - 8)) -1), MID(Website,9,LEN(Website)-8)),

IF(FIND(&apos;/&apos;,MID(Website, 1, LEN(Website))) !=0,MID(Website,1,FIND(&apos;/&apos;, Website) - 1), Website ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/BI_Data__c.object-meta.xml
<CustomObject>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/fields/Top_10_Searches__c.field-meta.xml
<CustomField>
    <fullName>Top_10_Searches__c</fullName>
    <label>Top 10 Searches</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <inlineHelpText>please use https://www.didnotfind.com if no LinkedIn found</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website__c , &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 5, LEN(Website__c) - 4)) != 0, MID(Website__c, 5, FIND(&apos;/&apos;, MID(Website__c, 5, LEN(Website__c) - 4)) -1), MID(Website__c, 5, LEN(Website__c) - 4)), 

If(BEGINS(Website__c, &quot;http://www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 12, LEN(Website__c) - 11)) != 0,MID(Website__c, 12, FIND(&apos;/&apos;, MID(Website__c,12,LEN(Website__c) - 11)) -1), MID(Website__c,12,LEN(Website__c)-11)), 

If(BEGINS(Website__c, &quot;https://www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 13, LEN(Website__c) - 12)) != 0,MID(Website__c, 13, FIND(&apos;/&apos;, MID(Website__c,13,LEN(Website__c) - 12)) -1), MID(Website__c,13,LEN(Website__c)-12)), 

If(BEGINS(Website__c, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 8, LEN(Website__c) - 7)) != 0,MID(Website__c, 8, FIND(&apos;/&apos;, MID(Website__c,8,LEN(Website__c) - 7)) -1), MID(Website__c,8,LEN(Website__c)-7)), 

If(BEGINS(Website__c, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website__c, 9, LEN(Website__c) - 8)) != 0,MID(Website__c, 9, FIND(&apos;/&apos;, MID(Website__c,9,LEN(Website__c) - 8)) -1), MID(Website__c,9,LEN(Website__c)-8)), 

IF(FIND(&apos;/&apos;,MID(Website__c, 1, LEN(Website__c))) !=0,MID(Website__c,1,FIND(&apos;/&apos;, Website__c) - 1), Website__c ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EeveeController.cls
public with sharing class EeveeController {
  @AuraEnabled(cacheable=false)
  public static String getData(String recordId) {
    String iframeUrl = 'https://eevee.int.similarweb.io/agent/deck';

    Account a = [
      SELECT
        Id,
        Website,
        BillingCountryCode,
        BI_Data__c,
        BI_Data__r.Top_10_Searches__c
      FROM Account
      WHERE Id = :recordId
    ];

    iframeUrl +=
      '?primary=' +
      (a.Website == 'no_website' || String.isBlank(a.Website)
        ? 'N/A'
        : a.Website);
    iframeUrl +=
      '&country=' +
      (String.isBlank(a.BillingCountryCode)
        ? 'N/A'
        : a.BillingCountryCode.toLowerCase());

    if (
      String.isNotBlank(a.BI_Data__c) &&
      String.isNotBlank(a.BI_Data__r.Top_10_Searches__c)
    ) {
      List<String> competitors = a.BI_Data__r.Top_10_Searches__c.split(', ');
      List<String> top4Competitors = new List<String>();
      Integer cnt = 0;

      for (String c : competitors) {
        if (cnt < 4) {
          top4Competitors.add(c);
          cnt++;
        } else {
          break;
        }
      }

      iframeUrl += '&competitors=' + String.join(top4Competitors, ',');
    }

    return iframeUrl;
  }

  @AuraEnabled(cacheable=false)
  public static String getContactEmailsData(String recordId) {
    String iframeUrl = 'https://eevee.int.similarweb.io/agent/draft---30-second-pe';

    Contact c = [
      SELECT
        Id,
        Website_Domain__c,
        MailingCountryCode,
        LinkedIn_Profile__c,
        Title
      FROM Contact
      WHERE Id = :recordId
    ];

    iframeUrl +=
      '?company_domain=' +
      (String.isBlank(c.Website_Domain__c) ? 'N/A' : c.Website_Domain__c);
    iframeUrl +=
      '&country=' +
      (String.isBlank(c.MailingCountryCode) ? 'N/A' : c.MailingCountryCode);
    iframeUrl +=
      '&linkedin_url=' +
      (String.isBlank(c.LinkedIn_Profile__c)
        ? (String.isBlank(c.Title) ? 'N/A' : c.Title)
        : c.LinkedIn_Profile__c);

    return iframeUrl;
  }
}