force-app/main/default/objects/Account/fields/Billing_expert__c.field-meta.xml
<CustomField>
    <fullName>Billing_expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Owner_Division__c</fullName>
    <formula>Owner.Division</formula>
    <label>Account Owner Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_expert_Mapping__c/Billing_expert_Mapping__c.object-meta.xml
<CustomObject>
    <label>Billing expert Mapping</label>
    <nameField>
        <displayFormat>BE-{00000}</displayFormat>
        <label>Billing expert  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing expert Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_expert_Mapping__c/fields/Billing_Expert__c.field-meta.xml
<CustomField>
    <fullName>Billing_Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Expert</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Billing_expert_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_expert_Mapping__c/fields/Change_in_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Change_in_Mapping__c</fullName>
    <defaultValue>true</defaultValue>
    <description>MIS-2458 - when there is a change in the billing expert field this checkbox will be true and the batch process will update all of the account that match the mapping</description>
    <label>Change in Mapping</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_expert_Mapping__c/fields/Owner_Division__c.field-meta.xml
<CustomField>
    <fullName>Owner_Division__c</fullName>
    <label>Owner Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BillingExpertBatchTest.cls
/**
 * @author          Itzik Winograd
 * @date            24/07/2022
 * @description     MIS-2458. Test for the BillingExpertBatch class
 */
@IsTest
public with sharing class BillingExpertBatchTest {
    private static FINAL Integer BATCH_SIZE = Integer.valueOf(
            GeneralUtil.getGeneralConfig('BillingExpertBatchSize').Number_Value__c
    );
    private static FINAL Integer N = 2;

    /**
     * @author          Itzik Winograd
     * @date            25/07/2022
     * @description     Create accounts and Billing_expert_Mapping__c record.
     *                  The account's billing_expert__c should be null.
     */
    
    @TestSetup
    public static void billingExpertTestSetup(){
		
        List<Account> accountsList = AccountUtils.getAccounts(N);
        insert accountsList;
        for(Integer i=0; i<N; i++){
            accountsList[i].Billing_Expert__c = null;
        }
        update accountsList;
        
        accountsList = [SELECT Id, OwnerId, Owner.Division FROM Account];
        
        List<Billing_expert_Mapping__c> billingExpertList = new List<Billing_expert_Mapping__c>();
        for(Integer i=0; i<N; i++){
            billingExpertList.add(new Billing_expert_Mapping__c(
                    Billing_Expert__c = accountsList[0].OwnerId,
                    Change_in_Mapping__c = true,
                    Owner_Division__c = accountsList[0].Owner.Division
            ));
        }
        insert billingExpertList;
    }

    /**
     * @author          Itzik Winograd
     * @date            25/07/2022
     * @description     Run the batch. verify that the
     * @Expected        After the batch run the BillingExpertRecord will be changed
     */
    @IsTest
    public static void billingExpertBatchChangedMappingTest(){
        List<Account> accountsList = [SELECT Id, Billing_expert__c, Owner_Division__c FROM Account];
        System.debug('@@@ Found accounts before update: ' + accountsList);
        
        Map<String, Billing_expert_Mapping__c> ownerDivisionToBillingExpert = getOwnerDivisonToBillingExpertMap();
        System.debug('@@@ Found ownerDivisionToBillingExpert: ' + ownerDivisionToBillingExpert);

        Test.setMock(HttpCalloutMock.class, new YayPaySetARSpecialistBatchTest.YayPayARSpecialistMock());

        Test.startTest();
        Database.executeBatch(new BillingExpertBatch(), BATCH_SIZE);
        Test.stopTest();
        
        ownerDivisionToBillingExpert = getOwnerDivisonToBillingExpertMap();
        accountsList = [SELECT Id, Billing_expert__c, Owner_Division__c FROM Account];
        System.debug('@@@ Found accounts after update: ' + accountsList);
        for(Integer i=0;i<N; i++){
            System.assertEquals(accountsList[i].Billing_expert__c , ownerDivisionToBillingExpert.get(accountsList[i].Owner_Division__c).Billing_expert__c, 'Error: billing expert mismatch!');
        }
        
        
    }
    
    //return a map of OwnerDivison to Billing_expert_Mapping__c record
    public static Map<String, Billing_expert_Mapping__c> getOwnerDivisonToBillingExpertMap(){
        Map<String, Billing_expert_Mapping__c> ownerDivisionToBillingExpert = new Map<String, Billing_expert_Mapping__c>();
        for (Billing_expert_Mapping__c bem : [SELECT Id, Billing_Expert__c, Owner_Division__c, Change_in_Mapping__c FROM Billing_expert_Mapping__c]){
            ownerDivisionToBillingExpert.put(bem.Owner_Division__c, bem);
        }
        return ownerDivisionToBillingExpert;
    } 
}