force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CLC_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>CLC_Start_Date__c</fullName>
    <label>CLC Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLC_Stage__c/CLC_Stage__c.object-meta.xml
<CustomObject>
    <label>CLC Stage</label>
    <nameField>
        <label>CLC Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLC Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLC_Stage__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Onboarding.recordType-meta.xml
<RecordType>
    <fullName>Onboarding</fullName>
    <active>true</active>
    <label>Onboarding Task</label>
</RecordType>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <displayFormat>TW-{00000}</displayFormat>
        <label>Task Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/CLC_Stage__c.field-meta.xml
<CustomField>
    <fullName>CLC_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CLC Stage</label>
    <referenceTo>CLC_Stage__c</referenceTo>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <label>Due date</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Generation_date__c.field-meta.xml
<CustomField>
    <fullName>Generation_date__c</fullName>
    <label>Generation date</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Task_Record_type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled - Irrelevant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Task_Record_type__c.field-meta.xml
<CustomField>
    <fullName>Task_Record_type__c</fullName>
    <label>Task Record type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insights/Nurturing</fullName>
            </value>
            <value>
                <fullName>Utilization/Engagement</fullName>
            </value>
            <value>
                <fullName>Insights/Utilization</fullName>
            </value>
            <value>
                <fullName>QBR</fullName>
            </value>
            <value>
                <fullName>Renewal Tasks</fullName>
            </value>
            <value>
                <fullName>Onboarding Task</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Demo/training</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLCTaskGenerationBatchTest.cls
@istest public class CLCTaskGenerationBatchTest {

    @testSetup static void setup(){
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createInferredSolutionSettings_CS();
    }
    
    @istest static void test1(){
        List<Account> accounts = new List<Account>{new Account(Name='Account 1', Business_Unit__c='Inside Sales', CLC_Start_Date__c=Date.today().addDays(-5), Status__c='Active'),  
            										new Account(Name='Account 2', Business_Unit__c='Enterprise', CLC_Start_Date__c=Date.today(), Status__c='Active')};
        insert accounts;
        List<CLC_Stage__c> stages = new List<CLC_Stage__c>{new CLC_Stage__c(Name='Activation', Business_Unit__c='Inside Sales'), 
            												new CLC_Stage__c(Name='Another Activation', Business_Unit__c='Enterprise')};
        insert stages;
            
        List<Task_Template__c> taskTemplateList = new List<Task_Template__c>{
            				new Task_Template__c(CLC_Stage__c=stages[0].Id, Due_date__c=10, Generation_date__c=5, Priority__c='Normal', Status__c='Not Started', Subject__c='Test Task1', Task_Record_type__c='Onboarding Task', Type__c='Call'),
                            new Task_Template__c(CLC_Stage__c=stages[1].Id, Due_date__c=2, Generation_date__c=0, Priority__c='Normal', Status__c='Not Started', Subject__c='Test Task2', Task_Record_type__c='Onboarding Task', Type__c='Call')
        };
        insert  taskTemplateList;
        
        Test.startTest();
        Database.executeBatch(new CLCTaskGenerationBatch());
        Test.stopTest();
        
        List<Task> newTasks = [SELECT Id, Subject, ActivityDate, WhatId FROM Task ORDER BY ActivityDate];
        System.debug('newTasks ' + newTasks);
        System.assertEquals(2, newTasks.size());
        System.assertEquals(accounts[1].Id, newTasks[0].WhatId);
        System.assertEquals('Test Task2', newTasks[0].Subject);
    }
    
    @istest static void testScheduler(){
        Test.startTest();
        System.schedule('Test CLC Job' , '0 0 10 * * ?' , new CLCTaskGenerationScheduler());
        Test.stopTest(); 
    }
}