force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employees_Max__c.field-meta.xml
<CustomField>
    <fullName>Employees_Max__c</fullName>
    <label>Employees Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employees_Min__c.field-meta.xml
<CustomField>
    <fullName>Employees_Min__c</fullName>
    <label>Employees Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmployeesMax_registration__c.field-meta.xml
<CustomField>
    <fullName>EmployeesMax_registration__c</fullName>
    <label>Employees Max (registration)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmployeesMin_registration__c.field-meta.xml
<CustomField>
    <fullName>EmployeesMin_registration__c</fullName>
    <label>Employees Min (registration)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NT_BU_override_one_time__c.field-meta.xml
<CustomField>
    <fullName>NT_BU_override_one_time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NT BU override one-time</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NT_CC_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>NT_CC_Holder_Name__c</fullName>
    <label>NT CC Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NT_master_website__c.field-meta.xml
<CustomField>
    <fullName>NT_master_website__c</fullName>
    <label>NT master website</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent_Company_Domain__c.field-meta.xml
<CustomField>
    <fullName>Parent_Company_Domain__c</fullName>
    <description>#1101356 Populates by SalesOps
[OB] - Field type changed to &quot;Text&quot; and checked &quot;External Id&quot; - This is for using the field in &quot;Get Records&quot; in Flow.</description>
    <externalId>true</externalId>
    <label>Parent Company Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>MIS-1696</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Strategic_Region__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Region__c</fullName>
    <label>Strategic Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agencies</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>LLM &amp; AI</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Consultancies</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Dach</fullName>
                <label>DACH</label>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Big 6 Agency</fullName>
                <isActive>false</isActive>
                <label>Big 6 Agency</label>
            </value>
            <value>
                <fullName>ENT TAM 2020</fullName>
                <isActive>false</isActive>
                <label>ENT FOCUS 2020</label>
            </value>
            <value>
                <fullName>ENT TOP 2021</fullName>
                <isActive>false</isActive>
                <label>ENT TOP 2021</label>
            </value>
            <value>
                <fullName>SMB FOCUS 2020</fullName>
                <isActive>false</isActive>
                <label>SMB FOCUS 2020</label>
            </value>
            <value>
                <fullName>Strategic INTL</fullName>
                <isActive>false</isActive>
                <label>Strategic INTL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website, &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) != 0, MID(Website, 5, FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) -1), MID(Website, 5, LEN(Website) - 4)),

If(BEGINS(Website, &quot;http://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 12, LEN(Website) - 11)) != 0,MID(Website, 12, FIND(&apos;/&apos;, MID(Website,12,LEN(Website) - 11)) -1), MID(Website,12,LEN(Website)-11)),

If(BEGINS(Website, &quot;https://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 13, LEN(Website) - 12)) != 0,MID(Website, 13, FIND(&apos;/&apos;, MID(Website,13,LEN(Website) - 12)) -1), MID(Website,13,LEN(Website)-12)),

If(BEGINS(Website, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 8, LEN(Website) - 7)) != 0,MID(Website, 8, FIND(&apos;/&apos;, MID(Website,8,LEN(Website) - 7)) -1), MID(Website,8,LEN(Website)-7)),

If(BEGINS(Website, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 9, LEN(Website) - 8)) != 0,MID(Website, 9, FIND(&apos;/&apos;, MID(Website,9,LEN(Website) - 8)) -1), MID(Website,9,LEN(Website)-8)),

IF(FIND(&apos;/&apos;,MID(Website, 1, LEN(Website))) !=0,MID(Website,1,FIND(&apos;/&apos;, Website) - 1), Website ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TR_Acc_BusinessUnitCalc.cls
/**
 * @author Gad Sharon
 * @date 25/11/2020
 * @description Calculate the account business unit according to changed data on the account.
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      - Itzik Winograd
 * date        - 18/01/2021
 * description - Changed "Handle" method to support insert, when "map_oldAccs" is null
 * --------------------------------------------------------------------------------------
 */

public with sharing class TR_Acc_BusinessUnitCalc {
  /**
   * @author Gad Sharon
   * @date 25/11/2020
   * @description Handle the functionlity of the class.
   * @param None.
   * @return Void.
   */

  public void handle(List<SObject> lst_newAccs, Map<Id, SObject> map_oldAccs) {
    System.debug('lola i am here!!!!---' + map_oldAccs);
    System.debug('isInsert---' + Trigger.isInsert);
    System.debug('isUpdate---' + Trigger.isUpdate);
    List<Account> lst_accs;
    if (map_oldAccs != null) {
      //on update - filter the records
      lst_accs = filter((List<Account>) lst_newAccs, map_oldAccs);
    } else {
      //on insert - pass all records for calculation
      lst_accs = lst_newAccs;
    }
    //Continue only if we have relevant accounts.
    if (!lst_accs.isEmpty()) {
      System.debug('going into business unit update');
      BusinessUnitUpdateHelper buuh = new BusinessUnitUpdateHelper();
      buuh.updateBusinessUnit(
        lst_accs,
        'Website_Domain__c',
        'BillingCountry',
        null,
        true
      );
      handleAfterBusinessUnitFinished(lst_accs);
    }
  }

  private void handleAfterBusinessUnitFinished(List<Account> newList) {
    for (Account acc : newList) {
      System.debug('acc.Business_Unit__c--' + acc.Business_Unit__c);
      System.debug(
        'acc.NT_BU_override_one_time__c--' + acc.NT_BU_override_one_time__c
      );
      System.debug('acc.Strategic_Pod__c--' + acc.Strategic_Pod__c);
      System.debug('acc.Strategic_Pod__c--' + acc.Strategic_Region__c);
      if (acc.NT_BU_override_one_time__c) {
        acc.NT_BU_override_one_time__c = false;
        if (acc.Business_Unit__c == 'Inside Sales') {
          //                    System.debug(' i am in inside sales');
          //                    acc.Website = acc.NT_master_website__c;
          //                    acc.Employees_Max__c = acc.EmployeesMax_registration__c;
          //                    acc.Employees_Min__c = acc.EmployeesMin_registration__c;
          acc.Name = 'Private Account - ' + acc.Website;
          //                    System.debug('acc.empl---'+acc.Employees_Max__c);
          //                    System.debug('acc.empl---'+acc.Employees_Min__c);
        } else {
          acc.Name = acc.NT_CC_Holder_Name__c;
          acc.Website = 'no_website';
          acc.Employees_Max__c = 10;
          acc.Employees_Min__c = 1;
          acc.Business_Unit__c = 'Inside Sales';
          acc.Strategic_Region__c = ''; // added in 1.1.25
          acc.Strategic_Pod__c = '';
          acc.Parent_Company_Domain__c = '';
        }
      }
    }
  }

  /**
   * @author Gad Sharon
   * @date 25/11/2020
   * @description Check if we have relevant records and if so, return them.
   * @param List<Account> lst_newAccs - The list of accounts to check.
   * @param Map<Id, SObject> map_oldAccs - The previous state of the accounts.
   * @return List <Account> - The list of accounts that we need to work on.
   * =================================================================================================
   * author: Itzik Winograd
   * date: 29/12/2021
   * description: Check the fields that were changed according to a custom metadata named Account_Business_Unit_Calc_Criteria
   */

  private List<Account> filter(
    List<Account> lst_newAccs,
    Map<Id, SObject> map_oldAccs
  ) {
    Set<Account> lst_relevantAccs = new Set<Account>();
    Account oldAcc;
    String rawAccountFieldNames = GeneralUtil.getGeneralConfig(
        'Account_Business_Unit_Calc_Criteria'
      )
      .Text_Value__c;
    if (rawAccountFieldNames != null) {
      List<String> accountFieldNamesList = rawAccountFieldNames.split(';');
      //Check if one of the relevant fields changed.
      for (Account curAcc : lst_newAccs) {
        oldAcc = (Account) map_oldAccs.get(curAcc.id);
        for (String fieldName : accountFieldNamesList) {
          if (curAcc.get(fieldName) != oldAcc.get(fieldName)) {
            lst_relevantAccs.add(curAcc);
          }
        }
      }
    }
    System.debug('lst_relevantAccs--' + lst_relevantAccs.size());
    System.debug('lst_relevantAccs--' + lst_relevantAccs);
    return new List<Account>(lst_relevantAccs);
  }
}