force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Use_Cases__c.field-meta.xml
<CustomField>
    <fullName>Use_Cases__c</fullName>
    <label>What is the customer&apos;s use case(s)?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Benchmark Performance Against Competitors</fullName>
            </value>
            <value>
                <fullName>Detect Fraud/Illicit Content (Media, Finance)</fullName>
            </value>
            <value>
                <fullName>Find, Qualify, and Close Partners &amp; Prospects</fullName>
            </value>
            <value>
                <fullName>Make investment decisions (Hedge Funds, VC)</fullName>
            </value>
            <value>
                <fullName>Maximize 3rd Party eCommerce Sales (CPG)</fullName>
            </value>
            <value>
                <fullName>Optimize Customer Acquisition</fullName>
            </value>
            <value>
                <fullName>Prove Advertising/Media Property Effectiveness (Publishers)Prove Advertising/Campaign/Media Property Effectiveness</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describes the business unit with the responsibility of the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Lost_Reason_2__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason_2__c</fullName>
    <label>Closed Lost Reason # 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>BANT</fullName>
            </value>
            <value>
                <fullName>Service / Relationship</fullName>
            </value>
            <value>
                <fullName>Company Structure / Human Resources</fullName>
            </value>
            <value>
                <fullName>Commercial Terms</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Duplicate / Part of Another Opp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason__c</fullName>
    <label>old Closed Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Gap - Client did not agree to Annual payment</fullName>
            </value>
            <value>
                <fullName>Client Gap - Client did not agree to Legal terms</fullName>
            </value>
            <value>
                <fullName>Client Gap - Company Reorg/M&amp;A/Closing</fullName>
            </value>
            <value>
                <fullName>Client Gap - Customer refused annual price increase</fullName>
            </value>
            <value>
                <fullName>Client Gap - Getting data from SW competitor</fullName>
            </value>
            <value>
                <fullName>Client Gap - Insufficient Budget</fullName>
            </value>
            <value>
                <fullName>Client Gap - Receiving data from Agency/Third Party</fullName>
            </value>
            <value>
                <fullName>Client Gap - SimilarWeb chose not to sell or renew (Frenemy, Competitor)</fullName>
            </value>
            <value>
                <fullName>Client Gap - Unresponsive/Lost stakeholder</fullName>
            </value>
            <value>
                <fullName>Integration / Tech</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Low panel Value</fullName>
            </value>
            <value>
                <fullName>Merged with/rolled into another opp/account</fullName>
            </value>
            <value>
                <fullName>No response from the partner</fullName>
            </value>
            <value>
                <fullName>Not for-analyzed</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Privacy</fullName>
            </value>
            <value>
                <fullName>Relationship - Insufficient touchpoints/onboarding/education</fullName>
            </value>
            <value>
                <fullName>Relationship - No need for upsell offering</fullName>
            </value>
            <value>
                <fullName>Relationship - No relationship with decision making authority</fullName>
            </value>
            <value>
                <fullName>Relationship - Not the right time for the customer (they were interested)</fullName>
            </value>
            <value>
                <fullName>Relationship - We started the renewal process too late</fullName>
            </value>
            <value>
                <fullName>Relationship - We tried selling to the wrong department</fullName>
            </value>
            <value>
                <fullName>Relationship - Working with few/wrong teams for company’s use case(s)</fullName>
            </value>
            <value>
                <fullName>Service / Relationship</fullName>
            </value>
            <value>
                <fullName>Solution Gap - Data Accuracy Discrepancies</fullName>
            </value>
            <value>
                <fullName>Solution Gap - Missing Coverage (country / platform)</fullName>
            </value>
            <value>
                <fullName>Solution Gap - Missing Feature / Granularity</fullName>
            </value>
            <value>
                <fullName>Solution Gap - Pricing and packaging unfit for use case</fullName>
            </value>
            <value>
                <fullName>Solution Gap - Pricing of upsell offering was too high</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Lost_Reason_More_details__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Reason_More_details__c</fullName>
    <inlineHelpText>What would have helped you close the deal?</inlineHelpText>
    <label>Closed Lost Reason - More details</label>
    <length>3200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cycle__c.field-meta.xml
<CustomField>
    <fullName>Cycle__c</fullName>
    <label>Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2 Years</fullName>
            </value>
            <value>
                <fullName>3 Years</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cycle_Price__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Price__c</fullName>
    <label>Cycle Price ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_will_be_relevant__c.field-meta.xml
<CustomField>
    <fullName>Opp_will_be_relevant__c</fullName>
    <label>Will the opp be relevant again?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not relevant</fullName>
                <default>true</default>
                <label>Not relevant</label>
            </value>
            <value>
                <fullName>60 days</fullName>
            </value>
            <value>
                <fullName>90 days</fullName>
            </value>
            <value>
                <fullName>120 days</fullName>
            </value>
            <value>
                <fullName>180 days</fullName>
            </value>
            <value>
                <fullName>0 days</fullName>
                <isActive>false</isActive>
                <label>0 days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Use_Cases__c.field-meta.xml
<CustomField>
    <fullName>Use_Cases__c</fullName>
    <inlineHelpText>Please select all applicable use cases.</inlineHelpText>
    <label>What is the customer&apos;s use case(s)?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>User Acquisition: Marketing mix optimization</fullName>
                <label>MI: Marketing mix optimization</label>
            </value>
            <value>
                <fullName>User Acquisition: Affiliates</fullName>
                <label>MI: Affiliates Marketing</label>
            </value>
            <value>
                <fullName>User Acquisition: Organic (SEO, Content)</fullName>
                <label>MI: Organic (SEO, Content)</label>
            </value>
            <value>
                <fullName>User Acquisition: Paid (PPC, Display)</fullName>
                <label>MI: Paid Marketing (PPC, Display)</label>
            </value>
            <value>
                <fullName>User Acquisition: Other (Brand, PR, Social Listening)</fullName>
                <label>MI: Other (Brand, PR, Social Listening)</label>
            </value>
            <value>
                <fullName>Path to Purchase: Product demand (what to sell)</fullName>
                <label>PI: Product demand (what to sell)</label>
            </value>
            <value>
                <fullName>Path to Purchase: Product distribution (where to sell)</fullName>
                <label>PI: Product distribution (where to sell)</label>
            </value>
            <value>
                <fullName>Path to Purchase: Optimize conversion</fullName>
                <label>PI: Optimize conversion</label>
            </value>
            <value>
                <fullName>Sales: Lead enrichment</fullName>
                <label>SI: Lead enrichment</label>
            </value>
            <value>
                <fullName>Sales: Sales intelligence (find, qualify, close, retain, monitor customers or compaines)</fullName>
                <label>SI: Sales intelligence (find, qualify, close, retain, monitor customers or compaines)</label>
            </value>
            <value>
                <fullName>Investors: Source investment opportunities</fullName>
                <label>II: Source investment opportunities</label>
            </value>
            <value>
                <fullName>Investors: Diligence, M&amp;A and investment research</fullName>
                <label>II: Diligence, M&amp;A and investment research</label>
            </value>
            <value>
                <fullName>Investors: Public market investors</fullName>
                <label>II: Public market investors</label>
            </value>
            <value>
                <fullName>Other: Data integration</fullName>
                <label>OO: Data integration</label>
            </value>
            <value>
                <fullName>Other: Other</fullName>
                <label>OO: Other</label>
            </value>
            <value>
                <fullName>Research: Benchmark traffic, engagement and market share</fullName>
            </value>
            <value>
                <fullName>Research: Benchmark marketing channels performance against competitors</fullName>
            </value>
            <value>
                <fullName>Agencies: Pitch new businesses</fullName>
            </value>
            <value>
                <fullName>Agencies: Optimize clients&apos; marketing strategies</fullName>
            </value>
            <value>
                <fullName>Market &amp; Consumer Research: Understand market share, market sizing &amp; trend analysis</fullName>
                <label>AI: Understand market share &amp; trend analysis</label>
            </value>
            <value>
                <fullName>Market &amp; Consumer Research: Understand audience</fullName>
                <label>AI: Understand audiences</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Marketing.recordType-meta.xml
<RecordType>
    <fullName>Marketing</fullName>
    <active>false</active>
    <businessProcess>Inside Sales</businessProcess>
    <label>Marketing</label>
</RecordType>

force-app/main/default/classes/CloudiusWSTest.cls
@istest
public class CloudiusWSTest {
  @testSetup
  static void setup() {
    //        SimilarWeb_Settings__c currentSettings = new SimilarWeb_Settings__c();
    //        currentSettings.API_Key__c='test';
    //        currentSettings.Create_Date_TimeFrame__c='test';
    //        currentSettings.Enriched_Entities__c='["lead"]';
    //        currentSettings.Invisible_Fields__c='test';
    //        currentSettings.Refresh_Data_Interval__c=0;
    //        currentSettings.Sync_on_create_and_update__c=true;
    //        insert currentSettings;
  }

  @istest
  public static void test() {
    Account acc = new Account(
      Name = 'Account_for_user',
      Business_unit__c = 'Inside Sales'
    );
    insert acc;

    Opportunity newOpp = new Opportunity(
      AccountId = acc.Id,
      Name = 'Acc1_Opportunity_2',
      Type = 'New Sell',
      Cycle__c = 'Annually',
      CloseDate = DAte.today(),
      Cycle_Price__c = 123,
      StageName = 'Closed Lost',
      Closed_Lost_Reason__c = 'test reason 1',
      Closed_Lost_Reason_More_details__c = 'more details',
      Closed_Lost_Reason_2__c = 'whatever',
      Opp_will_be_relevant__c = '90 days',
      Use_Cases__c = 'Marketing: SEO / Content'
    );
    insert newOpp;
    CloudiusWS.CheckBillingAccount(newOpp.Id);
    CloudiusWS.CheckBillingAccountBasic(newOpp.Id, true);
    CloudiusWS.CheckBillingAccountBasic(newOpp.Id, false);
  }
}