force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ProductImplementation__c.field-meta.xml
<CustomField>
    <fullName>ProductImplementation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Implementation</label>
    <referenceTo>Product_Implementation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Implementation__c/Product_Implementation__c.object-meta.xml
<CustomObject>
    <label>Handover</label>
    <nameField>
        <displayFormat>ProImp-{000000}</displayFormat>
        <label>Product Implementation  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Handovers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Implementation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Product_Implementations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductImplUpdateBatchTest.cls
@istest
public class ProductImplUpdateBatchTest {
  @istest
  public static void test() {
    Account acc1 = new Account(Name = 'Test1', Business_Unit__c = 'Enterprise');
    Account acc2 = new Account(Name = 'Test2', Business_Unit__c = 'Enterprise');
    Account acc3 = new Account(Name = 'Test3', Business_Unit__c = 'Enterprise');
    insert new List<Account>{ acc1, acc2, acc3 };

    Product_Implementation__c impl1 = new Product_Implementation__c(
      Account__c = acc1.ID
    );
    Product_Implementation__c impl21 = new Product_Implementation__c(
      Account__c = acc2.ID
    );
    //Product_Implementation__c impl22 = new Product_Implementation__c(Account__c = acc2.ID);
    insert new List<Product_Implementation__c>{ impl1, impl21 }; //, impl22

    Contact cnt1 = new Contact(LastName = 'Test Contact1', AccountID = acc1.Id);
    Contact cnt2 = new Contact(LastName = 'Test Contact2', AccountID = acc2.Id);
    insert new List<Contact>{ cnt1, cnt2 };
    System.assertEquals(null, cnt1.ProductImplementation__c);

    ProductImplUpdateBatch batch = new ProductImplUpdateBatch();
    Test.startTest();
    cnt1.AccountId = acc2.Id;
    cnt2.AccountId = acc3.Id;
    update new List<Contact>{ cnt1, cnt2 };

    Database.executeBatch(batch);
    Test.stopTest();

    batch.processContacts(new List<Id>{ cnt1.Id, cnt2.Id });

    Contact cntUpdated = [
      SELECT id, ProductImplementation__c
      FROM Contact
      WHERE Id = :cnt1.Id
    ];
    System.assertEquals(impl21.Id, cntUpdated.ProductImplementation__c);
  }

  @istest
  public static void testSchedule() {
    Test.startTest();
    System.schedule(
      'Test product impl update',
      '20 30 8 10 2 ?',
      new ProductImplUpdateBatch()
    );
    Test.stopTest();
  }
}