force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Customers</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <label>UID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <label>Bucket</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CS_FreeEmailProvidersList__c/CS_FreeEmailProvidersList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Free Email Providers List</label>
</CustomObject>

force-app/main/default/objects/CSTeam__c/CSTeam__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Routing Tier 1 - Teams</label>
</CustomObject>

force-app/main/default/objects/CSTeam__c/fields/Lead_Routing_Group__c.field-meta.xml
<CustomField>
    <fullName>Lead_Routing_Group__c</fullName>
    <label>Lead Routing Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSTeam__c/fields/PayingAccount__c.field-meta.xml
<CustomField>
    <fullName>PayingAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PayingAccount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CloudiusTests.cls
@isTest
private class CloudiusTests {
	
	
	/**
	 @isTest// (seealldata=false)      
    static void TestOne(){     	
    	LeadTriggerHelperTEMP.isTest = true;
		AccountTriggerHelperTEMP.isTest = true;
		AccountTriggerHelperTemp.codeoff=false;
		
		LeadTriggerHelperTemp.ValidBusinessUnit.add('SMB');//,'ENTERPRISCE') 
		LeadTriggerHelperTemp.ValidBusinessUnit.add('Enterprise');
		
	    CS_FreeEmailProvidersList__c FreeEmail =TestObjectCreator.CreateFreeEmailProvider('gmail.com');
        insert FreeEmail;
    	
    	TestObjectCreator.CreateCSBatch();
    	
    	CSSettings__c csset = TestObjectCreator.CreateCSSettings();
	    insert csset;
	    
	    CSTeam__c cs1=new CSTeam__c(Name='A',Bucket__c='SMB',Business_Unit__c='SMB',Lead_Routing_Group__c='',PayingAccount__c=false,Team__c='');
	    insert cs1;   
	    
	    List<Account> lAccs=new List<Account>();
	    insert lAccs;
	    
	    Account parentAccount=TestObjectCreator.CreateAccount();
	    parentAccount.recurly__Account_Code__c='parentTest@gmail.com';
        parentAccount.recurly__Last_Name__c='parentSokolov';  
        parentAccount.Type='Reseller';  
	    insert parentAccount;
	    system.debug('Inserted Account: '+ parentAccount);
	    
	    Account tempAccount1 = TestObjectCreator.CreateAccount();
	    tempAccount1.recurly__Account_Code__c='test@gmail.com';
        tempAccount1.recurly__Last_Name__c='Sokolov';
        tempAccount1.parent=parentAccount;  
        tempAccount1.Reseller__c=parentAccount.Id;  
        tempAccount1.Business_Unit__c='SMB';       
        insert tempAccount1;        
        system.debug('Inserted Account: '+ tempAccount1);
        lAccs.add(tempAccount1);
        update lAccs;
                
        tempAccount1.ShippingCountry='Albania';
        tempAccount1.BillingCountry='Algeria';
        update tempAccount1; 
        update lAccs;       
        system.debug('After updated Account: '+ tempAccount1);
        
        Contact tempContactZ=TestObjectCreator.CreateContact(tempAccount1,'z@gmail.com');
	    insert tempContactZ;    	    
        system.debug('Inserted Contact: '+ tempContactZ);
        
        tempAccount1.uid__c=tempContactZ.Id;	    
	    tempAccount1.email__c=tempContactZ.Email;
	    update tempAccount1;
	    update lAccs;	
	    
	    Account tempAccount2 = TestObjectCreator.CreateAccount();
	    tempAccount2.recurly__Account_Code__c='t@gmail.com';
        tempAccount2.recurly__Last_Name__c='Vokolosz';           
        insert tempAccount2;       
        lAccs.add(tempAccount2);
        //update lAccs; 
        system.debug('Inserted Account: '+ tempAccount2);
                
        tempAccount2.ShippingCountry='Algeria';
        update tempAccount2; 
        //update lAccs;       
        system.debug('After updated Account: '+ tempAccount2);
        	    
	    tempAccount2.email__c=tempContactZ.Email;
	    update tempAccount2; 
	    //update lAccs;
	    
	   // update csset;
	    //  l1.Reseller__c=parentAccount.Id;
	    //  update l1;	    
	  
	 //   AccountTriggerHelperTEMP.RecurlyAccountAllocation (lAccs);
   }    
     */   
}