force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cycle__c.field-meta.xml
<CustomField>
    <fullName>Cycle__c</fullName>
    <label>Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>2 Years</fullName>
            </value>
            <value>
                <fullName>3 Years</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cycle_Price__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Price__c</fullName>
    <label>Cycle Price ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Similarweb_Forecasting_status__c.field-meta.xml
<CustomField>
    <fullName>Similarweb_Forecasting_status__c</fullName>
    <label>Similarweb Forecasting status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Best Case</fullName>
            </value>
            <value>
                <fullName>Commit</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
            <value>
                <fullName>60% - Projected In</fullName>
            </value>
            <value>
                <fullName>80% - Confirmed In</fullName>
            </value>
            <value>
                <fullName>40% - Projected Out</fullName>
            </value>
            <value>
                <fullName>25% - Confirmed Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FillSimilarWebForecastBatchTest.cls
@isTest  
public class FillSimilarWebForecastBatchTest {

    @isTest
    static void test(){
        Test.startTest();
        Account acc = new Account( Name = 'Account_for_user', Business_unit__c='Inside Sales'); //account whose opps will be visible
        Account acc2 = new Account( Name = 'Account_for_user_2', Business_unit__c='Inside Sales'); 
        insert new List<Account>{acc, acc2};        
        List<Opportunity> opps = new List<opportunity>{
                new Opportunity(AccountId=acc.Id, Name = 'Acc1_Opportunity_1', Type='New Sell', Cycle__c='Annually', CloseDate = DAte.today(), Cycle_Price__c=123, StageName='Prospect',Similarweb_Forecasting_status__c=null), 
                new Opportunity(AccountId=acc2.Id, Name = 'Acc2_Opportunity_1', Type='New Sell', Cycle__c='Annually', CloseDate = DAte.today(), Cycle_Price__c=123, StageName='Prospect',Similarweb_Forecasting_status__c=null)
            }; 
        insert opps;        
        Database.executeBatch(new FillSimilarWebForecastBatch());
        Test.stopTest();
    }
}