force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Clean_Domain__c.field-meta.xml
<CustomField>
    <fullName>Clean_Domain__c</fullName>
    <formula>IF(AND(
       ISPICKVAL(Email_address_domain_type_SFDC__c, &apos;Company&apos;),
       NOT(ISBLANK(Email_Domain__c))),
                                      Email_Domain__c,Website_Domain__c)</formula>
    <label>Clean Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Code_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_ISO3__c</fullName>
    <description>updated from CMT - Country Picklist Values</description>
    <label>Country Code ISO3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_address_domain_type_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type_SFDC__c</fullName>
    <label>Email address domain type SFDC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employees_Min__c.field-meta.xml
<CustomField>
    <fullName>Employees_Min__c</fullName>
    <label>Employees Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Force_Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Force_Enrichment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Force Enrichment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Groudon_Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Groudon_Call_Status__c</fullName>
    <label>Groudon Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groudon_Call_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Groudon_Enrichment_Date__c.field-meta.xml
<CustomField>
    <fullName>Groudon_Enrichment_Date__c</fullName>
    <label>Groudon Enrichment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Groudon_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Groudon_Timestamp__c</fullName>
    <label>Groudon Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website, &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) != 0, MID(Website, 5, FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) -1), MID(Website, 5, LEN(Website) - 4)),

If(BEGINS(Website, &quot;http://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 12, LEN(Website) - 11)) != 0,MID(Website, 12, FIND(&apos;/&apos;, MID(Website,12,LEN(Website) - 11)) -1), MID(Website,12,LEN(Website)-11)),

If(BEGINS(Website, &quot;https://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 13, LEN(Website) - 12)) != 0,MID(Website, 13, FIND(&apos;/&apos;, MID(Website,13,LEN(Website) - 12)) -1), MID(Website,13,LEN(Website)-12)),

If(BEGINS(Website, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 8, LEN(Website) - 7)) != 0,MID(Website, 8, FIND(&apos;/&apos;, MID(Website,8,LEN(Website) - 7)) -1), MID(Website,8,LEN(Website)-7)),

If(BEGINS(Website, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 9, LEN(Website) - 8)) != 0,MID(Website, 9, FIND(&apos;/&apos;, MID(Website,9,LEN(Website) - 8)) -1), MID(Website,9,LEN(Website)-8)),

IF(FIND(&apos;/&apos;,MID(Website, 1, LEN(Website))) !=0,MID(Website,1,FIND(&apos;/&apos;, Website) - 1), Website ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <label>Detailed Error Message</label>
    <length>32678</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Body__c.field-meta.xml
<CustomField>
    <fullName>Http_Body__c</fullName>
    <label>Http Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Record_Ids__c</fullName>
    <label>Record Ids</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/SF_Type__c.field-meta.xml
<CustomField>
    <fullName>SF_Type__c</fullName>
    <label>SF Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountGroudonHandler.cls
public with sharing class AccountGroudonHandler implements GroudonQueueable.GroudonHandler {
  public List<Account> accounts;

  public AccountGroudonHandler(Account a) {
    this.accounts = new List<Account>{ a };
  }

  public AccountGroudonHandler(List<Account> accounts) {
    this.accounts = accounts;
  }

  public void process() {
    List<Log_Event__e> eventList = new List<Log_Event__e>();
    API_Configuration__mdt apiConfiguration = GeneralUtil.getAPIConfig(
      'Groudon_Integration'
    );

    GroudonIntegrationService groudonService = new GroudonIntegrationService(
      new AccountGroudonRequestGenerator(),
      new AccountGroudonResponseGenerator(),
      apiConfiguration
    );

    try {
      GroudonIntegrationService.GroudonResponse response = this.accounts.size() >
        1
        ? groudonService.callGroudonBulk(this.accounts)
        : groudonService.callGroudon(this.accounts.get(0));

      for (Account a : this.accounts) {
        fillLog(a, response, eventList);
      }
    } catch (Exception ex) {
      Log_Event__e log = new Log_Event__e();
      log.Email__c = this.accounts.size() > 1
        ? 'mass update'
        : this.accounts.isEmpty() ? 'no accounts' : this.accounts[0].Name;
      log.Apex_class__c = 'GroudonIntegrationService';
      log.Apex_Method__c = 'callGroudon';
      log.Record_Ids__c = this.accounts.size() > 1
        ? 'mass update'
        : this.accounts.isEmpty() ? 'no accounts' : this.accounts[0].id;
      log.Log_Type__c = 'Error';
      log.Http_Body__c = 'no payload available';
      log.Detailed_Error_Message__c =
        ex.getMessage() +
        ' ' +
        ex.getStackTraceString();
      log.SF_Type__c = 'Account';
      eventList.add(log);
    }
    List<Account> accountsAfterLambdaCallout = [
      SELECT Id
      FROM Account
      WHERE Id IN :this.accounts
    ];
    for (Account a : accountsAfterLambdaCallout) {
      a.Force_Enrichment__c = false;
      a.Groudon_Timestamp__c = Datetime.now();
      a.Groudon_Enrichment_Date__c = Datetime.now();
      a.Groudon_Call_Status__c = 'Enrichment_Ended';
    }

    if (!eventList.isEmpty()) {
      Eventbus.publish(eventList);
    }

    update accountsAfterLambdaCallout;
  }

  private void fillLog(
    Account a,
    GroudonIntegrationService.GroudonResponse response,
    List<Log_Event__e> eventList
  ) {
    Log_Event__e log = new Log_Event__e();
    log.Email__c = a.Name;
    log.Apex_Method__c = this.accounts.size() > 0
      ? 'callGroudonBulk'
      : 'callGroudonSingle';
    log.Apex_class__c = 'GroudonIntegrationService';
    log.Record_Ids__c = a.id;
    log.Log_Type__c = response.isSuccess ? 'Info' : 'Error';
    log.Http_Body__c = response.leadIdToBodyMap.get(a.Id);
    log.Sub_Type__c = 'callGroudon';
    log.SF_Type__c = 'Account';
    eventList.add(log);
  }

  public class AccountGroudonRequestGenerator implements GroudonQueueable.GroudonRequestGenerator {
    public GroudonIntegrationService.GroudonRequest generate(SObject record) {
      Account accountItem = (Account) record;

      GroudonIntegrationService.GroudonRequest requestBody = new GroudonIntegrationService.GroudonRequest();

      requestBody.first_name = null;
      requestBody.last_name = null;
      requestBody.domain = accountItem.Website_Domain__c;
      requestBody.Country_Code = accountItem.Country_Code_ISO3__c;
      requestBody.email = accountItem.Email__c;
      requestBody.industry = accountItem.SW_Industry__c;
      requestBody.website = accountItem.Website;
      requestBody.Business_Unit = accountItem.Business_Unit__c;
      requestBody.Clean_Domain = accountItem.Clean_Domain__c;
      requestBody.country = accountItem.BillingCountry;
      requestBody.Email_address_domain_type = accountItem.Email_address_domain_type_SFDC__c;
      requestBody.Employees_Min = accountItem.Employees_Min__c;
      requestBody.Company = accountItem.Name;
      requestBody.sf_id = accountItem.Id;
      requestBody.timestamp = Datetime.now();
      requestBody.sf_type = 'Account';

      return requestBody;
    }
  }

  public class AccountGroudonResponseGenerator implements GroudonQueueable.GroudonResponseGenerator {
    public GroudonIntegrationService.GroudonResponse generate(
      List<GroudonIntegrationService.GroudonRequest> requestBodies
    ) {
      GroudonIntegrationService.GroudonResponse groudonResponse = new GroudonIntegrationService.GroudonResponse();

      for (GroudonIntegrationService.GroudonRequest r : requestBodies) {
        groudonResponse.accountIdToBodyMap.put(
          r.sf_id,
          JSON.serializePretty(r, true)
        );
      }

      return groudonResponse;
    }
  }
}