force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describe the business unit of the account</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>PA_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLineItem__c/fields/Total_DAU__c.field-meta.xml
<CustomField>
    <fullName>Total_DAU__c</fullName>
    <label>Total DAU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoicePDFSettings__c/InvoicePDFSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Invoice PDF Settings</label>
</CustomObject>

force-app/main/default/objects/PA_Invoice__c/PA_Invoice__c.object-meta.xml
<CustomObject>
    <label>PA Invoice</label>
    <nameField>
        <displayFormat>Invoice N-{000000000}</displayFormat>
        <label>PA Invoice  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PA Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PA_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PA Invoices</relationshipLabel>
    <relationshipName>PA_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Bank_Detials__c.field-meta.xml
<CustomField>
    <fullName>Bank_Detials__c</fullName>
    <label>Bank Detials</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Invoice_Note__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Note__c</fullName>
    <label>Invoice Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PA_Invoice__c/fields/Paid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_To_Date__c</fullName>
    <label>Paid To Date</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicePDFControllerTest.cls
@istest public class InvoicePDFControllerTest {

    @istest static void test(){
        List<InvoicePDFSettings__c> settings = new List<InvoicePDFSettings__c>{new InvoicePDFSettings__c(Name='To', Value__c='Test'), new InvoicePDFSettings__c(Name='Email', Value__c='test@test.som')};
        insert settings;
        Account acc = new Account(Name='Account 1', Business_Unit__c='Inside Sales');
        insert acc;
        
        PA_Invoice__c inv = new PA_Invoice__c(Account__c = acc.Id,  Bank_Detials__c='some text',Description__c='Descr', Invoice_Note__c='invoice note', Paid_To_Date__c=123.45);
        insert inv;
        InvoiceLineItem__c li = new InvoiceLineItem__c(Name='Test1', Invoice__c = inv.Id, Amount__c=123.45, Description__c='Description ', Total_DAU__c = 2);
        insert li;
        
         ApexPages.StandardController sc = new ApexPages.StandardController(inv);
        InvoicePDFController controller = new InvoicePDFController(sc);
        
        PageReference pageRef = Page.InvoicePDFPage;
        pageRef.getParameters().put('id', String.valueOf(inv.Id));
        Test.setCurrentPage(pageRef);
        
    }
}