force-app/main/default/objects/Account/fields/Country_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Country_Subsidiary__c</fullName>
    <description>Populate from account after save flow , according to account country in CountrySubsidiary</description>
    <label>Country Subsidiary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Subsidiary__c/Country_Subsidiary__c.object-meta.xml
<CustomObject>
    <label>Country Subsidiary</label>
    <nameField>
        <label>Country Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountrySubsidiary</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Netsuite_Daily_Exchange_Rate__c/Netsuite_Daily_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Netsuite Daily Exchange Rate</label>
</CustomObject>

force-app/main/default/objects/Netsuite_Daily_Exchange_Rate__c/fields/Currency_DDL__c.field-meta.xml
<CustomField>
    <fullName>Currency_DDL__c</fullName>
    <label>Currency (DDL)</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Netsuite_Daily_Exchange_Rate__c/fields/USD_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>USD_Exchange_Rate__c</fullName>
    <label>USD Exchange Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1113759 populates manually</description>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Technical_Solutions.recordType-meta.xml
<RecordType>
    <fullName>Technical_Solutions</fullName>
    <active>true</active>
    <label>DaaS request</label>
</RecordType>

force-app/main/default/classes/QuoteOppFilesRelatedListControllerTest.cls
@isTest
public with sharing class QuoteOppFilesRelatedListControllerTest {
  @testSetup
  static void setup() {
    String currencyCode = 'USD';
    Decimal exchangeRate = 1;
    Decimal actualExchangeRate = 0;
    Netsuite_Daily_Exchange_Rate__c netsuiteDailyExchangeRateSetting = new Netsuite_Daily_Exchange_Rate__c();
    netsuiteDailyExchangeRateSetting.Name = currencyCode;
    netsuiteDailyExchangeRateSetting.Currency_DDL__c = currencyCode;
    netsuiteDailyExchangeRateSetting.USD_Exchange_Rate__c = exchangeRate;
    insert netsuiteDailyExchangeRateSetting;
    Utils.CodeOff = true;
    TestDataFactory.createSimilarWeb_CS();
    TestDataFactory.createBaseProductConfiguration_CS();
    TestDataFactory.createInferredSolutionSettings_CS();
    List<String> countries = TestObjectCreator.getCountries();
    Account a = TestObjectCreator.CreateAccount();
    a.billingcountry = countries[countries.size() - 1];
    insert a;
    Contact c = TestDataFactory.createContact(a, 'test@testing.com');
    c.MailingCountry = countries[countries.size() - 1];
    insert c;
    list<Country_Subsidiary__c> lcsc = TestObjectCreator.CreateCountries();
    Opportunity o = TestObjectCreator.CreateOpportunity(a);
    insert o;
    zqu__Quote__c q = TestDataFactory.createZQuote(o, c);
    q.zqu__Currency__c = 'USD';
    q.zqu__Previewed_Total__c = 100001;
    insert q;
    ContentVersion cvPdf = TestDataFactory.createContentVersionWithType('pdf');
    insert cvPdf;
    cvPdf = [
      SELECT Id, ContentDocumentId
      FROM ContentVersion
      WHERE Id = :cvPdf.Id
      LIMIT 1
    ];
    ContentDocumentLink cdl = TestDataFactory.createContentDocumentLink(
      q.id,
      cvPdf.ContentDocumentId
    );
    insert cdl;
    Attachment att = TestDataFactory.createAttachment(q.Id);
    insert att;
  }

  @isTest
  static void obtainFilesFromRelatedOpportunityTest() {
    zqu__Quote__c quote = [SELECT Id FROM zqu__Quote__c LIMIT 1];
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    Response faultResponse = QuoteOppFilesRelatedListController.obtainFilesFromRelatedOpportunity(
      quote.Id
    );
    // System.assertEquals(false, faultResponse.success);
    quote.zqu__Opportunity__c = opp.Id;
    update quote;
    Response succesfyllResponse = QuoteOppFilesRelatedListController.obtainFilesFromRelatedOpportunity(
      quote.Id
    );
    // System.assertEquals(true, succesfyllResponse.success);
    Test.stopTest();
  }

  @isTest
  static void deleteFileNotFoundTest() {
    ContentVersion file = [SELECT Id FROM ContentVersion LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    QuoteOppFilesRelatedListController.deleteFile(file.Id);
    Test.stopTest();
  }

  @isTest
  static void deleteFileContentDocumentTest() {
    ContentDocument file = [SELECT Id FROM ContentDocument LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    QuoteOppFilesRelatedListController.deleteFile(file.Id);
    Test.stopTest();
  }

  @isTest
  static void deleteFileAttachmentTest() {
    Attachment file = [SELECT Id FROM Attachment LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    QuoteOppFilesRelatedListController.deleteFile(file.Id);
    Test.stopTest();
  }

  @isTest
  static void editFileNotFoundTest() {
    ContentVersion file = [SELECT Id FROM ContentVersion LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    QuoteOppFilesRelatedListController.editFile(file.Id, 'test', 'test');
    Test.stopTest();
  }

  @isTest
  static void editFileContentDocumentTest() {
    ContentDocument file = [SELECT Id FROM ContentDocument LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    QuoteOppFilesRelatedListController.editFile(file.Id, 'test', 'test');
    Test.stopTest();
  }

  @isTest
  static void editFileAttachmentTest() {
    Attachment file = [SELECT Id FROM Attachment LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    QuoteOppFilesRelatedListController.editFile(file.Id, 'test', 'test');
    Test.stopTest();
  }

  @isTest
  static void validateQuoteStatusTest() {
    zqu__Quote__c quote = [SELECT Id FROM zqu__Quote__c LIMIT 1];
    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    Response resp = QuoteOppFilesRelatedListController.validateQuoteStatus(
      quote.Id,
      true
    );
    System.assert(resp.success);
    quote.zqu_Quote_Status__c = 'Sent To Zuora';
    update quote;
    resp = QuoteOppFilesRelatedListController.validateQuoteStatus(
      quote.Id,
      true
    );
    System.assert(!resp.success);
    Test.stopTest();
  }

  @isTest
  static void obtainFilesFromRelatedOpportunityWithRequestIdTest() {
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
    zqu__Quote__c quote = [SELECT Id FROM zqu__Quote__c LIMIT 1];
    quote.zqu__Opportunity__c = opp.Id;
    Request__c request = TestDataFactory.createRequest(opp);
    request.RecordTypeId = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName()
      .get('Technical_Solutions')
      .getRecordTypeId();

    Test.startTest();
    MockUtil.NetsuiteExchangeRatesServiceHttpMock mockServiceInstance = new MockUtil.NetsuiteExchangeRatesServiceHttpMock();
    Test.setMock(HttpCalloutMock.class, mockServiceInstance);
    update quote;
    insert request;
    Response failedResponse = QuoteOppFilesRelatedListController.obtainFilesFromRelatedOpportunity(
      request.Id
    );
    request.Quote__c = quote.id;
    update request;
    Response succesfyllResponse = QuoteOppFilesRelatedListController.obtainFilesFromRelatedOpportunity(
      request.Id
    );
    Test.stopTest();
  }
}