force-app/main/default/objects/Account/fields/Country_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Country_Subsidiary__c</fullName>
    <description>Populate from account after save flow , according to account country in CountrySubsidiary</description>
    <label>Country Subsidiary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Zuora_Quote__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zuora Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Subsidiary__c/Country_Subsidiary__c.object-meta.xml
<CustomObject>
    <label>Country Subsidiary</label>
    <nameField>
        <label>Country Subsidiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountrySubsidiary</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Applicable_Quote__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Quote__c</fullName>
    <label>Applicable Quote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Green_Lane_Document__c.field-meta.xml
<CustomField>
    <fullName>Green_Lane_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked By Billing when final version approved</description>
    <label>Green Lane Document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1113759 populates manually</description>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>FA with analyst/eng</fullName>
            </value>
            <value>
                <fullName>Pending Client</fullName>
            </value>
            <value>
                <fullName>Pending GTM</fullName>
            </value>
            <value>
                <fullName>Pending finance</fullName>
            </value>
            <value>
                <fullName>Pending Dragons</fullName>
            </value>
            <value>
                <fullName>In R&amp;D process</fullName>
            </value>
            <value>
                <fullName>DaaS to Deliver - Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed lost</fullName>
                <label>Closed Lost</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Account Preliminary Interest</fullName>
            </value>
            <value>
                <fullName>Actively Working</fullName>
            </value>
            <value>
                <fullName>Approved By Billing</fullName>
            </value>
            <value>
                <fullName>Assigned to SE/CSA</fullName>
            </value>
            <value>
                <fullName>Building Presentation</fullName>
            </value>
            <value>
                <fullName>Feasibility Pending</fullName>
                <label>Checking feasibility &amp; estimating effort</label>
            </value>
            <value>
                <fullName>Client Approval received</fullName>
                <label>Client Approval</label>
            </value>
            <value>
                <fullName>Client interest confirmed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Completed (sent to billing)</fullName>
            </value>
            <value>
                <fullName>Data Set Trial</fullName>
            </value>
            <value>
                <fullName>Data Set Trial - Evaluation</fullName>
            </value>
            <value>
                <fullName>Effort estimated</fullName>
            </value>
            <value>
                <fullName>Feasibility assessment (with Analysts / Engineers)</fullName>
            </value>
            <value>
                <fullName>Feasibility Confirmed</fullName>
            </value>
            <value>
                <fullName>Full Brief received</fullName>
            </value>
            <value>
                <fullName>Initiated - Future deliveries remaining</fullName>
            </value>
            <value>
                <fullName>Not Feasible</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Technical_Solutions.recordType-meta.xml
<RecordType>
    <fullName>Technical_Solutions</fullName>
    <active>true</active>
    <label>DaaS request</label>
</RecordType>

force-app/main/default/objects/User/fields/Admin_Console__c.field-meta.xml
<CustomField>
    <fullName>Admin_Console__c</fullName>
    <label>Life Cycle Admin Console</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FileUploadController_Test.cls
@isTest
with sharing class FileUploadController_Test {
  @testSetup
  static void testSetup() {
    Utils.CodeOff = true;
    TestDataFactory.createSimilarWeb_CS();
    TestDataFactory.createBaseProductConfiguration_CS();
    TestDataFactory.createInferredSolutionSettings_CS();
    List<String> countries = TestObjectCreator.getCountries();
    Account a = TestObjectCreator.CreateAccount();
    a.billingcountry = countries[countries.size() - 1];
    insert a;
    Contact c = TestObjectCreator.CreateContact(
      a,
      'test' + TestObjectCreator.randomStream(9, 2) + '@testing.com'
    );
    c.MailingCountry = countries[countries.size() - 1];
    insert c;
    list<Country_Subsidiary__c> lcsc = TestObjectCreator.CreateCountries();
    Opportunity o = TestObjectCreator.CreateOpportunity(a);
    insert o;
    zqu__Quote__c q = TestObjectCreator.CreateZQuote(o, c);
    q.zqu__Currency__c = 'USD';
    insert q;
    ContentVersion cvPdf = TestDataFactory.createContentVersionWithType('pdf');
    insert cvPdf;

    /* 
        cvPdf = [SELECT Id,ContentDocumentId FROM ContentVersion WHERE Id = :cvPdf.Id LIMIT 1];
        ContentDocumentLink cdl = TestDataFactory.createContentDocumentLink(o.id,cvPdf.ContentDocumentId);
        insert cdl; */
  }

  @isTest
  static void testInsert() {
    zqu__Quote__c quote = [SELECT Id FROM zqu__Quote__c LIMIT 1];
    Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
    ContentVersion cvPdf = [
      SELECT Id, ContentDocumentId
      FROM ContentVersion
      LIMIT 1
    ];
    ContentDocument cd = [SELECT Id, Title FROM ContentDocument LIMIT 1];
    Map<String, String> cdMap = new Map<String, String>();
    cdMap.put('documentId', cd.Id);
    List<Map<String, String>> jsn = new List<Map<String, String>>();
    jsn.add(cdMap);
    String jsonStr = JSON.serialize(jsn);

    Test.startTest();
    FileUploadController.setLookup(
      jsonStr,
      (String) quote.Id,
      (String) opp.Id,
      Date.today(),
      true
    );
    Test.stopTest();
  }

  @isTest
  static void updateQuoteToGreenLineTest() {
    zqu__Quote__c quote = [SELECT Id FROM zqu__Quote__c LIMIT 1];
    Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
    ContentVersion cvPdf = [
      SELECT Id, ContentDocumentId
      FROM ContentVersion
      LIMIT 1
    ];
    ContentDocument cd = [SELECT Id, Title FROM ContentDocument LIMIT 1];

    ContentVersion cvPdf2 = TestDataFactory.createContentVersion();
    cvPdf2.Origin = 'H';
    cvPdf2.Zuora_Quote__c = quote.Id;
    insert cvPdf2;
    cvPdf2 = [
      SELECT Id, ContentDocumentId, Title
      FROM ContentVersion
      WHERE Id = :cvPdf2.Id
    ];
    id linkedEntityId = quote.Id;
    ContentDocumentLink cd2 = new ContentDocumentLink(
      ContentDocumentId = cvPdf2.ContentDocumentId,
      LINKEDENTITYID = linkedEntityId
    );
    insert cd2;

    Map<String, String> cdMap = new Map<String, String>();
    cdMap.put('documentId', cd.Id);
    List<Map<String, String>> jsn = new List<Map<String, String>>();
    jsn.add(cdMap);
    String jsonStr = JSON.serialize(jsn);

    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
    User u = new User(
      Alias = 'standt',
      Email = 'sometrestuser' + DateTime.now().getTime() + '@testorg.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com',
      Admin_Console__c = 'CLC'
    );

    Test.startTest();
    Request__c rquest = TestDataFactory.createRequest(opp);
    rquest.Quote__c = quote.id;
    rquest.RecordTypeId = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName()
      .get('Technical_Solutions')
      .getRecordTypeId();
    rquest.Status__c = 'Completed';
    rquest.Green_Lane_Document__c = true;
    rquest.Applicable_Quote__c = 'Yes';
    insert rquest;

    System.assertNotEquals(null, rquest.id);
    System.runAs(u) {
      FileUploadController.setLookup(
        jsonStr,
        (String) quote.Id,
        (String) opp.Id,
        Date.today(),
        true
      );
    }
    Test.stopTest();
  }

  @isTest
  static void validateTest() {
    zqu__Quote__c quote = [SELECT Id FROM zqu__Quote__c LIMIT 1];
    quote.zqu__PaymentMethod__c = 'Other';
    quote.zqu_Quote_Status__c = 'Terms Pending';
    update quote;

    Test.startTest();
    try {
      FileUploadController.validate(quote.id, true);
    } catch (Exception ex) {
      System.debug(ex.getMessage());
    }
    Test.stopTest();
  }
}