force-app/main/default/objects/Account/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <formula>Case(BillingCountry,

&quot;United States&quot;,1,
&quot;US&quot;,1,
&quot;Canada&quot;,1,
&quot;Japan&quot;,1,
&quot;Australia&quot;,1,
&quot;India&quot;,1,
&quot;Russia&quot;,1,
&quot;China&quot;,1,
&quot;United Kingdom&quot;,1,
&quot;France&quot;,1,
&quot;Germany&quot;,1,

&quot;Brazil&quot;,2,
&quot;Columbia&quot;,2,
&quot;Argentina&quot;,2,
&quot;Mexico&quot;,2,
&quot;Hong Kong&quot;,2,
&quot;Singapore&quot;,2,
&quot;New Zealand&quot;,2,
&quot;Malaysia&quot;,2,
&quot;Austria&quot;,2,
&quot;Switzerland&quot;,2,
&quot;Sweden&quot;,2,
&quot;Denmark&quot;,2,
&quot;Spain&quot;,2,
&quot;Portugal&quot;,2,
&quot;Italy&quot;,2,
&quot;Netherlands&quot;,2,
&quot;Ireland&quot;,2,
&quot;Israel&quot;,2,
&quot;Norway&quot;,2,
&quot;Finland&quot;,2,

&quot;&quot;,Null,

3
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wolves_Status__c.field-meta.xml
<CustomField>
    <fullName>Wolves_Status__c</fullName>
    <label>Wolves Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Wolves.recordType-meta.xml
<RecordType>
    <fullName>Wolves</fullName>
    <active>true</active>
    <label>Panel Acquisition</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Monthly - Fix Price</fullName>
            </value>
            <value>
                <fullName>Monthly - Flex Rate</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>BI - Annual</fullName>
            </value>
            <value>
                <fullName>Fix Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <formula>Case(Country,

&quot;United States&quot;,1,
&quot;US&quot;,1,
&quot;Canada&quot;,1,
&quot;Japan&quot;,1,
&quot;Australia&quot;,1,
&quot;India&quot;,1,
&quot;Russia&quot;,1,
&quot;China&quot;,1,
&quot;United Kingdom&quot;,1,
&quot;France&quot;,1,
&quot;Germany&quot;,1,

&quot;Brazil&quot;,2,
&quot;Columbia&quot;,2,
&quot;Argentina&quot;,2,
&quot;Mexico&quot;,2,
&quot;Hong Kong&quot;,2,
&quot;Singapore&quot;,2,
&quot;New Zealand&quot;,2,
&quot;Malaysia&quot;,2,
&quot;Austria&quot;,2,
&quot;Switzerland&quot;,2,
&quot;Sweden&quot;,2,
&quot;Denmark&quot;,2,
&quot;Spain&quot;,2,
&quot;Portugal&quot;,2,
&quot;Italy&quot;,2,
&quot;Netherlands&quot;,2,
&quot;Ireland&quot;,2,
&quot;Israel&quot;,2,
&quot;Norway&quot;,2,
&quot;Finland&quot;,2,

&quot;&quot;,Null,

3
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Wolves.recordType-meta.xml
<RecordType>
    <fullName>Wolves</fullName>
    <active>true</active>
    <businessProcess>Wolves</businessProcess>
    <label>Panel Acquisition</label>
</RecordType>

force-app/main/default/objects/Monthly_Data_Request__c/Monthly_Data_Request__c.object-meta.xml
<CustomObject>
    <description>Monthly data information we get per each &quot;Source&quot;. The data Method can be &quot;DAU&quot;/&quot;MAU&quot;/&quot;S2S&quot; and more. 
We get the data on a monthly bases from BI.</description>
    <label>Monthly Data Request</label>
    <nameField>
        <label>Monthly Data Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Data Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country that the DAU is pulled from. Used for BI to detect the Request.</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <description>Represents the Value of the &quot;Country/Tier&quot; field on the related &quot;Rate&quot;.</description>
    <label>Country/Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Tier_for_Data_Partners</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Monthly_Source_Request__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Source_Request__c</fullName>
    <description>All the Monthly Data Request should roll up to the relevant Monthly Source Data</description>
    <label>Monthly Source Request</label>
    <referenceTo>Monthly_Source_Request__c</referenceTo>
    <relationshipLabel>Monthly Data Requests</relationshipLabel>
    <relationshipName>Monthly_Data_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Monthly Data Requests</relationshipLabel>
    <relationshipName>Monthly_Data_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>Key number for BI to detect each Data Request</description>
    <label>Request Type</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Data_Request__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Source of the Data Method. MIS-1690</description>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Monthly Data Requests</relationshipLabel>
    <relationshipName>Monthly_Data_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Partner_Request__c/Monthly_Partner_Request__c.object-meta.xml
<CustomObject>
    <description>Roll up data monthly payment on the Contract payment (final payment for the partner each month).</description>
    <label>Monthly Partner Request</label>
    <nameField>
        <label>Monthly Partner Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Partner Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Partner_Request__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <description>The Monthly Payment Data holds the total payment for the partner per month. It must be related to the Contract of the Partner.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Monthly_Partner_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Source_Request__c/Monthly_Source_Request__c.object-meta.xml
<CustomObject>
    <description>Each month new &quot;Monthly Data Method&quot; are created. These should be under a Monthly Source Data records. So we can roll up each Monthly payment to the Source level (and then to the Contract level)</description>
    <label>Monthly Source Request</label>
    <nameField>
        <label>Monthly Source Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Source Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Source_Request__c/fields/Monthly_Partner_Request__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Partner_Request__c</fullName>
    <description>All the Monthly Source Data should roll up to the &quot;Monthly Partner Data&quot;</description>
    <label>Monthly Partner Request</label>
    <referenceTo>Monthly_Partner_Request__c</referenceTo>
    <relationshipLabel>Monthly Source Requests</relationshipLabel>
    <relationshipName>Monthly_Source_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Source_Request__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Monthly Source Requests</relationshipLabel>
    <relationshipName>Monthly_Source_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Source_Request__c/fields/Source_Number__c.field-meta.xml
<CustomField>
    <fullName>Source_Number__c</fullName>
    <formula>Source__r.Source_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Information for every &quot;Data Request&quot; for each Source. Part of the Data Partner model.</description>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>In case the &quot;End Date&quot; of the Rate is not blank and equal/less TODAY the CB will be true.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The Tier/Country of the Request that will be created according the Rate</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <label>Country/Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Tier_for_Data_Partners</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Once populated, the &quot;Rate&quot; is no longer valid in the &quot;Monthly Data Request&quot; calculation.</description>
    <inlineHelpText>Once populated and Date is in the past, no Monthly Data Records will be created. In case the Source is no longer relevant, make sure to deactivate it!</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The actual Rate we pay for each data unit as agreed in the Contract</description>
    <label>Rate</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <referenceTo>Source__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <description>Part of the &quot;Data Partner&quot; model. A Source represents the Products that Similarweb pulls the data from. We get the &quot;Sources&quot; from the Data Partners.</description>
    <label>Source</label>
    <nameField>
        <label>Sources  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the Source is active or not. In case all the related &quot;Rates&quot; are with End Date less than Today it should be deactivated.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Sources</relationshipLabel>
    <relationshipName>Sources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Source__c/fields/Source_Number__c.field-meta.xml
<CustomField>
    <fullName>Source_Number__c</fullName>
    <label>Source Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DataPartnerManagementBatch.cls
/**
 * @author Zohar Sinay
 * @date 03/02/2022
 * @description Distribute leads to marketing cloud and pardot lead
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      -
 * date        -
 * description -
 * --------------------------------------------------------------------------------------
 */

public with sharing class DataPartnerManagementBatch implements Database.Batchable<sObject>, Database.Stateful {
  private static final string dataPartnerRecordTypeId = Utility.getRecordTypeIdForObject(
    new Account().getSObjectType(),
    'Wolves'
  );
  private static final Integer thisMonth = Date.today().month();
  private static final Integer thisYear = Date.today().year();
  public static List<Log_Event__e> logList = new List<Log_Event__e>();
  public static Log_Event__e log = new Log_Event__e();
  private String accountId;

  public DataPartnerManagementBatch(String accountId) {
    this.accountId = accountId;
  }

  public DataPartnerManagementBatch() {
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    String activeStr = 'Active';
    Set<String> paymentMethodStringSet = new Set<String>{
      'Monthly',
      'Monthly - Fix Price',
      'Monthly - Flex Rate'
    };
    String query =
      'SELECT ID, Name, (SELECT Id, Name FROM Contracts WHERE Payment_Method__c IN:paymentMethodStringSet )' +
      'FROM Account ' +
      'WHERE RecordTypeId = :dataPartnerRecordTypeId AND Wolves_Status__c =:activeStr ';
    query += this.accountId != null ? 'AND Id = :accountId' : '';
    System.debug('query--' + query);

    return Database.getQueryLocator(query);
  }

  /**
   * @param bc
   * @param scope
   */
  public void execute(Database.BatchableContext bc, List<Account> scope) {
    List<Id> ContractIdList = new List<Id>();
    List<Source__c> sourceList = new List<Source__c>();
    List<Monthly_Partner_Request__c> MPRList = new List<Monthly_Partner_Request__c>();
    List<Monthly_Source_Request__c> MSRList = new List<Monthly_Source_Request__c>();
    List<Monthly_Data_Request__c> MDRList = new List<Monthly_Data_Request__c>();

    try {
      for (Account acc : scope) {
        for (Contract cont : acc.Contracts) {
          System.debug(cont.Id);
          ContractIdList.add(cont.Id);
          String MPRName = String.isBlank(cont.Name) ? acc.Name : cont.Name;
          MPRName += '/' + thisMonth + '/' + thisYear;
          MPRList.add(
            new Monthly_Partner_Request__c(
              Name = MPRName,
              Contracts__c = cont.Id
            )
          );
        }
      }
      sourceList = [
        SELECT
          Id,
          Name,
          Source_Number__c,
          Contract__c,
          Contract__r.Name,
          (
            SELECT
              Id,
              Name,
              Source__c,
              Source__r.Name,
              Request_Type__c,
              Source__r.Source_Number__c,
              Country__c,
              Country_Tier__c
            FROM Rates__r
            WHERE End_Date__c = NULL OR End_Date__c > :Date.today()
          )
        FROM Source__c
        WHERE Contract__c IN :ContractIdList AND Active__c = TRUE
      ];
      System.debug('sourceList--' + sourceList);
      Map<Id, List<Source__c>> sourceByContractIdMap = new Map<Id, List<Source__c>>();
      Map<Id, List<Rate__c>> rateBySourceIdMap = new Map<Id, List<Rate__c>>();
      for (Source__c so : sourceList) {
        if (!sourceByContractIdMap.containsKey(so.Contract__c)) {
          sourceByContractIdMap.put(so.Contract__c, new List<Source__c>{ so });
        } else {
          sourceByContractIdMap.get(so.Contract__c).add(so);
        }
      }
      System.debug('sourceByContractIdMap---' + sourceByContractIdMap);
      if (!MPRList.isEmpty()) {
        insert MPRList;
        for (Monthly_Partner_Request__c mpr : MPRList) {
          System.debug('mpr--' + mpr);
          System.debug('mpr.Contracts__c--' + mpr.Contracts__c);
          System.debug(
            'sourceByContractIdMap--' +
            sourceByContractIdMap.get(mpr.Contracts__c)
          );
          if (sourceByContractIdMap.containsKey(mpr.Contracts__c)) {
            for (Source__c so : sourceByContractIdMap.get(mpr.Contracts__c)) {
              MSRList.add(
                new Monthly_Source_Request__c(
                  Name = so.Name +
                    '/' +
                    so.Source_Number__c +
                    '/' +
                    String.valueOf(thisMonth) +
                    '/' +
                    String.valueOf(thisYear),
                  Monthly_Partner_Request__c = mpr.Id,
                  Source__c = so.Id
                )
              );
              for (Rate__c rat : so.Rates__r) {
                if (!rateBySourceIdMap.containsKey(rat.Source__c)) {
                  rateBySourceIdMap.put(
                    rat.Source__c,
                    new List<Rate__c>{ rat }
                  );
                } else {
                  rateBySourceIdMap.get(rat.Source__c).add(rat);
                }
              }
            }
          }
        }
        if (!MSRList.isEmpty()) {
          insert MSRList;
        }
        for (Monthly_Source_Request__c msr : MSRList) {
          System.debug('msr--' + msr);
          System.debug('msr.Source__c--' + msr.Source__c);
          System.debug(
            'rateBySourceIdMap--' + rateBySourceIdMap.get(msr.Source__c)
          );
          if (rateBySourceIdMap.containsKey(msr.Source__c)) {
            for (Rate__c rat : rateBySourceIdMap.get(msr.Source__c)) {
              MDRList.add(
                new Monthly_Data_Request__c(
                  Name = rat.Source__r.Name +
                    '/' +
                    rat.Source__r.Source_Number__c +
                    '/' +
                    rat.Request_Type__c +
                    '/' +
                    rat.Country_Tier__c +
                    '/' +
                    String.valueOf(thisMonth) +
                    '/' +
                    String.valueOf(thisYear),
                  Monthly_Source_Request__c = msr.Id,
                  Source__c = rat.Source__c,
                  Rate__c = rat.Id
                )
              );
            }
          }
        }
        if (!MDRList.isEmpty()) {
          insert MDRList;
        }
      }
    } catch (Exception ex) {
      System.debug('EXCEPTION: ' + ex.getMessage());
      System.debug('EXCEPTION Path: ' + ex.getStackTraceString());
    }
  }

  public void finish(Database.BatchableContext bc) {
  }
}