force-app/main/default/objects/Account/fields/Country_Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Country_Subsidiary__c</fullName>
    <description>Populate from account after save flow , according to account country in CountrySubsidiary</description>
    <label>Country Subsidiary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
                <isActive>false</isActive>
                <label>CAD</label>
            </value>
            <value>
                <fullName>ILS</fullName>
                <isActive>false</isActive>
                <label>ILS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>MIS-1036</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Applicable_Quote__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Quote__c</fullName>
    <label>Applicable Quote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>#1113520</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Recipient_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Picklist__c</fullName>
    <label>Recipient</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aaron Feinblatt</fullName>
            </value>
            <value>
                <fullName>Aaron Wong</fullName>
            </value>
            <value>
                <fullName>Adam Wertheim</fullName>
            </value>
            <value>
                <fullName>Aidan Krakowsky</fullName>
            </value>
            <value>
                <fullName>Alexandre Koniecko</fullName>
            </value>
            <value>
                <fullName>Alex Donchenko</fullName>
            </value>
            <value>
                <fullName>Alex Donchenko (PS)</fullName>
            </value>
            <value>
                <fullName>Alisha Kapur</fullName>
            </value>
            <value>
                <fullName>Amit Ram</fullName>
            </value>
            <value>
                <fullName>Anand Ramanathan</fullName>
            </value>
            <value>
                <fullName>Anastasia Segal</fullName>
            </value>
            <value>
                <fullName>Andrea Girardello</fullName>
            </value>
            <value>
                <fullName>Andrew Bonnici</fullName>
            </value>
            <value>
                <fullName>Andrew Liu</fullName>
            </value>
            <value>
                <fullName>Anne-Christele Antoine</fullName>
            </value>
            <value>
                <fullName>Antonello Musina</fullName>
            </value>
            <value>
                <fullName>Aria Ertefaie</fullName>
            </value>
            <value>
                <fullName>Ariane Turley</fullName>
            </value>
            <value>
                <fullName>Ariel Even</fullName>
            </value>
            <value>
                <fullName>Ariella Magid</fullName>
            </value>
            <value>
                <fullName>Ariyeh Taitz</fullName>
            </value>
            <value>
                <fullName>Audrey Guilloux</fullName>
            </value>
            <value>
                <fullName>Aurore Miniatura</fullName>
            </value>
            <value>
                <fullName>Banke daCosta</fullName>
            </value>
            <value>
                <fullName>Becca Edelman</fullName>
            </value>
            <value>
                <fullName>Becca Edelman (EMEA)</fullName>
            </value>
            <value>
                <fullName>Becka Abram (M)</fullName>
            </value>
            <value>
                <fullName>Belinda Kwok</fullName>
            </value>
            <value>
                <fullName>Ben Fernando (EMEA)</fullName>
            </value>
            <value>
                <fullName>Ben Fernando (VAP)</fullName>
            </value>
            <value>
                <fullName>Chris Foale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Regularity__c.field-meta.xml
<CustomField>
    <fullName>Regularity__c</fullName>
    <label>Delivery Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>One time</fullName>
            </value>
            <value>
                <fullName>Recurring Quarterly</fullName>
                <label>Recurring - Quarterly</label>
            </value>
            <value>
                <fullName>Recurring Monthly</fullName>
                <label>Recurring - Monthly</label>
            </value>
            <value>
                <fullName>Recurring - Ad Hoc</fullName>
            </value>
            <value>
                <fullName>Recurring - Weekly</fullName>
            </value>
            <value>
                <fullName>Recurring - Daily</fullName>
            </value>
            <value>
                <fullName>One-time + Recurring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requester</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Signed_contract__c.field-meta.xml
<CustomField>
    <fullName>Signed_contract__c</fullName>
    <description>#1113520</description>
    <inlineHelpText>Attach the contract to the opportunity if yes</inlineHelpText>
    <label>Signed contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomLookupFieldControllerTest.cls
@isTest
public with sharing class CustomLookupFieldControllerTest {
    @TestSetup
    static void setup(){
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createInferredSolutionSettings_CS();

        List<String> countries =  TestObjectCreator.getCountries();
        list<Country_Subsidiary__c> lcsc = TestObjectCreator.CreateCountries();
        Account a = TestObjectCreator.CreateAccount();
        a.billingcountry = countries[countries.size()-1];
        insert a;
        Contact c = TestObjectCreator.CreateContact(a, 'test'+TestObjectCreator.randomStream(9,2)+'@testing.com');
        c.MailingCountry = countries[countries.size()-1];
        insert c;
        Opportunity opp = TestObjectCreator.CreateOpportunity(a);
        opp.Primary_Contact__c = c.id;
        insert opp;

        List<Request__c> requestList = new List<Request__c>();
        Request__c rquest1 = new Request__c();
        rquest1.Requester__c = UserInfo.getUserId();
        rquest1.Recipient_Picklist__c = 'Chris Foale';
        rquest1.Applicable_Quote__c = 'Yes';
        rquest1.Opportunity__c = opp.Id;
        rquest1.Account__c = opp.AccountId;
        rquest1.Signed_contract__c = 'Yes';
        rquest1.Currency__c = 'USD';
        rquest1.RecordTypeId = '0120X0000005lrhQAA';
        rquest1.Regularity__c = 'One time';
        rquest1.Status__c = 'Submitted';
        rquest1.List_Price__c = 788;
        rquest1.Account__c = a.id;
        rquest1.Opportunity__c = opp.id;
        rquest1.Manager__c = UserInfo.getUserId();
        requestList.add(rquest1);
        insert requestList;

        zqu__Quote__c quote = TestDataFactory.CreateZQuote(opp, c);
        quote.Quote_contains_AS_products__c = true;
        quote.zqu__QuoteBusinessType__c = 'Co-Term Upsell';
        quote.zqu__SubscriptionType__c = 'Amendment';
        quote.zqu__Previewed_SubTotal__c = 10;
        quote.Target_Quote_Total_Price__c = 10;
        quote.zqu__PaymentMethod__c = 'Other';
        insert quote;
    }
    @isTest
    static void fetchRecordsTest(){
        Request__c req = [SELECT Id, Name FROM Request__c LIMIT 1];
        String objectName = 'Request__c';
        String filterField = 'Regularity__c';
        String searchString = 'One time';
        String value = '';
        Test.startTest();
        List<CustomLookupFieldController.RecordWrapper> records = CustomLookupFieldController.fetchRecords(objectName, filterField, searchString, value);
        value = req.id;
        records = CustomLookupFieldController.fetchRecords(objectName, filterField, searchString, value);
        Test.stopTest();
        System.assert(records.size() > 0, 'Must be returned at least one request');
    }

    @isTest
    static void fetchRequestsTest(){
        Request__c req = [SELECT Id, Name, Status__c FROM Request__c LIMIT 1];
        String searchString = req.Name;
        String quoteId = [SELECT Id FROM zqu__Quote__c LIMIT 1].Id;
        String requestType = 'onetime';
        Test.startTest();
        req.Status__c = 'Submitted';
        update req;
        List<CustomLookupFieldController.RecordWrapper> records = CustomLookupFieldController.fetchRequests(searchString, quoteId, requestType);
        Test.stopTest();
    }
}