force-app/main/default/objects/Account/fields/Exclude_From_Territory_Owner_Change__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Territory_Owner_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Exclude the account from the owner&apos;s changes in the territory automation.
MIS-3611</description>
    <inlineHelpText>Exclude the account from the owner&apos;s changes in the territory automation.</inlineHelpText>
    <label>Exclude From Territory Owner Change</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Member__c/Territory_Member__c.object-meta.xml
<CustomObject>
    <label>Territory Member</label>
    <nameField>
        <displayFormat>TMN-{000}</displayFormat>
        <label>Territory Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Member__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory Members</relationshipLabel>
    <relationshipName>Territory_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory_Member__c/fields/Territory_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>Territory_Member_Role__c</fullName>
    <label>Territory Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>SDR</fullName>
            </value>
            <value>
                <fullName>CSS</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
                <isActive>false</isActive>
                <label>CSA</label>
            </value>
            <value>
                <fullName>SE</fullName>
                <isActive>false</isActive>
                <label>SE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TerritoryMemberHandler.cls
/**
 * Created by alon.shalev on 5/11/2025.
 */

public with sharing class TerritoryMemberHandler {
  public void duplicationValidation(List<Territory_Member__c> newList) {
    System.debug('duplicationValidation started');
    Set<Id> territoryIdSet = new Set<Id>();
    for (Territory_Member__c territoryMember : newList) {
      territoryIdSet.add(territoryMember.Territory__c);
    }
    Map<Id, Set<Id>> territoryToUserMap = new Map<Id, Set<Id>>();
    List<Territory__c> territoryWithExistingMembersList = [
      SELECT Id, Ownerid, (SELECT Name__c FROM Territory_Members__r)
      FROM Territory__c
      WHERE Id IN :territoryIdSet
    ];
    System.debug(
      'territoryWithExistingMembersList--' + territoryWithExistingMembersList
    );
    if (!territoryWithExistingMembersList.isEmpty()) {
      for (Territory__c territory : territoryWithExistingMembersList) {
        if (!territoryToUserMap.containsKey(territory.Id)) {
          territoryToUserMap.put(territory.Id, new Set<Id>());
        }
        territoryToUserMap.get(territory.Id).add(territory.OwnerId);
        for (
          Territory_Member__c territoryMember : territory.Territory_Members__r
        ) {
          territoryToUserMap.get(territory.Id).add(territoryMember.Name__c);
        }
      }
    }

    for (Territory_Member__c territoryMember : newList) {
      Set<Id> userOfThisTerritorySet = territoryToUserMap.get(
        territoryMember.Territory__c
      );
      if (userOfThisTerritorySet != null) {
        if (userOfThisTerritorySet.contains(territoryMember.Name__c)) {
          territoryMember.addError(
            'The user is already assigned to this territory.'
          );
        }
      }
    }
  }

  public void handleBeforeDelete(List<Territory_Member__c> members) {
    List<String> memberIds = new List<String>();

    for (Territory_Member__c m : members) {
      memberIds.add(m.Id);
    }

    List<Territory_Member__c> territoryMembers = [
        SELECT Id, Name__c, Territory_Member_Role__c, Territory__r.OwnerId
        FROM Territory_Member__c
        WHERE Id IN :memberIds
      ],
      excludedFromTerritoryChangeMembers = new List<Territory_Member__c>();

    for (Territory_Member__c m : territoryMembers) {
      if (
        m.Territory_Member_Role__c == 'Sales Manager' &&
        m.Territory__r.OwnerId != m.Name__c
      ) {
        excludedFromTerritoryChangeMembers.add(m);
      }
    }

    excludeFromTerritoryChange(excludedFromTerritoryChangeMembers);
  }

  private void excludeFromTerritoryChange(List<Territory_Member__c> members) {
    List<String> territoryAndOwner = new List<String>();

    for (Territory_Member__c m : members) {
      territoryAndOwner.add(
        '(Territory__c = \'' +
          m.Territory__c +
          '\' AND OwnerId = \'' +
          m.Territory__r.OwnerId +
          '\')'
      );
    }

    if (territoryAndOwner.size() > 0) {
      String query =
        'SELECT Id, Exclude_From_Territory_Owner_Change__c ' +
        'FROM Account ' +
        'WHERE Exclude_From_Territory_Owner_Change__c = true AND (' +
        String.join(territoryAndOwner, ' OR ') +
        ')';

      Database.executeBatch(new TerritoryMemberAccountBatchable(query), 250);
    }
  }
}