force-app/main/default/objects/Account/fields/Hierarchy_Total_Open_Opps__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Total_Open_Opps__c</fullName>
    <label>Hierarchy Total Open Opps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_Of_Open_Opps_Changed_Today__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Open_Opps_Changed_Today__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will be checked when roll up # of open opps is changed/ will be used for scheduled flow entry creteria</description>
    <label>Number Of Open Opps Changed Today</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent_Company_Domain__c.field-meta.xml
<CustomField>
    <fullName>Parent_Company_Domain__c</fullName>
    <description>#1101356 Populates by SalesOps
[OB] - Field type changed to &quot;Text&quot; and checked &quot;External Id&quot; - This is for using the field in &quot;Get Records&quot; in Flow.</description>
    <externalId>true</externalId>
    <label>Parent Company Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Website_Domain__c.field-meta.xml
<CustomField>
    <fullName>Website_Domain__c</fullName>
    <formula>If(BEGINS(Website, &quot;www.&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) != 0, MID(Website, 5, FIND(&apos;/&apos;, MID(Website, 5, LEN(Website) - 4)) -1), MID(Website, 5, LEN(Website) - 4)),

If(BEGINS(Website, &quot;http://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 12, LEN(Website) - 11)) != 0,MID(Website, 12, FIND(&apos;/&apos;, MID(Website,12,LEN(Website) - 11)) -1), MID(Website,12,LEN(Website)-11)),

If(BEGINS(Website, &quot;https://www.&quot;),
IF(FIND(&apos;/&apos;, MID(Website, 13, LEN(Website) - 12)) != 0,MID(Website, 13, FIND(&apos;/&apos;, MID(Website,13,LEN(Website) - 12)) -1), MID(Website,13,LEN(Website)-12)),

If(BEGINS(Website, &quot;http://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 8, LEN(Website) - 7)) != 0,MID(Website, 8, FIND(&apos;/&apos;, MID(Website,8,LEN(Website) - 7)) -1), MID(Website,8,LEN(Website)-7)),

If(BEGINS(Website, &quot;https://&quot;), 
IF(FIND(&apos;/&apos;, MID(Website, 9, LEN(Website) - 8)) != 0,MID(Website, 9, FIND(&apos;/&apos;, MID(Website,9,LEN(Website) - 8)) -1), MID(Website,9,LEN(Website)-8)),

IF(FIND(&apos;/&apos;,MID(Website, 1, LEN(Website))) !=0,MID(Website,1,FIND(&apos;/&apos;, Website) - 1), Website ))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateHierarchyOpenOppsAccountBatch.cls
/**
 * Created by Alon.Shalev on 6/9/2024.
 */

global with sharing class UpdateHierarchyOpenOppsAccountBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
  private final Integer batchSize;
  private Map<Id, Integer> accountIdToNumberOfOpenOppsInHierarcyMap = new Map<Id, Integer>();

  global UpdateHierarchyOpenOppsAccountBatch(Integer batchSize) {
    this.batchSize = batchSize;
  }

  global UpdateHierarchyOpenOppsAccountBatch() {
  }

  global void execute(SchedulableContext param1) {
    UpdateHierarchyOpenOppsAccountBatch batch = new UpdateHierarchyOpenOppsAccountBatch();
    Database.executeBatch(batch, this.batchSize != null ? this.batchSize : 3);
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    String query =
      'SELECT Id,Parent_Company_Domain__c,Website_Domain__c ' +
      ' FROM Account ' +
      'WHERE Number_Of_Open_Opps_Changed_Today__c  = true';
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<Account> scope) {
    Map<String, Account> companyParentDomainToAccountMap = new Map<String, Account>();
    Map<String, Account> websiteDomainToAccountMap = new Map<String, Account>();
    Map<String, List<Account>> companyDomainToSimilarAccountMap = new Map<String, List<Account>>();
    Map<String, List<Account>> websiteDomainToSimilarAccountMap = new Map<String, List<Account>>();
    List<Account> accountToUpdateList = new List<Account>();
    for (Account acc : scope) {
      if (String.isNotBlank(acc.Parent_Company_Domain__c)) {
        companyParentDomainToAccountMap.put(acc.Parent_Company_Domain__c, acc);
      }
      if (
        !companyParentDomainToAccountMap.containsKey(acc.Website_Domain__c) &&
        String.isNotBlank(acc.Website_Domain__c)
      ) {
        websiteDomainToAccountMap.put(acc.Website_Domain__c, acc);
      }
    }

    List<Account> similarAccountByParentDomainList = [
      SELECT
        Id,
        Name,
        Website_Domain__c,
        Parent_Company_Domain__c,
        Hierarchy_Total_Open_Opps__c,
        (SELECT Id FROM Opportunities WHERE IsClosed = FALSE)
      FROM Account
      WHERE
        Parent_Company_Domain__c IN :companyParentDomainToAccountMap.keySet()
    ];
    List<Account> similarAccountByWebsiteDomainList = [
      SELECT
        Id,
        Name,
        Website_Domain__c,
        Parent_Company_Domain__c,
        (SELECT Id FROM Opportunities WHERE IsClosed = FALSE)
      FROM Account
      WHERE
        Website_Domain__c IN :websiteDomainToAccountMap.keySet()
        AND Parent_Company_Domain__c = NULL
    ];

    for (Account similarAccount : similarAccountByParentDomainList) {
      System.debug(
        'similarAccount--' + similarAccount.Hierarchy_Total_Open_Opps__c
      );
      System.debug(
        'size of opportunities in similarAccountByParentDomainList--' +
        similarAccount.Opportunities.size()
      );
      if (String.isNotBlank(similarAccount.Parent_Company_Domain__c)) {
        if (
          !companyDomainToSimilarAccountMap.containsKey(
            similarAccount.Parent_Company_Domain__c
          )
        ) {
          companyDomainToSimilarAccountMap.put(
            similarAccount.Parent_Company_Domain__c,
            new List<Account>()
          );
        }
        companyDomainToSimilarAccountMap.get(
            similarAccount.Parent_Company_Domain__c
          )
          .add(similarAccount);
      }
    }

    for (Account similarAccount : similarAccountByWebsiteDomainList) {
      System.debug(
        'size of opportunities in similarAccountByWebsiteDomainList--' +
        similarAccount.Opportunities.size()
      );
      if (String.isNotBlank(similarAccount.Website_Domain__c)) {
        if (
          !websiteDomainToSimilarAccountMap.containsKey(
            similarAccount.Website_Domain__c
          )
        ) {
          websiteDomainToSimilarAccountMap.put(
            similarAccount.Website_Domain__c,
            new List<Account>()
          );
        }
        websiteDomainToSimilarAccountMap.get(similarAccount.Website_Domain__c)
          .add(similarAccount);
      }
    }

    populateAccount(
      companyDomainToSimilarAccountMap,
      websiteDomainToSimilarAccountMap
    );
    //        populateAccount(websiteDomainToAccountMap, companyDomainToSimilarAccountMap, accountToUpdateList);
    System.debug('accountToUpdateList--' + accountToUpdateList);

    //        update accountToUpdateList;
  }

  private void populateAccount(
    Map<String, List<Account>> companyDomainToSimilarAccountMap,
    Map<String, List<Account>> websiteDomainToSimilarAccountMap
  ) {
    for (String domain : companyDomainToSimilarAccountMap.keySet()) {
      Integer numberOfOpenOpps = 0;
      Integer newNumberOfOppenOpps = getNumberOfOppenOpps(
        companyDomainToSimilarAccountMap,
        domain,
        numberOfOpenOpps
      );
      List<Account> allAccountsInHierarchy = companyDomainToSimilarAccountMap.get(
        domain
      );
      for (Account accountInThisHierarchy : allAccountsInHierarchy) {
        this.accountIdToNumberOfOpenOppsInHierarcyMap.put(
          accountInThisHierarchy.Id,
          newNumberOfOppenOpps
        );
      }
      //            System.debug('numberOfOpenOpps--' + numberOfOpenOpps);
      //            accToUpdate.Hierarchy_Total_Open_Opps__c = newNumberOfOppenOpps;
      //            accToUpdate.Number_Of_Open_Opps_Changed_Today__c = false;
      //            accountToUpdateList.add(accToUpdate);
    }
    for (String domain : websiteDomainToSimilarAccountMap.keySet()) {
      Integer numberOfOpenOpps = 0;
      Integer newNumberOfOppenOpps = getNumberOfOppenOpps(
        websiteDomainToSimilarAccountMap,
        domain,
        numberOfOpenOpps
      );
      List<Account> allAccountsInHierarchy = websiteDomainToSimilarAccountMap.get(
        domain
      );
      for (Account accountInThisHierarchy : allAccountsInHierarchy) {
        this.accountIdToNumberOfOpenOppsInHierarcyMap.put(
          accountInThisHierarchy.Id,
          newNumberOfOppenOpps
        );
      }
    }
  }

  private Integer getNumberOfOppenOpps(
    Map<String, List<Account>> companyDomainToSimilarAccountMap,
    String domain,
    Integer numberOfOpenOpps
  ) {
    if (companyDomainToSimilarAccountMap.containsKey(domain)) {
      for (
        Account similarAccount : companyDomainToSimilarAccountMap.get(domain)
      ) {
        numberOfOpenOpps += similarAccount.Opportunities.size();
      }
    }
    return numberOfOpenOpps;
  }

  public void finish(Database.BatchableContext param1) {
    Database.executeBatch(
      new UpdateHierarchyOpenOppsActionBatch(
        this.accountIdToNumberOfOpenOppsInHierarcyMap
      ),
      10
    );
  }
}