force-app/main/default/objects/Account/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <description>MIS-2388</description>
    <inlineHelpText>please use https://www.didnotfind.com if no LinkedIn found</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Inferral_Solution_Valid_Criteria_List__c/Inferral_Solution_Valid_Criteria_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution L Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/InferralSolutionCValidCriteriaList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution C Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMap__c/InferralSolutionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Lead</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/InferralSolutionMapContact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Contact</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <inlineHelpText>Link to LinkedIn Profile</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Banking and insurance</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Recruitment and HR</fullName>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/RecordIFrameControllerTest.cls
@isTest
public class RecordIFrameControllerTest {
  @TestSetup
  static void setUp() {
    Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
    iss.Name = 'Default Value';
    iss.Value__c = 'Sales';
    insert iss;

    InferralSolutionMap__c ismTest = new InferralSolutionMap__c();
    ismTest.SW_Industry__c = 'AdTech and AdNetwork';
    ismTest.Department__c = 'BI / Analytics';
    ismTest.Inferred_Solution__c = 'Research';
    ismTest.Name = 'test';
    insert ismTest;

    InferralSolutionMapContact__c ismCTest = new InferralSolutionMapContact__c();
    ismCTest.SW_Industry__c = 'AdTech and AdNetwork';
    ismTest.Department__c = 'BI / Analytics';
    ismCTest.Inferred_Solution__c = 'Research';
    ismCTest.Name = 'test';
    insert ismCTest;

    Inferral_Solution_Valid_Criteria_List__c islvcl = new Inferral_Solution_Valid_Criteria_List__c();
    islvcl.Name = 'department__c';
    islvcl.Is_Valid__c = true;
    insert islvcl;

    Inferral_Solution_Valid_Criteria_List__c islvcl2 = new Inferral_Solution_Valid_Criteria_List__c();
    islvcl2.Name = 'sw_industry__c';
    islvcl2.Is_Valid__c = true;
    insert islvcl2;

    InferralSolutionCValidCriteriaList__c islcvcl = new InferralSolutionCValidCriteriaList__c();
    islcvcl.Name = 'department__c';
    islcvcl.Is_Valid__c = true;
    insert islcvcl;

    InferralSolutionCValidCriteriaList__c islcvcl2 = new InferralSolutionCValidCriteriaList__c();
    islcvcl2.Name = 'sw_industry__c';
    islcvcl2.Is_Valid__c = true;
    insert islcvcl2;
    CSSettings__c cs = TestObjectCreator.CreateCSSettings();
    insert cs;
  }

  @isTest
  static void testGetData_ForAccount() {
    Account acc = new Account(Name = 'Test Account');
    insert acc;

    Test.startTest();
    String iframeUrl = RecordIFrameController.getData(acc.Id);
    Test.stopTest();

    System.assertNotEquals(null, iframeUrl);
    System.assert(
      iframeUrl.contains('/lightning/r/Account/' + acc.Id + '/view')
    );
    System.assert(
      iframeUrl.contains(System.Url.getOrgDomainUrl().toExternalForm())
    );
  }

  @isTest
  static void testGetData_ForLead_NoWebsiteAndLinkedIn() {
    Lead l = TestObjectCreator.CreateLead();
    l.Website = 'no_website';
    l.LinkedIn_Profile__c = 'https://linkedin.com/in/test';
    l.CountryCode = 'US';
    insert l;

    Test.startTest();
    String iframeUrl = RecordIFrameController.getData(l.Id);
    Test.stopTest();

    System.assertNotEquals(null, iframeUrl);
    System.assert(!iframeUrl.contains('no_website'));
    System.assert(iframeUrl.contains('linkedin_url=' + l.LinkedIn_Profile__c));
    System.assert(iframeUrl.contains('country=' + l.CountryCode));
    System.assert(iframeUrl.contains('company_domain='));
  }
}