force-app/main/default/objects/Account/fields/No_Touch_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Touch_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Touch Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_Touch_Status__c.field-meta.xml
<CustomField>
    <fullName>No_Touch_Status__c</fullName>
    <label>No Touch Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/Apex_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to log apex actions on salesforce</description>
    <label>Apex Event Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <description>The calling apex class</description>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <description>The method name where the log came from</description>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <description>Detailed Error message</description>
    <label>Detailed Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Detailed_Information__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Information__c</fullName>
    <description>Record/s informations</description>
    <label>Detailed Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/HTTP_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Endpoint__c</fullName>
    <label>HTTP Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ShareASale_New_Transaction_Response__c.field-meta.xml
<CustomField>
    <fullName>ShareASale_New_Transaction_Response__c</fullName>
    <description>Holds the response from the ShareASale integration</description>
    <label>ShareASale New Transaction Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/No_Touch_Status__c.field-meta.xml
<CustomField>
    <fullName>No_Touch_Status__c</fullName>
    <description>Populated by Pardot (Bisons)
Ticket #1082475</description>
    <label>No Touch Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NT Marketing Solution - Basic Monthly - Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Basic Annual - Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Professional Monthly - Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Professional Annual - Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Basic Monthly After Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Basic Annual After Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Professional Monthly - After Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Professional Annual - After Trial</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Basic Monthly - Cancelled</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Basic Annual - Cancelled</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Professional Monthly - Cancelled</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Professional Annual - Cancelled</fullName>
            </value>
            <value>
                <fullName>NT Marketing Solution - Basic Monthly - After Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>ShareASale tracking number</description>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Pro_User_Type__c.field-meta.xml
<CustomField>
    <fullName>Pro_User_Type__c</fullName>
    <label>Pro User Type Old field</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ShareASale_New_Transaction_Response__c.field-meta.xml
<CustomField>
    <fullName>ShareASale_New_Transaction_Response__c</fullName>
    <description>Holds the response of new transaction to ShareASale</description>
    <label>ShareASale New Transaction Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShareASaleIntegrationTest.cls
/**
 * @author Itzik Winograd
 * @date 10/03/2021
 * @description Test class for ShareASale logging solution
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      -
 * date        -
 * description -
 * --------------------------------------------------------------------------------------
 */
@isTest
public class ShareASaleIntegrationTest {
  /**
   * @author Itzik Winograd
   * @date 11/04/2021
   * @Description Create test prerequisites
   * @param none
   * @return none
   */
  @testSetup
  public static void shareASaleTestSetup() {
    TestDataFactory.createSimilarWeb_CS();
    TestDataFactory.createBaseProductConfiguration_CS();
    TestDataFactory.createInferredSolutionSettings_CS();
    Test.setMock(
      HttpCalloutMock.class,
      new TR_Acc_BusinessUnitCalcTest.MockHttpResponseGenerator()
    );
  }

  /**
   * @author Itzik Winograd
   * @date 11/04/2021
   * @Description Create 15 contacts. Query for Apex_Event_Log__c  records.
   * @Expecte only BATCH_LIMIT log records will be created.
   * Also, assert '178' is part of the called enpoint.
   */
  @isTest
  public static void shareASaleContactsTest() {
    Account acc = AccountUtils.getAccounts(1)[0];
    insert acc;
    //insert some contacts
    List<Contact> cons = ContactUtils.getContacts(15);
    for (Contact con : cons) {
      con.Affiliate_Id__c = '178';
      con.AccountId = acc.Id;
      con.MailingCountry = 'Austria';
    }
    cons[14].Order_Number__c = 'someOrderNumber'; //this will use for phase 2 "reference" call
    cons[14].Pro_User_Type__c = 'User';
    Test.startTest();
    Test.setMock(
      HttpCalloutMock.class,
      new TR_Acc_BusinessUnitCalcTest.MockHttpResponseGenerator()
    );
    insert cons;
    Test.stopTest();

    List<Apex_Event_Log__c> logs = new List<Apex_Event_Log__c>(
      [
        SELECT
          Id,
          Log_Type__c,
          Apex_Class__c,
          Detailed_Information__c,
          Detailed_Error_Message__c,
          Apex_Method__c,
          Http_Endpoint__c
        FROM Apex_Event_Log__c
        WHERE
          Apex_Class__c = 'ShareASaleQuauableCalls'
          AND Apex_Method__c = 'execute'
        //AND Http_Endpoint__c != null
        ORDER BY Apex_Class__c ASC
      ]
    );
    for (Apex_Event_Log__c lg : logs) {
      System.debug('@@@ log: ' + lg);
    }
    Integer BATCH_LIMIT = Integer.valueOf(
      GeneralUtil.getGeneralConfig('ShareASale_Transaction_Batch_Size')
        .Number_Value__c
    );
    System.assertEquals(
      BATCH_LIMIT,
      logs.size(),
      'shareASaleContactsTest Mismatch on the number of logs created'
    );
    System.assert(logs[0].Http_Endpoint__c.contains('178'));
  }

  /**
   * @author Itzik Winograd
   * @date 11/04/2021
   * @Description Test Lead Conversion. Create a lead and convert it.
   * @Expected: Make sure there is only one log record - for the lead and none was created for the contact
   * @param none
   * @return none
   */
  @isTest
  public static void shareASaleLeadConversionTest() {
    Lead myLead = new Lead(
      LastName = 'lastName',
      email = 'testLead@testLead.com',
      Company = 'testComp',
      Country = 'Austria',
      Affiliate_Id__c = '4444'
    );
    Test.setMock(HttpCalloutMock.class, new ShareASaleMock());
    Test.startTest();
    insert myLead;

    //convert lead
    Database.LeadConvert lc = new database.LeadConvert();
    lc.setLeadId(myLead.id);
    LeadStatus convertStatus = [
      SELECT Id, MasterLabel
      FROM LeadStatus
      WHERE IsConverted = TRUE
      LIMIT 1
    ];
    lc.setConvertedStatus(convertStatus.MasterLabel);
    Database.LeadConvertResult lcr = Database.convertLead(lc);
    Test.stopTest();

    System.assert(lcr.isSuccess());
    System.debug(
      '@@@ found contact: ' +
      [
        SELECT Id, Name, Affiliate_Id__c
        FROM Contact
        WHERE email = 'testLead@testLead.com'
      ]
    );
    Lead insertedLead = [
      SELECT Id, Affiliate_Id__c, ShareASale_New_Transaction_Response__c
      FROM Lead
      WHERE Affiliate_Id__c = '4444'
    ][0];
    System.debug('@@@ insertedLead: ' + insertedLead);
    List<Apex_Event_Log__c> logs = new List<Apex_Event_Log__c>(
      [
        SELECT
          Id,
          Log_Type__c,
          Apex_Class__c,
          Detailed_Information__c,
          Detailed_Error_Message__c,
          Apex_Method__c,
          Http_Endpoint__c
        FROM Apex_Event_Log__c
        WHERE Apex_Method__c = 'execute'
        //AND Http_Endpoint__c LIKE '%4444%'
        ORDER BY CreatedDate DESC
      ]
    );
    System.debug('@@@ found logs: ' + logs);
    System.assertEquals(
      1,
      logs.size(),
      '@@@ shareASaleLeadConversionTest mismatch in log amount'
    );
  }

  /**
   * @author Itzik Winograd
   * @date 11/04/2021
   * @Description Test Lead Conversion with error. Create a lead but with ShareASaleMockError
   * @Expected: make sure that the only existing log is of type 'error'.
   * Also expect that the field 'ShareASale_New_Transaction_Response__c' will hold the error recevied.
   * @param none
   * @return none
   */
  @isTest
  public static void shareASaleTestErrorLog() {
    Lead myLead = new Lead(
      LastName = 'lastName',
      email = 'testLead@testLead.com',
      Company = 'testComp',
      Country = 'Austria',
      Affiliate_Id__c = '5555'
    );
    Test.setMock(HttpCalloutMock.class, new ShareASaleMockError());
    Test.startTest();
    insert myLead;
    Test.stopTest();
    Apex_Event_Log__c logRecord = [
      SELECT Id, Apex_Class__c, Apex_Method__c, Http_Endpoint__c, Log_Type__c
      FROM Apex_Event_Log__c
      WHERE Apex_Class__c = 'ShareASaleQuauableCalls'
      //AND Http_Endpoint__c LIKE '%5555%'
      ORDER BY CreatedDate DESC
    ][0];
    System.assertEquals(
      'Error',
      logRecord.Log_Type__c,
      '@@@ shareASaleTestErrorLog mismatch in log type'
    );
    Lead insertedLead = [
      SELECT Id, ShareASale_New_Transaction_Response__c
      FROM Lead
      WHERE Affiliate_Id__c = '5555'
    ][0];
    System.assertEquals(
      'Transaction Failed',
      insertedLead.ShareASale_New_Transaction_Response__c,
      '@@@ shareASaleTestErrorLog mismatch error message'
    );
  }

  /**
   * @author Itzik Winograd
   * @date 02/06/2021
   * @Description test account updated to "after trial successful"
   * and verify that only one shareasale phase-2 record was created.
   */
  @isTest
  public static void shareASaleReferenceTest() {
    Test.setMock(
      HttpCalloutMock.class,
      new TR_Acc_BusinessUnitCalcTest.MockHttpResponseGenerator()
    );
    Account acc = AccountUtils.getAccounts(1)[0];
    acc.No_Touch_Status__c = 'Trial';
    acc.No_Touch_Account__c = true;
    insert acc;
    Contact con = ContactUtils.getContacts(1)[0];
    con.Affiliate_Id__c = '178';
    con.AccountId = acc.Id;
    con.Order_Number__c = 'someOrderNumber'; //this will use for phase 2 "reference" call
    con.Pro_User_Type__c = 'User';
    con.MailingCountry = 'Austria';
    Test.startTest();
    insert con;
    acc.No_Touch_Status__c = 'After Trial, Success';
    update acc;
    Test.stopTest();
    List<Apex_Event_Log__c> logs = new List<Apex_Event_Log__c>(
      [
        SELECT Id, HTTP_Endpoint__c
        FROM Apex_Event_Log__c
        //WHERE HTTP_Endpoint__c LIKE '%reference%'
      ]
    );
    System.assertEquals(
      1,
      logs.size(),
      '@@@ Extra reference logs were found: ' + logs
    );
  }

  /**
   * @author Itzik Winograd
   * @date 30/06/2021
   * @Description Test wrong country name, one that is not in the list.
   * @Expected : no log record will be found
   */
  @isTest
  public static void shareASaleTestWrongCountry() {
    List<Contact> cons = ContactUtils.getContacts(3);
    for (Contact con : cons) {
      con.Affiliate_Id__c = '178';
      con.MailingCountry = 'Neverland';
    }
    Test.startTest();
    insert cons;
    Test.stopTest();
    List<Apex_Event_Log__c> logs = new List<Apex_Event_Log__c>(
      [
        SELECT Id, HTTP_Endpoint__c
        FROM Apex_Event_Log__c
        //WHERE HTTP_Endpoint__c like '%shareasale%'
      ]
    );
    System.assertEquals(
      0,
      logs.size(),
      '@@@ Extra reference logs were found: ' + logs
    );
  }

  /**
   * @author Itzik Winograd
   * @date 10/03/2021
   * @Description Mocks shareASale response, one with error and one without
   */
  public class ShareASaleMock implements System.HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      HttpResponse res = new HttpResponse();
      res.setHeader('ContentType', 'application/json');
      res.setBody('Transaction Created');
      res.setStatusCode(200);
      return res;
    }
  }
  public class ShareASaleMockError implements System.HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      HttpResponse res = new HttpResponse();
      res.setHeader('ContentType', 'application/json');
      res.setBody('Transaction Failed');
      res.setStatusCode(200);
      return res;
    }
  }
}