force-app/main/default/objects/Account/fields/No_Touch_Account__c.field-meta.xml
<CustomField>
    <fullName>No_Touch_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Touch Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NT_Scenario__c.field-meta.xml
<CustomField>
    <fullName>NT_Scenario__c</fullName>
    <label>NT Scenario</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/No_Touch_User__c.field-meta.xml
<CustomField>
    <fullName>No_Touch_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Touch User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/EmailDomain__c/EmailDomain__c.object-meta.xml
<CustomObject>
    <label>Email Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailDomain__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Email_Domains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EmailDomain__c/recordTypes/Enterprise.recordType-meta.xml
<RecordType>
    <fullName>Enterprise</fullName>
    <active>true</active>
    <label>Enterprise</label>
</RecordType>

force-app/main/default/objects/EmailDomain__c/recordTypes/Free.recordType-meta.xml
<RecordType>
    <fullName>Free</fullName>
    <active>true</active>
    <label>Free</label>
</RecordType>

force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/NoTouchProcessTest.cls
/**
 * Created by Alon.Shalev on 1/17/2024.
 */
@isTest
public with sharing class NoTouchProcessTest {

    @testSetup
    static void setup() {
        Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
        iss.Name = 'Default Value';
        iss.Value__c = 'Sales';
        insert iss;
    }


    @isTest
    static void  scenario1Test() {
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Active';
        account.Website = 'TestWebsite@test.com';
        insert account;

        Contact contact = TestDataFactory.createContact(account,email);
        insert contact;

        system.assert(contact.No_Touch_User__c == false);
        Test.startTest();

        NoTouchProcess nt = new NoTouchProcess();
        String accountId = nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);
        Test.stopTest();

        // assert
        Contact contactAfterProcess = [SELECT No_Touch_User__c  FROM Contact WHERE Id =: contact.Id];
        Account acountAfterProcess = [SELECT NT_Scenario__c FROM Account WHERE Id = :accountId];
        System.debug('contactAfterProcess--'+contactAfterProcess);
        system.assertEquals(true,contactAfterProcess.No_Touch_User__c);
        system.assertEquals(acountAfterProcess.NT_Scenario__c,'Scenario 1');

    }
    @isTest
    static void  scenario2Test() {
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Suspended';
        account.Website = 'TestWebsite@test.com';
        insert account;

        Contact contact = TestDataFactory.createContact(account,email);
        contact.MailingCountryCode = 'UA';
        insert contact;

        NoTouchProcess nt = new NoTouchProcess();
        nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);

        // assert
        Account accountAfterProcess = [SELECT No_Touch_Account__c,Name  FROM Account WHERE Id =: account.Id];
        system.assertEquals(true,accountAfterProcess.No_Touch_Account__c);
        system.assertEquals(true,accountAfterProcess.Name.contains('No Touch'));


    }
    @isTest
    static void  scenario3Test() {
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Suspended';
        insert account;

        Lead lead = TestDataFactory.createLead();
        lead.Email = email;
        insert lead;

        EmailDomain__c ed = new EmailDomain__c();
        ed.Name = 'gmail.com';
        ed.RecordTypeId = Schema.SObjectType.EmailDomain__c.getRecordTypeInfosByName().get('Enterprise').getRecordTypeId();
        ed.User__c = UserInfo.getUserId();
        insert ed;

        NoTouchProcess nt = new NoTouchProcess();
        String accountId = nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);

        // assert
        Lead leadAfterConvert = [SELECT IsConverted  FROM Lead WHERE Id =: lead.Id];
        Account accountAfterProcess = [SELECT Id,No_Touch_Account__c FROM Account WHERE Id =: accountId];
        System.assert(true,leadAfterConvert.IsConverted);
        system.assertEquals(true,accountAfterProcess.No_Touch_Account__c);
//        system.assertEquals(true,accountAfterProcess.Name.contains('No Touch'));

    }
    @isTest
    static void  scenario4Test() {//this.existingAccount.Status__c == 'Active'
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Active';
        account.BillingCountryCode = 'IS';
        account.Website = 'Ikea.com';
        insert account;

        Lead lead = TestDataFactory.createLead();
        lead.Email = email;
        insert lead;

        EmailDomain__c ed = new EmailDomain__c();
        ed.Name = 'gmail.com';
        ed.RecordTypeId = Schema.SObjectType.EmailDomain__c.getRecordTypeInfosByName().get('Enterprise').getRecordTypeId();
        ed.User__c = UserInfo.getUserId();
        insert ed;

        NoTouchProcess nt = new NoTouchProcess();
        String accountId = nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);

        // assert
        Lead leadAfterConvert = [SELECT IsConverted  FROM Lead WHERE Id =: lead.Id];
        Account accountAfterProcess = [SELECT Id,No_Touch_Account__c,ParentId FROM Account WHERE Id =: accountId];
        System.assert(true,leadAfterConvert.IsConverted);
        system.assertEquals(true,accountAfterProcess.No_Touch_Account__c);
        system.assertEquals(account.Id,accountAfterProcess.ParentId);
//        system.assertEquals(true,accountAfterProcess.Name.contains('No Touch'));

    }
    @isTest
    static void  scenario5Test() {//this.existingAccount.Status__c != 'Active'
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Suspended';
        account.BillingCountryCode = 'IS';
        account.Website = 'Ikea.com';
        insert account;

        Lead lead = TestDataFactory.createLead();
        lead.Email = email;
        insert lead;

        EmailDomain__c ed = new EmailDomain__c();
        ed.Name = 'gmail.com';
        ed.RecordTypeId = Schema.SObjectType.EmailDomain__c.getRecordTypeInfosByName().get('Enterprise').getRecordTypeId();
        ed.User__c = UserInfo.getUserId();
        insert ed;

        NoTouchProcess nt = new NoTouchProcess();
        String accountId = nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);
        String response = '{"response": {"status": "Success", "message": "", "accountId": "'+accountId+'" }}';
        nt.recordLog(true,response,accountId);

        // assert
        Lead leadAfterConvert = [SELECT IsConverted  FROM Lead WHERE Id =: lead.Id];
        Account accountAfterProcess = [SELECT Id,No_Touch_Account__c,ParentId FROM Account WHERE Id =: accountId];
        System.assert(true,leadAfterConvert.IsConverted);
        system.assertEquals(true,accountAfterProcess.No_Touch_Account__c);
//        system.assertEquals(true,accountAfterProcess.Name.contains('No Touch'));

    }
    @isTest
    static void  scenario6Test() {
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Suspended';
        insert account;

        Contact contact = TestDataFactory.createContact(account,email);
        contact.MailingCountryCode = 'UA';
        insert contact;

        EmailDomain__c ed = new EmailDomain__c();
        ed.Name = 'gmail.com';
        ed.RecordTypeId = Schema.SObjectType.EmailDomain__c.getRecordTypeInfosByName().get('Free').getRecordTypeId();
        ed.User__c = UserInfo.getUserId();
        insert ed;

        NoTouchProcess nt = new NoTouchProcess();
        nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);

        // assert
        Account accountAfterProcess = [SELECT No_Touch_Account__c,Name  FROM Account WHERE Id =: account.Id];
//        system.assertEquals(true,accountAfterProcess.No_Touch_Account__c);
//        system.assertEquals(true,accountAfterProcess.Name.contains('No Touch'));

    }
    @isTest
    static void  scenario7Test() {

        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);

        Account account = TestDataFactory.createAccount();
        account.Status__c = 'Suspended';
        account.BillingCountryCode = 'IS';
        account.Website = 'Ikea.com';
        insert account;

        Lead lead = TestDataFactory.createLead();
        lead.Email = email;
        insert lead;

        EmailDomain__c ed = new EmailDomain__c();
        ed.Name = 'gmail.com';
        ed.RecordTypeId = Schema.SObjectType.EmailDomain__c.getRecordTypeInfosByName().get('Free').getRecordTypeId();
        ed.User__c = UserInfo.getUserId();
        insert ed;

        NoTouchProcess nt = new NoTouchProcess();
        String accountId = nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);

        // assert
        Lead leadAfterConvert = [SELECT IsConverted  FROM Lead WHERE Id =: lead.Id];
        Account accountAfterProcess = [SELECT Id,No_Touch_Account__c,ParentId FROM Account WHERE Id =: accountId];
        System.assert(true,leadAfterConvert.IsConverted);
        system.assertEquals(true,accountAfterProcess.No_Touch_Account__c);
//        system.assertEquals(true,accountAfterProcess.Name.contains('No Touch'));

    }
    @isTest
    static void  scenario8Test() {
        String uid;
        String email = 'alonTest@gmail.com';
        string cname = 'alonCompany';
        string fName = 'test';
        String lName = 'tewst ';
        String country = 'IS';
        String websiteDomain = 'Ikea.com';
        String industry = 'Agency';
        String minEmployees = '100';
        String maxEmployees = '500';
        Date todayDate = Date.today();
        String todayDateString = String.valueOf(todayDate);
        NoTouchProcess nt = new NoTouchProcess();
        String accountId = nt.handleNoTouch(uid,email,cname,fName,lName,country,websiteDomain,industry,minEmployees,maxEmployees,todayDateString,0);
        //assert
        List<Account> accountCreated = [SELECT Id FROM Account WHERE Id =:accountId];
        system.assertEquals(false,accountCreated.isEmpty());


    }

}