force-app/main/default/objects/Account/fields/Number_Of_Open_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Open_Meetings__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Open Meetings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <description>Disclaimer:
Record type = who created the meeting
Owner = who got the meeting</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meetings__c.field-meta.xml
<CustomField>
    <fullName>Meetings__c</fullName>
    <description>Used in report to generate a list of # meetings per user, even if no meeting exists</description>
    <formula>VALUE(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label># Meetings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>In MIR, SDR and Sales Meetings - use the &quot;Complete Meeting&quot; Button at the top of the page</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Rescheduling</fullName>
            </value>
            <value>
                <fullName>Scheduling in Progress</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountMeetingRollupBatch.cls
public class AccountMeetingRollupBatch implements Database.Batchable<sObject>, Schedulable {
  private final Integer BATCH_SCOPE_SIZE;

  public AccountMeetingRollupBatch() {
    this.BATCH_SCOPE_SIZE = 50;
  }

  public AccountMeetingRollupBatch(Integer batchScopeSize) {
    this.BATCH_SCOPE_SIZE = batchScopeSize;
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      'SELECT Id, Number_Of_Open_Meetings__c, ' +
        '(SELECT Id, Account__c, Status__c FROM Meetings__r) ' +
        'FROM Account'
    );
  }

  public void execute(Database.BatchableContext bc, List<Account> records) {
    List<Account> accountsToUpdate = new List<Account>();
    for (Account acc_i : records) {
      Integer numOfOpenMeetings = 0;
      if (acc_i.Meetings__r != null) {
        for (Meeting__c meet_i : acc_i.Meetings__r) {
          Boolean isActive =
            meet_i.Status__c == 'Pending' ||
            meet_i.Status__c == 'In Progress' ||
            meet_i.Status__c == 'Rescheduling';
          if (isActive) {
            numOfOpenMeetings++;
          }
        }
      }
      if (acc_i.Number_Of_Open_Meetings__c != numOfOpenMeetings) {
        acc_i.Number_Of_Open_Meetings__c = numOfOpenMeetings;
        accountsToUpdate.add(acc_i);
      }
    }
    Database.update(accountsToUpdate, false);
  }

  public void finish(Database.BatchableContext bc) {
  }

  public void execute(SchedulableContext sc) {
    AccountMeetingRollupBatch batch = new AccountMeetingRollupBatch();
    Database.executeBatch(batch, this.BATCH_SCOPE_SIZE);
  }
}