force-app/main/default/objects/Account/fields/Number_Of_Open_Meetings__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Open_Meetings__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Open Meetings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <description>Disclaimer:
Record type = who created the meeting
Owner = who got the meeting</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>In MIR, SDR and Sales Meetings - use the &quot;Complete Meeting&quot; Button at the top of the page</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Rescheduling</fullName>
            </value>
            <value>
                <fullName>Scheduling in Progress</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountMeetingRollupBatchTest.cls
@isTest
private class AccountMeetingRollupBatchTest {

    static final Integer ACCOUNT_NUM = 10;
    static final Integer MEETING_PER_ACCOUNT_NUM = 5;

    @testSetup 
    static void setup() {
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createInferredSolutionSettings_CS();

        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < ACCOUNT_NUM; i++) {
            accounts.add(TestDataFactory.createAccount());
        }
        insert accounts;
        List<Meeting__c> meetings = new List<Meeting__c>();
        for (Account acc_i : accounts) {
            for (Integer i = 0; i < MEETING_PER_ACCOUNT_NUM; i++) {
                meetings.add(
                    new Meeting__c(
                        Account__c = acc_i.Id,
                        Status__c = 'Rescheduling'
                    )
                );
            }
        }
        insert meetings;
    }

    @isTest 
    static void testBatch() {
        AccountMeetingRollupBatch batch = new AccountMeetingRollupBatch();
        Test.startTest();
        Database.executeBatch(batch, 50);
        Test.stopTest();
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Number_Of_Open_Meetings__c FROM Account]);
        List<Meeting__c> meetingList = [SELECT Id, Account__c, Status__c FROM Meeting__c WHERE Account__c IN :accountMap.keySet()];
        Map<Id, List<Meeting__c>> accountToMeetingsMap = new Map<Id, List<Meeting__c>>();
        for (Meeting__c meet_i : meetingList) {
            if (accountToMeetingsMap.get(meet_i.Account__c) == null) {
                accountToMeetingsMap.put(meet_i.Account__c, new List<Meeting__c>());
            }
            accountToMeetingsMap.get(meet_i.Account__c).add(meet_i);
        }
        for (Id accId_i : accountToMeetingsMap.keySet()) {
            Account acc_i = accountMap.get(accId_i);
            List<Meeting__c> meetings_i = accountToMeetingsMap.get(accId_i);
            System.assertEquals(acc_i.Number_Of_Open_Meetings__c, meetings_i.size());
        }
    }

    @isTest
    static void testScheduler() {
        AccountMeetingRollupBatch batch = new AccountMeetingRollupBatch();
        Test.startTest();
        System.schedule('AccountMeetingRollupBatch', '0 0 8 * * ?', batch);
        Test.stopTest();
    }

    @isTest
    static void testScheduler_batchScopeConfig() {
        AccountMeetingRollupBatch batch = new AccountMeetingRollupBatch(100);
        Test.startTest();
        System.schedule('AccountMeetingRollupBatch', '0 0 8 * * ?', batch);
        Test.stopTest();
    }
}