force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/Manage_Users_Log__c.object-meta.xml
<CustomObject>
    <description>Logs for Manage Users automations,
PRD: https://docs.google.com/document/d/1L2NtEfWzvR9L8EdccQNR9jf1R34oiWkhlTouKkb2pCk/edit?usp=sharing</description>
    <label>Manage Users Log</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Manage Users Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manage Users Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manage_Users_Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The Action requested in the process</description>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deactivate</fullName>
                <default>true</default>
                <label>Deactivate</label>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Role Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Date_For_Action__c.field-meta.xml
<CustomField>
    <fullName>Date_For_Action__c</fullName>
    <description>The requested date to run the action.</description>
    <inlineHelpText>The requested date to run the action.</inlineHelpText>
    <label>Date For Action</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manage_Users_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The User that needs to be updated</description>
    <inlineHelpText>The User that needs to be updated</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Manage_Users_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <description>Disclaimer:
Record type = who created the meeting
Owner = who got the meeting</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>In MIR, SDR and Sales Meetings - use the &quot;Complete Meeting&quot; Button at the top of the page</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Rescheduling</fullName>
            </value>
            <value>
                <fullName>Scheduling in Progress</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountOwnerFromInactiveUsersBatch.cls
/**
 * Created by Alon.Shalev on 3/4/2024.
 */

public with sharing class AccountOwnerFromInactiveUsersBatch implements Database.Batchable<sObject> ,Schedulable,Database.Stateful{

    Set<Id> accountIdSet = new Set<Id>();
    Set<Id> meetingIdSet = new Set<Id>();
    Set<Id> territoryIdSet = new Set<Id>();

    public void execute (SchedulableContext SC){
        AccountOwnerFromInactiveUsersBatch batch = new AccountOwnerFromInactiveUsersBatch();
        Database.executeBatch(batch,1);
    }

    public Database.QueryLocator start (Database.BatchableContext BC){

        String deactivateAction = 'Deactivate';
        String query = 'SELECT User__c,Status__c,Action__c,Date_For_Action__c' +
                        ' FROM Manage_Users_Log__c' +
                        ' WHERE Action__c =: deactivateAction ' +
                        ' AND Date_For_Action__c = YESTERDAY';
        return Database.getQueryLocator(query);


    }

    public void execute(Database.BatchableContext BC, List<Manage_Users_Log__c> scope){
        Set<Id> userIdSet = new Set<Id>();

        for(Manage_Users_Log__c manageLog : scope){
            userIdSet.add(manageLog.User__c);
        }
        List<Account> ownerAccountList = [SELECT Id FROM Account WHERE OwnerId IN: userIdSet];
        for(Account acc : ownerAccountList){
            accountIdSet.add(acc.Id);
        }
        Set<String> openMeetingsStatus = new Set<String>();
        openMeetingsStatus.add('Rescheduling');
        openMeetingsStatus.add('Scheduling in Progress');
        openMeetingsStatus.add('Placeholder');
        openMeetingsStatus.add('In Progress');
        openMeetingsStatus.add('Pending');
        List<Meeting__c> ownerMeetingList = [SELECT Id FROM Meeting__c WHERE OwnerId IN :userIdSet AND Status__c IN : openMeetingsStatus];
        for(Meeting__c meeting : ownerMeetingList){
            meetingIdSet.add(meeting.Id);
        }

        for(Territory__c terr : [SELECT Id FROM Territory__c WHERE OwnerId IN : userIdSet]){
            territoryIdSet.add(terr.Id);
        }
        System.debug([SELECT Count(id) FROM Territory__c WHERE OwnerId IN : userIdSet] +' asdasdasdasd');

    }



    public void finish(Database.BatchableContext BC){
        Database.executeBatch(new UpdateAccountOwnerBatch(accountIdSet),3);
        Database.executeBatch(new UpdateMeetingOwnerBatch(meetingIdSet),3);
        Database.executeBatch(new UpdateTerritoryOwnerBatch(territoryIdSet),3);
    }

}