force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
                <isActive>false</isActive>
                <label>CAD</label>
            </value>
            <value>
                <fullName>ILS</fullName>
                <isActive>false</isActive>
                <label>ILS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Applicable_Quote__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Quote__c</fullName>
    <label>Applicable Quote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>#1113520</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#1113759 populates manually</description>
    <label>Quote</label>
    <referenceTo>zqu__Quote__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Recipient_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Picklist__c</fullName>
    <label>Recipient</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aaron Feinblatt</fullName>
            </value>
            <value>
                <fullName>Aaron Wong</fullName>
            </value>
            <value>
                <fullName>Adam Wertheim</fullName>
            </value>
            <value>
                <fullName>Aidan Krakowsky</fullName>
            </value>
            <value>
                <fullName>Alexandre Koniecko</fullName>
            </value>
            <value>
                <fullName>Alex Donchenko</fullName>
            </value>
            <value>
                <fullName>Alex Donchenko (PS)</fullName>
            </value>
            <value>
                <fullName>Alisha Kapur</fullName>
            </value>
            <value>
                <fullName>Amit Ram</fullName>
            </value>
            <value>
                <fullName>Anand Ramanathan</fullName>
            </value>
            <value>
                <fullName>Anastasia Segal</fullName>
            </value>
            <value>
                <fullName>Andrea Girardello</fullName>
            </value>
            <value>
                <fullName>Andrew Bonnici</fullName>
            </value>
            <value>
                <fullName>Andrew Liu</fullName>
            </value>
            <value>
                <fullName>Anne-Christele Antoine</fullName>
            </value>
            <value>
                <fullName>Antonello Musina</fullName>
            </value>
            <value>
                <fullName>Aria Ertefaie</fullName>
            </value>
            <value>
                <fullName>Ariane Turley</fullName>
            </value>
            <value>
                <fullName>Ariel Even</fullName>
            </value>
            <value>
                <fullName>Ariella Magid</fullName>
            </value>
            <value>
                <fullName>Ariyeh Taitz</fullName>
            </value>
            <value>
                <fullName>Audrey Guilloux</fullName>
            </value>
            <value>
                <fullName>Aurore Miniatura</fullName>
            </value>
            <value>
                <fullName>Banke daCosta</fullName>
            </value>
            <value>
                <fullName>Becca Edelman</fullName>
            </value>
            <value>
                <fullName>Becca Edelman (EMEA)</fullName>
            </value>
            <value>
                <fullName>Becka Abram (M)</fullName>
            </value>
            <value>
                <fullName>Belinda Kwok</fullName>
            </value>
            <value>
                <fullName>Ben Fernando (EMEA)</fullName>
            </value>
            <value>
                <fullName>Ben Fernando (VAP)</fullName>
            </value>
            <value>
                <fullName>Chris Foale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>&quot;Bill to&quot;/&quot;Sold to&quot; Information</fullName>
            </value>
            <value>
                <fullName>Account Configuration</fullName>
            </value>
            <value>
                <fullName>Account Maintenance/Value</fullName>
            </value>
            <value>
                <fullName>Add SOW (for Advisory Services/Managed Services/DaaS)</fullName>
            </value>
            <value>
                <fullName>Ad Hoc Training</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>API Dashboard</fullName>
            </value>
            <value>
                <fullName>API Integration</fullName>
            </value>
            <value>
                <fullName>Apps Android - Accuracy</fullName>
            </value>
            <value>
                <fullName>Apps Android - Coverage</fullName>
            </value>
            <value>
                <fullName>Apps IOS - Accuracy</fullName>
            </value>
            <value>
                <fullName>Apps IOS - Coverage</fullName>
            </value>
            <value>
                <fullName>Growth</fullName>
                <label>Basic Onboarding Package</label>
            </value>
            <value>
                <fullName>Best Practice Webinar</fullName>
            </value>
            <value>
                <fullName>Account Update request</fullName>
                <label>Billing Account Update Request</label>
            </value>
            <value>
                <fullName>Campaign Feature Upsell</fullName>
            </value>
            <value>
                <fullName>Campaign Trial</fullName>
            </value>
            <value>
                <fullName>Change Start/End Date</fullName>
            </value>
            <value>
                <fullName>Churn Prevention</fullName>
            </value>
            <value>
                <fullName>Client Breach</fullName>
            </value>
            <value>
                <fullName>Client Call (Not specific to a project)</fullName>
            </value>
            <value>
                <fullName>Client Red Lines</fullName>
            </value>
            <value>
                <fullName>Code of Conduct</fullName>
            </value>
            <value>
                <fullName>Conditional Trial</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Contact Data</fullName>
            </value>
            <value>
                <fullName>Contract Review request</fullName>
                <label>Contract Review Request</label>
            </value>
            <value>
                <fullName>Customer Success Plan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requester</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Signed_contract__c.field-meta.xml
<CustomField>
    <fullName>Signed_contract__c</fullName>
    <description>#1113520</description>
    <inlineHelpText>Attach the contract to the opportunity if yes</inlineHelpText>
    <label>Signed contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Ticket_number_in_Zendesk__c.field-meta.xml
<CustomField>
    <fullName>Ticket_number_in_Zendesk__c</fullName>
    <description>Populates only for Vendor_form at the moment</description>
    <label>Ticket number in Zendesk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Zuora_Account_number__c.field-meta.xml
<CustomField>
    <fullName>Zuora_Account_number__c</fullName>
    <label>Zuora Account number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Legal_Services.recordType-meta.xml
<RecordType>
    <fullName>Legal_Services</fullName>
    <active>false</active>
    <label>Legal Services</label>
</RecordType>

force-app/main/default/classes/RequestDomainTest.cls
@isTest
public class RequestDomainTest {
    @TestSetup
    static void setup(){
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createBaseProductConfiguration_CS();
        TestDataFactory.createInferredSolutionSettings_CS();
        insert TestDataFactory.createBaseProductContract_CS();
        insert TestDataFactory.createBaseProductConfiguration_CS();
        insert TestDataFactory.createBaseProductControlling_CS();
        insert TestDataFactory.createBaseProductDependent_CS();     
        insert TestDataFactory.createBaseProductDefaultAddon_CS();
        insert TestDataFactory.createBaseProductDynamicAddon_CS();
        insert TestDataFactory.createBaseProductNumOfUsers_CS();

        Account a = TestDataFactory.CreateAccount();
        a.billingcountry = 'Israel';
        insert a;
        Contact c = TestDataFactory.CreateContact(a, 'test@testing.com');
        c.MailingCountry = 'Israel';
        insert c;
        Opportunity opp = TestDataFactory.CreateOpportunity (a);
        opp.Type='New Sale';
        insert opp;             
    }

    @isTest
    static void createTicketTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        Request__c rquest = TestDataFactory.createRequest(opp);
        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        insert rquest;
        RequestDomain.createTicket(new List<Request__c>{rquest});
        Test.stopTest();
    }

    @isTest
    static void updateAccountNumberTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        Zuora__CustomerAccount__c zuoraAcc = TestDataFactory.createBillingAccount(account);
        insert zuoraAcc;
        Request__c rquest = TestDataFactory.createRequest(opp);
        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        insert rquest;
        RequestDomain.createTicket(new List<Request__c>{rquest});
        Test.stopTest();
        rquest = [SELECT Id, Zuora_Account_number__c FROM Request__c LIMIT 1];
        System.assert(String.isNotBlank(rquest.Zuora_Account_number__c));

    }

    @isTest
    static void checkUnsupportedRequestTypeTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        Zuora__CustomerAccount__c zuoraAcc = TestDataFactory.createBillingAccount(account);
        insert zuoraAcc;
        Request__c rquest = TestDataFactory.createRequest(opp);
        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        rquest.Request_Type__c = 'Other';
        insert rquest;
        Test.stopTest();
        rquest = [SELECT Id, Ticket_number_in_Zendesk__c FROM Request__c LIMIT 1];
        System.assertEquals('Error: Unsupported request type', rquest.Ticket_number_in_Zendesk__c);
    }

    @isTest
    static void RequestTypeIsNullTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        Zuora__CustomerAccount__c zuoraAcc = TestDataFactory.createBillingAccount(account);
        insert zuoraAcc;
        Request__c rquest = TestDataFactory.createRequest(opp);
        Test.startTest();
        rquest.Request_Type__c = null;
        try{
            insert rquest;
        }catch(Exception e){
            System.assert(e.getMessage().contains('Request Type cannot be null'));
        }
        Test.stopTest();
    }

    @isTest
    static void updateRequestStatusTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        zqu__Quote__c quote = TestDataFactory.createZQuote(opp);
        insert quote;
        Request__c rquest = new Request__c();
        rquest.Requester__c = UserInfo.getUserId();
        rquest.Recipient_Picklist__c = 'Chris Foale';
        rquest.Applicable_Quote__c = 'Yes';
        rquest.Opportunity__c = opp.Id;
        rquest.Account__c = opp.AccountId;
        rquest.Quote__c = quote.id;
        rquest.Signed_contract__c = 'Yes';
        rquest.Currency__c = 'USD';
        rquest.Request_Type__c = 'Other';
        rquest.RecordTypeId = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Legal_Services').getRecordTypeId();
        

        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        insert rquest;
        RequestDomain.createTicket(new List<Request__c>{rquest});
        rquest.Status__c = 'Completed';
        rquest.Green_Lane_Document__c = true;
        update rquest;
        Test.stopTest();

    }

    @isTest
    static void updateRelatedQuoteOnUpdateTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        zqu__Quote__c quote = TestDataFactory.createZQuote(opp);
        insert quote;
        Request__c rquest = getLegalServiceRequest(opp,quote);
        Request__c rq = getLegalServiceRequest(opp,quote);

        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        insert rquest;
        insert rq;
        RequestDomain.createTicket(new List<Request__c>{rquest});
        RequestDomain.createTicket(new List<Request__c>{rq});
        rquest.Status__c = 'Completed';
        update rquest;
        update rq;
        Test.stopTest();
    }

    @isTest
    static void updateRelatedQuoteOnUpdateGLTest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        zqu__Quote__c quote = TestDataFactory.createZQuote(opp);
        insert quote;
        Request__c rquest = getLegalServiceRequest(opp,quote);
        Request__c rq = getLegalServiceRequest(opp,quote);

        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        insert rquest;
        insert rq;
        RequestDomain.createTicket(new List<Request__c>{rquest});
        RequestDomain.createTicket(new List<Request__c>{rq});
        rquest.Status__c = 'Completed';
        rquest.Green_Lane_Document__c = true;
        update rquest;
        Test.stopTest();
        rq.Green_Lane_Document__c = true;
        rq.Status__c = 'Completed';
        update rq;
    }
    
    @isTest
    public static void testLegalServiceRequest(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        opp.SalesLoft1__Primary_Contact__c = [SELECT Id FROM Contact LIMIT 1].Id;
        update opp;
        zqu__Quote__c quote = TestDataFactory.createZQuote(opp);
        insert quote;
        Request__c rq = getLegalServiceRequest(opp,quote);
        MockUtil.ZendeskIntegrationServiceHttpMock mock = new MockUtil.ZendeskIntegrationServiceHttpMock();
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        	insert rq;
            rq.Ticket_number_in_Zendesk__c = null;
            rq.Status__c = 'Pending update from Billing';
            update rq;
        Test.stopTest();
        
        
    }
    
    public static Request__c getLegalServiceRequest(Opportunity opp, zqu__Quote__c quote){
        Request__c rq = new Request__c();
        rq.Requester__c = UserInfo.getUserId();
        rq.Recipient_Picklist__c = 'Chris Foale';
        rq.Applicable_Quote__c = 'Yes';
        rq.Opportunity__c = opp.Id;
        rq.Account__c = opp.AccountId;
        rq.Quote__c = quote.id;
        rq.Signed_contract__c = 'Yes';
        rq.Currency__c = 'USD';
        rq.Request_Type__c = 'Other';
        rq.RecordTypeId = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Legal_Services').getRecordTypeId();
        return rq;
    }
}