force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department you work at in Similarweb</inlineHelpText>
    <label>Department</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Development</fullName>
            </value>
            <value>
                <fullName>Demand Generation</fullName>
            </value>
            <value>
                <fullName>Product Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MQL__c.field-meta.xml
<CustomField>
    <fullName>MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateLeadCntMQLBatchTest.cls
@istest
public class UpdateLeadCntMQLBatchTest {
  @istest
  public static void test() {
    Account acc = new Account(Name = 'Test acc');
    insert acc;
    Account acc2 = new Account(Name = 'SimilarWEB');
    insert acc2;

    Contact cnt1 = new Contact(
      AccountId = acc.Id,
      LastName = 'Test',
      Status__c = 'Unqualified',
      HasOptedOutOfEmail = false
    ); //should not pass in processing as status not valid
    Contact cnt2 = new Contact(
      AccountId = acc2.Id,
      LastName = 'Test2',
      Status__c = 'Qualified',
      HasOptedOutOfEmail = false
    ); //should not pass in processing as account name not valid
    Contact cnt3 = new Contact(
      AccountId = acc.Id,
      LastName = 'Test3',
      Status__c = 'Qualified',
      HasOptedOutOfEmail = false
    ); //should pass
    Contact cnt4 = new Contact(
      AccountId = acc.Id,
      LastName = 'Test3',
      Status__c = 'Qualified',
      HasOptedOutOfEmail = false,
      MQL__c = true
    );

    Lead ld1 = new Lead(
      Company = 'Similarweb',
      LastName = 'Lead1',
      Status = 'Unqualified',
      HasOptedOutOfEmail = false
    );
    Lead ld2 = new Lead(
      Company = 'Test',
      LastName = 'Lead2',
      Status = 'Unqualified',
      HasOptedOutOfEmail = false
    );
    Lead ld3 = new Lead(
      Company = 'Test',
      LastName = 'Lead3',
      Status = 'Qualified',
      HasOptedOutOfEmail = false
    ); //should pass
    Lead ld4 = new Lead(
      Company = 'Test',
      LastName = 'Lead4',
      Status = 'Qualified',
      HasOptedOutOfEmail = false,
      MQL__c = true
    );

    insert new List<Sobject>{ cnt1, cnt2, cnt3, cnt4, ld1, ld2, ld3, ld4 };

    Campaign cmp = new Campaign(Name = 'Test CMP', Department__c = 'Marketing');
    insert cmp;

    List<CampaignMember> members = new List<CampaignMember>{
      new CampaignMember(
        ContactId = cnt1.Id,
        Rating__c = 4,
        CampaignId = cmp.Id
      ),
      new CampaignMember(
        ContactId = cnt2.Id,
        Rating__c = 5,
        CampaignId = cmp.Id
      ),
      //new CampaignMember(ContactId=cnt3.Id, Rating__c = 2, CampaignId = cmp.Id), 		//should not pass as ratng low
      new CampaignMember(
        ContactId = cnt3.Id,
        Rating__c = 4,
        CampaignId = cmp.Id
      ), //should pass
      new CampaignMember(
        ContactId = cnt4.Id,
        Rating__c = 4,
        CampaignId = cmp.Id
      ),
      new CampaignMember(LeadId = ld1.Id, Rating__c = 4, CampaignId = cmp.Id),
      new CampaignMember(LeadId = ld2.Id, Rating__c = 4, CampaignId = cmp.Id),
      //new CampaignMember(LeadId=ld3.Id, Rating__c = 1, CampaignId = cmp.Id),
      new CampaignMember(LeadId = ld3.Id, Rating__c = 5, CampaignId = cmp.Id), //should pass
      new CampaignMember(LeadId = ld4.Id, Rating__c = 5, CampaignId = cmp.Id)
    };
    insert members;

    Test.startTest();
    String query =
      'select id, ContactId, Contact.MQL__c, LeadId, Lead.MQL__c, Rating__c, Contact.Status__c, Lead.Status, CompanyOrAccount, ' +
      'Contact.HasOptedOutOfEmail, Contact.Account.Name, Lead.HasOptedOutOfEmail, Lead.Company from CampaignMember ' +
      'where (Rating__c = 4 or Rating__c = 5) and ((Contact.MQL__c = false and Contact.Status__c !=  \'Unqualified\' and Contact.HasOptedOutOfEmail = false )' +
      ' or ( Lead.MQL__c = false and Lead.Status != \'Unqualified\' and Lead.HasOptedOutOfEmail = false))  and CompanyOrAccount != \'SimilarWeb\'';
    System.debug('s ' + Database.query(query));
    Database.executeBatch(new UpdateLeadCntMQLBatch());
    Test.stopTest();

    List<Contact> updatedCnt = [
      SELECT id, MQL__c, LastName
      FROM Contact
      WHERE MQL__c = TRUE
      ORDER BY lastname
    ];
    System.assertEquals(2, updatedCnt.size());
    System.assertEquals(updatedCnt[0].Lastname, 'Test3');
  }
}