force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Part Of Another Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Member_Of_5_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Member_Of_5_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Member Of 5* Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>SDR Prospecting</fullName>
            </value>
            <value>
                <fullName>SDR Converted</fullName>
            </value>
            <value>
                <fullName>Sales Contacted</fullName>
            </value>
            <value>
                <fullName>Sales Prospecting</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Post Demo</fullName>
            </value>
            <value>
                <fullName>MIR Prospecting</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Automated Prospecting</fullName>
            </value>
            <value>
                <fullName>Automated Education</fullName>
            </value>
            <value>
                <fullName>Automated Re-engagement</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Automated Onboarding</fullName>
            </value>
            <value>
                <fullName>Do not contact</fullName>
                <label>Do Not Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MQL__c.field-meta.xml
<CustomField>
    <fullName>MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateLeadCntMQLBatch.cls
global class UpdateLeadCntMQLBatch implements Database.Batchable<sObject>, Schedulable{

    String query;
    
    global UpdateLeadCntMQLBatch(){
		        
    }
    
    global void execute(SchedulableContext SC) {
        Database.executeBatch(new UpdateLeadCntMQLBatch());
    }
    
    global Database.QueryLocator start (Database.BatchableContext BC){
        query = 'select id, ContactId, Contact.MQL__c, LeadId, Lead.MQL__c, Rating__c, Contact.Status__c, Contact.Name, Lead.Name, Lead.Status, CompanyOrAccount, ' + 
            	'Contact.HasOptedOutOfEmail, Contact.Account.Name, Lead.HasOptedOutOfEmail, Lead.Company from CampaignMember '+ 
            	'where (Rating__c = 4 or Rating__c = 5) and ((Contact.MQL__c = false and Contact.Status__c !=  \'Unqualified\' and Contact.HasOptedOutOfEmail = false )' +
            	' or ( Lead.MQL__c = false and Lead.Status != \'Unqualified\' and Lead.HasOptedOutOfEmail = false))  and CompanyOrAccount != \'SimilarWeb\'';
        System.debug('start');
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<CampaignMember> scope){
        System.debug('scopr ' + scope);
        List<Contact> contactsToUpdate = new List<Contact>();
        List<Lead> leadsToUpdate = new List<Lead>();
        for (CampaignMember member : scope) {
            if (member.Contact != null && !member.Contact.MQL__c && member.Contact.Status__c != 'Unqualified') {
                contactsToUpdate.add(new Contact(Id = member.ContactId, MQL__c  = true, Member_Of_5_Campaign__c = true));
            } 
            if (member.Lead != null && !member.Lead.MQL__c && member.Lead.Status != 'Unqualified') {
                leadsToUpdate.add(new Lead(Id = member.LeadId, MQL__c  = true));
            }
        }
            System.debug('leadsToUpdate ' + leadsToUpdate );
            System.debug('contactsToUpdate ' + contactsToUpdate );
        if (!contactsToUpdate.isEmpty() )
            update contactsToUpdate;
        if (!leadsToUpdate.isEmpty() )
            update leadsToUpdate;
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}