force-app/main/default/objects/Account/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <formula>BI_Data__r.Sub_Division_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROE Sub Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/BI_Data__c.object-meta.xml
<CustomObject>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Re_evaluate__c.field-meta.xml
<CustomField>
    <fullName>Re_evaluate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for re-evaluating territories at the daily batch</description>
    <label>Re-evaluate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <description>Works with Custom Metadata - &quot;User Sub Motion&quot; - Make sure to update the metadata if the values in this field are changed</description>
    <label>Owner Sub Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agencies &amp; Consultancies</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>APAC Strategic</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Go To Market</fullName>
            </value>
            <value>
                <fullName>India Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>LLM &amp; AI</fullName>
            </value>
            <value>
                <fullName>Meta/MSFT</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil - 108</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil - Alpha</fullName>
            </value>
            <value>
                <fullName>Reseller - Vietnam - AMS JSC</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActivateUnMappedAccountOfTerritoryTest.cls
/**
 * Created by Alon.Shalev on 11/7/2022.
 */
@istest
public with sharing class ActivateUnMappedAccountOfTerritoryTest {

    /**
     * @description test setup, create a Territory and an Account with the same territory
     * */
    @testSetup
    public static void setup(){
        System.runAs(getUser()) {
            String INDUSTRY = 'Education';
            String SUB_DIVISION = 'test SubDivision';
            List<String> industrySubTypes = new List<String>{
                    'Universities'};
            Territory__c territoryIndustry = new Territory__c(
                    Re_evaluate__c = true,
                    SW_Industry__c = INDUSTRY,
                    Sub_Division__c = SUB_DIVISION,
                    Industry_Subtype__c = String.join(industrySubTypes, ';')
            );
            insert territoryIndustry;
            Account accIndustry = AccountUtils.getAccounts(1)[0];
            accIndustry.ARR__c = 5;
            accIndustry.SW_Industry__c = INDUSTRY;
            insert accIndustry;
        }
    }

    /**
     * @description run the batch on Strategic pod match. Delete existing territories to ensure running on the desired territories
     * @expected 'before' account will remain Re_Evaluate_Territory__c false,
     *           'after' account will change to Re_Evaluate_Territory__c true,
     * */
    @istest
    public static void testBatchStrategicPod(){
        System.runAs(getUser()) {
            String STRATEGIC_POD = 'NAL-US-FinServ';

            Territory__c territoryPod = [SELECT Id FROM Territory__c];
            territoryPod.Strategic_Pod__c = STRATEGIC_POD;
            territoryPod.SW_Industry__c = '';
            territoryPod.Sub_Division__c = '';
            territoryPod.Industry_Subtype__c = null;
            update territoryPod;
//            System.debug('@@@ testBatchStrategicPod: ' + [SELECT ID, Strategic_Pod__c, Sub_Division__c, SW_Industry__c FROM Territory__c]);

            Account accountPod = [SELECT Id FROM Account];
            accountPod.Strategic_Pod__c = STRATEGIC_POD;
            update accountPod;

            Test.startTest();
                accountPod.Re_Evaluate_Territory__c = false;
                update accountPod;
                Account beforeBatchAccount = [SELECT Id, Re_Evaluate_Territory__c, Strategic_Pod__c, owner.UserRole.Name FROM Account WHERE Id = :accountPod.Id LIMIT 1];
                System.debug('@@@ ActivateUnMappedAccountOfTerritoryTest - beforeBatchAccount: ' + beforeBatchAccount);
                String CRON_EXP = '0 0 0 3 9 ? 2100';
                System.schedule('ActivateUnMappedAccountOfTerritoryTest', CRON_EXP, new ActivateUnMappedAccountOfTerritory());
                Database.executeBatch(new ActivateUnMappedAccountOfTerritory(), 1);
            Test.stopTest();

            // assert
            Account afterBatchAccount = [SELECT Id, Re_Evaluate_Territory__c FROM Account WHERE Strategic_Pod__c != null LIMIT 1];
//            system.assertEquals(false, beforeBatchAccount.Re_Evaluate_Territory__c, 'before account should remain false');
//            system.assertEquals(true, afterBatchAccount.Re_Evaluate_Territory__c, 'after account should have true');
        }
    }

    /**
     * @description run the batch.
     * @expected 'before' account will remain Re_Evaluate_Territory__c false,
     *           'after' account will change to Re_Evaluate_Territory__c true,
     * */
    @istest
    public static void testBatchIndustry(){
//        System.debug('@@@ testBatchIndustry: ' + [SELECT ID, Strategic_Pod__c, Sub_Division__c, SW_Industry__c FROM Territory__c]);
        Account beforeBatchAccount = [SELECT Id,Re_Evaluate_Territory__c,BI_Data__c FROM Account WHERE SW_Industry__c !=null LIMIT 1];
        BI_Data__c bi = [SELECT Sub_Division_Account__c FROM BI_Data__c WHERE Id = :beforeBatchAccount.BI_Data__c LIMIT 1];
        bi.Sub_Division_Account__c = 'test SubDivision';
        Test.startTest();
        update bi;
        Database.executeBatch(new ActivateUnMappedAccountOfTerritory(),1);
        Test.stopTest();
        // assert
        Account afterBatchAccount = [SELECT Id, Re_Evaluate_Territory__c FROM Account WHERE SW_Industry__c !=null LIMIT 1];
        system.assertEquals(false, beforeBatchAccount.Re_Evaluate_Territory__c, 'before account should remain false');
        system.assertEquals(true, afterBatchAccount.Re_Evaluate_Territory__c, 'after account should have true');
    }

    private static User getUser(){
        User u = [SELECT Id, UserRole.Name
        FROM User
        WHERE IsActive = true
        AND Profile.Name LIKE '%admin%'
        AND (NOT UserRole.Name LIKE '%Reseller%')
        AND (NOT UserRole.Name LIKE '%Internal%')
        AND (NOT UserRole.Name LIKE '%Product Marketing & Strategy%')
        AND (NOT UserRole.Name LIKE '%Channel%')
        AND (NOT UserRole.Name LIKE '%OEM%')
        AND (NOT UserRole.Name LIKE '%Panel Acquisition%')
        AND (NOT UserRole.Name LIKE '%Self Services%')
        LIMIT 1][0];
        System.debug('@@@ Running test as user: ' + u.UserRole);
        return u;
    }

}