force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sold__c.field-meta.xml
<CustomField>
    <fullName>Product_Sold__c</fullName>
    <label>Product Sold</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Sold</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account.SW_Industry__c ,
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;,
&apos;Agency&apos;, &apos;Agency&apos;,
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;,
&apos;B2B Software&apos;,&apos;B2B Software&apos;,
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;,
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;,
&apos;Big Tech&apos;,&apos;Big Tech&apos;,
&apos;Classifieds&apos;,&apos;Classifieds&apos;,
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;,
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;,
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;,
&apos;Education&apos;,&apos;Education&apos;,
&apos;Equity Research&apos;,&apos;Equity Research&apos;,
&apos;Financial services&apos;,&apos;Financial services&apos;,
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;,
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;,
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;,
&apos;Investors&apos;,&apos;Investors&apos;,
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;,
&apos;Other&apos;,&apos;Other&apos;,
&apos;Payments&apos;,&apos;Payments&apos;,
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;,
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;,
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;,
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;,
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;,
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;,
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;,
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;,
&apos;Private Equity and Venture Capital&apos;,&apos;Private Equity and Venture Capital&apos;,
&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account__r.SW_Industry__c ,
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;,
&apos;Agency&apos;, &apos;Agency&apos;,
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;,
&apos;B2B Software&apos;,&apos;B2B Software&apos;,
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;,
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;,
&apos;Classifieds&apos;,&apos;Classifieds&apos;,
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;,
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;,
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;,
&apos;Education&apos;,&apos;Education&apos;,
&apos;Equity Research&apos;,&apos;Equity Research&apos;,
&apos;Financial services&apos;,&apos;Financial services&apos;,
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;,
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;,
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;,
&apos;Investors&apos;,&apos;Investors&apos;,
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;,
&apos;Other&apos;,&apos;Other&apos;,
&apos;Payments&apos;,&apos;Payments&apos;,
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;,
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;,
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;,
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;,
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;,
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;,
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;,
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;,
text(Account__r.SW_Industry__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddInvalidToEmailFieldsTest.cls
/**
 * @author Itzik Winograd
 * @date 09/01/2022
 * @description Test Class for AddInvalidToEmailFields
 * --------------------------------------------------------------------------------------
 * CHANGE HISTORY:
 * --------------------------------------------------------------------------------------
 * author      - Itzik Winograd
 * date        - 2022-05-19
 * description - add  acc.SW_Industry__c = 'Agency' since error occured when tested.
 * --------------------------------------------------------------------------------------
 * author      - Itzik Winograd
 * date        - 2022-07-20
 * description - Changed the test accordingly to work with the Bacth version.
 * --------------------------------------------------------------------------------------
 */
@isTest
public class AddInvalidToEmailFieldsTest {
  private static final string OPPORTUNITY_FIELDS_LIST = 'Sandbox_Refresh_Opportunity_Fields';
  private static final string REQUEST_FIELDS_LIST = 'Sandbox_Refresh_Request_Fields';
  private static List<String> requestEmailFieldsToUpdateList = GeneralUtil.getGeneralConfig(
      REQUEST_FIELDS_LIST
    )
    .Text_Value__c.split(';');
  private static List<String> oppEmailFieldsToUpdateList = GeneralUtil.getGeneralConfig(
      OPPORTUNITY_FIELDS_LIST
    )
    .Text_Value__c.split(';');

  /**
   * @author Itzik Winograd
   * @date 09/01/2022
   * @description Create accounts, opps and requests for the upcoming test.
   * 			   Put values in all relevant email fields
   * --- change---
   * @author Elnur Alibaev
   * @date 01/08/2025
   * @description Removed Product_Sold__c assignment from opp
   */
  @testSetup
  public static void makeTestData() {
    //Create accounts
    Integer numOfRecords = 1;
    List<Account> accountsList = AccountUtils.getAccounts(numOfRecords);
    for (Account acc : accountsList) {
      acc.SW_Industry__c = 'Agency';
    }
    insert accountsList;
    System.debug('@@@ accountsList: ' + accountsList);
    //Create Opps
    List<Opportunity> oppsList = new List<Opportunity>();
    for (Integer i = 0; i < numOfRecords; i++) {
      Opportunity opp = TestDataFactory.createOpportunity(accountsList[i]);
      for (String emailField : oppEmailFieldsToUpdateList) {
        opp.put(emailField, 'test' + i + '@test.com');
      }
      oppsList.add(opp);
    }
    insert oppsList;
    System.debug('@@@ oppsList: ' + oppsList);
    //create Request__c
    List<Request__c> requestsList = new List<Request__c>();
    for (Integer i = 0; i < numOfRecords; i++) {
      Request__c req = TestDataFactory.createRequest(oppsList[i]);
      for (String emailField : requestEmailFieldsToUpdateList) {
        req.put(emailField, 'test' + i + '@test.com');
      }
      requestsList.add(req);
    }
    insert requestsList;
    System.debug('@@@ requestsList: ' + requestsList);
  }

  /**
   * @author Itzik Winograd
   * @date 09/01/2022
   * @description Run the process.
   * @expected - No email field will be found without "invalid"
   */
  @isTest
  public static void checkForEmailWitoutInvalid() {
    Test.startTest();
    //AddInvalidToEmailFields addInvlaid = new AddInvalidToEmailFields();
    //addInvlaid.handle();
    Database.executeBatch(
      new AddInvalidToEmailFields('Sandbox_Refresh_Opportunity_Fields'),
      200
    );
    Database.executeBatch(
      new AddInvalidToEmailFields('Sandbox_Refresh_Request_Fields'),
      200
    );
    Database.executeBatch(
      new AddInvalidToEmailFields('Sandbox_Refresh_Meeting_Fields'),
      200
    );
    Test.stopTest();
    //check opps
    List<SObject> oppsList = Database.query(
      CustomQueriesUtils.getCustomQuery(OPPORTUNITY_FIELDS_LIST)
    );
    for (SObject opp : oppsList) {
      for (String emailField : oppEmailFieldsToUpdateList) {
        if (opp.get(emailField) != null) {
          System.assert(
            ((String) opp.get(emailField)).contains('invalid'),
            'No invalid found in Opportunity field ' + emailField
          );
        }
      }
    }
    //check requests
    List<SObject> requestsList = Database.query(
      CustomQueriesUtils.getCustomQuery(REQUEST_FIELDS_LIST)
    );
    for (SObject req : requestsList) {
      for (String emailField : requestEmailFieldsToUpdateList) {
        if (req.get(emailField) != null) {
          System.assert(
            ((String) req.get(emailField)).contains('invalid'),
            'No invalid found in Request__c field ' + emailField
          );
        }
      }
    }
  }
}