force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Current_Registration_Type__c</fullName>
    <description>Populated by Pardot</description>
    <label>Current Registration Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketing_Persona__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Persona__c</fullName>
    <description>MIS-4768</description>
    <label>Marketing Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account.SW_Industry__c , 
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;, 
&apos;Agency&apos;, &apos;Agency&apos;, 
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;, 
&apos;B2B Software&apos;,&apos;B2B Software&apos;, 
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;, 
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;, 
&apos;Classifieds&apos;,&apos;Classifieds&apos;, 
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;, 
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;, 
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;, 
&apos;Education&apos;,&apos;Education&apos;, 
&apos;Equity Research&apos;,&apos;Equity Research&apos;, 
&apos;Financial services&apos;,&apos;Financial services&apos;, 
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;, 
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;, 
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;, 
&apos;Investors&apos;,&apos;Investors&apos;, 
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;, 
&apos;Other&apos;,&apos;Other&apos;, 
&apos;Payments&apos;,&apos;Payments&apos;, 
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;, 
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;, 
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;, 
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;, 
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;, 
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;, 
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;, 
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;, 

&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Persona__mdt/Marketing_Persona__mdt.object-meta.xml
<CustomObject>
    <description>MIS-4768</description>
    <label>Marketing Persona</label>
    <pluralLabel>Marketing Personas</pluralLabel>
</CustomObject>

force-app/main/default/objects/Marketing_Persona__mdt/fields/Account_SW_Industries__c.field-meta.xml
<CustomField>
    <fullName>Account_SW_Industries__c</fullName>
    <label>Account SW Industries</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Persona__mdt/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>MIS-4768</description>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Persona__mdt/fields/Marketing_Persona_with_Industry__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Persona_with_Industry__c</fullName>
    <description>MIS-4768</description>
    <label>Marketing Persona with Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Persona__mdt/fields/Marketing_Persona_without_Industry__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Persona_without_Industry__c</fullName>
    <description>MIS-4768</description>
    <label>Marketing Persona without Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateMarketingPersonaQueueable.cls
/**
 * Created by Alon.Shalev on 2/12/2024.
 */

public with sharing class UpdateMarketingPersonaQueueable implements Queueable{

    private static final Integer maximumNumberOfContacts = 5;
    private Map<Id,Contact> allContactMap;
    private Set<Id> accountIdSet;
    private Boolean fromNoTouchRetry = false;

    public UpdateMarketingPersonaQueueable(Set<Id> accountIdSet){
        this.allContactMap = new map<Id,Contact>([SELECT id,Department__c,Account.SW_Industry__c,Marketing_Persona__c,Current_Registration_Type__c FROM Contact WHERE AccountId IN : accountIdSet]);
    }
    public UpdateMarketingPersonaQueueable(Map<Id,Contact> allContactMap){
        this.allContactMap = allContactMap;
    }

    public UpdateMarketingPersonaQueueable(Set<Id> accountIdSet, Boolean fromNoTouchRetry){
        this.allContactMap = new map<Id,Contact>([SELECT id,Department__c,Account.SW_Industry__c,Marketing_Persona__c,Current_Registration_Type__c FROM Contact WHERE AccountId IN : accountIdSet]);
        this.accountIdSet = accountIdSet;
        this.fromNoTouchRetry = fromNoTouchRetry;
    }

    public void execute(QueueableContext context) {
        Integer counter = 0;
        List<Marketing_Persona__mdt> settings = [SELECT Department__c,Marketing_Persona_with_Industry__c,Marketing_Persona_without_Industry__c,Account_SW_Industries__c FROM Marketing_Persona__mdt];
        Map<String,Marketing_Persona__mdt> settingMap = new Map<String,Marketing_Persona__mdt>();
        for(Marketing_Persona__mdt setting  : settings){
            settingMap.put(setting.Department__c, setting);
        }
        List<Contact> contactToUpdateList = new List<Contact>();

        for(Id contactId : allContactMap.keySet()){
            Contact contItem = allContactMap.get(contactId);
            if(String.isNotBlank(contItem.Current_Registration_Type__c) && contItem.Current_Registration_Type__c.contains('Shopper')){
                counter++;
                contItem.put('Marketing_Persona__c','Shopper');
            } else if (String.isNotBlank(contItem.Current_Registration_Type__c) && contItem.Current_Registration_Type__c.contains('app-solution')) {
                counter++;
                contItem.put('Marketing_Persona__c','Apps');
            }
            Marketing_Persona__mdt setting =  settingMap.get(allContactMap.get(contactId).Department__c);
            List<String> swIndustriesFromMetaData = setting != null ?  setting.Account_SW_Industries__c.split(',') : new List<String>();
            Object newValue =  setting != null ? (
                                    swIndustriesFromMetaData.contains(contItem.Account.SW_Industry__c) ?
                                        setting.Marketing_Persona_with_Industry__c :
                                        getValueFromRegistrationType(contItem,true,setting.Marketing_Persona_without_Industry__c)) :
                                    getValueFromRegistrationType(contItem,false,null);

            if(counter < maximumNumberOfContacts){
                contItem.put('Marketing_Persona__c',newValue);
                contactToUpdateList.add(contItem);
                counter++;
                allContactMap.remove(contactId);
            }

        }

        if(!contactToUpdateList.isEmpty()){
            update contactToUpdateList;
        }

        if(!allContactMap.isEmpty()){
            if(!Test.isRunningTest()){
                system.enqueueJob(new UpdateMarketingPersonaQueueable(allContactMap)); // will run the job with te reminders
            }
        }

        if (this.fromNoTouchRetry) {
            system.enqueueJob(new UpdatestrategicPodOnContactsQueueable(this.accountIdSet));
        }
    }

    private String getValueFromRegistrationType(Contact contact , boolean withSettingExist,String defaultValue){
        String newPersonaValue = defaultValue != null ? defaultValue : 'No Persona';
        if(contact.Current_Registration_Type__c != null){
            if(contact.Current_Registration_Type__c.containsIgnoreCase('Sales') ||
               contact.Current_Registration_Type__c.containsIgnoreCase('sales-solution') ||
               contact.Current_Registration_Type__c.containsIgnoreCase('Digital Marketing') ||
               contact.Current_Registration_Type__c.containsIgnoreCase('web-solution')) {
                if(!withSettingExist || (contact.Department__c == null || contact.Department__c == 'Other')){
                    newPersonaValue = contact.Current_Registration_Type__c.containsIgnoreCase('Sales') ||
                                      contact.Current_Registration_Type__c.containsIgnoreCase('sales-solution') ?
                                        'Sales' : 'Marketing - General';
                }
            }
        }
        return newPersonaValue;
    }
}