force-app/main/default/objects/Account/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Big Tech</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Current_Registration_Type__c</fullName>
    <description>Populated by Pardot</description>
    <label>Current Registration Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Shopper</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketing_Persona__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Persona__c</fullName>
    <description>MIS-4768</description>
    <label>Marketing Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account.SW_Industry__c , 
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;, 
&apos;Agency&apos;, &apos;Agency&apos;, 
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;, 
&apos;B2B Software&apos;,&apos;B2B Software&apos;, 
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;, 
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;, 
&apos;Classifieds&apos;,&apos;Classifieds&apos;, 
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;, 
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;, 
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;, 
&apos;Education&apos;,&apos;Education&apos;, 
&apos;Equity Research&apos;,&apos;Equity Research&apos;, 
&apos;Financial services&apos;,&apos;Financial services&apos;, 
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;, 
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;, 
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;, 
&apos;Investors&apos;,&apos;Investors&apos;, 
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;, 
&apos;Other&apos;,&apos;Other&apos;, 
&apos;Payments&apos;,&apos;Payments&apos;, 
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;, 
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;, 
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;, 
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;, 
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;, 
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;, 
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;, 
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;, 

&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Inferral_Solution_Valid_Criteria_List__c/Inferral_Solution_Valid_Criteria_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution L Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/InferralSolutionCValidCriteriaList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution C Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMap__c/InferralSolutionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Lead</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/InferralSolutionMapContact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Contact</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateMarketingPersonaQueueableTest.cls
@isTest
private class UpdateMarketingPersonaQueueableTest {
    @testSetup
    static void setup(){
        Inferral_Solution_Settings__c iss = new Inferral_Solution_Settings__c();
        iss.Name='Default Value';
        iss.Value__c='Sales';
        insert iss;

        InferralSolutionMap__c ismTest = new InferralSolutionMap__c();
        ismTest.SW_Industry__c = 'AdTech and AdNetwork';
        ismTest.Department__c = 'BI / Analytics';
        ismTest.Inferred_Solution__c = 'Research';
        ismTest.Name = 'test';
        insert ismTest;

        InferralSolutionMapContact__c ismCTest = new InferralSolutionMapContact__c();
        ismCTest.SW_Industry__c = 'AdTech and AdNetwork';
        ismTest.Department__c = 'BI / Analytics';
        ismCTest.Inferred_Solution__c = 'Research';
        ismCTest.Name = 'test';
        insert ismCTest;

        Inferral_Solution_Valid_Criteria_List__c islvcl = new Inferral_Solution_Valid_Criteria_List__c();
        islvcl.Name='department__c';
        islvcl.Is_Valid__c=true;
        insert islvcl;

        Inferral_Solution_Valid_Criteria_List__c islvcl2 = new Inferral_Solution_Valid_Criteria_List__c();
        islvcl2.Name='sw_industry__c';
        islvcl2.Is_Valid__c=true;
        insert islvcl2;

        InferralSolutionCValidCriteriaList__c islcvcl = new InferralSolutionCValidCriteriaList__c();
        islcvcl.Name='department__c';
        islcvcl.Is_Valid__c=true;
        insert islcvcl;

        InferralSolutionCValidCriteriaList__c islcvcl2 = new InferralSolutionCValidCriteriaList__c();
        islcvcl2.Name='sw_industry__c';
        islcvcl2.Is_Valid__c=true;
        insert islcvcl2;
    }

    @isTest static void testExecute_UpdatesUpToMaximumAndSetsSalesPersona() {
        Account acc = new Account(Name = 'Acct Test', SW_Industry__c = 'Ind1');
        insert acc;

        List<Contact> contactsToInsert = new List<Contact>{
                new Contact(LastName = 'C0', AccountId = acc.Id, Current_Registration_Type__c = 'Shopper Intelligence', Department__c = null, Email = 'testC0@gmail.com'),
                new Contact(LastName = 'C1', AccountId = acc.Id, Current_Registration_Type__c = 'Sales Representative', Department__c = null, Email = 'testC1@gmail.com'),
                new Contact(LastName = 'C2', AccountId = acc.Id, Current_Registration_Type__c = 'app-solution foo', Department__c = 'Other', Email = 'testC2@gmail.com'),
                new Contact(LastName = 'C3', AccountId = acc.Id, Current_Registration_Type__c = 'sales-solution bar', Department__c = 'Other', Email = 'testC3@gmail.com'),
                new Contact(LastName = 'C4', AccountId = acc.Id, Current_Registration_Type__c = 'Other Registration', Department__c = 'Other', Email = 'testC4@gmail.com'),
                new Contact(LastName = 'C5', AccountId = acc.Id, Current_Registration_Type__c = 'Unprocessed Contact', Department__c = 'Other', Email = 'testC5@gmail.com')
                };
        insert contactsToInsert;

        List<Contact> queried = [SELECT Id, Department__c, Account.SW_Industry__c, Marketing_Persona__c, Current_Registration_Type__c
        FROM Contact WHERE AccountId = :acc.Id ORDER BY CreatedDate ASC];
        Map<Id, Contact> contactMap = new Map<Id, Contact>(queried);
        UpdateMarketingPersonaQueueable job = new UpdateMarketingPersonaQueueable(contactMap);

        Test.startTest();
        job.execute(null);
        Test.stopTest();

        List<Contact> after = [SELECT Id, Current_Registration_Type__c, Marketing_Persona__c FROM Contact WHERE AccountId = :acc.Id ORDER BY CreatedDate ASC];

        Integer updatedCount = 0;
        for (Contact c : after) {
            if (c.Marketing_Persona__c != null) updatedCount++;
        }

        System.assertEquals(6, updatedCount, 'Exactly 6 contacts should be updated in one run');
        System.assertEquals('Sales', after[1].Marketing_Persona__c, 'Sales registration type should map to Sales persona');
        System.assertEquals('Sales', after[3].Marketing_Persona__c, 'sales-solution registration type should map to Sales persona');
        System.assertEquals('No Persona', after[5].Marketing_Persona__c, 'The 6th contact should remain unprocessed and have null Marketing_Persona__c');
    }
}