force-app/main/default/objects/Campaign_Member_History_Tracking__c/Campaign_Member_History_Tracking__c.object-meta.xml
<CustomObject>
    <label>Campaign Member History Tracking</label>
    <nameField>
        <label>Campign Member History Traking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Member History Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Campign_Member_History_Trakings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Campaign_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Id__c</fullName>
    <label>Campaign Member Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Changed_Field__c.field-meta.xml
<CustomField>
    <fullName>Changed_Field__c</fullName>
    <label>Changed Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Changed_value__c.field-meta.xml
<CustomField>
    <fullName>Changed_value__c</fullName>
    <label>Changed value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Member_History_Tracking__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMemberHandler.cls
/**
 * Created by Alon.Shalev on 11/19/2023.
 */

public with sharing class CampaignMemberHandler {

    public void createHistoryRecords(List<CampaignMember> newList , Map<Id,CampaignMember> oldMap){
        List<Campaign_Member_History_Tracking__c> campaignMemberHistoryTrackingList = new List<Campaign_Member_History_Tracking__c>();
        String eventType = oldMap == null ? 'Created' : 'Updated';
        List<Schema.SObjectField> campaignMemberFields = CampaignMember.SObjectType.getDescribe().fields.getMap().values();
        for(CampaignMember campaignMember : newList){
            for (Schema.SObjectField field : campaignMemberFields) {
                Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
                if(fieldDescribe.isCustom()){
                    String fieldName = fieldDescribe.getName();
                    if(oldMap == null){
                        if(campaignMember.get(fieldName) != null){
                            campaignMemberHistoryTrackingList.add(createHistory(campaignMember.get(fieldName),null,fieldName,eventType,campaignMember));
                        }
                    }else if(campaignMember.get(fieldName) != oldMap.get(campaignMember.Id).get(fieldName)){
                        campaignMemberHistoryTrackingList.add(createHistory(campaignMember.get(fieldName),oldMap.get(campaignMember.Id).get(fieldName),fieldName,eventType,campaignMember));

                    }

                }

            }
        }
        insert campaignMemberHistoryTrackingList;
    }
    private Campaign_Member_History_Tracking__c createHistory(Object changedValue , Object originalVale , String fieldName , String eventType , CampaignMember campaignMember){
        System.debug('changedValue--'+changedValue);

        Campaign_Member_History_Tracking__c trackingItem = new Campaign_Member_History_Tracking__c();
        trackingItem.Changed_value__c = cutStringToLength(String.valueOf(changedValue), 255);
        trackingItem.Original_Value__c = cutStringToLength(String.valueOf(originalVale), 255);
        trackingItem.Changed_Field__c = cutStringToLength(fieldName, 50);
        trackingItem.Event_Type__c = eventType;
        trackingItem.Campaign_Member_Id__c = campaignMember.Id;
        trackingItem.Email__c = campaignMember.Email;
        trackingItem.Campaign__c = campaignMember.CampaignId;

        return trackingItem;
    }

	private String cutStringToLength(String str, Integer length) {
		if (str != null && str.length() > length) {
			str = str.substring(0, length);
		}

		return str;
	}
}