force-app/main/default/objects/BOI_Currency_Settings__c/BOI_Currency_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BOI Currency Settings</label>
</CustomObject>

force-app/main/default/objects/BOI_Currency_Settings__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Daily_Exchange_Rate__c/Daily_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Daily Exchange Rate</label>
    <nameField>
        <label>Daily Exc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Exchange_Rate__c/fields/BOI_currency_update_date__c.field-meta.xml
<CustomField>
    <fullName>BOI_currency_update_date__c</fullName>
    <label>BOI currency update date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Exchange_Rate__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <label>Change</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Exchange_Rate__c/fields/Converted_To__c.field-meta.xml
<CustomField>
    <fullName>Converted_To__c</fullName>
    <description>MIS-945</description>
    <label>Converted To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>NIS</fullName>
                <default>true</default>
                <label>NIS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Exchange_Rate__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Exchange_Rate__c/fields/Currency_Name__c.field-meta.xml
<CustomField>
    <fullName>Currency_Name__c</fullName>
    <label>Currency Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Exchange_Rate__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Information for every &quot;Data Request&quot; for each Source. Part of the Data Partner model.</description>
    <label>Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>The Tier/Country of the Request that will be created according the Rate</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The actual Rate we pay for each data unit as agreed in the Contract</description>
    <label>Rate</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExchangeRatesScheduler.cls
/*
 * Made by Dmitry Trufanov from Synebo
 * Created date : 04/10/2019
     * Last update date: 
     * Change made: 07/10/2019
 */
public class ExchangeRatesScheduler implements Schedulable{
    
    private static String REQUEST_URL = 'https://www.boi.org.il/currency.xml?curr=';
    
    public static void scheduleDaily() {
        System.schedule('ExchangeRatesScheduler','0 0 01 * * ?', new ExchangeRatesScheduler());
    }
    
    public void execute(SchedulableContext SC) {  
        retreiveExchangeRates();
    }
    
    @future(callout=true)
    private static void retreiveExchangeRates(){
        List<BOI_Currency_Settings__c> settings = BOI_Currency_Settings__c.getAll().values();
        List<Daily_Exchange_Rate__c> exchangeRateList = new List<Daily_Exchange_Rate__c>();
        //What is the purpose of 'exchangeRateDates'? - This date values used to find is there any duplicate records exists for those dates
        List<Date> exchangeRateDates = new List<Date>();
        for(BOI_Currency_Settings__c setting_i : settings){
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(REQUEST_URL + setting_i.Currency_Code__c);
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            SYstem.debug('response.getStatusCode() - ' + response.getStatusCode());
            if (response.getStatusCode() == 200) {
				Dom.XMLNode currencies = response.getBodyDocument().getRootElement();
                Dom.XMLNode curency = currencies.getChildElement('CURRENCY',null);
                if(curency!=null){
                    Daily_Exchange_Rate__c der = new Daily_Exchange_Rate__c();
                    der.Change__c = Decimal.valueOf(curency.getChildElement('CHANGE',null).getText());
                    der.Rate__c = Decimal.valueOf(curency.getChildElement('RATE',null).getText());
                    der.Country__c = curency.getChildElement('COUNTRY',null).getText();
                    der.Currency_Name__c = curency.getChildElement('NAME',null).getText();
                    der.Currency_Code__c = curency.getChildElement('CURRENCYCODE',null).getText();
                    der.Unit__c = Decimal.valueOf(curency.getChildElement('UNIT',null).getText());
                    Date boiCurrencyUpdateDate= Date.valueOf(currencies.getChildElement('LAST_UPDATE',null).getText());
                    exchangeRateDates.add(boiCurrencyUpdateDate);
                    der.BOI_currency_update_date__c= boiCurrencyUpdateDate;
                    exchangeRateList.add(der);
                }               
            }            
        }
        //Itzik Winograd, 2021-11-15: Add AND Converted_To__c != 'USD'
        List<Daily_Exchange_Rate__c> oldExchangeRateList = [SELECT ID
                                                              FROM Daily_Exchange_Rate__c
                                                             WHERE BOI_currency_update_date__c IN :exchangeRateDates
                                                               AND Converted_To__c != 'USD' ]; // Check for duplicates, but exclude Netsuite records
        if(!oldExchangeRateList.isEmpty())
            delete oldExchangeRateList;																														// Delete duplicates
        insert exchangeRateList;
        for(Daily_Exchange_Rate__c der_i:exchangeRateList)
            System.debug('der_i.Id ' + der_i.Id);
    }
}