force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>Use to define Account Members for Stegetic Accounts</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Member__c/Territory_Member__c.object-meta.xml
<CustomObject>
    <label>Territory Member</label>
    <nameField>
        <displayFormat>TMN-{000}</displayFormat>
        <label>Territory Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Member__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory Members</relationshipLabel>
    <relationshipName>Territory_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <description>Works with Custom Metadata - &quot;User Sub Motion&quot; - Make sure to update the metadata if the values in this field are changed</description>
    <label>Owner Sub Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agencies &amp; Consultancies</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>APAC Strategic</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Go To Market</fullName>
            </value>
            <value>
                <fullName>India Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>LLM &amp; AI</fullName>
            </value>
            <value>
                <fullName>Meta/MSFT</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil - 108</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil - Alpha</fullName>
            </value>
            <value>
                <fullName>Reseller - Vietnam - AMS JSC</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TerritoryHandler.cls
/**
 * Created by Alon.Shalev on 3/27/2024.
 */

public with sharing class TerritoryHandler {
  public TerritoryHandler() {
  }

  public void nalTerritoryValidation(List<Territory__c> newList) {
    for (Territory__c terItem : newList) {
      if (String.isNotBlank(terItem.Strategic_Pod__c)) {
        if (!terItem.Strategic_Pod__c.startsWith('NAL')) {
          if (String.isNotBlank(terItem.Sub_Division__c)) {
            List<String> subDivisionList = terItem.Sub_Division__c.split(';');
            if (subDivisionList.size() > 1) {
              terItem.addError(
                'U cant  have more then 1 subdivision if the strategic pod doesnt starts with NAL'
              );
            }
          }
        }
      }
    }
  }
  public void nalTerritoryValidationOnUpdate(
    List<Territory__c> newList,
    Map<Id, Territory__c> oldMap
  ) {
    List<Territory__c> relevantTerritoriesList = new List<Territory__c>();
    for (Territory__c terItem : newList) {
      if (
        terItem.Sub_Division__c != oldMap.get(terItem.Id).Sub_Division__c ||
        terItem.Strategic_Pod__c != oldMap.get(terItem.Id).Strategic_Pod__c
      ) {
        relevantTerritoriesList.add(terItem);
      }
    }
    if (!relevantTerritoriesList.isEmpty()) {
      nalTerritoryValidation(relevantTerritoriesList);
    }
  }

  public void validationOfTerritoryMemberDuplication(
    List<Territory__c> newList,
    Map<Id, Territory__c> oldMap
  ) {
    List<Territory__c> relevantList = new List<Territory__c>();
    for (Territory__c territory : newList) {
      if (territory.OwnerId != oldMap.get(territory.Id).OwnerId) {
        relevantList.add(territory);
      }
    }
    if (!relevantList.isEmpty()) {
      List<Territory_Member__c> territoryMembers = [
        SELECT Id, Name__c
        FROM Territory_Member__c
        WHERE Territory__c IN :relevantList
      ];
      Set<Id> userIdFromMembers = new Set<Id>();
      for (Territory_Member__c territoryMember : territoryMembers) {
        userIdFromMembers.add(territoryMember.Name__c);
      }
      for (Territory__c territory : relevantList) {
        if (userIdFromMembers.contains(territory.OwnerId)) {
          territory.addError('The user is already assigned to this territory.');
        }
      }
    }
  }
}