force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <description>Use to define Account Members for Stegetic Accounts</description>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <label>Sub Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Member__c/Territory_Member__c.object-meta.xml
<CustomObject>
    <label>Territory Member</label>
    <nameField>
        <displayFormat>TMN-{000}</displayFormat>
        <label>Territory Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Member__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory Members</relationshipLabel>
    <relationshipName>Territory_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Sub_Division__c.field-meta.xml
<CustomField>
    <fullName>Sub_Division__c</fullName>
    <description>Works with Custom Metadata - &quot;User Sub Motion&quot; - Make sure to update the metadata if the values in this field are changed</description>
    <label>Owner Sub Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agencies &amp; Consultancies</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>ANZ Enterprise</fullName>
            </value>
            <value>
                <fullName>ANZ Inside Sales</fullName>
            </value>
            <value>
                <fullName>APAC Strategic</fullName>
            </value>
            <value>
                <fullName>EMEA Enterprise</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2B</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales B2C</fullName>
            </value>
            <value>
                <fullName>EMEA Inside Sales ENT</fullName>
            </value>
            <value>
                <fullName>EMEA Mid Market</fullName>
            </value>
            <value>
                <fullName>GCR Enterprise</fullName>
            </value>
            <value>
                <fullName>GCR Inside Sales</fullName>
            </value>
            <value>
                <fullName>Go To Market</fullName>
            </value>
            <value>
                <fullName>India Inside Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>JPKR Enterprise</fullName>
            </value>
            <value>
                <fullName>JPKR Inside Sales</fullName>
            </value>
            <value>
                <fullName>LATAM Inside Sales</fullName>
            </value>
            <value>
                <fullName>LLM &amp; AI</fullName>
            </value>
            <value>
                <fullName>Meta/MSFT</fullName>
            </value>
            <value>
                <fullName>NA Enterprise</fullName>
            </value>
            <value>
                <fullName>NA Inside Sales</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil - 108</fullName>
            </value>
            <value>
                <fullName>Reseller - Brazil - Alpha</fullName>
            </value>
            <value>
                <fullName>Reseller - Vietnam - AMS JSC</fullName>
            </value>
            <value>
                <fullName>SEA Enterprise</fullName>
            </value>
            <value>
                <fullName>SEA Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TerritoryHandlerTest.cls
@isTest
private class TerritoryHandlerTest {
  @testSetup
  static void setupData() {
    User u1 = new User(
      Alias = 'user1',
      Email = 'user1@test.com',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = UserInfo.getProfileId(),
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'user12341@test.com',
      LastName = 'test'
    );
    insert u1;
  }

  @isTest
  static void testNalTerritoryValidation() {
    // Setup - create a territory record that should trigger the validation error
    Territory__c ter = new Territory__c(
      Strategic_Pod__c = 'Agencies',
      Sub_Division__c = 'NAL-AUSG-ALL;NAL-DACH-B2B-MEDIA-TRAV-FIN-AUTO' // This should trigger the error
    );

    Test.startTest();
    try {
      insert ter;
    } catch (DmlException e) {
      System.debug('e----' + e.getMessage());
      System.assert(
        e.getMessage()
          .contains(
            'U cant  have more then 1 subdivision if the strategic pod doesnt starts with NAL'
          ),
        'Expected validation error not thrown'
      );
    }
    Test.stopTest();
  }

  @isTest
  static void testNalTerritoryValidationOnUpdate() {
    // Insert a record that doesn't initially trigger the validation
    Territory__c ter = new Territory__c(
      Strategic_Pod__c = 'NAL-US-FinServ',
      Sub_Division__c = 'NAL-DACH-B2B-MEDIA-TRAV-FIN-AUTO'
    );
    insert ter;

    // Update the record in a way that should trigger the validation
    ter.Sub_Division__c = 'NAL-AUSG-ALL;NAL-DACH-B2B-MEDIA-TRAV-FIN-AUTO'; // Change that should trigger the error

    Test.startTest();
    try {
      update ter;
    } catch (DmlException e) {
      System.assert(
        e.getMessage()
          .contains(
            'U cant  have more then 1 subdivision if the strategic pod doesnt starts with NAL'
          ),
        'Expected validation error not thrown on update'
      );
    }
    Test.stopTest();
  }
  @IsTest
  static void validationOfTerritoryMemberDuplicationTestNoValidation() {
    Territory__c ter = new Territory__c(
      Strategic_Pod__c = 'NAL-US-FinServ',
      Sub_Division__c = 'NAL-DACH-B2B-MEDIA-TRAV-FIN-AUTO'
    );
    insert ter;
    User otherUser = [SELECT Id FROM User WHERE Alias = 'user1'];
    ter.OwnerId = otherUser.id;

    update ter;
  }

  @IsTest
  static void validationOfTerritoryMemberDuplicationTestWithValidation() {
    Territory__c ter = new Territory__c(
      Strategic_Pod__c = 'NAL-US-FinServ',
      Sub_Division__c = 'NAL-DACH-B2B-MEDIA-TRAV-FIN-AUTO'
    );
    insert ter;
    User otherUser = [SELECT Id FROM User WHERE Alias = 'user1'];
    Territory_Member__c duplicateMember = new Territory_Member__c(
      Territory__c = ter.Id,
      Name__c = otherUser.Id
    );
    insert duplicateMember;
    try {
      ter.OwnerId = otherUser.id;
      update ter;
    } catch (Exception ex) {
      System.assertEquals(
        true,
        ex.getMessage()
          .contains('The user is already assigned to this territory')
      );
    }
  }
}