force-app/main/default/objects/BI_Data__c/BI_Data__c.object-meta.xml
<CustomObject>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/fields/Intent_Log_Ins__c.field-meta.xml
<CustomField>
    <fullName>Intent_Log_Ins__c</fullName>
    <description>MIS-5713</description>
    <label>Intent Log Ins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Minisite_Section_Visits__c.field-meta.xml
<CustomField>
    <fullName>Intent_Minisite_Section_Visits__c</fullName>
    <description>MIS-5713</description>
    <label>Intent Minisite Section Visits</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_dashboards__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_dashboards__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of dashboards the user created in trial</description>
    <label>intent_num_of_dashboards</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_handraises__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_handraises__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of handraises</description>
    <label>intent_num_of_handraises</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_invite_users__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_invite_users__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of users the user invited in trial</description>
    <label>intent_num_of_invite_users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Num_of_Keyword_Lists__c.field-meta.xml
<CustomField>
    <fullName>Intent_Num_of_Keyword_Lists__c</fullName>
    <defaultValue>0</defaultValue>
    <description>MIS-6013</description>
    <label>Intent Num of Keyword Lists</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_minisites_visits__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_minisites_visits__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of visits to the minisites</description>
    <label>intent_num_of_minisites_visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_package_page_visits__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_package_page_visits__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of visits to package page</description>
    <label>intent_num_of_package_page_visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_pdf_downloads__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_pdf_downloads__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of PDFs the user downloaded in trial</description>
    <label>intent_num_of_pdf_downloads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_png_downloads__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_png_downloads__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of PNGs the user downloaded in trial</description>
    <label>intent_num_of_png_downloads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/intent_num_of_pro_actions__c.field-meta.xml
<CustomField>
    <fullName>intent_num_of_pro_actions__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of actions in the pro</description>
    <label>intent_num_of_pro_actions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Num_of_SI_Advanced_Searches__c.field-meta.xml
<CustomField>
    <fullName>Intent_Num_of_SI_Advanced_Searches__c</fullName>
    <defaultValue>0</defaultValue>
    <description>MIS-6013</description>
    <label>Intent Num of SI Advanced Searches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Num_of_SI_Company_Overview_Signal__c.field-meta.xml
<CustomField>
    <fullName>Intent_Num_of_SI_Company_Overview_Signal__c</fullName>
    <defaultValue>0</defaultValue>
    <description>MIS-6013</description>
    <label>Intent Num of SI Company Overview Signal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Num_of_SI_Sales_Signal__c.field-meta.xml
<CustomField>
    <fullName>Intent_Num_of_SI_Sales_Signal__c</fullName>
    <defaultValue>0</defaultValue>
    <description>MIS-6013</description>
    <label>Intent Num of SI Sales Signal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Num_of_SI_Saved_Searches__c.field-meta.xml
<CustomField>
    <fullName>Intent_Num_of_SI_Saved_Searches__c</fullName>
    <defaultValue>0</defaultValue>
    <description>MIS-6013</description>
    <label>Intent Num of SI Saved Searches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Pricing_Visits_Dates__c.field-meta.xml
<CustomField>
    <fullName>Intent_Pricing_Visits_Dates__c</fullName>
    <description>MIS-5713</description>
    <label>Intent Pricing Visits Dates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Intent_Trial_Section_and_Sub__c.field-meta.xml
<CustomField>
    <fullName>Intent_Trial_Section_and_Sub__c</fullName>
    <description>MIS-5713</description>
    <label>Intent Trial Section and Sub</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Mrkt_Industries_Searched__c.field-meta.xml
<CustomField>
    <fullName>Mrkt_Industries_Searched__c</fullName>
    <label>Mrkt Industries Searched</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Mrkt_Last_3_Compare_Websites__c.field-meta.xml
<CustomField>
    <fullName>Mrkt_Last_3_Compare_Websites__c</fullName>
    <description>MIS-5713</description>
    <label>Mrkt Last 3 Compare Websites</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Mrkt_Last_3_Keyword_List__c.field-meta.xml
<CustomField>
    <fullName>Mrkt_Last_3_Keyword_List__c</fullName>
    <description>MIS-5713</description>
    <label>Mrkt Last 3 Keyword List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Mrkt_Premium_Features_Dates__c.field-meta.xml
<CustomField>
    <fullName>Mrkt_Premium_Features_Dates__c</fullName>
    <description>MIS-5713</description>
    <label>Mrkt Premium Features Dates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Mrkt_Pro_Hook_Clicked__c.field-meta.xml
<CustomField>
    <fullName>Mrkt_Pro_Hook_Clicked__c</fullName>
    <description>MIS-5713</description>
    <label>Mrkt Pro Hook Clicked</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Data__c/fields/Mrkt_Pro_Hook_Clicked_Dates__c.field-meta.xml
<CustomField>
    <fullName>Mrkt_Pro_Hook_Clicked_Dates__c</fullName>
    <description>MIS-5713</description>
    <label>Mrkt Pro Hook Clicked Dates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Asset_Type2__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type2__c</fullName>
    <description>MIS-4271</description>
    <inlineHelpText>Specify the activity’s sub-category</inlineHelpText>
    <label>Asset Type2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Event - External</fullName>
            </value>
            <value>
                <fullName>Event - Innovation Days</fullName>
            </value>
            <value>
                <fullName>Event - Owned</fullName>
            </value>
            <value>
                <fullName>Event - Online</fullName>
            </value>
            <value>
                <fullName>Content - Report</fullName>
            </value>
            <value>
                <fullName>Content - Case Study</fullName>
            </value>
            <value>
                <fullName>Content - Infographic</fullName>
            </value>
            <value>
                <fullName>Content - Blog Post</fullName>
            </value>
            <value>
                <fullName>Content - Video</fullName>
            </value>
            <value>
                <fullName>Content - Landing Page</fullName>
            </value>
            <value>
                <fullName>Email - One-off</fullName>
            </value>
            <value>
                <fullName>Email - Automated Cadence</fullName>
            </value>
            <value>
                <fullName>Email - Triggered</fullName>
            </value>
            <value>
                <fullName>Email - Newsletter</fullName>
            </value>
            <value>
                <fullName>Chat Bot - One-off</fullName>
            </value>
            <value>
                <fullName>Chat Bot - Automated</fullName>
            </value>
            <value>
                <fullName>Webinar - Recording</fullName>
            </value>
            <value>
                <fullName>Webinar - Internal</fullName>
            </value>
            <value>
                <fullName>Webinar - External</fullName>
            </value>
            <value>
                <fullName>Lead List</fullName>
            </value>
            <value>
                <fullName>Survey - Feedback</fullName>
            </value>
            <value>
                <fullName>Survey - Satisfaction</fullName>
            </value>
            <value>
                <fullName>Survey - NPS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Marketing</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Utility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <description>use this field whenever we will upload lists manually to Pardot and then push it to SFDC</description>
    <label>Campaign Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/First_MQL_Date__c.field-meta.xml
<CustomField>
    <fullName>First_MQL_Date__c</fullName>
    <label>First MQL Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mql_Status__c.field-meta.xml
<CustomField>
    <fullName>Mql_Status__c</fullName>
    <description>MIS-5529</description>
    <formula>IF(
  OR(
    AND(
      TEXT(SW_Fit_Score__c) = &apos;A&apos;,
      BI_Data__r.Intent_Score__c &gt;= 4
    ),
    AND(
      TEXT(SW_Fit_Score__c) = &apos;B&apos;,
      BI_Data__r.Intent_Score__c &gt;= 7
    ),
    AND(
      TEXT(SW_Fit_Score__c) = &apos;C&apos;,
      BI_Data__r.Intent_Score__c &gt;= 7
    )
  ),
  &apos;Hard MQL&apos;,
  IF(
    OR(
      TEXT(SW_Fit_Score__c) = &apos;A&apos;,
      AND(
        TEXT(SW_Fit_Score__c) = &apos;B&apos;,
        BI_Data__r.Intent_Score__c &gt;= 4
      ),
      AND(
        TEXT(SW_Fit_Score__c) = &apos;D&apos;,
        BI_Data__r.Intent_Score__c &gt;= 7
      )
    ),
    &apos;Soft MQL&apos;,
    IF(
      OR(
        TEXT(SW_Fit_Score__c) = &apos;B&apos;,
        TEXT(SW_Fit_Score__c) = &apos;C&apos;
      ),
      &apos;Reserve&apos;,
      IF(
        OR(
          AND(
            TEXT(SW_Fit_Score__c) = &apos;E&apos;,
            BI_Data__r.Intent_Score__c &gt;= 7
          )
        ),
        &apos;Unverified MQL&apos;,
        &apos;Nurture&apos;
      )
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MQL Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MqlScoreCtrl.cls
/**
 * Created by Alon.Shalev on 10/20/2024.
 */

public with sharing class MqlScoreCtrl {
  @AuraEnabled(cacheable=true)
  public static Map<String, Object> getRecordData(
    String recordId,
    String sObjectType
  ) {
    String query = 'SELECT Id, mql_status__c, First_MQL_Date__c, First_Owner_Assigned_Timestamp__c';
    query += ' FROM  ' + sObjectType;
    query += ' WHERE Id = : recordId';
    SObject objRecord = Database.query(query);

    Map<String, Object> result = new Map<String, Object>();
    result.put('mql_status', objRecord.get('mql_status__c'));
    result.put('firstMQLDate', objRecord.get('First_MQL_Date__c'));
    result.put(
      'firstOwnerTimestamp',
      objRecord.get('First_Owner_Assigned_Timestamp__c')
    );
    return result;
  }

  @AuraEnabled(cacheable=true)
  public static Map<String, Object> getMQLScoreTableInfoFromApex(
    String recordId,
    String sObjectType
  ) {
    System.debug('started getMQLScoreTableInfoFromApex');
    Map<String, Object> resultObj = new Map<String, Object>();
    try {
      String query =
        'SELECT BI_Data__r.Mrkt_Industries_Searched__c,' +
        'BI_Data__r.intent_num_of_package_page_visits__c,' +
        'BI_Data__r.Intent_Num_of_Keyword_Lists__c,' +
        'BI_Data__r.Intent_Minisite_Section_Visits__c,' +
        'BI_Data__r.Intent_Trial_Section_and_Sub__c,' +
        'BI_Data__r.Intent_Log_Ins__c,' +
        'BI_Data__r.intent_num_of_pro_actions__c,' +
        'BI_Data__r.Intent_Pricing_Visits_Dates__c,' +
        'BI_Data__r.Mrkt_Pro_Hook_Clicked__c,' +
        'BI_Data__r.Mrkt_Pro_Hook_Clicked_Dates__c,' +
        'BI_Data__r.intent_num_of_handraises__c,' +
        'BI_Data__r.Mrkt_Premium_Features_Dates__c,' +
        'BI_Data__r.intent_num_of_minisites_visits__c,' +
        'BI_Data__r.intent_num_of_dashboards__c,' +
        'BI_Data__r.intent_num_of_png_downloads__c,' +
        'BI_Data__r.intent_num_of_pdf_downloads__c,' +
        'BI_Data__r.intent_num_of_invite_users__c,' +
        'BI_Data__r.Mrkt_Last_3_Compare_Websites__c,' +
        'BI_Data__r.Intent_Num_of_SI_Advanced_Searches__c,' +
        'BI_Data__r.Intent_Num_of_SI_Company_Overview_Signal__c,' +
        'BI_Data__r.Intent_Num_of_SI_Sales_Signal__c,' +
        'BI_Data__r.Intent_Num_of_SI_Saved_Searches__c,' +
        'BI_Data__r.Mrkt_Last_3_Keyword_List__c';
      query += ' FROM  ' + sObjectType;
      query += ' WHERE Id = : recordId';
      SObject objRecord = Database.query(query);
      BI_Data__c biData = (BI_Data__c) objRecord.getSObject('Bi_Data__r');
      String queryForCampMember = 'SELECT Id,CreatedDate,Status,Campaign_Name__c,Campaign.Asset_Type2__c,Campaign.Type ';
      queryForCampMember += 'FROM CampaignMember ';
      queryForCampMember += sObjectType == 'Contact'
        ? 'WHERE ContactId = :recordId '
        : 'WHERE LeadId = : recordId ';
      List<CampaignMember> campaignMemberList = Database.query(
        queryForCampMember
      );

      resultObj.put('biData', biData);
      resultObj.put(
        'campaignMembers',
        campaignMemberList.isEmpty()
          ? new List<CampaignMember>()
          : filterCampaignMembers(campaignMemberList)
      );
      resultObj.put('isSuccess', true);
    } catch (Exception ex) {
      resultObj.put('isSuccess', false);
      resultObj.put('exception', ex.getMessage());
    }
    return resultObj;
  }

  private static List<CampaignMember> filterCampaignMembers(
    List<CampaignMember> originalCampaignMemberList
  ) {
    List<CampaignMember> campaignMembersAfterFilter = new List<CampaignMember>();
    Set<String> typeWithNoRestrictionsSet = new Set<String>{
      'Content',
      'Webinar'
    };
    Set<String> statusOfEmailCampaignAllowed = new Set<String>{
      'Responded',
      'Clicked'
    };
    for (CampaignMember campaignMember : originalCampaignMemberList) {
      if (typeWithNoRestrictionsSet.contains(campaignMember.Campaign.Type)) {
        campaignMembersAfterFilter.add(campaignMember);
      } else if (
        campaignMember.Campaign.Type == 'Email' &&
        statusOfEmailCampaignAllowed.contains(campaignMember.Status)
      ) {
        campaignMembersAfterFilter.add(campaignMember);
      } else if (
        campaignMember.Campaign.Type == 'Event' &&
        campaignMember.Campaign.Asset_Type2__c != 'Event - Owned'
      ) {
        campaignMembersAfterFilter.add(campaignMember);
      }
    }
    return campaignMembersAfterFilter;
  }
}