force-app/main/default/objects/BI_Data__c/BI_Data__c.object-meta.xml
<CustomObject>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BI_Data__c/fields/Intent_Score__c.field-meta.xml
<CustomField>
    <fullName>Intent_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>MIS-4061</description>
    <label>Intent Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intent_Score__c.field-meta.xml
<CustomField>
    <fullName>Intent_Score__c</fullName>
    <formula>BI_Data__r.Intent_Score__c</formula>
    <label>Intent Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mql_Status__c.field-meta.xml
<CustomField>
    <fullName>Mql_Status__c</fullName>
    <description>MIS-5529</description>
    <formula>IF(
  OR(
    AND(
      TEXT(SW_Fit_Score__c) = &apos;A&apos;,
      BI_Data__r.Intent_Score__c &gt;= 4
    ),
    AND(
      TEXT(SW_Fit_Score__c) = &apos;B&apos;,
      BI_Data__r.Intent_Score__c &gt;= 7
    ),
    AND(
      TEXT(SW_Fit_Score__c) = &apos;C&apos;,
      BI_Data__r.Intent_Score__c &gt;= 7
    )
  ),
  &apos;Hard MQL&apos;,
  IF(
    OR(
      TEXT(SW_Fit_Score__c) = &apos;A&apos;,
      AND(
        TEXT(SW_Fit_Score__c) = &apos;B&apos;,
        BI_Data__r.Intent_Score__c &gt;= 4
      ),
      AND(
        TEXT(SW_Fit_Score__c) = &apos;D&apos;,
        BI_Data__r.Intent_Score__c &gt;= 7
      )
    ),
    &apos;Soft MQL&apos;,
    IF(
      OR(
        TEXT(SW_Fit_Score__c) = &apos;B&apos;,
        TEXT(SW_Fit_Score__c) = &apos;C&apos;
      ),
      &apos;Reserve&apos;,
      IF(
        OR(
          AND(
            TEXT(SW_Fit_Score__c) = &apos;E&apos;,
            BI_Data__r.Intent_Score__c &gt;= 7
          )
        ),
        &apos;Unverified MQL&apos;,
        &apos;Nurture&apos;
      )
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MQL Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SLA_Start_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>SLA_Start_Timestamp__c</fullName>
    <label>SLA Start Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/General_Key_Value_pair__mdt/General_Key_Value_pair__mdt.object-meta.xml
<CustomObject>
    <description>Hold a key-value pair for specific process</description>
    <label>General Key-Value pair</label>
    <pluralLabel>General Key-Value pairs</pluralLabel>
</CustomObject>

force-app/main/default/objects/General_Key_Value_pair__mdt/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>The process name to query the key-value pairs by.</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BI_Data__c.field-meta.xml
<CustomField>
    <fullName>BI_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Data</label>
    <referenceTo>BI_Data__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Intent_Score__c.field-meta.xml
<CustomField>
    <fullName>Intent_Score__c</fullName>
    <description>MIS-4061</description>
    <formula>BI_Data__r.Intent_Score__c</formula>
    <label>Intent Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/mql_status__c.field-meta.xml
<CustomField>
    <fullName>mql_status__c</fullName>
    <formula>IF(
      OR(AND(TEXT(SW_Fit_Score__c)=&apos;A&apos;,BI_Data__r.Intent_Score__c &gt;=4),AND(TEXT(SW_Fit_Score__c)=&apos;B&apos;,BI_Data__r.Intent_Score__c &gt;=7),AND(TEXT(SW_Fit_Score__c)=&apos;C&apos;,BI_Data__r.Intent_Score__c &gt;=7)),&apos;Hard MQL&apos;,
      IF(OR(TEXT(SW_Fit_Score__c) = &apos;A&apos;,AND(TEXT(SW_Fit_Score__c)=&apos;B&apos;,BI_Data__r.Intent_Score__c &gt;=4),AND(TEXT(SW_Fit_Score__c)=&apos;D&apos;,BI_Data__r.Intent_Score__c &gt;=7)),&apos;Soft MQL&apos;,
      IF(OR(TEXT(SW_Fit_Score__c) = &apos;B&apos;,TEXT(SW_Fit_Score__c) = &apos;C&apos;),&apos;Reserve&apos;,
      IF(OR(AND(TEXT(SW_Fit_Score__c)=&apos;E&apos;,BI_Data__r.Intent_Score__c &gt;=7)),&apos;Unverified MQL&apos;,
      &apos;Nurture&apos;
      ))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MQL Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>SW_Fit_Score__c</fullName>
    <label>SW Fit Score</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CountDownClockCtrl.cls
/**
 * Created by Alon.Shalev on 10/8/2024.
 */

public with sharing class CountDownClockCtrl {

    @AuraEnabled
    public static Map<String, Object> getMQLInfoFromApex(String objectType,String recordId) {
        Map<String, Decimal> mqlMap = new Map<String, Decimal>();
        List<General_Key_Value_pair__mdt> settings = [SELECT Id,Key__c,Value__c FROM General_Key_Value_pair__mdt WHERE ProcessName__c = 'CountDownClock'];
        for(General_Key_Value_pair__mdt setting : settings){
            mqlMap.put(setting.Key__c,Decimal.valueOf(setting.Value__c));
        }
        String query = 'SELECT SW_Fit_Score__c,BI_Data__r.Intent_Score__c,SLA_Start_Timestamp__c,mql_status__c';
        query += objectType == 'Lead' ? ' FROM Lead' : ' FROM Contact';
        query += ' WHERE Id = : recordId LIMIT 1';
        SObject record = Database.query(query);
        Map<String,object> resultMap = new Map<String, Object>();
        resultMap.put('mqlMap',mqlMap);
        resultMap.put('SobjectInfo',record);
        return resultMap;
    }

}