force-app/main/default/objects/Feature_Flag_Setting__mdt/Feature_Flag_Setting__mdt.object-meta.xml
<CustomObject>
    <description>will allow rollback</description>
    <label>Feature Flag Setting</label>
    <pluralLabel>Feature Flag Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Flag_Setting__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feature_Flag_Setting__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>if this is active a process will run</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feature_Flag_Setting__mdt/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FieldsToMerge.cls
public class FieldsToMerge implements Queueable {

    private Map<String,Object> leadCaptureWrpMap;
    private LeadCaptureService.leadCaptureWrapper leadCaptureWrp;

    public FieldsToMerge(Map<String,Object> leadCaptureWrpMap) {
        this.leadCaptureWrpMap = leadCaptureWrpMap;
    }

    public FieldsToMerge(LeadCaptureService.leadCaptureWrapper lcw) {
        this.leadCaptureWrp = lcw;
    }

    public void execute(QueueableContext context) {
        List<Feature_Flag_Setting__mdt> flags = [SELECT Is_Active__c,Process_Name__c FROM Feature_Flag_Setting__mdt WHERE  Class_Name__c = 'LeadCaptureServiceHandler'];
        Map<String,Feature_Flag_Setting__mdt> flagsMap = new Map<String, Feature_Flag_Setting__mdt>();
        for(Feature_Flag_Setting__mdt flag : flags){
            flagsMap.put(flag.Process_Name__c,flag);
        }
        if(leadCaptureWrpMap != null){
            LeadCaptureService.leadCaptureResponseWrapper lcrw = LeadCaptureServiceHandler.handleTouchCall(leadCaptureWrpMap,flagsMap);
            LeadCaptureServiceHandler.recordLog(true, lcrw, new RestRequest(), leadCaptureWrpMap,true);
        }else{
            LeadCaptureService.leadCaptureResponseWrapper lcrw = LeadCaptureServiceHandler.handleTouchCallWithWrapper(leadCaptureWrp,flagsMap);
            LeadCaptureServiceHandler.recordLogWithWrapper(true, lcrw, new RestRequest(), leadCaptureWrp,true);
        }

    }
}