force-app/main/default/objects/CLC_Stage__c/CLC_Stage__c.object-meta.xml
<CustomObject>
    <label>CLC Stage</label>
    <nameField>
        <label>CLC Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CLC Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CLC_Stage__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLC_Stage__c/fields/Insert_After__c.field-meta.xml
<CustomField>
    <fullName>Insert_After__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insert After</label>
    <referenceTo>CLC_Stage__c</referenceTo>
    <relationshipLabel>CLC Stages</relationshipLabel>
    <relationshipName>CLC_Stages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CLCStageTriggerhandlerTest.cls
@istest
public class CLCStageTriggerhandlerTest {
  @istest
  static void test() {
    List<CLC_Stage__c> parents = new List<CLC_Stage__c>{
      new CLC_Stage__c(Name = 'Activation', Business_Unit__c = 'Inside Sales'),
      new CLC_Stage__c(Name = 'Activation', Business_Unit__c = 'Enterprise')
    };
    insert parents;
    String orderDulpicateMessage = '2 or more CLC Stages on the same order with the same business unit aren\'t allowed.';
    CLC_Stage__c newOkStage = new CLC_Stage__c(
      Name = 'Adoption',
      Business_Unit__c = 'Inside Sales',
      Insert_After__c = parents[0].Id
    );
    try {
      insert newOkStage;
      insert new CLC_Stage__c(
        Name = 'Adoption 2',
        Business_Unit__c = 'Inside Sales',
        Insert_After__c = parents[0].Id
      );
    } catch (Exception e) {
      System.assert(e.getMessage().contains(orderDulpicateMessage));
    }

    try {
      parents[1].Business_Unit__c = 'Inside Sales';
      update parents[1];
    } catch (Exception e) {
      System.assert(e.getMessage().contains(orderDulpicateMessage));
    }
  }
}