force-app/main/default/objects/Lead/fields/Behavioral_Rate_Counter__c.field-meta.xml
<CustomField>
    <fullName>Behavioral_Rate_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Behavioral Rate Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Behavioral_Rate_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Behavioral_Rate_Timestamp__c</fullName>
    <label>Behavioral Rate Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describes the business unit with the responsibility of the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_unit_timestamp__c.field-meta.xml
<CustomField>
    <fullName>Business_unit_timestamp__c</fullName>
    <label>Business unit timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_unit_timestamp_del__c.field-meta.xml
<CustomField>
    <fullName>Business_unit_timestamp_del__c</fullName>
    <label>Business unit timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Behavioral_Rate_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>First_Behavioral_Rate_Timestamp__c</fullName>
    <label>First Behavioral Rate Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Fit_Score_Counter__c.field-meta.xml
<CustomField>
    <fullName>Fit_Score_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fit Score Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/New_Behavioral_Rate__c.field-meta.xml
<CustomField>
    <fullName>New_Behavioral_Rate__c</fullName>
    <label>SW Behavioral Rate (old)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Original_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Original_Lead_Source__c</fullName>
    <label>Original Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3Scale</fullName>
            </value>
            <value>
                <fullName>42matters</fullName>
            </value>
            <value>
                <fullName>Admetricks</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>Blogs</fullName>
            </value>
            <value>
                <fullName>ChiraCEO</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
            </value>
            <value>
                <fullName>Deal Registration</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook - Paid</fullName>
            </value>
            <value>
                <fullName>Internal - F2F Event</fullName>
            </value>
            <value>
                <fullName>Internal - Virtual Event</fullName>
            </value>
            <value>
                <fullName>Internal - Webinars</fullName>
            </value>
            <value>
                <fullName>Investors - Paid</fullName>
            </value>
            <value>
                <fullName>LinkedIn - Paid</fullName>
            </value>
            <value>
                <fullName>LinkedIn - Paid - Convo Ads</fullName>
            </value>
            <value>
                <fullName>LinkedIn sales navigator</fullName>
            </value>
            <value>
                <fullName>MIR</fullName>
            </value>
            <value>
                <fullName>MIR Chat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outbound - RB2B</fullName>
            </value>
            <value>
                <fullName>Outbound - ZoomInfo</fullName>
            </value>
            <value>
                <fullName>Partnership - Content</fullName>
            </value>
            <value>
                <fullName>Partnership - F2F Event</fullName>
            </value>
            <value>
                <fullName>Partnership - Virtual Events</fullName>
            </value>
            <value>
                <fullName>Partnership - Webinars</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>SW_Fit_Score__c</fullName>
    <label>SW Fit Score</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Fit_Score_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>SW_Fit_Score_Timestamp__c</fullName>
    <label>SW Fit Score Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FunelMonitorHandler.cls
public with sharing class FunelMonitorHandler {

    @TestVisible
    private static final String JOURNEY_DROPPED_OWNER_ID = '005b0000002iwIAAAY';
    @TestVisible
    private static final String JOURNEY_OLD_OWNER_ID = '005b0000002iwIAAAY';
    
    public void funelMonitorUpdateLogic(List<Lead> recordList,Map<Id,Lead> oldMap) {
        for (Lead lead_i : recordList) {
            Lead oldLead_i = oldMap.get(lead_i.Id);
            if (lead_i.New_Behavioral_Rate__c != oldLead_i.New_Behavioral_Rate__c) {
                lead_i.Behavioral_Rate_Counter__c = lead_i.Behavioral_Rate_Counter__c == null ? 1 : lead_i.Behavioral_Rate_Counter__c + 1;
                lead_i.Behavioral_Rate_Timestamp__c = Datetime.now();
                if (lead_i.First_Behavioral_Rate_Timestamp__c == null) {
                    lead_i.First_Behavioral_Rate_Timestamp__c = Datetime.now();
                }
            }
            if (lead_i.SW_Fit_Score__c != oldLead_i.SW_Fit_Score__c) {
                lead_i.Fit_Score_Counter__c = lead_i.Fit_Score_Counter__c == null ? 1 : lead_i.Fit_Score_Counter__c + 1;
                lead_i.SW_Fit_Score_Timestamp__c = Datetime.now();
            }
            if (lead_i.Business_Unit__c != oldLead_i.Business_Unit__c) {
                lead_i.Business_unit_timestamp__c = Datetime.now();
                lead_i.Business_unit_timestamp_del__c = Datetime.now();
            }
            if (lead_i.OwnerId != oldLead_i.OwnerId 
                && lead_i.OwnerId != JOURNEY_DROPPED_OWNER_ID
                && 
                    (
                        oldLead_i.OwnerId == JOURNEY_OLD_OWNER_ID
                        && lead_i.Journey_Completed_Timestamp__c == null
                    )
                ) 
            {
                lead_i.Journey_Completed_Timestamp__c = Datetime.now();
            } else if(lead_i.LeadSource != oldLead_i.LeadSource 
                      && String.IsBlank(oldLead_i.LeadSource)
                      && String.isBlank(lead_i.Original_Lead_Source__c)) 
            {
                lead_i.Original_Lead_Source_Last_Updated__c = Datetime.now();
                lead_i.Original_Lead_Source__c = lead_i.LeadSource;
            }
        }
    }

    public void funelMonitorInsertLogic(List<Lead> recordList) {
        for (Lead lead_i : recordList) {
            if (lead_i.LeadSource != '') {
                lead_i.Original_Lead_Source_Last_Updated__c = Datetime.now();
                lead_i.Original_Lead_Source__c = lead_i.LeadSource;
            }
        }
    }
}