force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Describes the business unit with the responsibility of the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Panel_Acquisition</fullName>
                <label>Panel Acquisition</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Clean_Domain__c.field-meta.xml
<CustomField>
    <fullName>Clean_Domain__c</fullName>
    <formula>CASE(Email_address_domain_type__c, 
     &apos;Company&apos;, Email_DomainClean__c , 
     Website_Domain__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clean Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <externalId>true</externalId>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_address_domain_type__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type__c</fullName>
    <inlineHelpText>Indicates if the email belongs to a company or a free email provider</inlineHelpText>
    <label>Email address domain type SFDC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company - Secondary</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Force_Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Force_Enrichment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Force Enrichment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Groudon_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Groudon_Timestamp__c</fullName>
    <label>Groudon Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Industry_Other_Description__c.field-meta.xml
<CustomField>
    <fullName>Industry_Other_Description__c</fullName>
    <label>Industry Other Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <description>LinkedIn URL</description>
    <label>LinkedIn URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <inlineHelpText>Link to LinkedIn Profile</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lugia_Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>Lugia_Fit_Score__c</fullName>
    <label>Lugia Fit Score</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lugia_Linkedin_Profile__c.field-meta.xml
<CustomField>
    <fullName>Lugia_Linkedin_Profile__c</fullName>
    <label>Lugia Linkedin Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MIR_Status__c.field-meta.xml
<CustomField>
    <fullName>MIR_Status__c</fullName>
    <description>#1100018 Updated by MIR</description>
    <label>MIR Status:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prioritized</fullName>
            </value>
            <value>
                <fullName>In Progress / Touched</fullName>
            </value>
            <value>
                <fullName>Fake Data</fullName>
            </value>
            <value>
                <fullName>Free Tools Sufficient / One-Time Use</fullName>
            </value>
            <value>
                <fullName>Low Traffic</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Not a Good Fit: Use Case / Persona / Industry</fullName>
            </value>
            <value>
                <fullName>Not Ready / Bad Timing / No Interest</fullName>
            </value>
            <value>
                <fullName>Unreachable / No Reply</fullName>
            </value>
            <value>
                <fullName>Unsubscribed</fullName>
            </value>
            <value>
                <fullName>Unsupported language speakers</fullName>
            </value>
            <value>
                <fullName>Unverified: No Website / No LinkedIn</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not for No Touch</fullName>
            </value>
            <value>
                <fullName>Agent Replied - Follow Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Pre_Mapped_Title__c.field-meta.xml
<CustomField>
    <fullName>Pre_Mapped_Title__c</fullName>
    <description>MIS-6878</description>
    <label>Pre Mapped Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Seniority__c.field-meta.xml
<CustomField>
    <fullName>Seniority__c</fullName>
    <description>MIS-3278. Fields converted to contact on Lead Conversion</description>
    <label>Seniority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Individual contributor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Team lead/manager</fullName>
            </value>
            <value>
                <fullName>VP/director</fullName>
            </value>
            <value>
                <fullName>C-Suite</fullName>
            </value>
            <value>
                <fullName>Student/Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SI_Enrichment_Visits__c.field-meta.xml
<CustomField>
    <fullName>SI_Enrichment_Visits__c</fullName>
    <description>MIS-4218</description>
    <label>SI Enrichment Visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Banking and insurance</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Recruitment and HR</fullName>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <label>Detailed Error Message</label>
    <length>32678</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Body__c.field-meta.xml
<CustomField>
    <fullName>Http_Body__c</fullName>
    <label>Http Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Record_Ids__c</fullName>
    <label>Record Ids</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/SF_Type__c.field-meta.xml
<CustomField>
    <fullName>SF_Type__c</fullName>
    <label>SF Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadGroudonHandler.cls
public with sharing class LeadGroudonHandler implements GroudonQueueable.GroudonHandler {
	private List<Lead> leadList;
	private Boolean isBulk = false;

	public LeadGroudonHandler(List<Lead> leadList){
		this.leadList = leadList;
	}

	public LeadGroudonHandler(List<Lead> leadList,Boolean isBulk){
		this.leadList = leadList;
		this.isBulk = isBulk;
	}

	public void process() {
		List<Log_Event__e> eventList = new List<Log_Event__e>();
		boolean needToUpdateLeads = false;
		API_Configuration__mdt apiConfiguration = GeneralUtil.getAPIConfig('Groudon_Integration');

		GroudonIntegrationService groudonService = new GroudonIntegrationService(
				new LeadGroudonRequestGenerator(),
				new LeadGroudonResponseGenerator(),
				apiConfiguration);

		try{
			if(this.isBulk){
				GroudonIntegrationService.GroudonResponse response = groudonService.callGroudonBulk(this.leadList);
				for(Lead leadItem : this.leadList){
					fillLog(leadItem, response, eventList);
				}
			}else{
				for(Lead leadItem : this.leadList){
					GroudonIntegrationService.GroudonResponse response = groudonService.callGroudon(leadItem);
					fillLog(leadItem,response,eventList);
				}
			}
		}catch(Exception ex){
			Log_Event__e log = new Log_Event__e();
			log.Email__c = this.isBulk ? 'mass update' : this.leadList.isEmpty() ? 'no leads' : this.leadList[0].Email;
			log.Apex_class__c = 'GroudonIntegrationService';
			log.Apex_Method__c = 'callGroudon';
			log.Record_Ids__c = this.isBulk ? 'mass update' : this.leadList.isEmpty() ? 'no leads' : this.leadList[0].id;
			log.Log_Type__c = 'Error';
			log.Http_Body__c = 'no payload available';
			log.Detailed_Error_Message__c = ex.getMessage() + ' ' + ex.getStackTraceString();
			log.SF_Type__c = 'Lead';
			eventList.add(log);

		}
		needToUpdateLeads = true;
		List<Lead> leadAfterLambdaCallout = [SELECT Id, Groudon_Timestamp__c FROM Lead WHERE Id IN : this.leadList];
		for (Lead leadItem : leadAfterLambdaCallout) {
			leadItem.Force_Enrichment__c = false;
			leadItem.Groudon_Call_Status__c = 'Enrichment_Ended';
			leadItem.Groudon_Timestamp__c = Datetime.now();
		}
		if (!eventList.isEmpty()) {
			Eventbus.publish(eventList);
		}
		if(needToUpdateLeads){
			update leadAfterLambdaCallout;
		}
	}

	private void fillLog(Lead leadItem, GroudonIntegrationService.GroudonResponse response, List<Log_Event__e> eventList) {
		Log_Event__e log = new Log_Event__e();
		log.Email__c = leadItem.email;
		log.Apex_Method__c = this.isBulk ?  'callGroudonBulk' : 'callGroudonSingle';
		log.Apex_class__c = 'GroudonIntegrationService';
		log.Record_Ids__c = leadItem.id;
		log.Log_Type__c = response.isSuccess ? 'Info' : 'Error';
		log.Http_Body__c = response.leadIdToBodyMap.get(leadItem.Id);
		log.Sub_Type__c = 'callGroudon';
		log.SF_Type__c = 'Lead';
		eventList.add(log);
	}

	public class LeadGroudonRequestGenerator implements GroudonQueueable.GroudonRequestGenerator {
		public GroudonIntegrationService.GroudonRequest generate(SObject record) {
			Lead leadItem = (Lead) record;

			GroudonIntegrationService.GroudonRequest requestBody = new GroudonIntegrationService.GroudonRequest();

			requestBody.first_name = leadItem.FirstName;
			requestBody.last_name = leadItem.LastName;
			requestBody.domain = leadItem.Domain__c;
			requestBody.Country_Code = leadItem.CountryCode;
			requestBody.Department_C = leadItem.Department__c;
			requestBody.Department_Other_Description = leadItem.Department_Other_Description__c;
			requestBody.email = leadItem.Email;
			requestBody.linkedin_profile = leadItem.Linkedin_Profile__c;
			requestBody.Seniority = leadItem.Seniority__c;
			requestBody.industry = leadItem.SW_Industry__c;
			requestBody.job_title = leadItem.Title;
			requestBody.Industry_Other_Description = leadItem.Industry_Other_Description__c;
			requestBody.Title_Other_Description = leadItem.Title_Other_Description__c;
			requestBody.Pre_mapped_industry = leadItem.Pre_mapped_industry__c;
			requestBody.Pre_Mapped_Title = leadItem.Pre_Mapped_Title__c;
			requestBody.website = leadItem.Website;
			requestBody.Business_Unit = leadItem.Business_Unit__c;
			requestBody.Clean_Domain = leadItem.Clean_Domain__c;
			requestBody.country = leadItem.country;
			requestBody.Email_address_domain_type = leadItem.Email_address_domain_type__c;
			requestBody.Employees_Min = leadItem.Employees_Min__c;
			requestBody.Lugia_Fit_Score = leadItem.Lugia_Fit_Score__c;
			requestBody.LinkedIn = leadItem.LinkedIn__c;
			requestBody.Lugia_Linkedin_Profile = leadItem.Lugia_Linkedin_Profile__c;
			requestBody.MIR_Status = leadItem.MIR_Status__c;
			requestBody.Quiz_Data_Incomplete = leadItem.Quiz_Data_Incomplete__c;
			requestBody.ROE_Division = leadItem.ROE_Division__c;
			requestBody.SI_Enrichment_Visits = leadItem.SI_Enrichment_Visits__c;
			requestBody.Strategic_Pod = leadItem.Strategic_Pod__c;
			requestBody.title = leadItem.title;
			requestBody.Use_of_Similarweb = leadItem.Use_of_Similarweb__c;
			requestBody.first_name = leadItem.FirstName;
			requestBody.last_name = leadItem.LastName;
			requestBody.Company = leadItem.Company;
			requestBody.SW_Fit_Score_Reason = leadItem.SW_Fit_Score_Reason__c;
			requestBody.Fit_Score_Test = leadItem.Fit_Score_Test__c;
			requestBody.Lugia_Fit_Score_Reasoning = leadItem.Lugia_Fit_Score_Reasoning__c;
			requestBody.Lugia_Employees_Count = leadItem.Lugia_Employees_Count__c;
			requestBody.sf_id = leadItem.Id;
			requestBody.timestamp = Datetime.now();
			requestBody.clientIp = leadItem.clientIp__c;
			requestBody.sf_type = 'Lead';
			requestBody.Registration_Type = leadItem.Registration_Type__c;
			requestBody.LeadSource = leadItem.LeadSource;

			return requestBody;
		}
	}

	public class LeadGroudonResponseGenerator implements GroudonQueueable.GroudonResponseGenerator {
		public GroudonIntegrationService.GroudonResponse generate(List<GroudonIntegrationService.GroudonRequest> requestBodies) {
			GroudonIntegrationService.GroudonResponse groudonResponse = new GroudonIntegrationService.GroudonResponse();

			for (GroudonIntegrationService.GroudonRequest r : requestBodies) {
				groudonResponse.leadIdToBodyMap.put(r.sf_id ,JSON.serializePretty(r,true));
			}

			return groudonResponse;
		}
	}
}