force-app/main/default/objects/Lead/fields/Company_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Company_LDR_Compare__c</fullName>
    <formula>If(((Upper(Polygraph_Company_Name__c)=Upper(Company))||Isblank(Polygraph_Company_Name__c)),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Country_LDR_Compare__c</fullName>
    <description>Compare &quot;Registration Country&quot; to &quot;Polygraph Country&quot;</description>
    <formula>If(Upper(Country)=Upper(Polygraph_Country_Name__c), True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Department_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Department_LDR_Compare__c</fullName>
    <formula>If(Upper(Department_registration__c)=Upper(Polygraph_Department__c), true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Department LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_address_domain_type__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type__c</fullName>
    <inlineHelpText>Indicates if the email belongs to a company or a free email provider</inlineHelpText>
    <label>Email address domain type SFDC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company - Secondary</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Employee_Min_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Employee_Min_LDR_Compare__c</fullName>
    <formula>If(EmployeesMin_registration__c=Polygraph_Employee_Min__c, true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Min LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Name_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>First_Name_LDR_Compare__c</fullName>
    <formula>If(Upper(Polygraph_First_Name__c)=Upper(First_Name_Registration__c),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Contact_Us_Form_Subject__c.field-meta.xml
<CustomField>
    <fullName>Last_Contact_Us_Form_Subject__c</fullName>
    <label>Last Contact Us Form Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Name_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Last_Name_LDR_Compare__c</fullName>
    <formula>If(Upper(Last_Name_Registration__c)=Upper(Polygraph_Last_Name__c),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Orchestration_Journey_Status__c.field-meta.xml
<CustomField>
    <fullName>Orchestration_Journey_Status__c</fullName>
    <label>Orchestration Journey Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Recycle bin</fullName>
            </value>
            <value>
                <fullName>Completed - Nurturing</fullName>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Pardot_List_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Pardot_List_Assignment__c</fullName>
    <description>Field to Assign Leads to Lists in Pardot</description>
    <inlineHelpText>Field to Assign Leads to Lists in Pardot</inlineHelpText>
    <label>Pardot List Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recycle Bin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Title_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Title_LDR_Compare__c</fullName>
    <formula>If(Upper(Title_Registration__c)=Upper(Polygraph_Title__c),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Unverified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unverified_Reason__c</fullName>
    <description>When lead is created the process in ORV API will decide if Lead should excluded from the journey and this is the reasons</description>
    <inlineHelpText>When lead is created the process in ORV API will decide if Lead should excluded from the journey and this is the reasons</inlineHelpText>
    <label>Unverified Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unverified by LDR</fullName>
            </value>
            <value>
                <fullName>Frenemies</fullName>
            </value>
            <value>
                <fullName>Panel Acquisition</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Deal Registration</fullName>
            </value>
            <value>
                <fullName>Unauthorized Country</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Website_LDR_Compare__c.field-meta.xml
<CustomField>
    <fullName>Website_LDR_Compare__c</fullName>
    <formula>If(Upper(Website_registration__c)=Upper(Polygarph_Website__c),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Website LDR Compare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pardot_Data_Manipulation_Setting__c/Pardot_Data_Manipulation_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pardot Data Manipulation Setting</label>
</CustomObject>

force-app/main/default/classes/FrenemyDataPopulationSchedule.cls
global class FrenemyDataPopulationSchedule implements Schedulable{
	private Set<Id> frenemyLeadSet;
        
        public FrenemyDataPopulationSchedule(Set<Id> frenemyLeadSet){
            this.frenemyLeadSet = frenemyLeadSet;
        }
        
        global void execute(SchedulableContext sc) {
            Pardot_Data_Manipulation_Setting__c ownerSetting = Pardot_Data_Manipulation_Setting__c.getInstance('FRENEMY_LEAD_OWNER_ID');
            if(ownerSetting != null){
                List<Lead> leadList = [SELECT Id,FirstName,LastName,Company,Website,Title,Department__c,Employees_Min__c,Employees_Max__c,Industry,Country,Email,Phone,Company_LDR_Compare__c,
                                       Country_LDR_Compare__c,First_Name_LDR_Compare__c,Last_Name_LDR_Compare__c,Website_LDR_Compare__c,Title_LDR_Compare__c,Employee_Min_LDR_Compare__c,Department_LDR_Compare__c,
                                       Email_address_domain_type__c,Last_Contact_Us_Form_Subject__c FROM Lead WHERE Id IN :frenemyLeadSet];
                System.debug('leadList q' + leadList);
                for(Lead lead_i : leadList){
                    lead_i.Unverified_Reason__c = 'Frenemies';
                    lead_i.OwnerId = ownerSetting.Value__c;
                    lead_i.Orchestration_Journey_Status__c = 'Excluded';
                    lead_i.Pardot_List_Assignment__c = 'Recycle Bin';
                    lead_i.Journey_Completed_Timestamp__c = System.now();
                }
                //PardotDataManipulationHandler.journeyDecisionFlow(leadList);
                update leadList;
            }
        }  
}