force-app/main/default/objects/Lead/fields/First_MQL_Date__c.field-meta.xml
<CustomField>
    <fullName>First_MQL_Date__c</fullName>
    <description>Marketo SFDC MQL Date</description>
    <label>First MQL Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/First_Owner_Assigned_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>First_Owner_Assigned_Timestamp__c</fullName>
    <description>MIS-2381</description>
    <label>First Owner Assigned Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>SW_Fit_Score__c</fullName>
    <label>SW Fit Score</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CountDownClockCtrlTest.cls
@IsTest
public class CountDownClockCtrlTest {


    @IsTest
    static void testGetMQLStatusHoursMap() {
        // Call the method being tested
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createInferredSolutionSettings_CS();
        Lead lead = new Lead(
                FirstName = 'Test',
                LastName = 'Lead',
                Company = 'Test Company',
                First_MQL_Date__c = Date.today(),
                SW_Fit_Score__c = 'B',
                First_Owner_Assigned_Timestamp__c = System.now(),
                Email = 'lead1@gmail.com'
        );
        insert lead;

        Map<String, Object> result = CountDownClockCtrl.getMQLInfoFromApex('lead',lead.id);

        // Verify the map is not null and contains the expected entries
        System.assertNotEquals(null, result, 'The result map should not be null');

    }
}