force-app/main/default/objects/Apex_Event_Log__c/Apex_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to log apex actions on salesforce</description>
    <label>Apex Event Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <description>The calling apex class</description>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <description>The method name where the log came from</description>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <description>Detailed Error message</description>
    <label>Detailed Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Detailed_Information__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Information__c</fullName>
    <description>Record/s informations</description>
    <label>Detailed Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/HTTP_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Endpoint__c</fullName>
    <label>HTTP Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ShareASale_New_Transaction_Response__c.field-meta.xml
<CustomField>
    <fullName>ShareASale_New_Transaction_Response__c</fullName>
    <description>Holds the response of new transaction to ShareASale</description>
    <label>ShareASale New Transaction Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShareASaleRetriesBatchTest.cls
/**
 * @author Itzik Winograd
 * @date 10/08/2021
 * @description Test class for ShareASaleRetriesBatch
 */
@isTest
public class ShareASaleRetriesBatchTest {
  @testSetup
  /**
   * @author Itzik Winograd
   * @date 10/08/2021
   * @description: Create a lead with shareasale error.
   */
  public static void shareASaleTestSetup() {
    TestDataFactory.createSimilarWeb_CS();
    TestDataFactory.createBaseProductConfiguration_CS();
    TestDataFactory.createInferredSolutionSettings_CS();
    Lead myLead = new Lead(
      LastName = 'lastName',
      email = 'testLead@testLead.com',
      Company = 'testComp',
      Country = 'Austria',
      Affiliate_Id__c = '5555'
    );
    Test.setMock(
      HttpCalloutMock.class,
      new ShareASaleIntegrationTest.ShareASaleMockError()
    );
    insert myLead;
  }
  /**
   * @author Itzik Winograd
   * @date 11/08/2021
   * @Description: query for an error lead. make sure it has "retry = 0". run the batch.
   * @Expect: the value on ShareASale_Retries_Counter__c will be > 0
   */
  @isTest
  public static void shareASaleRetryTest() {
    Lead newLead = queryLead();
    System.assertEquals(
      newLead.ShareASale_Retries_Counter__c,
      0,
      'The ShareASale_Retries_Counter__c is not 0!'
    );

    Test.startTest();
    Test.setMock(
      HttpCalloutMock.class,
      new ShareASaleIntegrationTest.ShareASaleMockError()
    );
    Database.executeBatch(new ShareASaleRetriesBatch('Lead'), 5);
    Test.stopTest();

    newLead = queryLead();
    System.debug('@@@ newLead.ShareASale_Retries_Counter__c: ' + newLead);
    System.assert(
      newLead.ShareASale_Retries_Counter__c > 0,
      'The ShareASale_Retries_Counter__c is not more then 0: ' +
      newLead.ShareASale_Retries_Counter__c
    );
  }

  /**
   * @author Itzik Winograd
   * @date 11/08/2021
   * @Description: query for an error lead. make sure it has "retry = 0". set the number of retries to 4 and run the batch .
   * @Expect: an error record with 'creatTooManyRetriesLog' will be created
   */
  @isTest
  public static void shareASaleRetryTestWithLog() {
    Lead newLead = queryLead();
    System.assertEquals(
      newLead.ShareASale_Retries_Counter__c,
      0,
      'The ShareASale_Retries_Counter__c is not 0!'
    );
    newLead.ShareASale_Retries_Counter__c = 4;
    update newLead;
    Test.startTest();
    Test.setMock(
      HttpCalloutMock.class,
      new ShareASaleIntegrationTest.ShareASaleMockError()
    );
    Database.executeBatch(new ShareASaleRetriesBatch('Lead'), 5);
    Test.stopTest();

    newLead = queryLead();
    List<Apex_Event_Log__c> logs = new List<Apex_Event_Log__c>(
      [
        SELECT
          Id,
          Log_Type__c,
          Apex_Class__c,
          Detailed_Information__c,
          Detailed_Error_Message__c,
          Apex_Method__c,
          Http_Endpoint__c
        FROM Apex_Event_Log__c
        WHERE Apex_Method__c = 'creatTooManyRetriesLog'
      ]
    );
    System.assert(
      logs.size() > 0,
      'No creatTooManyRetriesLog record was created!'
    );
  }

  //Retrieve a lead
  private static Lead queryLead() {
    return [
      SELECT
        Id,
        Affiliate_Id__c,
        ShareASale_Retries_Counter__c,
        ShareASale_New_Transaction_Response__c
      FROM Lead
      WHERE Affiliate_Id__c = '5555'
      LIMIT 1
    ];
  }
}