force-app/main/default/objects/Apex_Event_Log__c/Apex_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to log apex actions on salesforce</description>
    <label>Apex Event Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <description>The calling apex class</description>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <description>The method name where the log came from</description>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <description>Detailed Error message</description>
    <label>Detailed Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Detailed_Information__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Information__c</fullName>
    <description>Record/s informations</description>
    <label>Detailed Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/HTTP_Body__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Body__c</fullName>
    <label>HTTP Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/HTTP_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Endpoint__c</fullName>
    <label>HTTP Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/HTTP_Headers__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Headers__c</fullName>
    <label>HTTP Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Http_Type__c.field-meta.xml
<CustomField>
    <fullName>Http_Type__c</fullName>
    <label>Http Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Matched_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Matched_Record_Id__c</fullName>
    <description>if there is an error like duplicate email detected
we want to understand what is the id</description>
    <label>Matched Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Original request body from the inbound call</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Record_Ids__c</fullName>
    <description>The record Id/ids the log is referring to</description>
    <label>Record Ids</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Session_Id__c</fullName>
    <description>Session Id from the SimilarWeb site</description>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/SF_Type__c.field-meta.xml
<CustomField>
    <fullName>SF_Type__c</fullName>
    <label>SF Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Event_Log__c/fields/sObjectId_Created__c.field-meta.xml
<CustomField>
    <fullName>sObjectId_Created__c</fullName>
    <description>will contain a campaign id or task id in the future.</description>
    <label>sObjectId Created</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <label>Detailed Error Message</label>
    <length>32678</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Detailed_Information__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Information__c</fullName>
    <label>Detailed Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Body__c.field-meta.xml
<CustomField>
    <fullName>Http_Body__c</fullName>
    <label>Http Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Http_Endpoint__c</fullName>
    <label>Http Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Headers__c.field-meta.xml
<CustomField>
    <fullName>Http_Headers__c</fullName>
    <label>Http Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Type__c.field-meta.xml
<CustomField>
    <fullName>Http_Type__c</fullName>
    <label>Http Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Matched_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Matched_Record_Id__c</fullName>
    <label>Matched Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Record_Ids__c</fullName>
    <label>Record Ids</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Id__c</fullName>
    <description>will hold the related lookup record or another referenced record</description>
    <label>Related Record Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Session_Id__c</fullName>
    <description>Session Id from integration with Similarweb&apos;s website.</description>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/SF_Type__c.field-meta.xml
<CustomField>
    <fullName>SF_Type__c</fullName>
    <label>SF Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/sObjectId_Created__c.field-meta.xml
<CustomField>
    <fullName>sObjectId_Created__c</fullName>
    <description>will contain task or lead or contact or campaign id</description>
    <label>sObjectId Created</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerHandler.cls
/**
* @author Itzik Winograd
* @date 09/03/2021
* @description Log Event Handler Class
* --------------------------------------------------------------------------------------
* CHANGE HISTORY:
* --------------------------------------------------------------------------------------
* author      - Itzik Winograd
* date        - 31/08/2022
* description - Add a fail-safe send email when the insertion of the logs records failed.
* --------------------------------------------------------------------------------------                     
*/
public without sharing class LogEventTriggerHandler {
    public void handle() {
        System.debug('### in LogEventTriggerHandler');
        List<Apex_Event_Log__c> logs = new List<Apex_Event_Log__c>();
        for(Log_Event__e record : (List<Log_Event__e>)Trigger.new) {
            logs.add(createLogRecord(record));
        }
        try{
            insert logs;
        } catch (Exception ex){
            sendMessage(ex, logs);
        }
    }

    /**
    * @author Itzik Winograd
    * @date 09/03/2021
    * @Description Create a Apex_Event_Log__c record bsed of values from the platform event.
    * @param Log_Event__e logEvent - Log event record with all log values
    * @return Apex_Event_Log__c with all fields assigned
    */
    public Apex_Event_Log__c createLogRecord(Log_Event__e logEvent){
        return new Apex_Event_Log__c(
                Matched_Record_Id__c = logEvent.Matched_Record_Id__c,
                Email__c = logEvent.Email__c,
                Record_Ids__c = logEvent.Record_Ids__c,
                Log_Type__c =   logEvent.Log_Type__c,
                Apex_class__c = logEvent.Apex_class__c,
                Apex_Method__c = logEvent.Apex_Method__c,
                Detailed_Error_Message__c = logEvent.Detailed_Error_Message__c,
                Detailed_Information__c = logEvent.Detailed_Information__c,
                HTTP_Body__c = logEvent.HTTP_Body__c,
                HTTP_Endpoint__c = logEvent.HTTP_Endpoint__c,
                HTTP_Headers__c = logEvent.HTTP_Headers__c,
                Http_Type__c = logEvent.Http_Type__c,
                Session_Id__c = logEvent.Session_Id__c,
                Related_Record_Id__c = logEvent.Related_Record_Id__c,
                sObjectId_Created__c = logEvent.sObjectId_Created__c,
                Sub_Type__c = logEvent.Sub_Type__c,
                Payload__c = logEvent.Payload__c,
                SF_Type__c = logEvent.SF_Type__c
        );
    }

    /**
    * @author Itzik Winograd
    * @date 01/09/2022
    * @Description Send an email to the team on errors
    * @param Exception ex - the failed exception
    * @param List<Apex_Event_Log__c> logs - logs failed to insert
    * @return none
    */
    public void sendMessage(Exception ex,  List<Apex_Event_Log__c> logs){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject('Error: failed to insert an Apex_Event_Log__c record!');
        String htmlBody = 'This error indicates a problem in the Apex Event Logs mechanism.<br>'+
                          'Please check the Log_Event__e Platform Event, The Apex_Event_Log__c object, LogEventTriggerHandler Apex Class and any other aspect that might impact this error.<br><br>'+
                          '<b>Exception caught:</b> ' + ex + '<br><br>' +
                          '<b>The Logs that were failed on insert are: </b><br>';
        for (Apex_Event_Log__c log : logs){
            htmlBody+= JSON.serializePretty(log) + '<br><br>';
        }
        System.debug('### LogEventTriggerHandler.sendMessage - htmlBody: ' + htmlBody);
        mail.setHtmlBody(htmlBody);
        mail.setToAddresses(new List<String>{'salesforce@similarweb.com'});
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
    }
}