force-app/main/default/objects/Apex_Event_Log__c/Apex_Event_Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to log apex actions on salesforce</description>
    <label>Apex Event Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Event_Log__c/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <description>The calling apex class</description>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExecuteDistibuteAccountValuesToConsTest.cls
/**
* @author Itzik Winograd
* @date 17/06/2021
* @description Test class for ExecuteDistibuteAccountValuesToCons
*/
@isTest
public class ExecuteDistibuteAccountValuesToConsTest {
	/**
    * @author Itzik Winograd
    * @date 17/06/2021
    * @description: Create and run an instance of this class.
    * @expected: the class will be created successfully and no errors will occure.
    */
    @istest
    public static void testImplementation(){
        String additionalProcessClassName ='ExecuteDistibuteAccountValuesToCons';
        Test.startTest();
        Type t = Type.forName(additionalProcessClassName);
        AdditionalLogicForAfterDML processHandler = (AdditionalLogicForAfterDML)t.newInstance();
        try{
            processHandler.handle(null, null);
        }
        catch(Exception ex){
            EventBus.Publish(LogEventUtils.createLogEventRecord(new List<Id>(), 'ExecuteDistibuteAccountValuesToConsTest', 'testImplementation', 
            '', 'Error executing additional logic: ' + additionalProcessClassName + ' -  ' + ex.getMessage(), 'Error',null,null));
        }
        Test.stopTest();
        System.assertEquals(0, 
                            [SELECT Id
                            FROM Apex_Event_Log__c
                            WHERE Apex_Class__c = 'ExecuteDistibuteAccountValuesToConsTest'].size(),
                           'Error occured during class run');
    }
}