force-app/main/default/objects/Contact/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Clean_Domain__c.field-meta.xml
<CustomField>
    <fullName>Clean_Domain__c</fullName>
    <formula>CASE( Email_address_domain_type__c , 
     &apos;Company&apos;,Email_Domain__c, 
      Website_Domain__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clean Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Department_Other_Description__c.field-meta.xml
<CustomField>
    <fullName>Department_Other_Description__c</fullName>
    <label>Department Other Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_address_domain_type__c.field-meta.xml
<CustomField>
    <fullName>Email_address_domain_type__c</fullName>
    <label>Email address domain type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Company - Secondary</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Employees_Min__c.field-meta.xml
<CustomField>
    <fullName>Employees_Min__c</fullName>
    <label>Employees Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Force_Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Force_Enrichment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MIS-7245</description>
    <label>Force Enrichment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Groudon_Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Groudon_Call_Status__c</fullName>
    <label>Groudon Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>NTS (Need To Send)</fullName>
            </value>
            <value>
                <fullName>Ignore</fullName>
            </value>
            <value>
                <fullName>Enrichment_Ended</fullName>
                <label>Enrichment Ended</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LinkedIn_Profile__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile__c</fullName>
    <inlineHelpText>please use https://www.didnotfind.com if no LinkedIn found</inlineHelpText>
    <label>LinkedIn Profile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lugia_Linkedin_Profile__c.field-meta.xml
<CustomField>
    <fullName>Lugia_Linkedin_Profile__c</fullName>
    <label>Lugia Linkedin Profile</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MIR_Status__c.field-meta.xml
<CustomField>
    <fullName>MIR_Status__c</fullName>
    <description>#1100018 Updated by MIR</description>
    <label>MIR Status:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fake Data</fullName>
            </value>
            <value>
                <fullName>Free Tools Sufficient / One-Time Use</fullName>
            </value>
            <value>
                <fullName>In Progress / Touched</fullName>
            </value>
            <value>
                <fullName>Low Traffic</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Not a Good Fit: Use Case / Persona / Industry</fullName>
            </value>
            <value>
                <fullName>Not Ready / Bad Timing / No Interest</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prioritized</fullName>
            </value>
            <value>
                <fullName>Unreachable / No Reply</fullName>
            </value>
            <value>
                <fullName>Unsubscribed</fullName>
            </value>
            <value>
                <fullName>Unverified: No Website / No LinkedIn</fullName>
            </value>
            <value>
                <fullName>Unsupported language speakers</fullName>
            </value>
            <value>
                <fullName>Not for No Touch</fullName>
            </value>
            <value>
                <fullName>Agent Replied - Follow Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Pre_mapped_industry__c.field-meta.xml
<CustomField>
    <fullName>Pre_mapped_industry__c</fullName>
    <label>Pre mapped industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Quiz_Data_Incomplete__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Data_Incomplete__c</fullName>
    <description>Syncs from Pardot - Prospect didn&apos;t / did finish the quiz</description>
    <label>Quiz Data Incomplete</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ROE_Division__c.field-meta.xml
<CustomField>
    <fullName>ROE_Division__c</fullName>
    <formula>TEXT(BI_Data__r.ROE_Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROE Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Seniority__c.field-meta.xml
<CustomField>
    <fullName>Seniority__c</fullName>
    <description>MIS-3278. Fields converted from Lead on Lead Conversion</description>
    <label>Seniority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Individual contributor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Team lead/manager</fullName>
            </value>
            <value>
                <fullName>VP/director</fullName>
            </value>
            <value>
                <fullName>C-Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Strategic_Pod__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Pod__c</fullName>
    <label>Strategic Pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Pod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account.SW_Industry__c , 
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;, 
&apos;Agency&apos;, &apos;Agency&apos;, 
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;, 
&apos;B2B Software&apos;,&apos;B2B Software&apos;, 
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;, 
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;, 
&apos;Classifieds&apos;,&apos;Classifieds&apos;, 
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;, 
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;, 
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;, 
&apos;Education&apos;,&apos;Education&apos;, 
&apos;Equity Research&apos;,&apos;Equity Research&apos;, 
&apos;Financial services&apos;,&apos;Financial services&apos;, 
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;, 
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;, 
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;, 
&apos;Investors&apos;,&apos;Investors&apos;, 
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;, 
&apos;Other&apos;,&apos;Other&apos;, 
&apos;Payments&apos;,&apos;Payments&apos;, 
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;, 
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;, 
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;, 
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;, 
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;, 
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;, 
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;, 
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;, 

&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Title_Other_Description__c.field-meta.xml
<CustomField>
    <fullName>Title_Other_Description__c</fullName>
    <label>Title Other Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <formula>Account.Website</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Website</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_class__c.field-meta.xml
<CustomField>
    <fullName>Apex_class__c</fullName>
    <label>Apex class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Apex_Method__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method__c</fullName>
    <label>Apex Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Detailed_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Error_Message__c</fullName>
    <label>Detailed Error Message</label>
    <length>32678</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Http_Body__c.field-meta.xml
<CustomField>
    <fullName>Http_Body__c</fullName>
    <label>Http Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Record_Ids__c</fullName>
    <label>Record Ids</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/SF_Type__c.field-meta.xml
<CustomField>
    <fullName>SF_Type__c</fullName>
    <label>SF Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactGroudonHandler.cls
public with sharing class ContactGroudonHandler implements GroudonQueueable.GroudonHandler {
	public List<Contact> contacts;

	public ContactGroudonHandler(Contact c) {
		this.contacts = new List<Contact>{c};
	}

	public ContactGroudonHandler(List<Contact> contacts){
		this.contacts = contacts;
	}

	public void process() {
		List<Log_Event__e> eventList = new List<Log_Event__e>();
		API_Configuration__mdt apiConfiguration = GeneralUtil.getAPIConfig('Groudon_Integration');

		GroudonIntegrationService groudonService = new GroudonIntegrationService(
				new ContactGroudonRequestGenerator(),
				new ContactGroudonResponseGenerator(),
				apiConfiguration);

		try{
			GroudonIntegrationService.GroudonResponse response = this.contacts.size() > 1 ?
																 groudonService.callGroudonBulk(this.contacts) :
																 groudonService.callGroudon(this.contacts.get(0));

			for(Contact c : this.contacts){
				fillLog(c, response, eventList);
			}
		}catch(Exception ex){
			Log_Event__e log = new Log_Event__e();
			log.Email__c = this.contacts.size() > 1 ? 'mass update' : this.contacts.isEmpty() ? 'no leads' : this.contacts[0].Email;
			log.Apex_class__c = 'GroudonIntegrationService';
			log.Apex_Method__c = 'callGroudon';
			log.Record_Ids__c = this.contacts.size() > 1 ? 'mass update' : this.contacts.isEmpty() ? 'no leads' : this.contacts[0].id;
			log.Log_Type__c = 'Error';
			log.Http_Body__c = 'no payload available';
			log.Detailed_Error_Message__c = ex.getMessage() + ' ' + ex.getStackTraceString();
			log.SF_Type__c = 'Contact';
			eventList.add(log);

		}
		List<Contact> contactsAfterLambdaCallout = [SELECT Id FROM Contact WHERE Id IN: this.contacts];
		for (Contact c : contactsAfterLambdaCallout) {
			c.Force_Enrichment__c = false;
			c.Groudon_Timestamp__c = Datetime.now();
			c.Groudon_Call_Status__c = 'Enrichment_Ended';
		}

		if (!eventList.isEmpty()) {
			Eventbus.publish(eventList);
		}

		update contactsAfterLambdaCallout;
	}

	private void fillLog(Contact c, GroudonIntegrationService.GroudonResponse response, List<Log_Event__e> eventList) {
		Log_Event__e log = new Log_Event__e();
		log.Email__c = c.email;
		log.Apex_Method__c = this.contacts.size() > 0 ?  'callGroudonBulk' : 'callGroudonSingle';
		log.Apex_class__c = 'GroudonIntegrationService';
		log.Record_Ids__c = c.id;
		log.Log_Type__c = response.isSuccess ? 'Info' : 'Error';
		log.Http_Body__c = response.leadIdToBodyMap.get(c.Id);
		log.Sub_Type__c = 'callGroudon';
		log.SF_Type__c = 'Contact';
		eventList.add(log);
	}

	public class ContactGroudonRequestGenerator implements GroudonQueueable.GroudonRequestGenerator {
		public GroudonIntegrationService.GroudonRequest generate(SObject record) {
			Contact contactItem = (Contact) record;

			GroudonIntegrationService.GroudonRequest requestBody = new GroudonIntegrationService.GroudonRequest();

			requestBody.first_name = contactItem.FirstName;
			requestBody.last_name = contactItem.LastName;
			requestBody.domain = contactItem.Website__c;
			requestBody.Country_Code = contactItem.MailingCountryCode;
			requestBody.Department_C = contactItem.Department__c;
			requestBody.Department_Other_Description = contactItem.Department_Other_Description__c;
			requestBody.email = contactItem.Email;
			requestBody.linkedin_profile = contactItem.Linkedin_Profile__c;
			requestBody.Seniority = contactItem.Seniority__c;
			requestBody.industry = contactItem.SW_Industry__c;
			requestBody.job_title = contactItem.Title;
			requestBody.Industry_Other_Description = contactItem.Industry_Other_Description__c;
			requestBody.Title_Other_Description = contactItem.Title_Other_Description__c;
			requestBody.Pre_mapped_industry = contactItem.Pre_mapped_industry__c;
			requestBody.Pre_Mapped_Title = contactItem.Pre_Mapped_Title__c;
			requestBody.website = contactItem.Website__c;
			requestBody.Business_Unit = contactItem.Business_Unit__c;
			requestBody.Clean_Domain = contactItem.Clean_Domain__c;
			requestBody.country = contactItem.MailingCountry;
			requestBody.Email_address_domain_type = contactItem.Email_address_domain_type__c;
			requestBody.Employees_Min = contactItem.Employees_Min__c;
			requestBody.Lugia_Fit_Score = contactItem.Lugia_Fit_Score__c;
			requestBody.LinkedIn = contactItem.LinkedIn_Profile__c;
			requestBody.Lugia_Linkedin_Profile = contactItem.Lugia_Linkedin_Profile__c;
			requestBody.MIR_Status = contactItem.MIR_Status__c;
			requestBody.Quiz_Data_Incomplete = contactItem.Quiz_Data_Incomplete__c;
			requestBody.ROE_Division = contactItem.ROE_Division__c;
			requestBody.SI_Enrichment_Visits = contactItem.SI_Enrichment_Visits__c;
			requestBody.Strategic_Pod = contactItem.Strategic_Pod__c;
			requestBody.title = contactItem.title;
			requestBody.Use_of_Similarweb = contactItem.Use_of_Similarweb__c;
			requestBody.first_name = contactItem.FirstName;
			requestBody.last_name = contactItem.LastName;
			requestBody.Company = contactItem.Account_name__c;
			requestBody.SW_Fit_Score_Reason = contactItem.SW_Fit_Score_Reason__c;
			requestBody.Fit_Score_Test = contactItem.Fit_Score_Test__c;
			requestBody.Lugia_Fit_Score_Reasoning = contactItem.Lugia_Fit_Score_Reasoning__c;
			requestBody.Lugia_Employees_Count = contactItem.Lugia_Employees_Count__c;
			requestBody.sf_id = contactItem.Id;
			requestBody.timestamp = Datetime.now();
			// requestBody.clientIp = contactItem.clientIp__c;
			requestBody.sf_type = 'Contact';
			requestBody.Registration_Type = contactItem.Registration_Type__c;
			requestBody.LeadSource = contactItem.LeadSource;

			return requestBody;
		}
	}

	public class ContactGroudonResponseGenerator implements GroudonQueueable.GroudonResponseGenerator {
		public GroudonIntegrationService.GroudonResponse generate(List<GroudonIntegrationService.GroudonRequest> requestBodies) {
			GroudonIntegrationService.GroudonResponse groudonResponse = new GroudonIntegrationService.GroudonResponse();

			for (GroudonIntegrationService.GroudonRequest r : requestBodies) {
				groudonResponse.contactIdToBodyMap.put(r.sf_id ,JSON.serializePretty(r,true));
			}

			return groudonResponse;
		}
	}
}