force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing: SEO / Content</fullName>
            </value>
            <value>
                <fullName>Marketing: Management / General</fullName>
            </value>
            <value>
                <fullName>Marketing: PPC / Display</fullName>
            </value>
            <value>
                <fullName>Marketing: PR / Comms / Social Media</fullName>
            </value>
            <value>
                <fullName>Marketing: Affiliate / Media Buying</fullName>
            </value>
            <value>
                <fullName>Sales / Business Development</fullName>
            </value>
            <value>
                <fullName>Account Management / Customer Success</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Strategy / Market Research</fullName>
            </value>
            <value>
                <fullName>Corporate Development / Mergers and Acquisitions</fullName>
            </value>
            <value>
                <fullName>BI / Analytics</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Management (C-Level)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Marketing Operations</fullName>
            </value>
            <value>
                <fullName>Student / Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Original_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Original_Lead_Source__c</fullName>
    <label>Original Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3Scale</fullName>
            </value>
            <value>
                <fullName>42matters</fullName>
            </value>
            <value>
                <fullName>Admetricks</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>Blogs</fullName>
            </value>
            <value>
                <fullName>CompeteReferral</fullName>
            </value>
            <value>
                <fullName>ContactForm</fullName>
            </value>
            <value>
                <fullName>Deal Registration</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook - Paid</fullName>
            </value>
            <value>
                <fullName>Hitwise Referral - Existed in CRM</fullName>
            </value>
            <value>
                <fullName>Hitwise Referral - New Account</fullName>
            </value>
            <value>
                <fullName>Hitwise Referral - Was in Pipeline</fullName>
            </value>
            <value>
                <fullName>Hitwise Referral - Was Paying</fullName>
            </value>
            <value>
                <fullName>Internal - F2F Event</fullName>
            </value>
            <value>
                <fullName>Internal - Virtual Event</fullName>
            </value>
            <value>
                <fullName>Internal - Webinars</fullName>
            </value>
            <value>
                <fullName>Investors - Paid</fullName>
            </value>
            <value>
                <fullName>LinkedIn - Paid</fullName>
            </value>
            <value>
                <fullName>LinkedIn - Paid - Convo Ads</fullName>
            </value>
            <value>
                <fullName>LinkedIn sales navigator</fullName>
            </value>
            <value>
                <fullName>MIR</fullName>
            </value>
            <value>
                <fullName>MIR Chat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outbound - ZoomInfo</fullName>
            </value>
            <value>
                <fullName>Partnership - Content</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactDraft__c/ContactDraft__c.object-meta.xml
<CustomObject>
    <label>ContactDraft</label>
    <nameField>
        <label>ContactDraft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactDrafts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactsImportBatchTest.cls
@isTest
public with sharing class ContactsImportBatchTest {
    @testSetup 
    static void setup() {
        TestDataFactory.createSimilarWeb_CS();
        TestDataFactory.createInferredSolutionSettings_CS();
        Account acc = TestDataFactory.createAccount();
        insert acc;
        ContactDraft__c cd = TestDataFactory.creatContactDraft(acc);
        insert cd;
    }

    static testmethod void test() {    
        List<Account> acc = [SELECT Id FROM Account];
        List<ContactDraft__c> cd = [SELECT Id FROM ContactDraft__c];
        Map<String,String> emailToCdId = new Map<String,String>();
        List<Contact> cntcts = new List<Contact>();
        Contact newContact = new Contact();
        newContact.AccountId = acc[0].Id;
        newContact.Email = 'test@test.com';
        newContact.FirstName = 'testFN';
        newContact.LastName = 'testLN';
        newContact.Title = 'testTitle';
        newContact.Department__c = 'Investment';
        newContact.Original_Lead_Source__c = 'Facebook';
        cntcts.add(newContact);
        emailToCdId.put(newContact.Email,cd[0].Id);
        System.debug([SELECT Id FROM Contact]);
        Test.startTest();
        ContactsImportBatch uca = new ContactsImportBatch(cntcts,emailToCdId);
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        System.assertEquals(1,[SELECT Id FROM Contact].size());
        System.assertEquals(0,[SELECT Id FROM ContactDraft__c].size());
    }
}