force-app/main/default/objects/Contact/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Shopper</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <formula>CASE( Account.SW_Industry__c , 
&apos;AdTech and AdNetwork&apos;, &apos;AdTech and AdNetwork&apos;, 
&apos;Agency&apos;, &apos;Agency&apos;, 
&apos;Automotive and Transportation&apos;, &apos;Automotive&apos;, 
&apos;B2B Software&apos;,&apos;B2B Software&apos;, 
&apos;B2C Internet Services&apos;,&apos;B2C Internet Services&apos;, 
&apos;Banking and insurance&apos;,&apos;Banking and insurance&apos;, 
&apos;Classifieds&apos;,&apos;Classifieds&apos;, 
&apos;Consulting and Market Research&apos;,&apos;Consulting and Market Research&apos;, 
&apos;CPG, Food &amp; Beverages&apos;,&apos;CPG&apos;, 
&apos;Data Integrators&apos;,&apos;Data Integrators&apos;, 
&apos;Education&apos;,&apos;Education&apos;, 
&apos;Equity Research&apos;,&apos;Equity Research&apos;, 
&apos;Financial services&apos;,&apos;Financial services&apos;, 
&apos;Gambling / Gaming&apos;,&apos;Gambling and Gaming&apos;, 
&apos;Hedge Funds and Asset Management&apos;,&apos;Hedge Funds and Asset Management&apos;, 
&apos;Investment Banking&apos;,&apos;Investment Banking&apos;, 
&apos;Investors&apos;,&apos;Investors&apos;, 
&apos;Logistics and Shipping&apos;,&apos;Logistics and Shipping&apos;, 
&apos;Other&apos;,&apos;Other&apos;, 
&apos;Payments&apos;,&apos;Payments&apos;, 
&apos;Pharma and Healthcare&apos;,&apos;Pharma and Healthcare&apos;, 
&apos;VC and Private Equity&apos;,&apos;Private Equity&apos;, 
&apos;Government Public Sector &amp; Non Profit&apos;,&apos;Public Sector, Non Profit, Fraud and Compliance&apos;, 
&apos;Media and Entertainment&apos;,&apos;Publishers and Media&apos;, 
&apos;Retail / eCommerce&apos;,&apos;Retail and eCommerce&apos;, 
&apos;Telecom and Hardware&apos;,&apos;Telecom&apos;, 
&apos;Travel and Hospitality&apos;,&apos;Travel&apos;, 
&apos;Venture Capital&apos;,&apos;Venture Capital&apos;, 

&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SW Industry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/objects/Inferral_Solution_Settings__c/Inferral_Solution_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Settings</label>
</CustomObject>

force-app/main/default/objects/Inferral_Solution_Valid_Criteria_List__c/Inferral_Solution_Valid_Criteria_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution L Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/InferralSolutionCValidCriteriaList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution C Valid Criteria List</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionCValidCriteriaList__c/fields/Is_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Valid__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMap__c/InferralSolutionMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Lead</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/InferralSolutionMapContact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Inferral Solution Map Contact</label>
</CustomObject>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InferralSolutionMapContact__c/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Inferred_Solution__c.field-meta.xml
<CustomField>
    <fullName>Inferred_Solution__c</fullName>
    <label>Inferred Solution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>Sales (SI)</fullName>
            </value>
            <value>
                <fullName>Agency (MI)</fullName>
            </value>
            <value>
                <fullName>Investors (II)</fullName>
            </value>
            <value>
                <fullName>Publishers &amp; Media</fullName>
            </value>
            <value>
                <fullName>AI / PI</fullName>
            </value>
            <value>
                <fullName>Marketing (MI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SW_Industry__c.field-meta.xml
<CustomField>
    <fullName>SW_Industry__c</fullName>
    <label>SW Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AdTech and AdNetwork</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Automotive and Transportation</fullName>
                <label>Automotive</label>
            </value>
            <value>
                <fullName>B2B Software</fullName>
            </value>
            <value>
                <fullName>B2C Internet Services</fullName>
            </value>
            <value>
                <fullName>Banking and insurance</fullName>
            </value>
            <value>
                <fullName>Classifieds</fullName>
            </value>
            <value>
                <fullName>Consulting and Market Research</fullName>
            </value>
            <value>
                <fullName>CPG, Food &amp; Beverages</fullName>
                <label>CPG</label>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Equity Research</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Gambling / Gaming</fullName>
                <label>Gambling and Gaming</label>
            </value>
            <value>
                <fullName>Hedge Funds and Asset Management</fullName>
            </value>
            <value>
                <fullName>Investment Banking</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
            <value>
                <fullName>Logistics and Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Pharma and Healthcare</fullName>
            </value>
            <value>
                <fullName>Private Equity and Venture Capital</fullName>
            </value>
            <value>
                <fullName>Government Public Sector &amp; Non Profit</fullName>
                <label>Public Sector, Non Profit, Fraud and Compliance</label>
            </value>
            <value>
                <fullName>Media and Entertainment</fullName>
                <label>Publishers and Media</label>
            </value>
            <value>
                <fullName>Recruitment and HR</fullName>
            </value>
            <value>
                <fullName>Retail / eCommerce</fullName>
                <label>Retail and eCommerce</label>
            </value>
            <value>
                <fullName>Telecom and Hardware</fullName>
                <label>Telecom</label>
            </value>
            <value>
                <fullName>Travel and Hospitality</fullName>
                <label>Travel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/InferredSolutionHandler.cls
public class InferredSolutionHandler {
    
    private Boolean isUpdateValid = true;
    private String sObjtype;
    
    public InferredSolutionHandler(String sObjtype){
        this.sObjtype = sObjtype;
    }
    
    public void setInferredSolution(List<sObject> newList,  Map<Id, sObject> oldMap) {
        System.debug(sObjtype);
         System.debug(newList);
         System.debug(oldMap);
        if(sObjtype == 'Lead'){
            Set<String> invalidColumnsList = new Set<String>();
            for(Inferral_Solution_Valid_Criteria_List__c isvc_i: [SELECT Name FROM Inferral_Solution_Valid_Criteria_List__c WHERE Is_Valid__c=false]){
                invalidColumnsList.add(isvc_i.Name);
            }
            Set<String> schemaFieldList = Schema.SObjectType.InferralSolutionMap__c.fields.getMap().keySet();
            Set<String> leadFieldList = Schema.SObjectType.Lead.fields.getMap().keySet();
            for(String schemaField : schemaFieldList){
                if(!schemaField.endsWith('__c') || invalidColumnsList.contains(schemaField) || schemaField == 'Inferred_Solution__c'){
                    schemaFieldList.remove(schemaField);
                }
            }
            Map<String,InferralSolutionMap__c> inferralSolutionMap = InferralSolutionMap__c.getAll();        
            if(oldMap == null){
                for(sObject sObj_i : newList){
                    String keyName='';
                    for(String schemaField : schemaFieldList){ 
                        if(!leadFieldList.contains(schemaField))
                            schemaField = schemaField.removeEnd('__c');
                        // New
                        String sObjValue = (sObj_i.get(schemaField) == null || sObj_i.get(schemaField) == 'NULL') ? 'NULL' : (String)sObj_i.get(schemaField);
                        // Old
                        // String sObjValue = sObj_i.get(schemaField) == null ? 'NULL' : (String)sObj_i.get(schemaField);
                        keyName+= sObjValue + ' + ';   
                    }
                    keyName = keyName.removeEnd(' + ');
                    System.debug('keyName - ' + keyName);
                    String index = EncodingUtil.convertToHex(Crypto.generateDigest('MD5',Blob.valueOf(keyName)));
                    if(inferralSolutionMap.containsKey(index)){                 
                        sObj_i.put('Inferred_Solution__c', inferralSolutionMap.get(index).Inferred_Solution__c);
                    }  else {
                        Boolean valueFound = false;
                        for(InferralSolutionMap__c ism_i : inferralSolutionMap.values()){
                            Boolean ch = false;
                            for(String schemaField : schemaFieldList){                                
                                if(ism_i.get(schemaField) != 'NULL' && ism_i.get(schemaField) != sObj_i.get(schemaField)){
                                    ch = true;
                                    break;
                                }
                            }
                            if(ch){
                                continue;
                            } else {
                                sObj_i.put('Inferred_Solution__c', ism_i.Inferred_Solution__c);
                                valueFound = true;
                                break;
                            }
                        }
                        if(!valueFound){
                            sObj_i.put('Inferred_Solution__c', Inferral_Solution_Settings__c.getValues('Default Value').Value__c);
                        }
                    }
                }
            } else {
                for(sObject sObj_i : newList){
                    sObject oldObject = (sObject)oldMap.get(sObj_i.Id);
                    String keyName='';
                    Boolean isUpdated = false;
                    for(String schemaField : schemaFieldList){
                        if(!leadFieldList.contains(schemaField))
                            schemaField = schemaField.removeEnd('__c');
                        if(sObj_i.get(schemaField) != oldObject.get(schemaField))
                            isUpdated=true;
                        System.debug('keyName - ' + keyName);
                        // New
                        String sObjValue = (sObj_i.get(schemaField) == null || sObj_i.get(schemaField) == 'NULL') ? 'NULL' : (String)sObj_i.get(schemaField);
                        // Old
                        // String sObjValue = sObj_i.get(schemaField) == null ? 'NULL' : (String)sObj_i.get(schemaField);
                        keyName+= sObjValue + ' + ';        
                    }
                    if(isUpdated){
                        keyName = keyName.removeEnd(' + ');
                        System.debug('keyName - ' + keyName);
                        String index = EncodingUtil.convertToHex(Crypto.generateDigest('MD5',Blob.valueOf(keyName)));
                        if(inferralSolutionMap.containsKey(index)){  
                            sObj_i.put('Inferred_Solution__c', inferralSolutionMap.get(index).Inferred_Solution__c);
                        } else {
                            Boolean valueFound = false;
                            for(InferralSolutionMap__c ism_i : inferralSolutionMap.values()){
                                Boolean ch = false;
                                for(String schemaField : schemaFieldList){
                                    if(!leadFieldList.contains(schemaField))
                                        schemaField = schemaField.removeEnd('__c');
                                    if(ism_i.get(schemaField) != 'NULL' && ism_i.get(schemaField) != sObj_i.get(schemaField)){
                                        ch = true;
                                        break;
                                    }
                                }
                                if(ch){
                                    continue;
                                } else {
                                    sObj_i.put('Inferred_Solution__c', ism_i.Inferred_Solution__c);
                                    valueFound = true;
                                    break;
                                }
                            }
                            if(!valueFound){
                                sObj_i.put('Inferred_Solution__c', Inferral_Solution_Settings__c.getValues('Default Value').Value__c);
                            }
                        }
                    }
                }             
            } 
        } else if(sObjtype == 'Contact'){
            System.debug('INIT');
            Set<String> invalidColumnsList = new Set<String>();
            for(InferralSolutionCValidCriteriaList__c isvc_i: [SELECT Name FROM InferralSolutionCValidCriteriaList__c WHERE Is_Valid__c=false]){
                invalidColumnsList.add(isvc_i.Name);
            }
            Set<String> schemaFieldList = Schema.SObjectType.InferralSolutionMapContact__c.fields.getMap().keySet();
            Set<String> contactFieldList = Schema.SObjectType.Contact.fields.getMap().keySet();
            for(String schemaField : schemaFieldList){
                if(!schemaField.endsWith('__c') || invalidColumnsList.contains(schemaField) || schemaField == 'Inferred_Solution__c'){
                    schemaFieldList.remove(schemaField);
                }
            }         
            Map<String,InferralSolutionMapContact__c> inferralSolutionMap = InferralSolutionMapContact__c.getAll();        
            if(oldMap == null){     
                for(sObject sObj_i : newList){
                    String keyName='';
                    for(String schemaField : schemaFieldList){
                        if(!contactFieldList.contains(schemaField))
                            schemaField = schemaField.removeEnd('__c');
                        // New
                        String sObjValue = (sObj_i.get(schemaField) == null || sObj_i.get(schemaField) == 'NULL') ? 'NULL' : (String)sObj_i.get(schemaField);
                        // Old
                        // String sObjValue = sObj_i.get(schemaField) == null ? 'NULL' : (String)sObj_i.get(schemaField);
                        keyName+= sObjValue + ' + ';   
                    }
                    keyName = keyName.removeEnd(' + ');
                    System.debug('keyNameSS - ' + keyName);
                    String index = EncodingUtil.convertToHex(Crypto.generateDigest('MD5',Blob.valueOf(keyName)));
                    System.debug('inferralSolutionMap.containsKey(index) - ' + inferralSolutionMap.containsKey(index));
                    if(inferralSolutionMap.containsKey(index)){                 
                        sObj_i.put('Inferred_Solution__c', inferralSolutionMap.get(index).Inferred_Solution__c);
                    } else {
                        Boolean valueFound = false;
                        for(InferralSolutionMapContact__c ism_i : inferralSolutionMap.values()){
                            Boolean ch = false;
                            for(String schemaField : schemaFieldList){                                
                                if(ism_i.get(schemaField) != 'NULL' && ism_i.get(schemaField) != sObj_i.get(schemaField)){
                                    ch = true;
                                    break;
                                }
                            }
                            if(ch){
                                continue;
                            } else {
                                sObj_i.put('Inferred_Solution__c', ism_i.Inferred_Solution__c);
                                valueFound = true;
                                break;
                            }
                        }
                        if(!valueFound){
                            sObj_i.put('Inferred_Solution__c', Inferral_Solution_Settings__c.getValues('Default Value').Value__c);
                        }
                    }
                }
            } else {
                for(sObject sObj_i : newList){
                    sObject oldObject = (sObject)oldMap.get(sObj_i.Id);
                    String keyName='';
                    Boolean isUpdated = false;
                    for(String schemaField : schemaFieldList){
                        if(!contactFieldList.contains(schemaField))
                            schemaField = schemaField.removeEnd('__c');
                        System.debug('schemaField '+schemaField);
                        if(sObj_i.get(schemaField) != oldObject.get(schemaField) || schemaField.equalsIgnoreCase('SW_Industry__c'))
                            isUpdated=true;
                        System.debug('keyName - ' + keyName);
                        // New
                        String sObjValue = (sObj_i.get(schemaField) == null || sObj_i.get(schemaField) == 'NULL') ? 'NULL' : (String)sObj_i.get(schemaField);
                        // Old
                        // String sObjValue = sObj_i.get(schemaField) == null ? 'NULL' : (String)sObj_i.get(schemaField);
                        keyName+= sObjValue + ' + ';        
                    }
                    if(isUpdated){
                        keyName = keyName.removeEnd(' + ');
                        System.debug('keyName - ' + keyName);
                        String index = EncodingUtil.convertToHex(Crypto.generateDigest('MD5',Blob.valueOf(keyName)));
                        if(inferralSolutionMap.containsKey(index)){                 
                            sObj_i.put('Inferred_Solution__c', inferralSolutionMap.get(index).Inferred_Solution__c);
                        } else {
                            Boolean valueFound = false;
                            for(InferralSolutionMapContact__c ism_i : inferralSolutionMap.values()){
                                Boolean ch = false;
                                for(String schemaField : schemaFieldList){
                                    if(!contactFieldList.contains(schemaField))
                                        schemaField = schemaField.removeEnd('__c');
                                    if(ism_i.get(schemaField) != 'NULL' && ism_i.get(schemaField) != sObj_i.get(schemaField)){
                                        ch = true;
                                        break;
                                    }
                                }
                                if(ch){
                                    continue;
                                } else {
                                    sObj_i.put('Inferred_Solution__c', ism_i.Inferred_Solution__c);
                                    valueFound = true;
                                    break;
                                }
                            }
                            if(!valueFound){
                                sObj_i.put('Inferred_Solution__c', Inferral_Solution_Settings__c.getValues('Default Value').Value__c);
                            }
                        }
                    }
                }             
            } 
        }
    }
}