force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/ZuoraQuoteStatusInctructionSettings__mdt.object-meta.xml
<CustomObject>
    <label>Zuora Quote Status Inctruction Setting</label>
    <pluralLabel>Zuora Quote Status Inctruction Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
                <default>true</default>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
                <default>true</default>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Subscription</fullName>
                <default>true</default>
                <label>New Subscription</label>
            </value>
            <value>
                <fullName>Amend Subscription</fullName>
            </value>
            <value>
                <fullName>Renew Subscription</fullName>
            </value>
            <value>
                <fullName>Cancel Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/fields/QuoteBusinessType__c.field-meta.xml
<CustomField>
    <fullName>QuoteBusinessType__c</fullName>
    <label>QuoteBusinessType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New Sale</label>
            </value>
            <value>
                <fullName>Co-Term Upsell</fullName>
            </value>
            <value>
                <fullName>Co-Term Upsell + Renewal</fullName>
            </value>
            <value>
                <fullName>Feature Update</fullName>
            </value>
            <value>
                <fullName>Feature Update + Renewal (with/without upsell)</fullName>
            </value>
            <value>
                <fullName>Renewal Only</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Renewal (with/without upsell)</fullName>
            </value>
            <value>
                <fullName>Feature Update + Renewal</fullName>
                <isActive>false</isActive>
                <label>Feature Update + Renewal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZuoraQuoteStatusInctructionSettings__mdt/fields/Renewal_by_client_confirmation__c.field-meta.xml
<CustomField>
    <fullName>Renewal_by_client_confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal by Renewal Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteInstructionsComponentController.cls
public with sharing class QuoteInstructionsComponentController {
  @AuraEnabled
  public static Response obtainQuoteInstructions(String quoteStatus) {
    List<ZuoraQuoteStatusInctructionSettings__mdt> quoteInstructionList = [
      SELECT
        Id,
        Instructions__c,
        Quote_Status__c,
        Quote_Type__c,
        Payment_Type__c,
        Payment_Method__c,
        QuoteBusinessType__c,
        Renewal_by_client_confirmation__c
      FROM ZuoraQuoteStatusInctructionSettings__mdt
    ];
    return new Response(quoteInstructionList);
  }
}