force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <description>Disclaimer:
Record type = who created the meeting
Owner = who got the meeting</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Cancelled_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Reason__c</fullName>
    <label>Cancelled/Unqualified Reason - Details</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>In MIR, SDR and Sales Meetings - use the &quot;Complete Meeting&quot; Button at the top of the page</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Rescheduling</fullName>
            </value>
            <value>
                <fullName>Scheduling in Progress</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Unqualified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unqualified_Reason__c</fullName>
    <label>Cancelled/Unqualified Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AM canceled</fullName>
                <label>AM Cancelled</label>
            </value>
            <value>
                <fullName>Company not ENT</fullName>
            </value>
            <value>
                <fullName>Feature is in the current package</fullName>
            </value>
            <value>
                <fullName>Irrelevant Prospect</fullName>
            </value>
            <value>
                <fullName>No need we can deliver</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Issue</fullName>
            </value>
            <value>
                <fullName>Prospect Cancelled</fullName>
            </value>
            <value>
                <fullName>Sales Cancelled</fullName>
            </value>
            <value>
                <fullName>Automate cancellation process</fullName>
            </value>
            <value>
                <fullName>NT Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelUnTouchOpenMeetingsBatch.cls
/**
 * Created by Alon.Shalev on 9/7/2023.
 */

public with sharing class CancelUnTouchOpenMeetingsBatch implements Database.Batchable<sObject> ,Schedulable{

    private Set<String> closedStatusSet = new Set<String>{'Cancelled','Completed','Unqualified'};
    private Integer batchSize = 1;
    private String recordTypeToExclude = 'Calendar Event';


    public void execute(SchedulableContext scMain) {

        CancelUnTouchOpenMeetingsBatch batch = new CancelUnTouchOpenMeetingsBatch(this.batchSize);
        Database.executeBatch(batch, this.batchSize);

    }
    public CancelUnTouchOpenMeetingsBatch(Integer batchSize){
        this.batchSize = batchSize;
    }

    public Database.QueryLocator start (Database.BatchableContext BC){
        String query = 'SELECT Id FROM Meeting__c WHERE Status__c NOT IN : closedStatusSet AND RecordType.Name !=:recordTypeToExclude ';
        query += Test.isRunningTest() ? '' : 'AND LastModifiedDate < LAST_N_MONTHS:6';
        return Database.getQueryLocator(query);

    }

    public void execute(Database.BatchableContext BC, List<Meeting__c> scope){
        for(Meeting__c meeting :scope){
            meeting.Status__c = 'Cancelled';
            meeting.Cancelled_Reason__c = 'this meeting was untouched for the last 6 months';
            meeting.Unqualified_Reason__c  = 'this meeting was untouched for the last 6 months';
        }
        update scope;
    }

    public void finish(Database.BatchableContext BC){
    }

}